CREATE VIEW [DWDocLocEMEA].[tblDocLocLog]
AS (
SELECT [LZBatchID]
      ,[ADLSBatchID]
      ,[ADLSTimestamp]
      ,[id]
      ,[log_time]
      ,[log_type]
      ,[implementation_type]
      ,[search_type]
      ,[search_source]
      ,[search_duration]
      ,[search_name]
      ,[search_address]
      ,[search_postal_code]
      ,[search_city]
      ,[search_state]
      ,[search_country]
      ,[search_filter]
      ,[search_sort]
      ,[search_latitude]
      ,[search_longitude]
      ,[search_results]
      ,[search_status]
      ,[search_data]
      ,[search_session_id]
      ,[search_context_id]
      ,[search_radius]
      ,[search_start_position]
      ,[search_effective_radius]
      ,[search_end_position]
      ,[primary_docid]
      ,[geocode_source]
      ,[docid_list]
      ,[client_ip]
      ,[viewer_id]
      ,[error_message]
  FROM [SrcDocLocEMEA].[tblDocLocLog]
);