CREATE TABLE [DWCONSDL].[FactGAUMsCTD] (
    [DWBatchID]           INT            NOT NULL,
    [DWHash]              CHAR (40)      NOT NULL,
    [DWHashKey]           CHAR (40)      NOT NULL,
    [Region]              NVARCHAR (50)  NULL,
    [DateKey]             DATE           NULL,
    [CountryFromHostName] NVARCHAR (200) NULL,
    [UVsWTD]              INT            NULL,
    [UVsWTDPY]            INT            NULL,
    [UVsMTD]              INT            NULL,
    [UVsMTDPY]            INT            NULL,
    [UVsQTD]              INT            NULL,
    [UVsQTDPY]            INT            NULL,
    [UVsYTD]              INT            NULL,
    [UVsYTDPY]            INT            NULL,
    [UPVsWTD]             INT            NULL,
    [UPVsWTDPY]           INT            NULL,
    [UPVsMTD]             INT            NULL,
    [UPVsMTDPY]           INT            NULL,
    [UPVsQTD]             INT            NULL,
    [UPVsQTDPY]           INT            NULL,
    [UPVsYTD]             INT            NULL,
    [UPVsYTDPY]           INT            NULL,
    [SessionsWTD]         INT            NULL,
    [SessionsWTDPY]       INT            NULL,
    [SessionsMTD]         INT            NULL,
    [SessionsMTDPY]       INT            NULL,
    [SessionsQTD]         INT            NULL,
    [SessionsQTDPY]       INT            NULL,
    [SessionsYTD]         INT            NULL,
    [SessionsYTDPY]       INT            NULL,
    [CreatedDate]         DATETIME       NULL,
    [ModifiedDate]        DATETIME       NULL
)
WITH (CLUSTERED INDEX([DateKey]), DISTRIBUTION = ROUND_ROBIN);

