CREATE TABLE [DWCONSDL].[FactLead] (
    [DWBatchID]                      INT             NOT NULL,
    [DWHashKey]                      CHAR (40)       NOT NULL,
    [Id]                             NVARCHAR (36)   NOT NULL,
    [Lead_Region__c]                 NVARCHAR (130)  NULL,
    [Region]                         NVARCHAR (150)  NULL,
    [Country]                        NVARCHAR (160)  NULL,
    [Lead_URL_Campaign__c]           NVARCHAR (510)  NULL,
    [Lead_URL_Content__c]            NVARCHAR (510)  NULL,
    [Lead_URL_Medium__c]             NVARCHAR (160)  NULL,
    [Lead_URL_Source__c]             NVARCHAR (160)  NULL,
    [Lead_URL_Term__c]               NVARCHAR (510)  NULL,
    [Unsubscribe__c]                 VARCHAR (10)    NULL,
    [Et4ae5__HasOptedOutOfMobile__C] VARCHAR (10)    NULL,
    [Channel]                        NVARCHAR (255)  NULL,
    [Zip]                            NVARCHAR (5)    NULL,
    [Lead_Assigned]                  NVARCHAR (20)   NULL,
    [Age_Segment]                    NVARCHAR (40)   NULL,
    [Age_Group]                      NVARCHAR (20)   NULL,
    [Days_Between_Create_Contact]    NVARCHAR (40)   NULL,
    [Days_Between_Schedule_Consult]  NVARCHAR (40)   NULL,
    [Days_Between_Schedule_Consult2] INT             NULL,
    [Days_Between_Create_CCA2]       INT             NULL,
    [Lead_Source_Granular]           NVARCHAR (150)  NULL,
    [Lead_Source]                    NVARCHAR (150)  NULL,
	[LeadSourceOriginal] 			 NVARCHAR (80) 	 NULL,
    [Age_Group2]                     NVARCHAR (510)  NULL,
    [Lead_Created_Date]              DATE            NULL,
    [Lead_Created_Week]              DATE            NULL,
    [Lead_Created_Month]             DATE            NULL,
    [Lead_Created_Quarter]           DATE            NULL,
    [Mos_Since_Created_Date]         INT             NULL,
    [First_Contact_Date]             DATE            NULL,
    [First_Contact_Month]            DATE            NULL,
    [Mos_Since_First_Contact_Date]   INT             NULL,
    [Scheduled_Date]                 DATE            NULL,
    [Scheduled_Month]                DATE            NULL,
    [Mos_Since_Scheduled_Date]       INT             NULL,
    [Consultation_Date]              DATE            NULL,
    [Lapsed_Consults]                INT             NULL,
    [Converted_Date]                 DATE            NULL,
    [Converted_Within_30_Days]       BIT             NULL,
    [Converted_Within_60_Days]       BIT             NULL,
    [Mos_Since_Converted_Date]       INT             NULL,
    [CCA_Date]                       DATE            NULL,
    [DID]                            NVARCHAR (2600) NULL,
    [ClinID]                         NVARCHAR (50)   NULL,
    [Doctor_Name]                    NVARCHAR (121)  NULL,
    [City_State]                     NVARCHAR (150)  NULL,
    [LID]                            NVARCHAR (40)   NULL,
    [Not_Interested]                 BIT             NULL,
    [Bad_Data]                       BIT             NULL,
    [In_Progress]                    BIT             NULL,
    [SystemModstamp]                 DATETIME        NULL,
    [CreatedDate]                    DATETIME        NULL,
    [ModifiedDate]                   DATETIME        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Id]));


GO
CREATE STATISTICS [STATS_DWCONSDL_FactLead_Id]
    ON [DWCONSDL].[FactLead]([Id]);

