CREATE VIEW [DWSFMC].[Email_Send_Log]
AS SELECT [JobID]
      ,[ListID]
      ,[BatchID]
      ,[SubID]
      ,[TriggeredSendID]
      ,[ErrorCode_]
      ,[Datetime]
      ,[MailingCountryCode]
      ,[acc_Billing_Language__c]
      ,[acc_ShippingCity]
      ,[CountryRegion]
      ,[OwnerName]
      ,[SubscriberKey]
  FROM [SrcSFMC].[Email_Send_Log];