CREATE VIEW [DWSFMC].[EMEAEmailDataTest]
AS SELECT [Email_JobId]
      ,[Emailsubject]
      ,[EmailName]
      ,[Sent_Date]
      ,[Total_Count]
      ,[Open_Count]
      ,[Click_Count]
      ,[Bounce_Count]
      ,[Unsub_Count]
      ,[Open_Rate]
      ,[Journey_Activity_Name]
      ,[Journey_Flag]
      ,[Sent_Date_Text]
  FROM [SrcSFMC].[EMEAEmailData];