CREATE VIEW [DWSFMC].[Standard_Tracking_SendJobs]
AS SELECT [ClientID]
      ,[SendID]
      ,[FromName]
      ,[FromEmail]
      ,[SchedTime]
      ,[SentTime]
      ,[Subject]
      ,[EmailName]
      ,[TriggeredSendExternalKey]
      ,[SendDefinitionExternalKey]
      ,[JobStatus]
      ,[PreviewURL]
      ,[IsMultipart]
      ,[Additional]
  FROM [SrcSFMC].[Standard_Tracking_SendJobs];