CREATE VIEW [DWSFMC].[Standard_Tracking_NotSent]
AS SELECT [ClientID]
      ,[SendID]
      ,[SubscriberKey]
      ,[EmailAddress]
      ,[SubscriberID]
      ,[ListID]
      ,[EventDate]
      ,[EventType]
      ,[BatchID]
      ,[TriggeredSendExternalKey]
      ,[Reason]
  FROM [SrcSFMC].[Standard_Tracking_NotSent];