CREATE VIEW [DWSFMC].[Standard_Tracking_Clicks]
AS SELECT [ClientID]
      ,[SendID]
      ,[SubscriberKey]
      ,[EmailAddress]
      ,[SubscriberID]
      ,[ListID]
      ,[EventDate]
      ,[EventType]
      ,[SendURLID]
      ,[URLID]
      ,[URL]
      ,[Alias]
      ,[BatchID]
      ,[TriggeredSendExternalKey]
      ,[IsUnique]
      ,[IsUniqueForURL]
  FROM [SrcSFMC].[Standard_Tracking_Clicks];