CREATE VIEW [DWSFMC].[Standard_Tracking_Bounces]
AS SELECT [ClientID]
      ,[SendID]
      ,[SubscriberKey]
      ,[EmailAddress]
      ,[SubscriberID]
      ,[ListID]
      ,[EventDate]
      ,[EventType]
      ,[BounceCategory]
      ,[SMTPCode]
      ,[BounceReason]
      ,[BatchID]
      ,[TriggeredSendExternalKey]
  FROM [SrcSFMC].[Standard_Tracking_Bounces];