CREATE TABLE [TABSAP].[FactShipments_Materialized] (
    [ADLSTimestamp]             DATETIME2 (0)   NULL,
    [PartitionColumn]           VARCHAR (25)    NOT NULL,
    [Delivery]                  NVARCHAR (10)   NULL,
    [DeliveryItem]              NVARCHAR (6)    NULL,
    [Deliverable Type]          NVARCHAR (30)   NULL,
    [Value Type]                INT             NOT NULL,
    [Plant]                     NVARCHAR (4)    NULL,
    [Volume unit]               NVARCHAR (3)    NULL,
    [Item Category]             NVARCHAR (4)    NULL,
    [Company Code]              NVARCHAR (4)    NULL,
    [Sales Organization]        NVARCHAR (4)    NULL,
    [DIVISION_KEY]              NVARCHAR (4)    NOT NULL,
    [Shipment Date]             NVARCHAR (15)   NULL,
    [Product Hierarchy]         NVARCHAR (18)   NULL,
    [PROFIT_CENTER_KEY]         NVARCHAR (21)   NOT NULL,
    [Delivered Quantity]        DECIMAL (17, 3) NULL,
    [Sales Order Number]        NVARCHAR (12)   NOT NULL,
    [Sales Order Key]           NVARCHAR (23)   NOT NULL,
    [Deliverable Quantity]      DECIMAL (18)    NOT NULL,
    [Total Quantity]            DECIMAL (21, 3) NOT NULL,
    [Deliverable Category]      NVARCHAR (15)   NULL,
    [Business Segment]          VARCHAR (13)    NULL,
    [TotalOrderQuantity]        DECIMAL (17, 3) NULL,
    [Volume Segment]            NVARCHAR (50)   NULL,
    [Volume Sub-Segment]        NVARCHAR (50)   NULL,
    [Volume Account]            NVARCHAR (41)   NULL,
    [Volume Quantity]           DECIMAL (22, 3) NULL,
    [Volume Quantity Undivided] DECIMAL (22, 3) NULL,
    [Shipment Count]            DECIMAL (13, 3) NULL,
    [Volume Count]              DECIMAL (13, 3) NULL,
    [Order Quantity]            DECIMAL (17, 3) NULL,
    [Order Quantity Undivided]  DECIMAL (17, 3) NULL,
    [Order Count]               DECIMAL (13, 3) NULL,
    [FoC Quantity]              DECIMAL (18)    NOT NULL,
    [Segment]                   NVARCHAR (12)   NULL,
    [COST_ELMNT_KEY]            NVARCHAR (54)   NOT NULL,
    [VolumeFlag]                VARCHAR (15)    NULL,
    [Date of MIM]               NVARCHAR (8)    NULL,
    [Reporting Channel]         DECIMAL (10)    NULL,
    [Reporting Region]          NVARCHAR (10)   NULL,
    [Promotion Bucket]          NVARCHAR (40)   NULL,
    [Equipment Serial Num]      NVARCHAR (18)   NULL,
    [Initiator Company ID]      NVARCHAR (10)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Sales Order Key]));

