--BI-12996 New Table
CREATE TABLE [DWSAP].[ScannerHistoryProcessed_Performance]
(
	[LZBatchID] [int] NULL,
	[ADLSBatchID] [int] NULL,
	[ADLSTimestamp] [datetime2](0) NULL,
	[DWBatchID] [int] NULL,
	[DWTimeStamp] [datetime2](0) NULL,
	[Sales Document] [nvarchar](10) NULL,
	[Item] [nvarchar](6) NULL,
	[Fiscal Year Variant] [nvarchar](2) NULL,
	[Cal. Year/Quarter] [nvarchar](5) NULL,
	[Quarter] [nvarchar](1) NULL,
	[Calender Year/Week] [nvarchar](6) NULL,
	[Fiscal Year] [nvarchar](4) NULL,
	[Fiscal Year/Period] [nvarchar](7) NULL,
	[Posting Period] [nvarchar](3) NULL,
	[Equipment Serial Num] [nvarchar](18) NULL,
	[Initiator Company ID] [nvarchar](10) NULL,
	[Reporting Region] [nvarchar](10) NULL,
	[Event Date] [date] NULL,
	[Document Type] [nvarchar](4) NULL,
	[Document Category] [nvarchar](2) NULL,
	[Item Category] [nvarchar](4) NULL,
	[Deliverable Type] [nvarchar](30) NULL,
	[Treatment Category] [nvarchar](15) NULL,
	[Company Code] [nvarchar](4) NULL,
	[Material] [nvarchar](18) NULL,
	[Product Hierarchy] [nvarchar](18) NULL,
	[CA_PRIMARY] [nvarchar](1) NULL,
	[CA_SECONDARY] [nvarchar](1) NULL,
	[CA_NONCAS] [nvarchar](1) NULL,
	[CA_OTHERS] [nvarchar](1) NULL,
	[CA_UNKNOWN] [nvarchar](1) NULL,
	[ITRO_SCNR] [nvarchar](1) NULL,
	[ITRO_SERV] [nvarchar](1) NULL,
	[Overall Rejection St] [nvarchar](1) NULL,
	[Reason For Rejection] [nvarchar](2) NULL,
	[Rejection Status] [nvarchar](1) NULL,
	[Rejection Date] [nvarchar](8) NULL,
	[Rejection Time] [nvarchar](12) NULL,
	[Document Date] [nvarchar](8) NULL,
	[Created On] [nvarchar](8) NULL,
	[Doc. Condition] [nvarchar](10) NULL,
	[Profit. Segment] [nvarchar](10) NULL,
	[Cost Center] [nvarchar](10) NULL,
	[Controlling Area] [nvarchar](4) NULL,
	[Profit Center] [nvarchar](10) NULL,
	[Cost Element(COPA)] [nvarchar](25) NULL,
	[Compliance Indicator] [nvarchar](10) NULL,
	[AMR DATE] [nvarchar](8) NULL,
	[CCS DATE] [nvarchar](8) NULL,
	[CCA DATE] [nvarchar](8) NULL,
	[External Patient ID] [nvarchar](15) NULL,
	[Source System Order] [nvarchar](12) NULL,
	[Patient ID] [nvarchar](36) NULL,
	[SFDC Order ID] [nvarchar](12) NULL,
	[FoC Quantity] [decimal](4, 0) NULL,
	[Deliverable Quantity] [decimal](5, 0) NULL,
	[Deliverable Quantity for COPA] [decimal](10, 0) NULL,
	[Total Quantity for COPA] [decimal](10, 0) NULL,
	[Sales Unit] [nvarchar](3) NULL,
	[BASE_UOM] [nvarchar](3) NULL,
	[TARGET_QU] [nvarchar](3) NULL,
	[Document Currency] [nvarchar](5) NULL,
	[CML_CF_QTY] [decimal](17, 3) NULL,
	[CML_CD_QTY] [decimal](17, 3) NULL,
	[Order Quantity] [decimal](17, 3) NULL,
	[Target Quantity] [decimal](17, 3) NULL,
	[Withdraw Quantity] [decimal](17, 3) NULL,
	[Net Price] [decimal](17, 3) NULL,
	[Net Value] [decimal](17, 3) NULL,
	[Age Tier] [nvarchar](4) NULL,
	[Reporting Channel] [decimal](2, 0) NULL,
	[Free/Paid] [nvarchar](15) NULL,
	[Sold-to Party] [nvarchar](10) NULL,
	[Customer Group 1] [nvarchar](3) NULL,
	[Customer Group 2] [nvarchar](3) NULL,
	[Customer Group 3] [nvarchar](3) NULL,
	[Customer Group 4] [nvarchar](3) NULL,
	[Customer Group 5] [nvarchar](3) NULL,
	[Sales Group] [nvarchar](3) NULL,
	[Sales Organization] [nvarchar](4) NULL,
	[Distribution Channel] [nvarchar](2) NULL,
	[Storage Location] [nvarchar](4) NULL,
	[Plant] [nvarchar](4) NULL,
	[Material Group] [nvarchar](9) NULL,
	[Bill-to Party] [nvarchar](10) NULL,
	[Ship-to Party] [nvarchar](10) NULL,
	[Division] [nvarchar](2) NULL,
	[Country] [nvarchar](3) NULL,
	[External Treatment ID] [nvarchar](19) NULL,
	[Treatment Option] [nvarchar](30) NULL,
	[Treatment ID] [nvarchar](12) NULL,
	[Max No Of Stages] [nvarchar](3) NULL,
	[Treatment Location] [nvarchar](10) NULL,
	[Treatment Doctor] [nvarchar](10) NULL,
	[Order Stages] [nvarchar](11) NULL,
	[Stages Bucket] [nvarchar](100) NULL,
	[Material Group 1] [nvarchar](5) NULL,
	[Material Group 2] [nvarchar](5) NULL,
	[Material Group 3] [nvarchar](5) NULL,
	[Material Group 4] [nvarchar](5) NULL,
	[Material Group 5] [nvarchar](5) NULL,
	[Territory Manager] [nvarchar](10) NULL,
	[Align Retail] [nvarchar](10) NULL,
	[Financial Contact] [nvarchar](10) NULL,
	[Junior Doctor] [nvarchar](10) NULL,
	[Submitting Student] [nvarchar](10) NULL,
	[Employee Responsible] [nvarchar](10) NULL,
	[Characteristic-Upper] [nvarchar](30) NULL,
	[Characteristic-Lower] [nvarchar](30) NULL,
	[Charac. Value-Upper] [nvarchar](30) NULL,
	[Charac. Value-Lower] [nvarchar](30) NULL,
	[/BIC/ZCLINICAL] [nvarchar](1) NULL,
	[DELIV_NUMB] [nvarchar](10) NULL,
	[DELIV_ITEM] [nvarchar](6) NULL,
	[ACT_GI_DTE] [date] NULL,
	[ACT_DL_QTY] [decimal](17, 3) NULL,
	[DLV_QTY] [decimal](17, 3) NULL,
	[/BIC/SHPMNTCNT] [decimal](10, 0) NULL,
	[/BIC/VOL_SEGMT] [nvarchar](50) NULL,
	[/BIC/VOL_COUNT] [decimal](10, 0) NULL,
	[/BIC/VOL_QUANT] [decimal](17, 3) NULL,
	[/BIC/SEGMENT] [nvarchar](20) NULL,
	[/BIC/VOLSSEGMT] [nvarchar](50) NULL,
	[/BIC/FILEYN] [nvarchar](1) NULL,
	[BILL_DATE] [nvarchar](8) NULL,
	[/BIC/IACTQTY] [decimal](17, 3) NULL,
	[PAYER] [nvarchar](10) NULL,
	[VOLUMEUNIT] [nvarchar](3) NULL,
	[CREA_TIME] [nvarchar](11) NULL,
	[ZALGNUSER] [decimal](8, 0) NULL,
	[/BIC/ZFRE_QTY] [decimal](17, 3) NULL,
	[Total Quantity] [decimal](17, 3) NULL,
	[/BIC/DELV_QTY] [decimal](17, 3) NULL,
	[Promotion Bucket] [nvarchar](40) NULL,
	[Data of MIM] [nvarchar](8) NULL,
	[Event Description] [nvarchar](3) NULL,
	[Process Name] [varchar](6) NULL,
	[Business Segment] [varchar](13) NULL,
	[BASe Unit of MeASure] [varchar](10) NULL,
	[Weight Unit] [varchar](10) NULL,
	[Revenue Recognition] [varchar](10) NULL,
	[Free_Paid] [nvarchar](100) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Sales Document] ),
	CLUSTERED COLUMNSTORE INDEX
)


