CREATE TABLE [DWSAP].[ConfigVolumeTransformations] (
    [MANDT]    NVARCHAR (40) NULL,
    [NAME]     NVARCHAR (80) NULL,
    [NUMB]     NVARCHAR (10) NULL,
    [SIGN]     NVARCHAR (20) NULL,
    [OPTI]     NVARCHAR (10) NULL,
    [OPERAND1] NVARCHAR (50) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

