CREATE TABLE [DWSAP].[DimProfitCenterStd] (
    [Level 1 S]      NVARCHAR (255) NULL,
    [Level 2 S]      NVARCHAR (255) NULL,
    [Level 3 S]      NVARCHAR (255) NULL,
    [Level 4 S]      NVARCHAR (255) NULL,
    [Level 5 S]      NVARCHAR (255) NULL,
    [Level 6 S]      NVARCHAR (255) NULL,
    [Level 7 S]      NVARCHAR (255) NULL,
    [PROFIT CTR S]   NVARCHAR (255) NULL,
    [PRFIT CENTER S] NVARCHAR (255) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

