--BI-12996 New Table
CREATE TABLE [DWSAP].[DimSalesDocumentHeader_Performance]
(
	[ADLSTimestamp] [datetime2](7) NULL,
	[PartitionColumn] [varchar](25) NULL,
	[Sales Document] [nvarchar](10) NULL,
	[Sales Document Type] [char](4) NULL,
	[Sales Document Category] [char](1) NULL,
	[Billing Type] [nvarchar](4) NULL,
	[Order Stages] [decimal](18, 0) NULL,
	[Stage Bucket] [varchar](5) NULL,
	[PatientType] [varchar](9) NULL,
	[SoldTo] [nvarchar](100) NULL,
	[CCADate] [date] NULL,
	[TreatmentCategory] [varchar](15) NULL,
	[ClinID] [nvarchar](100) NULL,
	[Advantage Program Name] [nvarchar](20) NULL,
	[MAF] [varchar](7) NULL,
	[Sales Org] [char](4) NULL,
	[Division] [char](2) NULL,
	[Compliance Indicator] [varchar](10) NULL,
	[PO Number] [nvarchar](20) NULL,
	[IDSOrderID] [varchar](12) NULL,
	[SFDCOrderID] [varchar](12) NULL,
	[Distribution Channel] [char](2) NULL,
	[Sales Group] [char](3) NULL,
	[Sales Office] [char](4) NULL,
	[Controlling Area] [nvarchar](4) NULL,
	[Purchasing Org] [nvarchar](4) NULL,
	[Unit of Dimension for length/Width/Height] [varchar](1) NULL,
	[Bill-to party] [nvarchar](1300) NULL,
	[Payer] [nvarchar](255) NULL,
	[Country of ship-to party] [nvarchar](50) NULL,
	[Customer Group1] [nvarchar](3) NULL,
	[Customer Group2] [nvarchar](3) NULL,
	[Customer Group3] [nvarchar](3) NULL,
	[Customer Group4] [nvarchar](3) NULL,
	[Customer Group5] [nvarchar](3) NULL,
	[Equipment Serial Num] [nvarchar](18) NULL,
	[Initiator Company Id] [varchar](10) NULL,
	[Document Year] [int] NULL,
	[UpperAlignerStartstage] [int] NULL,
	[UpperAlignerEndStage] [int] NULL,
	[LowerAlignerStartstage] [int] NULL,
	[LowerAlignerEndStage] [int] NULL,
	[CustomerGroupType] [nvarchar](255) NULL,
	[AgeTierRange] [nvarchar](30) NULL,
	[AgeTierDetail] [nvarchar](30) NULL,
	[AgeSegment] [nvarchar](30) NULL,
	[AgeCategory] [nvarchar](15) NULL,
	[TreatmentId] [varchar](12) NULL,
	[ECC_CCADate] [date] NULL,
	[Total Net Amount] [decimal](15, 3) NULL,
	[Document Date] [nvarchar](10) NULL,
	[RecordType] [nvarchar](15) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Sales Document] ),
	CLUSTERED COLUMNSTORE INDEX
)