CREATE TABLE [DWSAP].[DimSalesDocument] (
    [ADLSTimestamp]                             DATETIME2 (0)   NULL,
    [PartitionColumn]                           VARCHAR (25)    NULL,
    [Sales Document]                            NVARCHAR (10)   NULL,
    [Sales Document Item]                       NVARCHAR (6)    NULL,
    [OrderQuantity]                             DECIMAL (15, 3) NULL,
    [Sales Document Type]                       CHAR (4)        NULL,
    [Sales Document Category]                   CHAR (1)        NULL,
    [Item Category-Sales Document]              NVARCHAR (4)    NULL,
    [Billing Type]                              NVARCHAR (4)    NULL,
    [Age Tier]                                  DECIMAL (18)    NULL,
    [Order Stages]                              DECIMAL (18)    NULL,
    [Stage Bucket]                              VARCHAR (5)     NULL,
    [PatientType]                               VARCHAR (9)     NULL,
    [ProductType]                               NVARCHAR (1300) NULL,
    [TreatingDoctor]                            NVARCHAR (1300) NULL,
    [ShipTo]                                    NVARCHAR (4000) NULL,
    [SoldTo]                                    NVARCHAR (1300) NULL,
    [CCADate]                                   DATE            NULL,
    [TreatmentCategory]                         VARCHAR (15)    NULL,
    [TreatmentLocation]                         NVARCHAR (1300) NULL,
    [ClinID]                                    NVARCHAR (1300) NULL,
    [Is IO Scan]                                VARCHAR (3)     NULL,
    [Professional Category]                     NVARCHAR (50)   NULL,
    [Advantage Tier]                            NVARCHAR (255)  NULL,
    [Advantage Program Name]                    NVARCHAR (20)   NULL,
    [MAF]                                       VARCHAR (7)     NULL,
    [Sales Org]                                 CHAR (4)        NULL,
    [Division]                                  CHAR (2)        NULL,
    [Sales Order Key]                           NVARCHAR (17)   NULL,
    [Compliance Indicator]                      VARCHAR (10)    NULL,
    [Free_Paid]                                 VARCHAR (5)     NULL,
    [PO Number]                                 NVARCHAR (20)   NULL,
    [Treatment Option]                          NVARCHAR (30)   NULL,
    [Deliverable Type]                          NVARCHAR (30)   NULL,
    [IDSOrderID]                                VARCHAR (12)    NULL,
    [SFDCOrderID]                               VARCHAR (12)    NULL,
    [Material Group]                            NVARCHAR (9)    NULL,
    [Material Number]                           NVARCHAR (18)   NULL,
    [Material Group 1]                          NVARCHAR (3)    NULL,
    [Material Group 2]                          NVARCHAR (3)    NULL,
    [Material Group 3]                          NVARCHAR (3)    NULL,
    [Material Group 4]                          NVARCHAR (3)    NULL,
    [Material Group 5]                          NVARCHAR (3)    NULL,
    [Distribution Channel]                      CHAR (2)        NULL,
    [Sales Group]                               CHAR (3)        NULL,
    [Sales Office]                              CHAR (4)        NULL,
    [Controlling Area]                          NVARCHAR (4)    NULL,
    [Purchasing Org]                            NVARCHAR (4)    NULL,
    [Base Unit of Measure]                      NVARCHAR (3)    NULL,
    [Sales Unit]                                NVARCHAR (3)    NULL,
    [Unit of Dimension for length/Width/Height] VARCHAR (1)     NULL,
    [Volume Unit]                               NVARCHAR (3)    NULL,
    [Weight Unit]                               NVARCHAR (3)    NULL,
    [Bill-to party]                             NVARCHAR (1300) NULL,
    [Payer]                                     NVARCHAR (255)  NULL,
    [Country of ship-to party]                  NVARCHAR (50)   NULL,
    [Customer Group1]                           NVARCHAR (3)    NULL,
    [Customer Group2]                           NVARCHAR (3)    NULL,
    [Customer Group3]                           NVARCHAR (3)    NULL,
    [Customer Group4]                           NVARCHAR (3)    NULL,
    [Customer Group5]                           NVARCHAR (3)    NULL,
    [Equipment Serial Num]                      NVARCHAR (18)   NULL,
    [Initiator Company Id]                      VARCHAR (10)    NULL,
    [AMR Date COPA]                             CHAR (8)        NULL,
    [Promotion Bucket]                          NVARCHAR (6)    NULL,
    [Revenue Recognition]                       NVARCHAR (8)    NULL,
    [Total Quantity]                            DECIMAL (18)    NULL,
    [Document Date]                             NVARCHAR (8)    NULL,
    [Document Year]                             INT             NULL,
    [UpperAlignerStartstage]                    INT             NULL,
    [UpperAlignerEndStage]                      INT             NULL,
    [LowerAlignerStartstage]                    INT             NULL,
    [LowerAlignerEndStage]                      INT             NULL,
    [CustomerGroupType]                         NVARCHAR (255)  NULL,
    [IsDSOOrder]                                VARCHAR (3)     NULL,
    [Storage Location]                          NVARCHAR (4)    NULL,
    [Align Retail]                              NVARCHAR (10)   NULL,
    [Employee Responsible]                      NVARCHAR (10)   NULL,
    [Financial Contact]                         NVARCHAR (10)   NULL,
    [Junior Doctor]                             NVARCHAR (10)   NULL,
    [Submitting Student]                        NVARCHAR (10)   NULL,
    [Territory Manager]                         NVARCHAR (10)   NULL,
    [AgeTierRange]                              NVARCHAR (30)   NULL,
    [AgeTierDetail]                             NVARCHAR (30)   NULL,
    [AgeSegment]                                NVARCHAR (30)   NULL,
    [AgeCategory]                               NVARCHAR (15)   NULL,
    [Material Text]                             NVARCHAR (40)   NULL,
    [Bill-to party text]                        NVARCHAR (255)  NULL,
    [ShipTo Text]                               NVARCHAR (255)  NULL,
    [SoldTo Text]                               NVARCHAR (255)  NULL,
    [TreatmentId]                               VARCHAR (12)    NULL,
    [Order Quantity]                            DECIMAL (17, 3) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Sales Document]));

