--BI-12996 New Table
CREATE TABLE [DWSAP].[FactCOPATranspose_Performance]
(
	[LZBatchID] [int] NULL,
	[ADLSTimestamp] [datetime2](0) NULL,
	[MANDT] [nvarchar](3) NULL,
	[PALEDGER] [nvarchar](2) NULL,
	[CURTP] [nvarchar](2) NULL,
	[VRGAR] [nvarchar](1) NULL,	
	[VERSI] [nvarchar](3) NULL,
	[PERIO] [nvarchar](7) NULL,
	[PAOBJNR] [nvarchar](10) NULL,
	[PASUBNR] [nvarchar](4) NULL,
	[BELNR] [nvarchar](10) NULL,
	[POSNR] [bigint] NULL,
	[HZDAT] [nvarchar](8) NULL,
	[USNAM] [nvarchar](12) NULL,
	[GJAHR] [nvarchar](4) NULL,
	[PERDE] [nvarchar](3) NULL,
	[WADAT] [nvarchar](8) NULL,
	[FADAT] [nvarchar](8) NULL,
	[BUDAT] [nvarchar](8) NULL,
	[ALTPERIO] [nvarchar](7) NULL,
	[PAPAOBJNR] [nvarchar](10) NULL,
	[PAPASUBNR] [nvarchar](4) NULL,
	[KNDNR] [nvarchar](10) NULL,
	[ARTNR] [nvarchar](18) NULL,
	[FKART] [nvarchar](4) NULL,
	[FRWAE] [nvarchar](5) NULL,
	[KURSF] [decimal](9, 5) NULL,
	[KURSBK] [decimal](9, 5) NULL,
	[KURSKZ] [decimal](9, 5) NULL,
	[REC_WAERS] [nvarchar](5) NULL,
	[KAUFN] [bigint] NULL,
	[KDPOS] [bigint] NULL,
	[OGKAUFN] [nvarchar](10) NULL,
	[OGKDPOS] [nvarchar](6) NULL,
	[RKAUFNR] [nvarchar](12) NULL,
	[SKOST] [nvarchar](10) NULL,
	[PRZNR] [nvarchar](12) NULL,
	[BUKRS] [nvarchar](4) NULL,
	[KOKRS] [nvarchar](4) NULL,
	[WERKS] [nvarchar](4) NULL,
	[GSBER] [nvarchar](4) NULL,
	[VKORG] [nvarchar](4) NULL,
	[VTWEG] [nvarchar](2) NULL,
	[SPART] [nvarchar](2) NULL,
	[HRKFT] [nvarchar](4) NULL,
	[PLIKZ] [nvarchar](1) NULL,
	[KSTAR] [nvarchar](10) NULL,
	[PSPNR] [nvarchar](8) NULL,
	[KSTRG] [nvarchar](12) NULL,
	[RBELN] [bigint] NULL,
	[RPOSN] [bigint] NULL,
	[STO_BELNR] [nvarchar](10) NULL,
	[STO_POSNR] [nvarchar](6) NULL,
	[PRCTR] [nvarchar](10) NULL,
	[PPRCTR] [nvarchar](10) NULL,
	[RKESTATU] [nvarchar](10) NULL,
	[TIMESTMP] [decimal](16, 0) NULL,
	[COPA_AWTYP] [nvarchar](5) NULL,
	[COPA_AWORG] [nvarchar](10) NULL,
	[COPA_BWZPT] [nvarchar](1) NULL,
	[COPA_AWSYS] [nvarchar](10) NULL,
	[BESKZ] [nvarchar](1) NULL,
	[KDGRP] [nvarchar](2) NULL,
	[KUNRE] [nvarchar](10) NULL,
	[KUNWE] [nvarchar](10) NULL,
	[LAND1] [nvarchar](3) NULL,
	[PSTYV] [nvarchar](4) NULL,
	[VKBUR] [nvarchar](4) NULL,
	[VRTNR] [nvarchar](8) NULL,
	[WWCST] [nvarchar](3) NULL,
	[WWCH2] [nvarchar](3) NULL,
	[WWSIZ] [nvarchar](3) NULL,
	[WWICI] [nvarchar](1) NULL,
	[COPA_KOSTL] [nvarchar](10) NULL,
	[VKGRP] [nvarchar](3) NULL,
	[WW010] [nvarchar](2) NULL,
	[WW021] [nvarchar](30) NULL,
	[WW022] [nvarchar](12) NULL,
	[PLTYP] [nvarchar](2) NULL,
	[BZIRK] [nvarchar](6) NULL,
	[WW023] [nvarchar](10) NULL,
	[MATKL] [nvarchar](9) NULL,
	[KVGR1] [nvarchar](3) NULL,
	[KVGR2] [nvarchar](3) NULL,
	[WW025] [decimal](10, 3) NULL,
	[WWA01] [decimal](10, 3) NULL,
	[WWA02] [decimal](10, 3) NULL,
	[AUART] [nvarchar](4) NULL,
	[WW027] [nvarchar](10) NULL,
	[WW028] [nvarchar](10) NULL,
	[WWFT1] [nvarchar](18) NULL,
	[WWFT2] [nvarchar](18) NULL,
	[WWFT3] [nvarchar](18) NULL,
	[WWFT4] [nvarchar](18) NULL,
	[WWFT5] [nvarchar](18) NULL,
	[WWFT6] [nvarchar](18) NULL,
	[WWFT7] [nvarchar](18) NULL,
	[WWFT8] [nvarchar](18) NULL,
	[WWFT9] [nvarchar](18) NULL,
	[AUGRU] [nvarchar](3) NULL,
	[ABGRU] [nvarchar](2) NULL,
	[ABSMG_ME] [nvarchar](3) NULL,
	[ABSMG] [decimal](15, 3) NULL,
	[ERLOS] [decimal](15, 2) NULL,
	[KWKDRB] [decimal](15, 2) NULL,
	[KWMARB] [decimal](15, 2) NULL,
	[MRABA] [decimal](15, 2) NULL,
	[KWMKPR] [decimal](15, 2) NULL,
	[VVFGS] [decimal](15, 2) NULL,
	[RABAT] [decimal](15, 2) NULL,
	[KWSKTO] [decimal](15, 2) NULL,
	[ValueField] [nvarchar](128) NULL,
	[ColumnValue] [decimal](19, 2) NULL,
	[DWBatchID] [varchar](1) NULL,
	[ZPROCESS] [nvarchar](20) NULL,
	[BUSSEGMNT] [varchar](13) NULL,
	[SPRAS] [varchar](1) NULL,
	[WW015] [int] NULL,
	[PRODH] [nvarchar](18) NULL,
	[vbapWERKS] [nvarchar](4) NULL,
	[vbapPSTYV] [nvarchar](4) NULL,
	[vbapZZDELI_TYPE] [nvarchar](30) NULL,
	[DDTEXT] [nvarchar](60) NULL,
	[LTEXT] [nvarchar](40) NULL,
	[IncentiveName] [nvarchar](123) NULL,
	[vbapMVGR1] [nvarchar](3) NULL,
	[vbapMVGR2] [nvarchar](3) NULL,
	[vbapMVGR3] [nvarchar](3) NULL,
	[vbapMVGR4] [nvarchar](3) NULL,
	[vbapMVGR5] [nvarchar](3) NULL,
	[vbapVRKME] [nvarchar](3) NULL,
	[vbapVOLEH] [nvarchar](3) NULL,
	[vbapGEWEI] [nvarchar](3) NULL,
	[vbapZZTREAT_OPT] [nvarchar](30) NULL,
	[vbapZZTREV_DATE] [nvarchar](8) NULL,
	[vbapMEINS] [nvarchar](3) NULL,
	[vbapLGORT] [nvarchar](4) NULL,
	[vbapMATNR] [nvarchar](18) NULL,
	[FreePaid] [varchar](5) NULL,
	[VBAPZZPROMO] [nvarchar](6) NULL,
	[VBAPAUDAT] [nvarchar](8) NULL,
	[VBAPKWMENG] [decimal](15, 3) NULL,
	[VBAPZZTOTAL_QTY] [smallint] NULL,
	[VBAPVBELN] [bigint] NULL,
	[Compliance Indicator] [nvarchar](10) NULL,
	[VBAPPOSNR] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)