--BI-12996 New Table
CREATE TABLE [DWSAP].[FactShipments_Materialized_Performance]
(
	[ADLSTimestamp] [datetime2](0) NULL,
	[PartitionColumn] [varchar](25) NULL,
	[Delivery] [nvarchar](10) NULL,
	[DeliveryItem] [nvarchar](6) NULL,
	[Deliverable Type] [nvarchar](30) NULL,
	[Value Type] [int] NULL,
	[Plant] [nvarchar](4) NULL,
	[Volume unit] [nvarchar](3) NULL,
	[Item Category] [nvarchar](4) NULL,
	[Company Code] [nvarchar](4) NULL,
	[Sales Organization] [nvarchar](4) NULL,
	[DIVISION_KEY] [nvarchar](4) NULL,
	[Shipment Date] [nvarchar](15) NULL,
	[Product Hierarchy] [nvarchar](18) NULL,
	[PROFIT_CENTER_KEY] [nvarchar](21) NULL,
	[Delivered Quantity] [decimal](17, 3) NULL,
	[Sales Order Number] [nvarchar](12) NULL,
	[Sales Order Item Number] [nvarchar](12) NULL,
	[Sales Order Key] [nvarchar](23) NULL,
	[Deliverable Quantity] [decimal](18, 0) NULL,
	[Total Quantity] [decimal](21, 3) NULL,
	[Deliverable Category] [nvarchar](15) NULL,
	[Business Segment] [varchar](13) NULL,
	[TotalOrderQuantity] [decimal](17, 3) NULL,
	[Volume Segment] [nvarchar](50) NULL,
	[Volume Sub-Segment] [nvarchar](50) NULL,
	[Volume Account] [nvarchar](41) NULL,
	[Volume Quantity] [decimal](22, 3) NULL,
	[Volume Quantity Undivided] [decimal](22, 3) NULL,
	[Shipment Count] [decimal](13, 3) NULL,
	[Volume Count] [decimal](13, 3) NULL,
	[Order Quantity] [decimal](17, 3) NULL,
	[Order Quantity Undivided] [decimal](17, 3) NULL,
	[Order Count] [decimal](13, 3) NULL,
	[FoC Quantity] [decimal](18, 0) NULL,
	[Segment] [nvarchar](12) NULL,
	[COST_ELMNT_KEY] [nvarchar](54) NULL,
	[VolumeFlag] [varchar](15) NULL,
	[Date of MIM] [nvarchar](8) NULL,
	[Reporting Channel] [decimal](10, 0) NULL,
	[Reporting Region] [nvarchar](10) NULL,
	[Promotion Bucket] [nvarchar](40) NULL,
	[Equipment Serial Num] [nvarchar](18) NULL,
	[Initiator Company ID] [nvarchar](10) NULL,
	[Material Group 1] [nvarchar](3) NULL,
	[Material Group 2] [nvarchar](3) NULL,
	[Material Group 3] [nvarchar](3) NULL,
	[Material Group 4] [nvarchar](3) NULL,
	[Material Group 5] [nvarchar](3) NULL,
	[Base Unit of Measure] [nvarchar](10) NULL,
	[Sales Unit] [nvarchar](3) NULL,
	[Weight Unit] [nvarchar](10) NULL,
	[Revenue Recognition] [nvarchar](20) NULL,
	[Document Date] [nvarchar](8) NULL,
	[Storage Location] [nvarchar](4) NULL,
	[Treatment Option] [nvarchar](30) NULL,
	[Delete Flag] [int] NULL,
	[Free_Paid] [nvarchar](255) NULL,
	[Material Number] [nvarchar](50) NULL,
	[COMPLIANCE INDICATOR] [nvarchar](20) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Sales Order Number] ),
	CLUSTERED COLUMNSTORE INDEX
)