CREATE TABLE [DWSAP].[Incremental_Datetime] (
    [PREVIOUS_DATETIME] DATETIME2 (7) NULL,
    [CURRENT_DATETIME]  DATETIME2 (7) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

