CREATE TABLE [DWSAP].[OperationsMaterialDocumentItem]
(
	[AccountingDocument] [bigint] NULL,
	[AccountingDocumentItem] [int] NULL,
	[BASeUnit] [nvarchar](25) NULL,
	[Batch] [nvarchar](15) NULL,
	[BusinessArea] [nvarchar](25) NULL,
	[CompanyCode] [nvarchar](25) NULL,
	[Amount in Local Currency] [decimal](38, 3) NULL,
	[ConsumptionPosting] [nvarchar](10) NULL,
	[ControllingArea] [nvarchar](25) NULL,
	[CostCenter] [nvarchar](25) NULL,
	[CustomerAccountNumber] [nvarchar](25) NULL,
	[DebitCreditCode] [nvarchar](25) NULL,
	[EnteredDate] [date] NULL,
	[FiscalYear] [nvarchar](25) NULL,
	[GLAccount] [nvarchar](25) NULL,
	[Movement Type] [nvarchar](10) NULL,
	[InventorySpecialStockType] [nvarchar](10) NULL,
	[InventoryValuationType] [nvarchar](15) NULL,
	[IsCompletelyDelivered] [nvarchar](20) NULL,
	[Material Number] [nvarchar](36) NULL,
	[MaterialDocument] [bigint] NULL,
	[MaterialDocumentYear] [int] NULL,
	[MaterialPriceControl] [decimal](20, 3) NULL,
	[Order] [nvarchar](25) NULL,
	[PartnerProfitCenter] [nvarchar](15) NULL,
	[Material Plant] [nvarchar](10) NULL,
	[Posting Date] [date] NULL,
	[YearMonth] [bigint] NULL,
	[ProfitCenter] [nvarchar](10) NULL,
	[ProfitabilitySegment] [nvarchar](25) NULL,
	[PurchASeOrderPriceUnit] [nvarchar](25) NULL,
	[PurchASingDocument] [nvarchar](15) NULL,
	[PurchASingDocumentItem] [nvarchar](25) NULL,
	[PurchASingDocumentOrderQty] [nvarchar](25) NULL,
	[SAPClient] [nvarchar](15) NULL,
	[SalesDocument] [bigint] NULL,
	[SalesOrderItem] [int] NULL,
	[ShelfLifeExpirationDate] [nvarchar](20) NULL,
	[StorageBin] [nvarchar](15) NULL,
	[StorageLocation] [nvarchar](10) NULL,
	[StorageType] [nvarchar](10) NULL,
	[TotVltdStockValueInCoCodeCrcy] [decimal](13, 3) NULL,
	[TotalVltdStockQuantity] [decimal](13, 3) NULL,
	[Vendor] [nvarchar](20) NULL,
	[Warehouse] [nvarchar](10) NULL,
	[WarehouseMvtType] [nvarchar](25) NULL,
	[WarehouseStockCategory] [nvarchar](20) NULL,
	[AmountInCompanyCodeCurrency] [decimal](38, 3) NULL,
	[QuantityInBASeUnit] [nvarchar](25) NULL,
	[GoodsMovementEntryQty] [decimal](38, 3) NULL,
	[PurchASeOrderQty] [decimal](38, 3) NULL,
	[GdsMvtExtAmtInCoCodeCrcy] [decimal](38, 3) NULL,
	[PurchASeDocumentOrderQty] [decimal](38, 3) NULL,
	[Amount in Local Currency2] [decimal](38, 3) NULL,
	[Local Currency] [nvarchar](15) NULL,
	[Local Currency2] [nvarchar](25) NULL,
	[ADLSTimestamp] [datetime2](0) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [SalesDocument] ),
	CLUSTERED COLUMNSTORE INDEX
)