CREATE TABLE [DWSAP].[OperationsSalesDeliveryDetails]
(
	[Sales Document] [bigint] NULL,
	[Sales Document Line Item] [int] NULL,
	[Delivery Document] [nvarchar](10) NULL,
	[Sales Document Item Category] [nvarchar](4) NULL,
	[Sales Group] [char](3) NULL,
	[Actual Goods Movement Date] [date] NULL,
	[Profit Center] [nvarchar](10) NULL,
	[Material] [nvarchar](18) NULL,
	[Product Hierarchy Node] [nvarchar](18) NULL,
	[Treatment Option] [nvarchar](30) NULL,
	[DeliverableType] [nvarchar](30) NULL,
	[Additional Customer Group1] [nvarchar](3) NULL,
	[Sales Order Count] [int] NULL,
	[Attachment Template Quantity] [decimal](18, 0) NULL,
	[TotalQuantity] [decimal](18, 0) NULL,
	[DeliverableQuantity] [decimal](18, 0) NULL,
	[Production Plant] [nvarchar](4) NULL,
	[Treatment Category] [varchar](15) NULL,
	[Sales Order Type] [char](4) NULL,
	[SFDC Order ID] [varchar](12) NULL,
	[IDS Order ID] [varchar](12) NULL,
	[Treatment ID] [varchar](12) NULL,
	[CCA Date] [date] NULL,
	[AMR Date] [char](8) NULL,
	[Sold To Party] [nvarchar](1300) NULL,
	[Bill To Party] [nvarchar](1300) NULL,
	[TreatmentLocationName] [nvarchar](255) NULL,
	[Treating Doctor Name] [nvarchar](121) NULL,
	[Total Net Amount] [decimal](15, 2) NULL,
	[Total Net Amount Unit/Currency] [nvarchar](5) NULL,
	[Order Quantity] [decimal](15, 3) NULL,
	[FOCQuantity] [decimal](18, 0) NULL,
	[Original Delivery Quantity] [decimal](13, 3) NULL,
	[Actual Delivery Quantity] [decimal](13, 3) NULL,
	[Compliance Indicator] [varchar](10) NULL,
	[Division] [nvarchar](2) NULL,
	[Distribution Channel] [char](2) NULL,
	[Contact Professional Category] [nvarchar](50) NULL,
	[Mandular Adjustment Flag] [varchar](7) NULL,
	[DSO Flag] [varchar](3) NULL,
	[Production Plant Name] [nvarchar](30) NULL,
	[Additional Customer Group1 Description] [nvarchar](30) NULL,
	[ADLSTimestamp] [datetime2](0) NULL,
	[YearMonth] [bigint] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Sales Document] ),
	CLUSTERED COLUMNSTORE INDEX
)