CREATE TABLE [DWSAP].[RevRecShipVolProcessed_Performance]
(
	[LZBATCHID] [int] NOT NULL,
	[ADLSBATCHID] [int] NOT NULL,
	[ADLSTIMESTAMP] [datetime2](0) NOT NULL,
	[DWBATCHID] [int] NULL,
	[DWTIMESTAMP] [datetime2](0) NULL,
	[PROFITCENTER] [nvarchar](10) NOT NULL,
	[ORDERNUMBER] [nvarchar](4000) NULL,
	[PARTNUMBER] [nvarchar](6) NOT NULL,
	[DOCUMENTTYPE] [nvarchar](4) NOT NULL,
	[INVOICEDATE] [nvarchar](8) NOT NULL,
	[COUNT] [decimal](4, 0) NOT NULL,
	[FISCAL VARIANT] [varchar](2) NOT NULL,
	[FILEYN] [varchar](1) NOT NULL,
	[CREATEDONDATE] [date] NULL,
	[CREATEDON] [datetime] NOT NULL,
	[USER] [nvarchar](128) NULL,
	[SEGMENT] [varchar](16) NOT NULL,
	[VOLUME SEGMENT] [varchar](16) NOT NULL,
	[VOLUME SUB-SEGMENT] [varchar](16) NOT NULL,
	[COST ELEMENT] [varchar](30) NOT NULL,
	[PROCESS NAME] [varchar](6) NOT NULL,
	[TREATMENTLOCATION] [nvarchar](1300) NULL,
	[TREATINGDOCTOR] [nvarchar](1300) NULL,
	[BUSINESS SEGMENT] [varchar](13) NULL,
	[DELIVERY] [bigint] NULL,
	[DELIVERY_ITEM] [int] NULL,
	[PRODUCT HIERARCHY] [nvarchar](18) NULL,
	[VOLUME] [decimal](15, 3) NULL,
	[VOLUME UNIT] [nvarchar](3) NULL,
	[SHIP-TO PARTY] [nvarchar](1300) NULL,
	[SOLD-TO PARTY] [nvarchar](1300) NULL,
	[NET WEIGHT] [decimal](15, 3) NULL,
	[TOTAL WEIGHT] [decimal](15, 3) NULL,
	[SALES ORGANIZATION] [nvarchar](4) NULL,
	[SHIPMENT DATE] [nvarchar](8) NULL,
	[Serial Number] [nvarchar](18) NULL,
	[Initiator Company ID] [nvarchar](10) NULL,
	[DIVISION] [nvarchar](2) NULL,
	[CONTROLLING AREA] [nvarchar](4) NULL,
	[MATERIAL NUMBER] [nvarchar](18) NULL,
	[DELIVERY QUANTITY] [decimal](13, 3) NULL,
	[ITEM CATEGORY] [nvarchar](4) NULL,
	[SALESORDER ITEM] [nvarchar](4000) NULL,
	[TOTAL QUANTITY] [decimal](10, 2) NULL,
	[DELIVERABLE QUANTITY] [decimal](10, 2) NULL,
	[TREATMENT CATEGORY] [nvarchar](15) NULL,
	[DELIVERABLE TYPE] [nvarchar](30) NULL,
	[AGE TIER] [decimal](18, 0) NULL,
	[ORDER QUANTITY] [decimal](15, 3) NULL,
	[DELIVERABLE CATEGORY] [nvarchar](15) NULL,
	[COMPLIANCE INDICATOR] [nvarchar](10) NULL,
	[VOLUMEFLAG] [varchar](14) NOT NULL,
	[REPORTING CHANNEL] [int] NOT NULL,
	[PLANT] [nvarchar](3) NULL,
	[DELIVERYITEM] [nvarchar](6) NULL,
	[Material Group 1] [nvarchar](5) NULL,
	[Material Group 2] [nvarchar](5) NULL,
	[Material Group 3] [nvarchar](5) NULL,
	[Material Group 4] [nvarchar](5) NULL,
	[Material Group 5] [nvarchar](5) NULL,
	[Base Unit of Measure] [nvarchar](10) NULL,
	[Sales Unit] [nvarchar](3) NULL,
	[Weight Unit] [nvarchar](10) NULL,
	[Promotion Bucket] [nvarchar](20) NULL,
	[Revenue Recognition] [nvarchar](20) NULL,
	[Document Date] [nvarchar](8) NULL,
	[Storage Location] [nvarchar](4) NULL,
	[Treatment Option] [nvarchar](30) NULL,
	[Free_Paid] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [ORDERNUMBER] ),
	CLUSTERED COLUMNSTORE INDEX
)