--BI-12996 New Table
CREATE TABLE [DWSAP].[ScannerRevenueUnitProcessed_Performance]
(
	[LZBatchID] [int] NULL,
	[ADLSBatchID] [int] NULL,
	[ADLSTimestamp] [datetime2](0) NULL,
	[DWBatchID] [int] NULL,
	[DWTimeStamp] [datetime2](0) NULL,
	[SalesOrder] [nvarchar](10) NULL,
	[EventDate] [nvarchar](8) NULL,
	[Ship-ToParty] [nvarchar](1300) NULL,
	[Sold-ToParty] [nvarchar](1300) NULL,
	[SalesOrderType] [nvarchar](4) NULL,
	[VolumeUnit] [nvarchar](3) NULL,
	[ProfitCenter] [nvarchar](16) NULL,
	[Material] [nvarchar](18) NULL,
	[CompanyCode] [nvarchar](4) NULL,
	[PGIDate] [nvarchar](8) NULL,
	[Product Hierarchy] [nvarchar](18) NULL,
	[Item Category] [nvarchar](4) NULL,
	[PromoBucket] [nvarchar](40) NULL,
	[DateofMIM] [nvarchar](8) NULL,
	[Fiscal Variant] [varchar](2) NULL,
	[FileYN] [varchar](1) NULL,
	[CreatedOnDate] [date] NULL,
	[CreatedOn] [datetime] NULL,
	[User] [nvarchar](128) NULL,
	[itro_scr] [varchar](1) NULL,
	[itro_serv] [varchar](1) NULL,
	[Shipment Count] [varchar](1) NULL,
	[Segment] [varchar](13) NULL,
	[Volume Segment] [varchar](20) NULL,
	[Volume Sub-Segment] [varchar](20) NULL,
	[Cost Element(COPA)] [varchar](20) NULL,
	[Sales Group] [nvarchar](50) NULL,
	[Controlling Area] [int] NULL,
	[Process Name] [varchar](6) NULL,
	[Business Segment] [varchar](13) NULL,
	[ActualDeliveryQuantity] [decimal](13, 3) NULL,
	[Age Tier] [decimal](18, 0) NULL,
	[Volume] [decimal](15, 3) NULL,
	[Net Weight] [decimal](15, 3) NULL,
	[Total Weight] [decimal](15, 3) NULL,
	[Delivery] [nvarchar](10) NULL,
	[Treatment Category] [nvarchar](15) NULL,
	[Document_Category] [nvarchar](1) NULL,
	[Delivery Type] [nvarchar](30) NULL,
	[Reason Rejection] [nvarchar](2) NULL,
	[KNUM] [nvarchar](10) NULL,
	[Profitability segment] [nvarchar](10) NULL,
	[CostCenter] [nvarchar](10) NULL,
	[Compliance Indicator] [nvarchar](10) NULL,
	[Serial Number] [nvarchar](18) NULL,
	[Initiator Company ID] [nvarchar](10) NULL,
	[AMR Date] [nvarchar](8) NULL,
	[CCS Date] [nvarchar](8) NULL,
	[CCADate] [date] NULL,
	[External Patient ID] [nvarchar](15) NULL,
	[Source System Order] [nvarchar](12) NULL,
	[SFDC Order ID] [nvarchar](12) NULL,
	[FoC Quantity] [decimal](10, 2) NULL,
	[Deliverable Quantity] [decimal](10, 2) NULL,
	[Sales Unit] [nvarchar](3) NULL,
	[Target Qu] [nvarchar](3) NULL,
	[Target Qty] [decimal](13, 3) NULL,
	[Document Currency] [nvarchar](5) NULL,
	[Net Price] [decimal](11, 2) NULL,
	[Net Value] [decimal](15, 2) NULL,
	[Customer Group1] [nvarchar](3) NULL,
	[Customer Group2] [nvarchar](3) NULL,
	[Customer Group3] [nvarchar](3) NULL,
	[Customer Group4] [nvarchar](3) NULL,
	[Customer Group5] [nvarchar](3) NULL,
	[SalesOrder Item] [nvarchar](4000) NULL,
	[Sales Organization] [nvarchar](4) NULL,
	[Distribution Channel] [nvarchar](2) NULL,
	[Storage Location] [nvarchar](4) NULL,
	[Division] [nvarchar](2) NULL,
	[External Treatment I] [nvarchar](19) NULL,
	[Treatment Option] [nvarchar](30) NULL,
	[ZZTREATMENT] [nvarchar](12) NULL,
	[MaxNoOfStages] [nvarchar](3) NULL,
	[TreatmentLocation] [nvarchar](1300) NULL,
	[TreatingDoctor] [nvarchar](1300) NULL,
	[OrderStages] [decimal](18, 0) NULL,
	[StagesBucket] [varchar](5) NULL,
	[MaterialGroup1] [nvarchar](3) NULL,
	[MaterialGroup2] [nvarchar](3) NULL,
	[MaterialGroup3] [nvarchar](3) NULL,
	[MaterialGroup4] [nvarchar](3) NULL,
	[MaterialGroup5] [nvarchar](3) NULL,
	[ClinicalStudy] [nvarchar](1) NULL,
	[Total Quantity] [decimal](10, 2) NULL,
	[CA_PRIMRY] [varchar](1) NULL,
	[CA_SECNDRY] [varchar](1) NULL,
	[CA_NONCAS] [varchar](1) NULL,
	[CA_OTHERS] [varchar](1) NULL,
	[ReasonRejection] [nvarchar](2) NULL,
	[Order Quantity] [decimal](15, 3) NULL,
	[Withdraw Quantity] [decimal](13, 3) NULL,
	[Delivery Quantity] [decimal](13, 3) NULL,
	[DeliveryItem] [nvarchar](6) NULL,
	[ActualsGoodIssueDate] [nvarchar](8) NULL,
	[Reporting Channel] [int] NULL,
	[Document Date] [nvarchar](8) NULL,
	[CertificationDate] [date] NULL,
	[CertificationYear] [int] NULL,
	[AdvantageTier] [nvarchar](255) NULL,
	[ProfessionalCategory] [nvarchar](50) NULL,
	[Country] [nvarchar](50) NULL,
	[CountryGroup] [nvarchar](50) NULL,
	[RegionPC] [nvarchar](50) NULL,
	[RegionGroup] [nvarchar](50) NULL,
	[GlobalRegion] [nvarchar](32) NULL,
	[Reporting Region] [nvarchar](10) NULL,
	[Plant] [nvarchar](4) NULL,
	[Base Unit of Measure] [nvarchar](10) NULL,
	[Weight Unit] [nvarchar](10) NULL,
	[Revenue Recognition] [nvarchar](20) NULL,
	[CA_UNKNOWN] [varchar](10) NULL,
	[Free_Paid] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [SalesOrder] ),
	CLUSTERED COLUMNSTORE INDEX
)