CREATE TABLE [DWSAP].[scannerrevenueunitprocessed] (
    [LZBatchID]              INT             NOT NULL,
    [ADLSBatchID]            INT             NOT NULL,
    [ADLSTimestamp]          DATETIME2 (0)   NOT NULL,
    [DWBatchID]              INT             NULL,
    [DWTimeStamp]            DATETIME2 (0)   NULL,
    [SalesOrder]             NVARCHAR (10)   NOT NULL,
    [EventDate]              NVARCHAR (8)    NULL,
    [Ship-ToParty]           NVARCHAR (1300) NULL,
    [Sold-ToParty]           NVARCHAR (1300) NULL,
    [SalesOrderType]         NVARCHAR (4)    NULL,
    [VolumeUnit]             NVARCHAR (3)    NULL,
    [ProfitCenter]           NVARCHAR (16)   NULL,
    [Material]               NVARCHAR (18)   NULL,
    [CompanyCode]            NVARCHAR (4)    NULL,
    [PGIDate]                NVARCHAR (8)    NULL,
    [Product Hierarchy]      NVARCHAR (18)   NULL,
    [Item Category]          NVARCHAR (4)    NULL,
    [PromoBucket]            NVARCHAR (40)   NULL,
    [DateofMIM]              NVARCHAR (8)    NULL,
    [Fiscal Variant]         VARCHAR (2)     NOT NULL,
    [FileYN]                 VARCHAR (1)     NOT NULL,
    [CreatedOnDate]          DATE            NULL,
    [CreatedOn]              DATETIME        NOT NULL,
    [User]                   NVARCHAR (128)  NULL,
    [itro_scr]               VARCHAR (1)     NOT NULL,
    [itro_serv]              VARCHAR (1)     NOT NULL,
    [Shipment Count]         VARCHAR (1)     NULL,
    [Segment]                VARCHAR (13)    NOT NULL,
    [Volume Segment]         VARCHAR (20)    NOT NULL,
    [Volume Sub-Segment]     VARCHAR (20)    NOT NULL,
    [Cost Element(COPA)]     VARCHAR (20)    NOT NULL,
    [Sales Group]            NVARCHAR (50)   NULL,
    [Controlling Area]       INT             NULL,
    [Process Name]           VARCHAR (6)     NOT NULL,
    [Business Segment]       VARCHAR (13)    NULL,
    [ActualDeliveryQuantity] DECIMAL (13, 3) NULL,
    [Age Tier]               DECIMAL (18)    NULL,
    [Volume]                 DECIMAL (15, 3) NULL,
    [Net Weight]             DECIMAL (15, 3) NULL,
    [Total Weight]           DECIMAL (15, 3) NULL,
    [Delivery]               NVARCHAR (10)   NULL,
    [Treatment Category]     VARCHAR (15)    NULL,
    [Document_Category]      CHAR (1)        NULL,
    [Delivery Type]          NVARCHAR (30)   NULL,
    [Reason Rejection]       NVARCHAR (2)    NULL,
    [KNUM]                   NVARCHAR (10)   NULL,
    [Profitability segment]  NVARCHAR (10)   NULL,
    [CostCenter]             NVARCHAR (10)   NULL,
    [Compliance Indicator]   VARCHAR (10)    NULL,
    [Serial Number]          NVARCHAR (18)   NULL,
    [Initiator Company ID]   NVARCHAR (10)   NULL,
    [AMR Date]               CHAR (8)        NULL,
    [CCS Date]               CHAR (8)        NULL,
    [CCADate]                DATE            NULL,
    [External Patient ID]    NVARCHAR (15)   NULL,
    [Source System Order]    VARCHAR (12)    NULL,
    [SFDC Order ID]          VARCHAR (12)    NULL,
    [FoC Quantity]           DECIMAL (18)    NULL,
    [Deliverable Quantity]   DECIMAL (18)    NULL,
    [Sales Unit]             NVARCHAR (3)    NULL,
    [Target Qu]              NVARCHAR (3)    NULL,
    [Target Qty]             DECIMAL (13, 3) NULL,
    [Document Currency]      NVARCHAR (5)    NULL,
    [Net Price]              DECIMAL (11, 2) NULL,
    [Net Value]              DECIMAL (15, 2) NULL,
    [Customer Group1]        NVARCHAR (3)    NULL,
    [Customer Group2]        NVARCHAR (3)    NULL,
    [Customer Group3]        NVARCHAR (3)    NULL,
    [Customer Group4]        NVARCHAR (3)    NULL,
    [Customer Group5]        NVARCHAR (3)    NULL,
    [SalesOrder Item]        NVARCHAR (10)   NULL,
    [Sales Organization]     CHAR (4)        NULL,
    [Distribution Channel]   CHAR (2)        NULL,
    [Storage Location]       NVARCHAR (4)    NULL,
    [Division]               CHAR (2)        NULL,
    [External Treatment I]   NVARCHAR (19)   NULL,
    [Treatment Option]       NVARCHAR (30)   NULL,
    [ZZTREATMENT]            VARCHAR (12)    NULL,
    [MaxNoOfStages]          VARCHAR (3)     NULL,
    [TreatmentLocation]      NVARCHAR (1300) NULL,
    [TreatingDoctor]         NVARCHAR (1300) NULL,
    [OrderStages]            DECIMAL (18)    NULL,
    [StagesBucket]           VARCHAR (5)     NULL,
    [MaterialGroup1]         NVARCHAR (3)    NULL,
    [MaterialGroup2]         NVARCHAR (3)    NULL,
    [MaterialGroup3]         NVARCHAR (3)    NULL,
    [MaterialGroup4]         NVARCHAR (3)    NULL,
    [MaterialGroup5]         NVARCHAR (3)    NULL,
    [ClinicalStudy]          NVARCHAR (1)    NULL,
    [Total Quantity]         DECIMAL (18)    NULL,
    [CA_PRIMRY]              VARCHAR (1)     NULL,
    [CA_SECNDRY]             VARCHAR (1)     NULL,
    [CA_NONCAS]              VARCHAR (1)     NULL,
    [CA_OTHERS]              VARCHAR (1)     NULL,
    [ReasonRejection]        NVARCHAR (2)    NULL,
    [Order Quantity]         DECIMAL (15, 3) NULL,
    [Withdraw Quantity]      DECIMAL (13, 3) NULL,
    [Delivery Quantity]      DECIMAL (13, 3) NULL,
    [DeliveryItem]           NVARCHAR (6)    NULL,
    [ActualsGoodIssueDate]   NVARCHAR (8)    NULL,
    [Reporting Channel]      INT             NULL,
    [Document Date]          NVARCHAR (8)    NULL,
    [CertificationDate]      DATE            NULL,
    [CertificationYear]      INT             NULL,
    [AdvantageTier]          NVARCHAR (255)  NULL,
    [ProfessionalCategory]   NVARCHAR (50)   NULL,
    [Country]                NVARCHAR (50)   NULL,
    [CountryGroup]           NVARCHAR (50)   NULL,
    [RegionPC]               NVARCHAR (50)   NULL,
    [RegionGroup]            NVARCHAR (50)   NULL,
    [GlobalRegion]           NVARCHAR (32)   NULL,
    [Reporting Region]       NVARCHAR (10)   NULL,
    [Plant]                  NVARCHAR (4)    NULL,
    [CA_UNKNOWN]             VARCHAR (1)     NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([SalesOrder]));

