CREATE TABLE [DWSAP].[ScannerHistoryProcessed] (
    [LZBatchID]                     INT             NOT NULL,
    [ADLSBatchID]                   INT             NOT NULL,
    [ADLSTimestamp]                 DATETIME2 (0)   NOT NULL,
    [DWBatchID]                     INT             NULL,
    [DWTimeStamp]                   DATETIME2 (0)   NULL,
    [Sales Document]                NVARCHAR (10)   NOT NULL,
    [Item]                          NVARCHAR (6)    NOT NULL,
    [Fiscal Year Variant]           NVARCHAR (2)    NOT NULL,
    [Cal. Year/Quarter]             NVARCHAR (5)    NOT NULL,
    [Quarter]                       NVARCHAR (1)    NOT NULL,
    [Calender Year/Week]            NVARCHAR (6)    NOT NULL,
    [Fiscal Year]                   NVARCHAR (4)    NOT NULL,
    [Fiscal Year/Period]            NVARCHAR (7)    NOT NULL,
    [Posting Period]                NVARCHAR (3)    NOT NULL,
    [Equipment Serial Num]          NVARCHAR (18)   NULL,
    [Initiator Company ID]          NVARCHAR (10)   NULL,
    [Reporting Region]              NVARCHAR (10)   NULL,
    [Event Date]                    DATE            NOT NULL,
    [Document Type]                 NVARCHAR (4)    NULL,
    [Document Category]             NVARCHAR (2)    NULL,
    [Item Category]                 NVARCHAR (4)    NULL,
    [Deliverable Type]              NVARCHAR (30)   NULL,
    [Treatment Category]            NVARCHAR (15)   NULL,
    [Company Code]                  NVARCHAR (4)    NULL,
    [Material]                      NVARCHAR (18)   NULL,
    [Product Hierarchy]             NVARCHAR (18)   NULL,
    [CA_PRIMARY]                    NVARCHAR (1)    NULL,
    [CA_SECONDARY]                  NVARCHAR (1)    NULL,
    [CA_NONCAS]                     NVARCHAR (1)    NULL,
    [CA_OTHERS]                     NVARCHAR (1)    NULL,
    [CA_UNKNOWN]                    NVARCHAR (1)    NULL,
    [ITRO_SCNR]                     NVARCHAR (1)    NULL,
    [ITRO_SERV]                     NVARCHAR (1)    NULL,
    [Overall Rejection St]          NVARCHAR (1)    NULL,
    [Reason For Rejection]          NVARCHAR (2)    NULL,
    [Rejection Status]              NVARCHAR (1)    NULL,
    [Rejection Date]                NVARCHAR (8)    NULL,
    [Rejection Time]                NVARCHAR (12)   NOT NULL,
    [Document Date]                 NVARCHAR (8)    NULL,
    [Created On]                    NVARCHAR (8)    NULL,
    [Doc. Condition]                NVARCHAR (10)   NULL,
    [Profit. Segment]               NVARCHAR (10)   NULL,
    [Cost Center]                   NVARCHAR (10)   NULL,
    [Controlling Area]              NVARCHAR (4)    NULL,
    [Profit Center]                 NVARCHAR (10)   NULL,
    [Cost Element(COPA)]            NVARCHAR (25)   NOT NULL,
    [Compliance Indicator]          NVARCHAR (10)   NULL,
    [AMR DATE]                      NVARCHAR (8)    NULL,
    [CCS DATE]                      NVARCHAR (8)    NULL,
    [CCA DATE]                      NVARCHAR (8)    NULL,
    [External Patient ID]           NVARCHAR (15)   NULL,
    [Source System Order]           NVARCHAR (12)   NULL,
    [Patient ID]                    NVARCHAR (36)   NULL,
    [SFDC Order ID]                 NVARCHAR (12)   NULL,
    [FoC Quantity]                  DECIMAL (4)     NOT NULL,
    [Deliverable Quantity]          DECIMAL (5)     NULL,
    [Deliverable Quantity for COPA] DECIMAL (10)    NULL,
    [Total Quantity for COPA]       DECIMAL (10)    NULL,
    [Sales Unit]                    NVARCHAR (3)    NULL,
    [BASE_UOM]                      NVARCHAR (3)    NULL,
    [TARGET_QU]                     NVARCHAR (3)    NULL,
    [Document Currency]             NVARCHAR (5)    NULL,
    [CML_CF_QTY]                    DECIMAL (17, 3) NOT NULL,
    [CML_CD_QTY]                    DECIMAL (17, 3) NOT NULL,
    [Order Quantity]                DECIMAL (17, 3) NOT NULL,
    [Target Quantity]               DECIMAL (17, 3) NOT NULL,
    [Withdraw Quantity]             DECIMAL (17, 3) NOT NULL,
    [Net Price]                     DECIMAL (17, 3) NOT NULL,
    [Net Value]                     DECIMAL (17, 3) NOT NULL,
    [Age Tier]                      NVARCHAR (4)    NULL,
    [Reporting Channel]             DECIMAL (2)     NOT NULL,
    [Free/Paid]                     NVARCHAR (15)   NULL,
    [Sold-to Party]                 NVARCHAR (10)   NULL,
    [Customer Group 1]              NVARCHAR (3)    NULL,
    [Customer Group 2]              NVARCHAR (3)    NULL,
    [Customer Group 3]              NVARCHAR (3)    NULL,
    [Customer Group 4]              NVARCHAR (3)    NULL,
    [Customer Group 5]              NVARCHAR (3)    NULL,
    [Sales Group]                   NVARCHAR (3)    NULL,
    [Sales Organization]            NVARCHAR (4)    NULL,
    [Distribution Channel]          NVARCHAR (2)    NULL,
    [Storage Location]              NVARCHAR (4)    NULL,
    [Plant]                         NVARCHAR (4)    NULL,
    [Material Group]                NVARCHAR (9)    NULL,
    [Bill-to Party]                 NVARCHAR (10)   NULL,
    [Ship-to Party]                 NVARCHAR (10)   NULL,
    [Division]                      NVARCHAR (2)    NULL,
    [Country]                       NVARCHAR (3)    NULL,
    [External Treatment ID]         NVARCHAR (19)   NULL,
    [Treatment Option]              NVARCHAR (30)   NULL,
    [Treatment ID]                  NVARCHAR (12)   NULL,
    [Max No Of Stages]              NVARCHAR (3)    NULL,
    [Treatment Location]            NVARCHAR (10)   NULL,
    [Treatment Doctor]              NVARCHAR (10)   NULL,
    [Order Stages]                  NVARCHAR (11)   NULL,
    [Stages Bucket]                 NVARCHAR (100)  NULL,
    [Material Group 1]              NVARCHAR (3)    NULL,
    [Material Group 2]              NVARCHAR (3)    NULL,
    [Material Group 3]              NVARCHAR (3)    NULL,
    [Material Group 4]              NVARCHAR (3)    NULL,
    [Material Group 5]              NVARCHAR (3)    NULL,
    [Territory Manager]             NVARCHAR (10)   NULL,
    [Align Retail]                  NVARCHAR (10)   NULL,
    [Financial Contact]             NVARCHAR (10)   NULL,
    [Junior Doctor]                 NVARCHAR (10)   NULL,
    [Submitting Student]            NVARCHAR (10)   NULL,
    [Employee Responsible]          NVARCHAR (10)   NULL,
    [Characteristic-Upper]          NVARCHAR (30)   NULL,
    [Characteristic-Lower]          NVARCHAR (30)   NULL,
    [Charac. Value-Upper]           NVARCHAR (30)   NULL,
    [Charac. Value-Lower]           NVARCHAR (30)   NULL,
    [/BIC/ZCLINICAL]                NVARCHAR (1)    NULL,
    [DELIV_NUMB]                    NVARCHAR (10)   NULL,
    [DELIV_ITEM]                    NVARCHAR (6)    NOT NULL,
    [ACT_GI_DTE]                    DATE            NOT NULL,
    [ACT_DL_QTY]                    DECIMAL (17, 3) NOT NULL,
    [DLV_QTY]                       DECIMAL (17, 3) NOT NULL,
    [/BIC/SHPMNTCNT]                DECIMAL (10)    NOT NULL,
    [/BIC/VOL_SEGMT]                NVARCHAR (50)   NOT NULL,
    [/BIC/VOL_COUNT]                DECIMAL (10)    NOT NULL,
    [/BIC/VOL_QUANT]                DECIMAL (17, 3) NOT NULL,
    [/BIC/SEGMENT]                  NVARCHAR (20)   NOT NULL,
    [/BIC/VOLSSEGMT]                NVARCHAR (50)   NOT NULL,
    [/BIC/FILEYN]                   NVARCHAR (1)    NULL,
    [BILL_DATE]                     NVARCHAR (8)    NULL,
    [/BIC/IACTQTY]                  DECIMAL (17, 3) NULL,
    [PAYER]                         NVARCHAR (10)   NULL,
    [VOLUMEUNIT]                    NVARCHAR (3)    NULL,
    [CREA_TIME]                     NVARCHAR (11)   NULL,
    [ZALGNUSER]                     DECIMAL (8)     NULL,
    [/BIC/ZFRE_QTY]                 DECIMAL (17, 3) NULL,
    [Total Quantity]                DECIMAL (17, 3) NULL,
    [/BIC/DELV_QTY]                 DECIMAL (17, 3) NULL,
    [Promotion Bucket]              NVARCHAR (40)   NULL,
    [Data of MIM]                   NVARCHAR (8)    NULL,
    [Event Description]             NVARCHAR (3)    NULL,
    [Process Name]                  VARCHAR (6)     NOT NULL,
    [Business Segment]              VARCHAR (13)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

