CREATE TABLE [DWSAP].[Transpose] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [CURTP]         VARCHAR (30)    NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [HZDAT]         NVARCHAR (8)    NOT NULL,
    [USNAM]         NVARCHAR (12)   NOT NULL,
    [GJAHR]         NVARCHAR (4)    NOT NULL,
    [PERDE]         NVARCHAR (3)    NOT NULL,
    [WADAT]         NVARCHAR (8)    NOT NULL,
    [FADAT]         NVARCHAR (8)    NOT NULL,
    [BUDAT]         NVARCHAR (8)    NOT NULL,
    [ALTPERIO]      NVARCHAR (7)    NOT NULL,
    [PAPAOBJNR]     NVARCHAR (10)   NOT NULL,
    [PAPASUBNR]     NVARCHAR (4)    NOT NULL,
    [KNDNR]         NVARCHAR (10)   NOT NULL,
    [ARTNR]         NVARCHAR (18)   NOT NULL,
    [FKART]         NVARCHAR (4)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [KURSF]         DECIMAL (9, 5)  NOT NULL,
    [KURSBK]        DECIMAL (9, 5)  NOT NULL,
    [KURSKZ]        DECIMAL (9, 5)  NOT NULL,
    [REC_WAERS]     NVARCHAR (5)    NOT NULL,
    [KAUFN]         NVARCHAR (10)   NOT NULL,
    [KDPOS]         NVARCHAR (6)    NOT NULL,
    [RKAUFNR]       NVARCHAR (12)   NOT NULL,
    [SKOST]         NVARCHAR (10)   NOT NULL,
    [PRZNR]         NVARCHAR (12)   NOT NULL,
    [BUKRS]         NVARCHAR (4)    NOT NULL,
    [KOKRS]         NVARCHAR (4)    NOT NULL,
    [WERKS]         NVARCHAR (4)    NOT NULL,
    [GSBER]         NVARCHAR (4)    NOT NULL,
    [VKORG]         NVARCHAR (4)    NOT NULL,
    [VTWEG]         NVARCHAR (2)    NOT NULL,
    [SPART]         NVARCHAR (2)    NOT NULL,
    [HRKFT]         NVARCHAR (4)    NOT NULL,
    [PLIKZ]         NVARCHAR (1)    NOT NULL,
    [KSTAR]         NVARCHAR (10)   NOT NULL,
    [PSPNR]         NVARCHAR (8)    NOT NULL,
    [KSTRG]         NVARCHAR (12)   NOT NULL,
    [RBELN]         NVARCHAR (10)   NOT NULL,
    [RPOSN]         NVARCHAR (6)    NOT NULL,
    [STO_BELNR]     NVARCHAR (10)   NOT NULL,
    [STO_POSNR]     NVARCHAR (6)    NOT NULL,
    [PRCTR]         NVARCHAR (10)   NOT NULL,
    [PPRCTR]        NVARCHAR (10)   NOT NULL,
    [RKESTATU]      NVARCHAR (10)   NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [COPA_AWTYP]    NVARCHAR (5)    NOT NULL,
    [COPA_AWORG]    NVARCHAR (10)   NOT NULL,
    [COPA_BWZPT]    NVARCHAR (1)    NOT NULL,
    [COPA_AWSYS]    NVARCHAR (10)   NOT NULL,
    [BESKZ]         NVARCHAR (1)    NOT NULL,
    [KDGRP]         NVARCHAR (2)    NOT NULL,
    [KUNRE]         NVARCHAR (10)   NOT NULL,
    [KUNWE]         NVARCHAR (10)   NOT NULL,
    [LAND1]         NVARCHAR (3)    NOT NULL,
    [PSTYV]         NVARCHAR (4)    NOT NULL,
    [VKBUR]         NVARCHAR (4)    NOT NULL,
    [VRTNR]         NVARCHAR (8)    NOT NULL,
    [WWCST]         NVARCHAR (3)    NOT NULL,
    [WWCH2]         NVARCHAR (3)    NOT NULL,
    [WWSIZ]         NVARCHAR (3)    NOT NULL,
    [WWICI]         NVARCHAR (1)    NOT NULL,
    [COPA_KOSTL]    NVARCHAR (10)   NOT NULL,
    [PRODH]         NVARCHAR (18)   NOT NULL,
    [VKGRP]         NVARCHAR (3)    NOT NULL,
    [WW010]         NVARCHAR (2)    NOT NULL,
    [WW021]         NVARCHAR (30)   NOT NULL,
    [WW022]         NVARCHAR (12)   NOT NULL,
    [PLTYP]         NVARCHAR (2)    NOT NULL,
    [MATKL]         NVARCHAR (9)    NOT NULL,
    [BZIRK]         NVARCHAR (6)    NOT NULL,
    [WW023]         NVARCHAR (10)   NOT NULL,
    [KVGR1]         NVARCHAR (3)    NOT NULL,
    [KVGR2]         NVARCHAR (3)    NOT NULL,
    [WW015]         NVARCHAR (2)    NOT NULL,
    [WW025]         DECIMAL (10, 3) NULL,
    [WWA01]         DECIMAL (10, 3) NULL,
    [WWA02]         DECIMAL (10, 3) NULL,
    [AUART]         NVARCHAR (4)    NOT NULL,
    [WW027]         NVARCHAR (10)   NOT NULL,
    [WW028]         NVARCHAR (10)   NOT NULL,
    [WWFT1]         NVARCHAR (18)   NOT NULL,
    [WWFT2]         NVARCHAR (18)   NOT NULL,
    [WWFT3]         NVARCHAR (18)   NOT NULL,
    [WWFT4]         NVARCHAR (18)   NOT NULL,
    [WWFT5]         NVARCHAR (18)   NOT NULL,
    [WWFT6]         NVARCHAR (18)   NOT NULL,
    [WWFT7]         NVARCHAR (18)   NOT NULL,
    [WWFT8]         NVARCHAR (18)   NOT NULL,
    [WWFT9]         NVARCHAR (18)   NOT NULL,
    [AUGRU]         NVARCHAR (3)    NOT NULL,
    [ABGRU]         NVARCHAR (2)    NOT NULL,
    [ABSMG_ME]      NVARCHAR (3)    NOT NULL,
    [ABSMG]         DECIMAL (15, 3) NOT NULL,
    [ERLOS]         DECIMAL (15, 2) NOT NULL,
    [KWKDRB]        DECIMAL (15, 2) NOT NULL,
    [KWMARB]        DECIMAL (15, 2) NOT NULL,
    [MRABA]         DECIMAL (15, 2) NOT NULL,
    [KWMKPR]        DECIMAL (15, 2) NOT NULL,
    [VVFGS]         DECIMAL (15, 2) NOT NULL,
    [RABAT]         DECIMAL (15, 2) NOT NULL,
    [KWSKTO]        DECIMAL (15, 2) NOT NULL,
    [ValueField]    NVARCHAR (128)  NULL,
    [ColumnValue]   DECIMAL (15, 2) NOT NULL,
    [CALWEEK]       NVARCHAR (20)   NULL,
    [FISCPER]       NVARCHAR (20)   NULL,
    [FISCPER3]      NVARCHAR (20)   NULL,
    [QRTR]          NVARCHAR (10)   NULL,
    [QRTR_YR]       NVARCHAR (10)   NULL,
    [FISCVARNT]     NVARCHAR (20)   NULL,
    [ZPROCESS]      NVARCHAR (50)   NULL,
    [BUSSEGMNT]     NVARCHAR (50)   NULL,
    [FREEPAID]      NVARCHAR (50)   NULL,
    [SPRAS]         NVARCHAR (20)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

