CREATE TABLE [SrcMyInvisalignApp].[events] (
    [LZBatchID]                             INT            NOT NULL,
    [ADLSBatchID]                           INT            NOT NULL,
    [ADLSTimestamp]                         DATETIME2 (0)  NOT NULL,
    [event_date]                            NVARCHAR (20)  NULL,
    [event_timestamp]                       BIGINT         NOT NULL,
    [event_name]                            NVARCHAR (50)  NOT NULL,
    [event_params_ga_session_id]            BIGINT         NULL,
    [event_params_ga_session_number]        BIGINT         NULL,
    [event_params_engaged_session_event]    BIGINT         NULL,
    [event_params_firebase_screen_id]       BIGINT         NULL,
    [event_params_entrances]                BIGINT         NULL,
    [event_params_engagement_time_msec]     BIGINT         NULL,
    [event_params_firebase_previous_id]     BIGINT         NULL,
    [event_params_freeride]                 BIGINT         NULL,
    [event_params_Value]                    BIGINT         NULL,
    [event_params_firebase_event_origin]    NVARCHAR (50)  NULL,
    [event_params_firebase_screen_class]    NVARCHAR (100) NULL,
    [event_params_firebase_previous_class]  NVARCHAR (100) NULL,
    [event_params_firebase_screen]          NVARCHAR (50)  NULL,
    [event_params_firebase_previous_screen] NVARCHAR (50)  NULL,
    [event_params_Label]                    NVARCHAR (100) NULL,
    [event_params_Category]                 NVARCHAR (100) NULL,
    [event_previous_timestamp]              BIGINT         NULL,
    [event_value_in_usd]                    NVARCHAR (50)  NULL,
    [event_bundle_sequence_id]              BIGINT         NULL,
    [event_server_timestamp_offset]         BIGINT         NOT NULL,
    [user_id]                               NVARCHAR (50)  NULL,
    [user_pseudo_id]                        NVARCHAR (50)  NULL,
    [user_properties_first_open_time]       BIGINT         NULL,
    [user_properties_ga_session_id]         BIGINT         NULL,
    [user_properties_ga_session_number]     BIGINT         NULL,
    [user_first_touch_timestamp]            BIGINT         NULL,
    [device_category]                       NVARCHAR (50)  NULL,
    [device_mobile_brand_name]              NVARCHAR (50)  NULL,
    [device_mobile_model_name]              NVARCHAR (50)  NULL,
    [device_mobile_marketing_name]          NVARCHAR (50)  NULL,
    [device_mobile_os_hardware_model]       NVARCHAR (50)  NULL,
    [device_operating_system]               NVARCHAR (50)  NULL,
    [device_operating_system_version]       NVARCHAR (50)  NULL,
    [device_vendor_id]                      NVARCHAR (50)  NULL,
    [device_advertising_id]                 NVARCHAR (50)  NULL,
    [device_language]                       NVARCHAR (50)  NULL,
    [device_is_limited_ad_tracking]         NVARCHAR (50)  NULL,
    [device_time_zone_offset_seconds]       BIGINT         NULL,
    [geo_continent]                         NVARCHAR (100) NULL,
    [geo_country]                           NVARCHAR (50)  NULL,
    [geo_region]                            NVARCHAR (100) NULL,
    [geo_city]                              NVARCHAR (50)  NULL,
    [geo_sub_continent]                     NVARCHAR (50)  NULL,
    [geo_metro]                             NVARCHAR (50)  NULL,
    [app_info_id]                           NVARCHAR (50)  NULL,
    [app_info_version]                      NVARCHAR (50)  NULL,
    [app_info_firebase_app_id]              NVARCHAR (50)  NULL,
    [app_info_install_source]               NVARCHAR (50)  NULL,
    [traffic_source_name]                   NVARCHAR (100) NULL,
    [traffic_source_medium]                 NVARCHAR (50)  NULL,
    [traffic_source_source]                 NVARCHAR (50)  NULL,
    [stream_id]                             NVARCHAR (50)  NULL,
    [platform]                              NVARCHAR (50)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

