CREATE TABLE [SrcKaiNexus].[itemList]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NULL,
	[TemplateId] [nvarchar](max) NULL,
	[TemplateName] [nvarchar](max) NULL,
	[IdeaID] [nvarchar](max) NULL,
	[Summary] [nvarchar](max) NULL,
	[Link] [nvarchar](max) NULL,
	[Status] [nvarchar](max) NULL,
	[Fields] [nvarchar](max) NULL,
	[Attributes] [nvarchar](max) NULL,
	[CreateDate] [nvarchar](max) NULL,
	[StartDate] [nvarchar](max) NULL,
	[DueDate] [nvarchar](max) NULL,
	[AssignDate] [nvarchar](max) NULL,
	[Completedate] [nvarchar](max) NULL,
	[LastUpdateDate] [nvarchar](max) NULL,
	[LikeCount] [nvarchar](max) NULL,
	[AckCount] [nvarchar](max) NULL,
	[VoteCount] [nvarchar](max) NULL,
	[Private] [nvarchar](max) NULL,
	[AuthorId] [nvarchar](max) NULL,
	[AuthorUserName] [nvarchar](max) NULL,
	[AuthorFirstName] [nvarchar](max) NULL,
	[AuthorlastName] [nvarchar](max) NULL,
	[ResponsibleId] [nvarchar](max) NULL,
	[ResponsibleLocation] [nvarchar](max) NULL,
	[result] [nvarchar](max) NULL,
	[Amount] [nvarchar](max) NULL,
	[ImpactedLocations] [nvarchar](max) NULL,
	[CurrencyCode] [nvarchar](max) NULL,
	[TypeName] [nvarchar](max) NULL,
	[TypeID] [nvarchar](max) NULL,
	[AmountTimeUnit] [nvarchar](max) NULL,
	[RecurringInterval] [nvarchar](max) NULL,
	[RecurringType] [nvarchar](max) NULL,
	[RangeStartTime] [nvarchar](max) NULL,
	[RangeEndTime] [nvarchar](max) NULL,
	[CustomYear] [nvarchar](max) NULL,
	[CustomMonth] [nvarchar](max) NULL,
	[CustomAmount] [nvarchar](max) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);