CREATE TABLE [SrcMES_AFAB_CN].[UDA_Order] (
    [LZBatchID]                 INT            NOT NULL,
    [ADLSBatchID]               INT            NOT NULL,
    [ADLSTimestamp]             DATETIME2 (0)  NOT NULL,
    [object_key]                BIGINT         NOT NULL,
    [site_num]                  INT            NOT NULL,
    [last_modifier_key]         BIGINT         NOT NULL,
    [last_modified_time]        DATETIME       NOT NULL,
    [xfr_insert_pid]            INT            NULL,
    [xfr_update_pid]            INT            NULL,
    [trx_id]                    CHAR (38)      NOT NULL,
    [at_DoctorID_S]             NVARCHAR (80)  NULL,
    [at_JDEOrderType_S]         NVARCHAR (80)  NULL,
    [at_JDERoutingType_S]       NVARCHAR (3)   NULL,
    [at_TreatmentID_S]          NVARCHAR (15)  NULL,
    [at_VipOrderNumber_S]       NVARCHAR (80)  NULL,
    [last_modified_time_u]      DATETIME       NULL,
    [last_modified_time_z]      NVARCHAR (64)  NULL,
    [list_key]                  BIGINT         NULL,
    [at_expedite_hold_status_I] BIGINT         NULL,
    [at_expedite_scope_S]       NVARCHAR (64)  NULL,
    [pd_xfr_update_pid]         INT            NOT NULL,
    [src_xfr_update_pid]        INT            NOT NULL,
    [purged]                    INT            NULL,
    [at_Pilot_S]                NVARCHAR (100) NULL,
    [at_TreatmentFile_S]        NVARCHAR (80)  NULL,
    [at_TreatmentFileVersion_S] NVARCHAR (80)  NULL,
    [at_TreatmentOption_S]      NVARCHAR (80)  NULL,
    [at_DeliverableType_S]      NVARCHAR (80)  NULL,
    [at_TreatmentCategory_S]    NVARCHAR (80)  NULL,
    [Top_SOIMaterialNumber_I]   BIGINT         NULL,
    [at_TopProductionOrder_S]   NVARCHAR (80)  NULL,
    [at_Plant_S]                NVARCHAR (80)  NULL,
    [at_Country_S]              NVARCHAR (80)  NULL,
    [at_ServiceLevel_S]         NVARCHAR (80)  NULL,
    [at_DoctorFirstName_S]      NVARCHAR (80)  NULL,
    [at_DoctorLastName_S]       NVARCHAR (80)  NULL,
    [ClinicianID_S]             NVARCHAR (80)  NULL,
    [at_TreatedArch_S]          NVARCHAR (80)  NULL,
    [at_ProductionOrderType_S]  NVARCHAR (80)  NULL,
    [at_SalesOrderItem_S]       NVARCHAR (80)  NULL,
    [at_externalTreatmentId_S]  NVARCHAR (80)  NULL,
    [at_StorageLocation_S]      NVARCHAR (80)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));