CREATE TABLE [SrcMES_AFAB_CN].[WORK_ORDER] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [order_key]            BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [order_number]         NVARCHAR (64)  NOT NULL,
    [customer]             NVARCHAR (64)  NULL,
    [entered_time]         DATETIME       NULL,
    [promised_time]        DATETIME       NULL,
    [finished_time]        DATETIME       NULL,
    [shipped_time]         DATETIME       NULL,
    [closed_time]          DATETIME       NULL,
    [inst_list_key]        BIGINT         NULL,
    [note_key]             BIGINT         NULL,
    [description]          NVARCHAR (255) NULL,
    [dscomment]            NVARCHAR (255) NULL,
    [order_state]          NVARCHAR (64)  NULL,
    [contact_person]       NVARCHAR (64)  NULL,
    [contact_phone]        NVARCHAR (64)  NULL,
    [shipping_method]      NVARCHAR (64)  NULL,
    [addr_name]            NVARCHAR (64)  NULL,
    [addr1]                NVARCHAR (64)  NULL,
    [addr2]                NVARCHAR (64)  NULL,
    [addr_city]            NVARCHAR (64)  NULL,
    [addr_state]           NVARCHAR (64)  NULL,
    [addr_zip]             NVARCHAR (64)  NULL,
    [email_address]        NVARCHAR (255) NULL,
    [revived]              INT            NULL,
    [order_close_type]     NVARCHAR (50)  NOT NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [uda_5]                NVARCHAR (255) NULL,
    [uda_6]                NVARCHAR (255) NULL,
    [uda_7]                NVARCHAR (255) NULL,
    [uda_8]                NVARCHAR (255) NULL,
    [uda_9]                NVARCHAR (255) NULL,
    [udt_0]                DATETIME       NULL,
    [udt_1]                DATETIME       NULL,
    [udt_2]                DATETIME       NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [creation_time]        DATETIME       NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [bill_account_key]     BIGINT         NULL,
    [build_account_key]    BIGINT         NULL,
    [ship_account_key]     BIGINT         NULL,
    [user_account_0]       BIGINT         NULL,
    [tobj_status_key]      BIGINT         NOT NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [category]             NVARCHAR (50)  NULL,
    [creator_key]          BIGINT         NULL,
    [last_modifier_key]    BIGINT         NULL,
    [entered_time_u]       DATETIME       NULL,
    [entered_time_z]       NVARCHAR (64)  NULL,
    [promised_time_u]      DATETIME       NULL,
    [promised_time_z]      NVARCHAR (64)  NULL,
    [finished_time_u]      DATETIME       NULL,
    [finished_time_z]      NVARCHAR (64)  NULL,
    [shipped_time_u]       DATETIME       NULL,
    [shipped_time_z]       NVARCHAR (64)  NULL,
    [closed_time_u]        DATETIME       NULL,
    [closed_time_z]        NVARCHAR (64)  NULL,
    [udt_0_u]              DATETIME       NULL,
    [udt_0_z]              NVARCHAR (64)  NULL,
    [udt_1_u]              DATETIME       NULL,
    [udt_1_z]              NVARCHAR (64)  NULL,
    [udt_2_u]              DATETIME       NULL,
    [udt_2_z]              NVARCHAR (64)  NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [purged]               INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([order_key]));