CREATE TABLE [SrcMES_FAB_CN].[OBJECT_STATE] (
    [LZBatchID]                INT           NOT NULL,
    [ADLSBatchID]              INT           NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0) NOT NULL,
    [object_state_key]         BIGINT        NOT NULL,
    [object_key]               BIGINT        NOT NULL,
    [object_type]              INT           NOT NULL,
    [fsm_config_item_key]      BIGINT        NOT NULL,
    [fsm_key]                  BIGINT        NOT NULL,
    [state_key]                BIGINT        NOT NULL,
    [entry_time]               DATETIME      NULL,
    [entry_time_u]             DATETIME      NULL,
    [entry_time_z]             NVARCHAR (64) NULL,
    [object_state_history_key] BIGINT        NULL,
    [xfr_insert_pid]           INT           NOT NULL,
    [pd_xfr_update_pid]        INT           NOT NULL,
    [src_xfr_update_pid]       INT           NOT NULL,
    [xfr_update_pid]           INT           NOT NULL,
    [trx_id]                   CHAR (38)     NOT NULL,
    [last_modified_time]       DATETIME      NOT NULL,
    [last_modified_time_u]     DATETIME      NULL,
    [last_modified_time_z]     NVARCHAR (64) NULL,
    [purged]                   INT           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));