CREATE TABLE [SrcMES_FAB_CN].[SUBLOT] (
    [LZBatchID]                  INT            NOT NULL,
    [ADLSBatchID]                INT            NOT NULL,
    [ADLSTimestamp]              DATETIME2 (0)  NOT NULL,
    [sublot_key]                 BIGINT         NOT NULL,
    [batch_key]                  BIGINT         NOT NULL,
    [sublot_name]                NVARCHAR (128) NOT NULL,
    [container_key]              BIGINT         NOT NULL,
    [container_type]             NVARCHAR (50)  NULL,
    [expiration_time]            DATETIME       NULL,
    [expiration_time_u]          DATETIME       NULL,
    [expiration_time_z]          NVARCHAR (64)  NULL,
    [logically_empty]            INT            NOT NULL,
    [logically_empty_quantity]   NVARCHAR (64)  NULL,
    [quantity]                   NVARCHAR (64)  NOT NULL,
    [initial_quantity]           NVARCHAR (64)  NOT NULL,
    [potency]                    NVARCHAR (64)  NULL,
    [category]                   NVARCHAR (50)  NULL,
    [description]                NVARCHAR (255) NULL,
    [creator_key]                BIGINT         NOT NULL,
    [creation_time]              DATETIME       NOT NULL,
    [creation_time_u]            DATETIME       NULL,
    [creation_time_z]            NVARCHAR (64)  NULL,
    [last_modifier_key]          BIGINT         NOT NULL,
    [last_modified_time]         DATETIME       NOT NULL,
    [last_modified_time_u]       DATETIME       NULL,
    [last_modified_time_z]       NVARCHAR (64)  NULL,
    [xfr_insert_pid]             INT            NOT NULL,
    [pd_xfr_update_pid]          INT            NOT NULL,
    [src_xfr_update_pid]         INT            NOT NULL,
    [xfr_update_pid]             INT            NOT NULL,
    [trx_id]                     CHAR (38)      NOT NULL,
    [quantity_consumed]          NVARCHAR (64)  NULL,
    [quantity_scrapped_consumed] NVARCHAR (64)  NULL,
    [inv_container_entry_time]   DATETIME       NULL,
    [inv_container_entry_time_u] DATETIME       NULL,
    [inv_container_entry_time_z] NVARCHAR (64)  NULL,
    [sublot_storage_history_key] BIGINT         NULL,
    [batch_type]                 INT            NULL,
    [joined_start_time]          DATETIME       NULL,
    [joined_start_time_u]        DATETIME       NULL,
    [joined_start_time_z]        NVARCHAR (64)  NULL,
    [joined_end_time]            DATETIME       NULL,
    [joined_end_time_u]          DATETIME       NULL,
    [joined_end_time_z]          NVARCHAR (64)  NULL,
    [loaded_time]                DATETIME       NULL,
    [loaded_time_u]              DATETIME       NULL,
    [loaded_time_z]              NVARCHAR (64)  NULL,
    [loaded_time_long]           BIGINT         NULL,
    [is_working_sublot]          INT            NULL,
    [purged]                     INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([sublot_key]));