CREATE TABLE [SrcLASA].[smile_quizzes] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [id]                   BIGINT         NOT NULL,
    [first_name]           NVARCHAR (255) NULL,
    [last_name]            VARCHAR (255)  NULL,
    [phone]                NVARCHAR (20)  NULL,
    [email]                NVARCHAR (255) NULL,
    [zip]                  NVARCHAR (10)  NULL,
    [smile_journey]        NVARCHAR (255) NULL,
    [smile_mean]           NVARCHAR (255) NULL,
    [treatment_experience] NVARCHAR (255) NULL,
    [gender]               NVARCHAR (40)  NULL,
    [date_of_birth]        NVARCHAR (40)  NULL,
    [goal]                 NVARCHAR (255) NULL,
    [user_type]            NVARCHAR (20)  NULL,
    [opt_in]               BIT            NULL,
    [apple_competition]    BIT            NULL,
    [account]              NVARCHAR (10)  NULL,
    [account2]             NVARCHAR (10)  NULL,
    [account3]             NVARCHAR (10)  NULL,
    [finance_marker]       BIT            NULL,
    [source]               NVARCHAR (255) NULL,
    [visitor_id]           NVARCHAR (12)  NULL,
    [minutes_on_site]      NVARCHAR (20)  NULL,
    [client_ip]            NVARCHAR (30)  NULL,
    [created_at]           DATETIME       NULL,
    [updated_at]           DATETIME       NULL,
    [quiz_option]          NVARCHAR (255) NULL,
    [prospect_id]          NVARCHAR (18)  NULL,
    [child_prospect_id]    NVARCHAR (255) NULL,
    [country]              NVARCHAR (2)   NULL,
    [locale]               NVARCHAR (255) NULL
)
WITH (CLUSTERED INDEX([id]), DISTRIBUTION = HASH([id]));

