CREATE TABLE [SrcLASA].[smile_assessments] (
    [LZBatchID]              INT             NOT NULL,
    [ADLSBatchID]            INT             NOT NULL,
    [ADLSTimestamp]          DATETIME2 (0)   NOT NULL,
    [id]                     BIGINT          NOT NULL,
    [ortho_insurance]        NVARCHAR (4000) NULL,
    [activity]               NVARCHAR (4000) NULL,
    [goal]                   NVARCHAR (4000) NULL,
    [spacing]                NVARCHAR (4000) NULL,
    [bite]                   NVARCHAR (4000) NULL,
    [start_treatment]        NVARCHAR (4000) NULL,
    [research]               NVARCHAR (4000) NULL,
    [agree]                  VARCHAR (255)   NULL,
    [conditions]             NVARCHAR (4000) NULL,
    [patient_type]           NVARCHAR (255)  NULL,
    [zip]                    NVARCHAR (255)  NULL,
    [first_name]             NVARCHAR (255)  NULL,
    [last_name]              NVARCHAR (255)  NULL,
    [email]                  NVARCHAR (255)  NULL,
    [user_type]              NVARCHAR (255)  NULL,
    [referring_site_id]      NVARCHAR (255)  NULL,
    [cookie_date]            NVARCHAR (255)  NULL,
    [age]                    NVARCHAR (255)  NULL,
    [receive_info_opt_in]    NVARCHAR (255)  NULL,
    [txtOmniture_Prop1]      NVARCHAR (255)  NULL,
    [cookie_id]              NVARCHAR (4000) NULL,
    [question_sequence_code] NVARCHAR (255)  NULL,
    [date_of_birth]          NVARCHAR (255)  NULL,
    [upper_image_value]      INT             NULL,
    [lower_image_value]      INT             NULL,
    [image_url]              NVARCHAR (255)  NULL,
    [image_name]             NVARCHAR (255)  NULL,
    [gender]                 NVARCHAR (255)  NULL,
    [household_income]       NVARCHAR (255)  NULL,
    [mobile_device]          NVARCHAR (255)  NULL,
    [txtSURL]                NVARCHAR (255)  NULL,
    [txtFURL]                NVARCHAR (255)  NULL,
    [created_at]             DATETIME        NOT NULL,
    [updated_at]             DATETIME        NOT NULL,
    [before_photo]           NVARCHAR (255)  NULL,
    [after_photo]            NVARCHAR (255)  NULL,
    [first_text]             NVARCHAR (255)  NULL,
    [second_text]            NVARCHAR (255)  NULL,
    [third_text]             NVARCHAR (255)  NULL,
    [fourth_text]            NVARCHAR (255)  NULL,
    [person_segment]         NVARCHAR (255)  NULL,
    [phone]                  NVARCHAR (255)  NULL,
    [contact_preference]     NVARCHAR (255)  NULL,
    [availability]           NVARCHAR (255)  NULL,
    [prospect_id]            NVARCHAR (255)  NULL,
    [source]                 NVARCHAR (255)  NULL,
    [visitor_id]             NVARCHAR (12)   NULL,
    [minutes_on_site]        VARCHAR (18)    NULL,
    [country]                NVARCHAR (2)    NULL,
    [utm_campaign]           NVARCHAR (255)  NULL,
    [utm_content]            NVARCHAR (255)  NULL,
    [utm_medium]             NVARCHAR (255)  NULL,
    [utm_source]             NVARCHAR (255)  NULL,
    [utm_term]               NVARCHAR (255)  NULL,
    [locale]                 NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([id]), DISTRIBUTION = HASH([id]));

