trigger: none

variables:
- name: BuildConfiguration
  value: release
- name: environment
  value: stg
- group: SQLadminVarGroup

pool:
  vmImage: 'windows-latest'

steps:
- task: MSBuild@1
  displayName: 'Build ADW project'
  inputs:
    solution: AzureSynapseAnalytics/AzureSynapseAnalytics.sqlproj
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:build /p:CmdLineInMemoryStorage=True'
    createLogFile: true

- task: PowerShell@2
  displayName: 'List Contents'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "List root contents ::"
      Get-ChildItem "AzureSynapseAnalytics" -erroraction silentlycontinue ;
      Write-Host "List bin contents ::"
      Get-ChildItem "AzureSynapseAnalytics\bin" -erroraction silentlycontinue ;
      Write-Host "List output contents ::"
      Get-ChildItem "AzureSynapseAnalytics\bin\$(BuildConfiguration)"-erroraction silentlycontinue ;

- task: CopyFiles@2
  displayName: 'Copy Files to default working directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     AzureSynapseAnalytics\bin\$(BuildConfiguration)\AzureSynapseAnalytics.dacpac
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PowerShell@2
  displayName: 'List artifact directory'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "List artifact directory contents ::"
      Get-ChildItem "$env:ARTIFACT_DIRECTORY" -erroraction silentlycontinue ;
  env:
    ARTIFACT_DIRECTORY: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Synapse_DACPAC_Artifact'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Script Artifact'
  inputs:
    targetPath: 'Powershell'
    artifact: PsScripts
  enabled: true
