CREATE VIEW DWC.DimLeadCall
AS
SELECT [SKLeadCall]
      ,[ADLSTimestamp]
      ,[KeyLeadCall]
      ,[CallConnected]
      ,[CreatedById]
      ,[CreatedByUserName]
      ,[CreatedDate]
      ,[CurrencyIsoCode]
      ,[IsDeleted]
      ,[LastModifiedById]
      ,[LastModifiedByUserName]
      ,[Name]
      ,[OwnerId]
      ,[OwnerUserName]
      ,[RingAbandonedCall]
      ,[RingAccountId]
      ,[RingActivityDate]
      ,[RingCallConnected]
      ,[RingCallDirection]
      ,[RingCallDuationSec]
      ,[RingCallHourOfDayAgent]
      ,[RingCallHourOfDayLocal]
      ,[RingCallStatus]
      ,[RingCallObject]
      ,[RingCampaignId]
      ,[RingContactId]
      ,[RingLeadId]
      ,[RingDescription]
      ,[RingLocalPresence]
      ,[RingStatus]
      ,[SystemModstamp]
      ,[TimeOfDay]
      ,[LeadCountryCode]
	  ,[LeadCountry]
      ,[SecRegion]
 FROM [DW].[DimLeadCall] c
 INNER JOIN dwglobal.GeographyRegion d on d.RegionGroup = c.SecRegion and d.dataset='DWC'