CREATE VIEW [DWC].[DimOrderSFDC] AS select  o.[SKOrder],  o.[KeyOrder], o.[SFDCOrderNumber], o.[SFDCOrderName], o.[AMRDate], o.[CancellationDate], o.[CCADate], o.[ShipmentDate], o.[SubmitDate]
, o.[RejectedImpressionsDate], o.[CCUDDate], o.[CCAADate], o.[ClinicalHoldDate], o.[ProductType], o.[TreatmentCategory], o.[SKContact], o.[SKAccountTreatmentLocation]
, o.[SKAccountShipTo], o.[SKAccountBillTo], o.[SKAccountSoldTo], o.[SKAccountScanOffice], o.[SKAccountPayer], o.[PatientIsArchived]
, o.[RefinementFeeDate], o.[ListPrice], o.[NetPrice], o.[DiscountAmount], o.[TreatmentID], o.[CurrencyCode]
, o.[LICaseSetupDeliverableType], o.[LICaseSetupTreatmentOption], o.[LIAlignerDeliverableType], o.[LIAlignerTreatmentOption], o.[LIAlignerQtyFromSFDC]
, o.[USListPrice], o.[PaymentTerms], o.[PaymentMethod], o.[HasComplianceIdicator], o.[PatientTypeBrand], o.[PatientType], o.[ScanType], o.[AdditionalAlignersUsed]
, o.[TreatmentExpiryDate], o.[TreatedArches], o.[UpperQuantity], o.[LowerQuantity], o.[MAF], o.[IDSOrderStatus] 
, o.[SKPricingGroupTreatLoc] 
, o.[SubscriptionPackage]
, o.[SubscriptionProgram]
, o.[LICaseSetupProductCode]
, o.[LIAlignerProductCode]
, o.[ContractNumber]
, o.[WithinRFDDate]
, o.[WithinTEDDate]
, o.[HoldReason]
, o.[HoldDate]
, o.[AARefinementsUsed]
, o.[ReplacementsUsed]
, o.[SecRegion]
, o.[PatientAge]
, o.[PatientGender]
, o.[FirstAMRDate]
, o.[LastAMRDate]
, o.[FirstCCADate]
, o.[LastCCADate]
from [DW].[DimOrderSFDC] o left join DW.DimAccount a on o.[SKAccountShipTo] = a.SKAccount
inner join dwglobal.GeographyRegion d on d.RegionGroup = o.SecRegion and d.dataset='DWC';