CREATE VIEW [DWC].[DimOrderIDS] AS
select
o.[SKOrder]
, o.[KeyOrder]
, o.[IDSOrderNumber]
, o.[SKContact]
, o.[OrderType]
, o.[DeliverableType]
, o.[TreatmentCategory]
, o.[TreatmentType]
, o.[PatientCurrentStageLowerArch]
, o.[PatientCurrentStageUpperArch]
, o.[LastStaffDiscountUtilizedDate]
, o.[CancelReasonCode]
, o.[TreatedArches]
, o.[IsIOScan]
, o.[ScanType]
, o.[CaseCode]
, o.[SubmissionType]
, o.[SubmitDate]
, o.[FirstCCUDDate]
, o.[LastCCUDDate]
, o.[FirstCCAADate]
, o.[LastCCAADate]
, o.[FirstCCMODDate]
, o.[LastCCMODDate]
, o.[ShipmentScheduledDate]
, o.[ShipmentDate]
, o.[CancellationDate]
, o.[FirstMaterialsRequiredDate]
, o.[LastMaterialsRequiredDate]
, o.[ClinicalHoldDate]
, o.[UnknownOrderConvertedDate]
, o.[ProductSwitchDate]
, o.[FirstGenerateMTPDate]
, o.[LastGenerateMTPDate]
, o.[TreatmentID]
, o.[EECDDate]
, o.[ArchConversion]
, o.[PatientIsArchived]
, o.[HoldReason]
, o.[LoanNumber]
, o.[LoanTreatmentFee]
, o.[LoanApproveAmount]
, o.[ScanOfficeContactSFID]
, sfo.[SKAccountShipTo]
, o.[SecRegion]
, o.[AMRDate] as [FirstAMRDate]
, o.[LastAMRDate]
, o.[CCADate] as [FirstCCADate]
, o.[LastCCADate]
, o.[TreatmentFeature]
, o.[OrderCompleteDate]	
, o.[CCAAAgeing]		
, o.[MTP]				
, o.[FullOrPartial]		
from [DW].[DimOrderIDS] o
inner join [DW].[DimOrderSFDC] sfo on o.SKOrder = sfo.SKOrder
left join DW.DimAccount a on sfo.[SKAccountShipTo] = a.SKAccount
INNER JOIN dwglobal.GeographyRegion d on d.RegionGroup = o.SecRegion and d.dataset ='DWC';