CREATE VIEW [DWC].[DimProduct] AS
SELECT [Product hierarchy]
      ,[Product Hierarchy Desc]
      ,[ProductCategory]
      ,[ProductClassification]
      ,[ProductGroup]
      ,[ProductSegment]
      ,[ProductSubGroup]
      ,[BusinessSegment]
      ,[Number of the level in the product hierarchy]
      ,[Level 1 A]
      ,[Level 2 A]
      ,[Level2Sorted]
      ,[Level 3 A]
      ,[Level3Sorted]
      ,[Level 4 A]
      ,[Level4Sorted]
      ,[Level 5 A]
      ,[Level5Sorted]
      ,[Level 6 A]
      ,[Level6Sorted]
      ,[Level 7 A]
      ,[Level7Sorted]
      ,[Level 8 A]
      ,[Level8Sorted]
      ,[Level 1 S]
      ,[Level 2 S]
      ,[Level 3 S]
      ,[Level 4 S]
      ,[Level 5 S]
      ,[Level 6 S]
      ,[Level2Sort]
      ,[Level3Sort]
      ,[Level4Sort]
      ,[Level5Sort]
      ,[Level6Sort]
  FROM [TABSAP].[DimProduct];


