CREATE VIEW [DWC].[FactSagaEnrollment]
AS SELECT  [ID]
		  ,[SKAccountSoldTo]
		  ,[SoldToAccountNumber]
		  ,[ContractNumber]
		  ,[IsActive]
		  ,[CreatedDate]
		  ,[StartDate]
		  ,[EligibilityStartDate]
		  ,[EndDate]
		  ,[EnrollmentType]
		  ,[PreEnrollmentAllowed]
		  ,[AllowableAligners]
		  ,[AlignersUsed]
		  ,[AlignersLeft]
		  ,[SecRegion]
		  ,[SoldToAccountType]
		  ,[SoldToAccountSubType]
		  ,[AccountPricingGroupTreatLocCountry]
		  ,[AccountPricingGroupTreatLoc]
  FROM [DW].[FactSagaEnrollment] a
INNER JOIN dwglobal.GeographyRegion d on d.RegionGroup = a.SecRegion and d.dataset='DWC';