CREATE TABLE [SrcSFDC].[Account] (
    [LZBatchID]                      INT              NOT NULL,
    [ADLSBatchID]                    INT              NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)    NOT NULL,
    [Accepted_Date__c]               DATETIME2 (7)    NULL,
    [Accepted_T_C_date__c]           DATETIME2 (7)    NULL,
    [Account_Auto_Number__c]         NVARCHAR (30)    NULL,
    [Account_Currency__c]            NVARCHAR (1300)  NULL,
    [Account_Level__c]               NVARCHAR (255)   NULL,
    [Account_Number__c]              NVARCHAR (40)    NULL,
    [Account_Owner_Role__c]          NVARCHAR (1300)  NULL,
    [Account_Status__c]              NVARCHAR (255)   NULL,
    [Account_Sub_Type__c]            NVARCHAR (255)   NULL,
    [Address_Street_1__c]            NVARCHAR (35)    NULL,
    [Address_Street_2__c]            NVARCHAR (35)    NULL,
    [Address_Street_3__c]            NVARCHAR (35)    NULL,
    [Address_Street_4__c]            NVARCHAR (35)    NULL,
    [Address_Type__c]                NVARCHAR (256)   NULL,
    [Address_Validation__c]          NVARCHAR (255)   NULL,
    [Adult_Patient_Ratio__c]         DECIMAL (18)     NULL,
    [Attitude__c]                    NVARCHAR (200)   NULL,
    [Auto_Payment_Enabled__c]        NVARCHAR (255)   NULL,
    [Billing_Language__c]            NVARCHAR (255)   NULL,
    [BillingCity]                    NVARCHAR (40)    NULL,
    [BillingCountry]                 NVARCHAR (80)    NULL,
    [BillingCountryCode]             NVARCHAR (10)    NULL,
    [BillingGeocodeAccuracy]         NVARCHAR (40)    NULL,
    [BillingLatitude]                DECIMAL (18, 15) NULL,
    [BillingLongitude]               DECIMAL (18, 15) NULL,
    [BillingPostalCode]              NVARCHAR (20)    NULL,
    [BillingState]                   NVARCHAR (80)    NULL,
    [BillingStateCode]               NVARCHAR (10)    NULL,
    [BillingStreet]                  NVARCHAR (255)   NULL,
    [Business_Unit__c]               NVARCHAR (255)   NULL,
    [Completed_Date__c]              DATETIME2 (7)    NULL,
    [Contact_Preference__c]          NVARCHAR (255)   NULL,
    [CreatedById]                    NCHAR (18)       NULL,
    [CreatedDate]                    DATETIME2 (7)    NOT NULL,
    [Customer_Group__c]              NVARCHAR (255)   NULL,
    [Declined_Date__c]               DATETIME2 (7)    NULL,
    [Doctor_Locator__c]              NVARCHAR (255)   NULL,
    [DSO_Private_Practice__c]        BIT              NULL,
    [DUNS_ID__c]                     NVARCHAR (40)    NULL,
    [Effective_Start_Date__c]        DATETIME2 (7)    NULL,
    [Email__c]                       NVARCHAR (80)    NULL,
    [Failed_to_Complete_Date__c]     DATETIME2 (7)    NULL,
    [Fax]                            NVARCHAR (40)    NULL,
    [Group_Account_Is_Targetable__c] NVARCHAR (255)   NULL,
    [Id]                             NCHAR (18)       NOT NULL,
    [Indirect_Customer_Number__c]    NVARCHAR (50)    NULL,
    [Invisalign_Sales_Channel__c]    NVARCHAR (255)   NULL,
    [LastModifiedById]               NCHAR (18)       NULL,
    [LastModifiedDate]               DATETIME2 (7)    NOT NULL,
    [Latitude__c]                    NVARCHAR (40)    NULL,
    [Line_of_Business__c]            NVARCHAR (256)   NULL,
    [Longitude__c]                   NVARCHAR (40)    NULL,
    [Mailing_Name__c]                NVARCHAR (35)    NULL,
    [Master_Quintile__c]             NVARCHAR (80)    NULL,
    [MAT_ID__c]                      NVARCHAR (25)    NULL,
    [Mobile_Phone__c]                NVARCHAR (40)    NULL,
    [Name]                           NVARCHAR (255)   NOT NULL,
    [Notification_Email__c]          NVARCHAR (80)    NULL,
    [OwnerId]                        NCHAR (18)       NOT NULL,
    [ParentId]                       NCHAR (18)       NULL,
    [Phone]                          NVARCHAR (40)    NULL,
    [PLD__c]                         NVARCHAR (10)    NULL,
    [Post_IFC_Call_Date__c]          DATETIME2 (7)    NULL,
    [Potential_Quintile__c]          NVARCHAR (80)    NULL,
    [PP_ID__c]                       NVARCHAR (25)    NULL,
    [Practice_Name__c]               NVARCHAR (1300)  NULL,
    [Pre_IFC_Call_Date__c]           DATETIME2 (7)    NULL,
    [Quarterly_Baseline__c]          NVARCHAR (50)    NULL,
    [RecordTypeId]                   NCHAR (18)       NULL,
    [Sales_Quintile__c]              NVARCHAR (50)    NULL,
    [Scanner_Type__c]                NVARCHAR (256)   NULL,
    [Shipping_County__c]             NVARCHAR (40)    NULL,
    [ShippingCity]                   NVARCHAR (40)    NULL,
    [ShippingCountry]                NVARCHAR (80)    NULL,
    [ShippingCountryCode]            NVARCHAR (10)    NULL,
    [ShippingGeocodeAccuracy]        NVARCHAR (40)    NULL,
    [ShippingLatitude]               DECIMAL (18, 15) NULL,
    [ShippingLongitude]              DECIMAL (18, 15) NULL,
    [ShippingPostalCode]             NVARCHAR (20)    NULL,
    [ShippingState]                  NVARCHAR (80)    NULL,
    [ShippingStateCode]              NVARCHAR (10)    NULL,
    [ShippingStreet]                 NVARCHAR (255)   NULL,
    [Special_account__c]             NVARCHAR (255)   NULL,
    [Status_Reason__c]               NVARCHAR (255)   NULL,
    [Step_1_Date__c]                 DATETIME2 (7)    NULL,
    [Step_2_Date__c]                 DATETIME2 (7)    NULL,
    [Step_3_Date__c]                 DATETIME2 (7)    NULL,
    [Step_4_Date__c]                 DATETIME2 (7)    NULL,
    [Step_5_Date__c]                 DATETIME2 (7)    NULL,
    [Step_6_Date__c]                 DATETIME2 (7)    NULL,
    [Step_7_Date__c]                 DATETIME2 (7)    NULL,
    [Study_Group__c]                 NCHAR (18)       NULL,
    [SystemModstamp]                 DATETIME2 (7)    NOT NULL,
    [Translated_City__c]             NVARCHAR (35)    NULL,
    [Translated_Country__c]          NVARCHAR (50)    NULL,
    [Translated_County__c]           NVARCHAR (40)    NULL,
    [Translated_FirstName__c]        NVARCHAR (35)    NULL,
    [Translated_LastName__c]         NVARCHAR (35)    NULL,
    [Translated_Mailing_Name__c]     NVARCHAR (35)    NULL,
    [Translated_Name2__c]            NVARCHAR (35)    NULL,
    [Translated_Name__c]             NVARCHAR (35)    NULL,
    [Translated_Postal_Code__c]      NVARCHAR (20)    NULL,
    [Translated_Salutation__c]       NVARCHAR (35)    NULL,
    [Translated_State__c]            NVARCHAR (50)    NULL,
    [Treatment_Team__c]              NVARCHAR (255)   NULL,
    [Trend__c]                       NVARCHAR (50)    NULL,
    [Type]                           NVARCHAR (40)    NULL,
    [Website]                        NVARCHAR (255)   NULL,
    [Region__c]                      NVARCHAR (1300)  NULL,
    [Pricing_Group__c]               NCHAR (18)       NULL,
	[Doctor_Name__c]                 NVARCHAR (1300)  NULL,
	[Lab_Type__c]                    NVARCHAR (255)   NULL,
    [Account_Segmentation__c]        NVARCHAR (510)   NULL,
    [Group_Accounts__c]              NCHAR (18)       NULL,
    [Invoice_preference__c]          NVARCHAR (255)   NULL,
    [Account_Accepted_Programs__c]   VARCHAR (4000)   NULL,
    [Promotion_Region__c]            NVARCHAR(255)    NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

