CREATE TABLE [SrcSFDC].[Account_Relationship__c] (
    [LZBatchID]                      INT             NOT NULL,
    [ADLSBatchID]                    INT             NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)   NOT NULL,
    [Account_Number__c]              NVARCHAR (1300) NULL,
    [Child_Account__c]               NCHAR (18)      NULL,
    [child_Account_Payment_Term__c]  NVARCHAR (1300) NULL,
    [child_Account_Status__c]        NVARCHAR (1300) NULL,
    [child_address_type__c]          BIT             NULL,
    [Child_MAT_Id__c]                NVARCHAR (1300) NULL,
    [child_parentid__c]              NVARCHAR (1300) NULL,
    [child_recordtype__c]            NVARCHAR (1300) NULL,
    [Child_Relationship__c]          NVARCHAR (255)  NULL,
    [child_sales_channel__c]         NVARCHAR (1300) NULL,
    [child_shippingcountrycode__c]   NVARCHAR (1300) NULL,
    [ConnectionReceivedId]           NCHAR (18)      NULL,
    [ConnectionSentId]               NCHAR (18)      NULL,
    [CreatedById]                    NCHAR (18)      NULL,
    [CreatedDate]                    DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                NVARCHAR (3)    NOT NULL,
    [External_Id__c]                 NVARCHAR (255)  NULL,
    [Id]                             NCHAR (18)      NOT NULL,
    [Is_Auto_Created__c]             BIT             NULL,
    [IsDeleted]                      BIT             NOT NULL,
    [LastModifiedById]               NCHAR (18)      NULL,
    [LastModifiedDate]               DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]             DATETIME2 (7)   NULL,
    [LastViewedDate]                 DATETIME2 (7)   NULL,
    [Line_of_Business__c]            NVARCHAR (1300) NULL,
    [Name]                           NVARCHAR (80)   NULL,
    [Parent_Account__c]              NCHAR (18)      NULL,
    [Parent_Account_Number__c]       NVARCHAR (1300) NULL,
    [Parent_Account_Payment_Term__c] NVARCHAR (1300) NULL,
    [Parent_Account_Status__c]       NVARCHAR (1300) NULL,
    [parent_country__c]              NVARCHAR (1300) NULL,
    [Parent_MAT_Id__c]               NVARCHAR (1300) NULL,
    [parent_recordtype__c]           NVARCHAR (1300) NULL,
    [Parent_Relationship__c]         NVARCHAR (255)  NULL,
    [Parent_Type__c]                 NVARCHAR (1300) NULL,
    [Status__c]                      NVARCHAR (255)  NULL,
    [SystemModstamp]                 DATETIME2 (7)   NOT NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

