create table SrcSFDC.Appointment__c
(
	LZBatchID int not null,
	ADLSBatchID int not null,
	ADLSTimestamp datetime2(0) not null,
	Account__c nchar(18),
	Canceled_Reason__c nvarchar(255),
	ClinCheck_Accepted_Date__c datetime2,
	Comments__c nvarchar(255),
	ConnectionReceivedId nvarchar(255),
	ConnectionSentId nvarchar(255),
	Consult_Date__c datetime2,
	Consult_Type__c nvarchar(255),
	Contact__c nchar(18),
	Converted_Date__c datetime2,
	Converted_to_Patient__c bit,
	CreatedById nchar(18),
	CreatedDate datetime2,
	CurrencyIsoCode nvarchar(3),
	Duration_In_Minutes__c int,
	End_Date__c datetime2,
	Heroku_External_Id__c nvarchar(255),
	Id nchar(18) not null,
	IsDeleted bit,
	LastActivityDate datetime2,
	LastModifiedById nchar(18),
	LastModifiedDate datetime2,
	LastReferencedDate datetime2,
	LastViewedDate datetime2,
	Lead__c nchar(18),
	Lead_Journey__c nchar(18),
	Name nvarchar(255),
	Notes__c nvarchar(1000),
	OwnerId nchar(18),
	Patient__c nchar(18),
	Reason__c nvarchar(255),
	RM__c nchar(18),
	Scheduled_Date__c datetime2,
	Start_Date__c datetime2,
	Status__c nvarchar(255),
	SystemModstamp datetime2,
	TM__c nchar(18)
	)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));