CREATE TABLE [SrcSFDC].[Apttus_Proposal__Proposal__c] (
    [LZBatchID]                                      INT             NOT NULL,
    [ADLSBatchID]                                    INT             NOT NULL,
    [ADLSTimestamp]                                  DATETIME2 (0)   NOT NULL,
    [Account_Number_from_Account__c]                 NVARCHAR (1300) NULL,
    [Account_Practice_Name__c]                       NVARCHAR (1300) NULL,
    [Additional_Information__c]                      NVARCHAR (255)  NULL,
    [Additional_Information_iTero__c]                NVARCHAR (255)  NULL,
    [Additional_Ship_To__c]                          BIT             NULL,
    [APTS_1st_iTero_Unit__c]                         BIT             NULL,
    [APTS_2_9_Restorative_Renewal__c]                BIT             NULL,
    [APTS_2nd_and_Additional_iTero_Unit__c]          BIT             NULL,
    [APTS_2nd_iTero_Scanner__c]                      BIT             NULL,
    [APTS_3rd_or_Addtional_iTero_Scanner__c]         BIT             NULL,
    [APTS_Accept__c]                                 NVARCHAR (1300) NULL,
    [APTS_Configure_Products__c]                     NVARCHAR (1300) NULL,
    [APTS_Preview__c]                                NVARCHAR (1300) NULL,
    [APTS_Second_iTero_Scanner__c]                   BIT             NULL,
    [APTS_Training_Required__c]                      BIT             NULL,
    [Apttus_Proposal__Account__c]                    NCHAR (18)      NULL,
    [Apttus_Proposal__Amount__c]                     DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Approval_Stage__c]             NVARCHAR (255)  NULL,
    [Apttus_Proposal__CreateAgreement__c]            NVARCHAR (1300) NULL,
    [Apttus_Proposal__Description__c]                NVARCHAR (MAX)  NULL,
    [Apttus_Proposal__Discount_Percent__c]           DECIMAL (18, 2) NULL,
    [Apttus_Proposal__ExpectedEndDate__c]            DATETIME2 (7)   NULL,
    [Apttus_Proposal__ExpectedStartDate__c]          DATETIME2 (7)   NULL,
    [Apttus_Proposal__Generate__c]                   NVARCHAR (1300) NULL,
    [Apttus_Proposal__Grand_Total__c]                DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Internal_Deadline__c]          DATETIME2 (7)   NULL,
    [Apttus_Proposal__MakePrimary__c]                NVARCHAR (1300) NULL,
    [Apttus_Proposal__Net_Amount__c]                 DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Opportunity__c]                NCHAR (18)      NULL,
    [Apttus_Proposal__Payment_Term__c]               NVARCHAR (255)  NULL,
    [Apttus_Proposal__Present__c]                    NVARCHAR (1300) NULL,
    [Apttus_Proposal__Presented_Date__c]             DATETIME2 (7)   NULL,
    [Apttus_Proposal__Preview__c]                    NVARCHAR (1300) NULL,
    [Apttus_Proposal__Primary__c]                    BIT             NULL,
    [Apttus_Proposal__Primary_Contact__c]            NCHAR (18)      NULL,
    [Apttus_Proposal__Proposal_Approval_Date__c]     DATETIME2 (7)   NULL,
    [Apttus_Proposal__Proposal_Category__c]          NVARCHAR (255)  NULL,
    [Apttus_Proposal__Proposal_Expiration_Date__c]   DATETIME2 (7)   NULL,
    [Apttus_Proposal__Proposal_Name__c]              NVARCHAR (255)  NULL,
    [Apttus_Proposal__ReadyToGenerate__c]            BIT             NULL,
    [Apttus_Proposal__ReadyToPresent__c]             BIT             NULL,
    [Apttus_Proposal__Request_Approval__c]           NVARCHAR (1300) NULL,
    [Apttus_Proposal__RFP_Intake_Date__c]            DATETIME2 (7)   NULL,
    [Apttus_Proposal__RFP_Response_Due_Date__c]      DATETIME2 (7)   NULL,
    [Apttus_Proposal__RFP_Stage__c]                  NVARCHAR (255)  NULL,
    [Apttus_Proposal__RFP_Value__c]                  DECIMAL (18)    NULL,
    [Apttus_Proposal__Risk_Factors__c]               NVARCHAR (MAX)  NULL,
    [Apttus_Proposal__Sales_Tax_Amount__c]           DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Sales_Tax_Percent__c]          DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Shipping_Handling__c]          DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Special_Terms__c]              NVARCHAR (255)  NULL,
    [Apttus_Proposal__Strategic_Importance__c]       NVARCHAR (255)  NULL,
    [Apttus_Proposal__SubmitForApproval__c]          NVARCHAR (1300) NULL,
    [Apttus_Proposal__Valid_Until_Date__c]           DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ABOType__c]                    NVARCHAR (255)  NULL,
    [Apttus_QPConfig__Accept__c]                     NVARCHAR (1300) NULL,
    [Apttus_QPConfig__AutoActivateOrder__c]          BIT             NULL,
    [Apttus_QPConfig__AutoCreateBill__c]             BIT             NULL,
    [Apttus_QPConfig__AutoCreateRevenue__c]          BIT             NULL,
    [Apttus_QPConfig__BillingPreferenceId__c]        NCHAR (18)      NULL,
    [Apttus_QPConfig__BillToAccountId__c]            NCHAR (18)      NULL,
    [Apttus_QPConfig__ConfigurationFinalizedDate__c] DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ConfigurationSyncDate__c]      DATETIME2 (7)   NULL,
    [Apttus_QPConfig__Configure__c]                  NVARCHAR (1300) NULL,
    [Apttus_QPConfig__ConfigureNG__c]                NVARCHAR (1300) NULL,
    [Apttus_QPConfig__IsAutoAccepted__c]             BIT             NULL,
    [Apttus_QPConfig__IsSystemGenerated__c]          BIT             NULL,
    [Apttus_QPConfig__IsTaskPending__c]              BIT             NULL,
    [Apttus_QPConfig__LocationId__c]                 NCHAR (18)      NULL,
    [Apttus_QPConfig__PaymentTermId__c]              NCHAR (18)      NULL,
    [Apttus_QPConfig__PODate__c]                     DATETIME2 (7)   NULL,
    [Apttus_QPConfig__PONumber__c]                   NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PriceListId__c]                NCHAR (18)      NULL,
    [Apttus_QPConfig__PricingDate__c]                DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForActivationDate__c]     DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForBillingDate__c]        DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForFulfillmentDate__c]    DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForRevRecDate__c]         DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ShipToAccountId__c]            NCHAR (18)      NULL,
    [Apttus_QPConfig__SyncAssetChangesToQuote__c]    BIT             NULL,
    [Apttus_QPConfig__SyncWithOpportunity__c]        NVARCHAR (1300) NULL,
    [Apttus_QPDSign__CheckESignatureStatus__c]       NVARCHAR (1300) NULL,
    [Apttus_QPDSign__RecallESignatureRequest__c]     NVARCHAR (1300) NULL,
    [Apttus_QPDSign__SendForESignature__c]           NVARCHAR (1300) NULL,
    [Apttus_QPDSign__ViewESignatureDocument__c]      NVARCHAR (1300) NULL,
    [CCA_Date__c]                                    DATETIME2 (7)   NULL,
    [Company_Name__c]                                NVARCHAR (255)  NULL,
    [ConnectionReceivedId]                           NCHAR (18)      NULL,
    [ConnectionSentId]                               NCHAR (18)      NULL,
    [Contract_Signed_Date__c]                        DATETIME2 (7)   NULL,
    [Contract_Type__c]                               NVARCHAR (255)  NULL,
    [Country__c]                                     NVARCHAR (255)  NULL,
    [Created_Date__c]                                DATETIME2 (7)   NULL,
    [CreatedById]                                    NCHAR (18)      NULL,
    [CreatedDate]                                    DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                                NVARCHAR (3)    NOT NULL,
    [Element_Scanner_Type__c]                        NVARCHAR (255)  NULL,
    [Existing_2_05_2_1_EOS_Customer__c]              BIT             NULL,
    [Funding_Source__c]                              NVARCHAR (1300) NULL,
    [Generate__c]                                    NVARCHAR (1300) NULL,
    [Generate_Proforma_Invoice__c]                   NVARCHAR (1300) NULL,
    [Id]                                             NCHAR (18)      NOT NULL,
    [IsDeleted]                                      BIT             NOT NULL,
    [LastActivityDate]                               DATETIME2 (7)   NULL,
    [LastModifiedById]                               NCHAR (18)      NULL,
    [LastModifiedDate]                               DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]                             DATETIME2 (7)   NULL,
    [LastViewedDate]                                 DATETIME2 (7)   NULL,
    [Multi_Scanner_Subscription_Billing__c]          BIT             NULL,
    [Name]                                           NVARCHAR (80)   NULL,
    [Net_Price__c]                                   DECIMAL (18, 2) NULL,
    [Net_Price_Main__c]                              DECIMAL (18, 2) NULL,
    [New_Owner_Account__c]                           NCHAR (18)      NULL,
    [New_Owner_Account_Contact__c]                   NCHAR (18)      NULL,
    [Opportunity_Contact__c]                         NVARCHAR (1300) NULL,
    [Opportunity_Stage__c]                           NVARCHAR (1300) NULL,
    [OwnerId]                                        NCHAR (18)      NOT NULL,
    [Paper_Document_Uploaded__c]                     BIT             NULL,
    [Proforma_Generated_Date__c]                     DATETIME2 (7)   NULL,
    [Proforma_Invoice_Date__c]                       DATETIME2 (7)   NULL,
    [Proforma_Valid_Thru__c]                         DATETIME2 (7)   NULL,
    [Promotion_Region__c]                            NVARCHAR (1300) NULL,
    [RecordTypeId]                                   NCHAR (18)      NULL,
    [Region__c]                                      NVARCHAR (1300) NULL,
    [Seller_Amount_Resale_Relo__c]                   DECIMAL (18, 2) NULL,
    [Send_For_Signatures__c]                         NVARCHAR (1300) NULL,
    [Service_Fees_PAV__c]                            NVARCHAR (255)  NULL,
    [Sold_on_Show_Floor__c]                          BIT             NULL,
    [Sold_To_Channel__c]                             NVARCHAR (1300) NULL,
    [Sold_To_Country__c]                             NVARCHAR (1300) NULL,
    [Sold_To_Currency__c]                            NVARCHAR (1300) NULL,
    [Subtotal__c]                                    DECIMAL (18, 2) NULL,
    [SystemModstamp]                                 DATETIME2 (7)   NOT NULL,
    [Tax_Amount__c]                                  DECIMAL (18, 2) NULL,
    [Total_Adjusted_Amount__c]                       DECIMAL (18, 2) NULL,
    [Total_Adjustment_Amount__c]                     DECIMAL (18, 2) NULL,
    [Total_Adjustment_Amount_Round__c]               DECIMAL (18)    NULL,
    [Total_Amount__c]                                DECIMAL (18, 2) NULL,
    [Total_Incentive_Adjustment_Amount__c]           DECIMAL (18, 2) NULL,
    [Total_List_Price_Accessories__c]                DECIMAL (18, 2) NULL,
    [Total_List_Price_Main__c]                       DECIMAL (18, 2) NULL,
    [Total_List_Price_without_Discount__c]           DECIMAL (18, 2) NULL,
    [Treatment_Category__c]                          NVARCHAR (255)  NULL,
    [Upload_Paper_Contract__c]                       NVARCHAR (1300) NULL,
    [Volume_Tier__c]                                 NVARCHAR (255)  NULL,
    [White_Glove_Training__c]                        DECIMAL (18, 2) NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

