CREATE TABLE [SrcSFDC].[Apttus_Proposal__Proposal_Line_Item__c] (
    [LZBatchID]                                     INT             NOT NULL,
    [ADLSBatchID]                                   INT             NOT NULL,
    [ADLSTimestamp]                                 DATETIME2 (0)   NOT NULL,
    [APTS_Net_Price1__c]                            DECIMAL (18, 2) NULL,
    [APTS_Product_Name__c]                          NVARCHAR (1300) NULL,
    [APTS_Quantity1__c]                             DECIMAL (18, 2) NULL,
    [APTS_Template_Description__c]                  NVARCHAR (1300) NULL,
    [Apttus_Proposal__Description__c]               NVARCHAR (255)  NULL,
    [Apttus_Proposal__Ext_Net_Price__c]             DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Ext_Price__c]                 DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Product__c]                   NCHAR (18)      NULL,
    [Apttus_Proposal__Proposal__c]                  NCHAR (18)      NULL,
    [Apttus_Proposal__Quantity__c]                  DECIMAL (18)    NULL,
    [Apttus_Proposal__Sales_Discount__c]            DECIMAL (18, 1) NULL,
    [Apttus_Proposal__Service_Date__c]              DATETIME2 (7)   NULL,
    [Apttus_Proposal__Unit_Net_Price__c]            DECIMAL (18, 2) NULL,
    [Apttus_Proposal__Unit_Price__c]                DECIMAL (18, 2) NULL,
    [Apttus_QPConfig__AdjustedPrice__c]             DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__AdjustmentAmount__c]          DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__AdjustmentType__c]            NVARCHAR (255)  NULL,
    [Apttus_QPConfig__AssetId__c]                   NCHAR (18)      NULL,
    [Apttus_QPConfig__AssetLineItemId__c]           NCHAR (18)      NULL,
    [Apttus_QPConfig__AttributeValueId__c]          NCHAR (18)      NULL,
    [Apttus_QPConfig__AutoActivateOrder__c]         BIT             NULL,
    [Apttus_QPConfig__AutoCreateBill__c]            BIT             NULL,
    [Apttus_QPConfig__AutoCreateRevenue__c]         BIT             NULL,
    [Apttus_QPConfig__BaseCost__c]                  DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__BaseCostOverride__c]          DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__BaseExtendedCost__c]          DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__BaseExtendedPrice__c]         DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__BasePrice__c]                 DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__BasePriceMethod__c]           NVARCHAR (255)  NULL,
    [Apttus_QPConfig__BasePriceOverride__c]         DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__BaseProductId__c]             NCHAR (18)      NULL,
    [Apttus_QPConfig__BillingFrequency__c]          NVARCHAR (255)  NULL,
    [Apttus_QPConfig__BillingPlanId__c]             NCHAR (18)      NULL,
    [Apttus_QPConfig__BillingPreferenceId__c]       NCHAR (18)      NULL,
    [Apttus_QPConfig__BillingRule__c]               NVARCHAR (255)  NULL,
    [Apttus_QPConfig__BillToAccountId__c]           NCHAR (18)      NULL,
    [Apttus_QPConfig__ChargeGroupId__c]             NCHAR (18)      NULL,
    [Apttus_QPConfig__ChargeType__c]                NVARCHAR (255)  NULL,
    [Apttus_QPConfig__ClassificationHierarchy__c]   NVARCHAR (255)  NULL,
    [Apttus_QPConfig__ClassificationId__c]          NCHAR (18)      NULL,
    [Apttus_QPConfig__Comments__c]                  NVARCHAR (MAX)  NULL,
    [Apttus_QPConfig__CommitmentQuantity__c]        DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__ConfigurationId__c]           NCHAR (18)      NULL,
    [Apttus_QPConfig__ContractNumbers__c]           NVARCHAR (255)  NULL,
    [Apttus_QPConfig__Cost__c]                      DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__CouponCode__c]                NVARCHAR (6)    NULL,
    [Apttus_QPConfig__DerivedFromId__c]             NCHAR (18)      NULL,
    [Apttus_QPConfig__EndDate__c]                   DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ExtendedCost__c]              DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__ExtendedDescription__c]       NVARCHAR (2048) NULL,
    [Apttus_QPConfig__ExtendedPrice__c]             DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__ExtendedQuantity__c]          DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__FlatOptionPrice__c]           DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__Frequency__c]                 NVARCHAR (255)  NULL,
    [Apttus_QPConfig__GroupAdjustmentPercent__c]    DECIMAL (18, 4) NULL,
    [Apttus_QPConfig__Guidance__c]                  NVARCHAR (255)  NULL,
    [Apttus_QPConfig__HasAttributes__c]             BIT             NULL,
    [Apttus_QPConfig__HasIncentives__c]             BIT             NULL,
    [Apttus_QPConfig__HasOptions__c]                BIT             NULL,
    [Apttus_QPConfig__HideInvoiceDisplay__c]        BIT             NULL,
    [Apttus_QPConfig__IncentiveAdjustmentAmount__c] DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__IncentiveCode__c]             NVARCHAR (255)  NULL,
    [Apttus_QPConfig__IncentiveExtendedPrice__c]    DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__IncentiveId__c]               NCHAR (18)      NULL,
    [Apttus_QPConfig__IncentiveType__c]             NVARCHAR (255)  NULL,
    [Apttus_QPConfig__IsAssetPricing__c]            BIT             NULL,
    [Apttus_QPConfig__IsCustomPricing__c]           BIT             NULL,
    [Apttus_QPConfig__IsOptionRollupLine__c]        BIT             NULL,
    [Apttus_QPConfig__IsPrimaryLine__c]             BIT             NULL,
    [Apttus_QPConfig__IsPrimaryRampLine__c]         BIT             NULL,
    [Apttus_QPConfig__IsUsageTierModifiable__c]     BIT             NULL,
    [Apttus_QPConfig__ItemSequence__c]              DECIMAL (18)    NULL,
    [Apttus_QPConfig__LineNumber__c]                DECIMAL (18)    NULL,
    [Apttus_QPConfig__LineStatus__c]                NVARCHAR (255)  NULL,
    [Apttus_QPConfig__LineType__c]                  NVARCHAR (255)  NULL,
    [Apttus_QPConfig__ListPrice__c]                 DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__LocationId__c]                NCHAR (18)      NULL,
    [Apttus_QPConfig__NetAdjustmentPercent__c]      DECIMAL (18, 4) NULL,
    [Apttus_QPConfig__NetPrice__c]                  DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__NetUnitPrice__c]              DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__OptionCost__c]                DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__OptionId__c]                  NCHAR (18)      NULL,
    [Apttus_QPConfig__OptionPrice__c]               DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__ParentBundleNumber__c]        DECIMAL (18)    NULL,
    [Apttus_QPConfig__PaymentTermId__c]             NCHAR (18)      NULL,
    [Apttus_QPConfig__PriceAdjustment__c]           DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__PriceAdjustmentAmount__c]     DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__PriceAdjustmentType__c]       NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PriceGroup__c]                NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PriceIncludedInBundle__c]     BIT             NULL,
    [Apttus_QPConfig__PriceListId__c]               NCHAR (18)      NULL,
    [Apttus_QPConfig__PriceListItemId__c]           NCHAR (18)      NULL,
    [Apttus_QPConfig__PriceMethod__c]               NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PriceType__c]                 NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PriceUom__c]                  NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PricingDate__c]               DATETIME2 (7)   NULL,
    [Apttus_QPConfig__PrimaryLineNumber__c]         DECIMAL (18)    NULL,
    [Apttus_QPConfig__ProductOptionId__c]           NCHAR (18)      NULL,
    [Apttus_QPConfig__Quantity2__c]                 DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__ReadyForActivationDate__c]    DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForBillingDate__c]       DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForFulfillmentDate__c]   DATETIME2 (7)   NULL,
    [Apttus_QPConfig__ReadyForRevRecDate__c]        DATETIME2 (7)   NULL,
    [Apttus_QPConfig__SellingFrequency__c]          NVARCHAR (255)  NULL,
    [Apttus_QPConfig__SellingTerm__c]               DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__ShipToAccountId__c]           NCHAR (18)      NULL,
    [Apttus_QPConfig__StartDate__c]                 DATETIME2 (7)   NULL,
    [Apttus_QPConfig__SummaryGroupId__c]            NCHAR (18)      NULL,
    [Apttus_QPConfig__Taxable__c]                   BIT             NULL,
    [Apttus_QPConfig__TaxCodeId__c]                 NCHAR (18)      NULL,
    [Apttus_QPConfig__TaxInclusive__c]              BIT             NULL,
    [Apttus_QPConfig__Term__c]                      DECIMAL (18)    NULL,
    [Apttus_QPConfig__Uom__c]                       NVARCHAR (255)  NULL,
    [Base_Extended_Price1__c]                       DECIMAL (18, 2) NULL,
    [ConnectionReceivedId]                          NCHAR (18)      NULL,
    [ConnectionSentId]                              NCHAR (18)      NULL,
    [CreatedById]                                   NCHAR (18)      NULL,
    [CreatedDate]                                   DATETIME2 (7)   NOT NULL,
    [Currency_Sign__c]                              NVARCHAR (1300) NULL,
    [CurrencyIsoCode]                               NVARCHAR (3)    NOT NULL,
    [Element_Scanner_Type__c]                       NVARCHAR (1300) NULL,
    [Id]                                            NCHAR (18)      NOT NULL,
    [Incentive_Adjustment_Amount_New__c]            DECIMAL (18, 2) NULL,
    [IsDeleted]                                     BIT             NOT NULL,
    [LastActivityDate]                              DATETIME2 (7)   NULL,
    [LastModifiedById]                              NCHAR (18)      NULL,
    [LastModifiedDate]                              DATETIME2 (7)   NOT NULL,
    [List_Price1__c]                                DECIMAL (18, 2) NULL,
    [Name]                                          NVARCHAR (80)   NULL,
    [Product_Code__c]                               NVARCHAR (1300) NULL,
    [Resale_Relo_Calc__c]                           DECIMAL (18, 2) NULL,
    [SystemModstamp]                                DATETIME2 (7)   NOT NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

