CREATE TABLE [SrcSFDC].[Apttus_Config2__IncentiveLoyaltyEnrollment__c] (
    [LZBatchID]                                       INT             NOT NULL,
    [ADLSBatchID]                                     INT             NOT NULL,
    [ADLSTimestamp]                                   DATETIME2 (0)   NOT NULL,
    [Apply_ADV_Promo__c]                              BIT             NULL,
    [Apttus_Config2__AccountId__c]                    NCHAR (18)      NULL,
    [Apttus_Config2__Active__c]                       BIT             NULL,
    [Apttus_Config2__AdditionalPointsForNextLevel__c] DECIMAL (18)    NULL,
    [Apttus_Config2__AdditionalPointsToKeepLevel__c]  DECIMAL (18)    NULL,
    [Apttus_Config2__ContactId__c]                    NCHAR (18)      NULL,
    [Apttus_Config2__CustomerType__c]                 NVARCHAR (255)  NULL,
    [Apttus_Config2__EligibilityStartDate__c]         DATETIME2 (7)   NULL,
    [Apttus_Config2__EndDate__c]                      DATETIME2 (7)   NULL,
    [Apttus_Config2__EnrollmentType__c]               NVARCHAR (255)  NULL,
    [Apttus_Config2__LifetimePoints__c]               DECIMAL (18)    NULL,
    [Apttus_Config2__LoyaltyLevel__c]                 NVARCHAR (255)  NULL,
    [Apttus_Config2__Points__c]                       DECIMAL (18)    NULL,
    [Apttus_Config2__StartDate__c]                    DATETIME2 (7)   NULL,
    [CreatedById]                                     NCHAR (18)      NULL,
    [CreatedDate]                                     DATETIME2 (7)   NOT NULL,
    [Cumulative_Points__c]                            DECIMAL (18)    NULL,
    [Cumulative_Tier__c]                              NVARCHAR (30)   NULL,
    [CurrencyIsoCode]                                 NVARCHAR (3)    NOT NULL,
    [Current_Advantage_Status__c]                     NVARCHAR (1300) NULL,
    [Education_Points__c]                             DECIMAL (18)    NULL,
    [External_Event_Points__c]                        DECIMAL (18)    NULL,
    [Id]                                              NCHAR (18)      NOT NULL,
    [Is_Bronze__c]                                    BIT             NULL,
    [IsDeleted]                                       BIT             NOT NULL,
    [LastActivityDate]                                DATETIME2 (7)   NULL,
    [LastModifiedById]                                NCHAR (18)      NULL,
    [LastModifiedDate]                                DATETIME2 (7)   NOT NULL,
    [Loyalty_Code__c]                                 NVARCHAR (1300) NULL,
    [Name]                                            NVARCHAR (80)   NULL,
    [NLP_Total_Cases_Points__c]                       DECIMAL (18, 2) NULL,
    [Pricing_Group__c]                                NCHAR (18)      NULL,
    [Pricing_Group_Treatment_Location__c]             NCHAR (18)      NULL,
    [Program_Registration__c]                         NCHAR (18)      NULL,
    [SystemModstamp]                                  DATETIME2 (7)   NOT NULL,
    [Tier_Override_Expiration_Date__c]                DATETIME2 (7)   NULL,
    [Account_Pricing_Group_Tremt_Loc_Country__c]      NVARCHAR (1300) NULL,
    [Account_Pricing_Group_Tremt_Location__c]         NVARCHAR (1300) NULL,
    [Aligners_Left__c]                                DECIMAL (18, 2) NULL,
    [Aligners_Used__c]                                DECIMAL (18)    NULL,
    [Allowable_Aligners__c]                           DECIMAL (18)    NULL,
    [Allowance__c]                                    DECIMAL (18)    NULL,
    [Apttus_Config2__IncentiveId__c]                  NCHAR (18)      NULL,
    [Apttus_Config2__LastProcessedOrderDate__c]       DATETIME2 (7)   NULL,
    [Apttus_Config2__LastProcessedOrderNumber__c]     NVARCHAR (255)  NULL,
    [Apttus_Config2__LoyaltyLevelEarned__c]           NVARCHAR (255)  NULL,
    [Apttus_Config2__LoyaltyLevelInitial__c]          NVARCHAR (255)  NULL,
    [Apttus_Config2__LoyaltyLevelOverride__c]         NVARCHAR (255)  NULL,
    [Apttus_Config2__OverrideDate__c]                 DATETIME2 (7)   NULL,
    [Apttus_Config2__OverrideReason__c]               NVARCHAR (255)  NULL,
    [Apttus_Config2__TermsAndConditionsAccepted__c]   VARCHAR (5)     NULL,
    [Carry_Over_Enrollment__c]                        VARCHAR (5)     NULL,
    [ConnectionReceivedId]                            NCHAR (18)      NULL,
    [ConnectionSentId]                                NCHAR (18)      NULL,
    [Contract_Number__c]                              NVARCHAR (255)  NULL,
    [Growth_Rate__c]                                  DECIMAL (18, 2) NULL,
    [Growth_Rate_Rounded__c]                          DECIMAL (18, 2) NULL,
    [Is_Eligible_for_NLP__c]                          VARCHAR (5)     NULL,
    [Max_Allowable_Aligners__c]                       DECIMAL (18, 2) NULL,
    [NLP_Program__c]                                  NVARCHAR (1300) NULL,
    [Other_Clin_Id_Points__c]                         DECIMAL (18)    NULL,
    [OtherEnrollment__c]                              NCHAR (18)      NULL,
    [Peak_Reword_Tier_Level__c]                       NVARCHAR (255)  NULL,
    [Points1__c]                                      DECIMAL (18, 2) NULL,
    [Pre_Enrollment_Allowed__c]                       VARCHAR (5)     NULL,
    [Previous_Cycle_Points__c]                        DECIMAL (18, 2) NULL,
    [Previous_Cycle_Tier__c]                          NVARCHAR (200)  NULL,
    [Previous_to_Previous_Cycle_Points__c]            DECIMAL (18, 2) NULL,
    [Previous_to_Previous_Cycle_Tier__c]              NVARCHAR (200)  NULL,
    [Promo_Start_Tier__c]                             NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

