CREATE TABLE [SrcSFDC].[Apttus_QPConfig__ProposalAdjustmentLineItem__c] (
    [LZBatchID]                                     INT             NOT NULL,
    [ADLSBatchID]                                   INT             NOT NULL,
    [ADLSTimestamp]                                 DATETIME2 (0)   NOT NULL,
    [Apttus_QPConfig__AdjustmentAmount__c]          DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__AdjustmentAppliesTo__c]       NVARCHAR (255)  NULL,
    [Apttus_QPConfig__AdjustmentType__c]            NVARCHAR (255)  NULL,
    [Apttus_QPConfig__BenefitQuantity__c]           DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__CouponCode__c]                NVARCHAR (6)    NULL,
    [Apttus_QPConfig__IncentiveAdjustmentAmount__c] DECIMAL (18, 5) NULL,
    [Apttus_QPConfig__IncentiveCode__c]             NVARCHAR (255)  NULL,
    [Apttus_QPConfig__IncentiveId__c]               NCHAR (18)      NULL,
    [Apttus_QPConfig__IsModifiable__c]              BIT             NULL,
    [Apttus_QPConfig__LineItemId__c]                NCHAR (18)      NULL,
    [Apttus_QPConfig__LineNumber__c]                DECIMAL (18)    NULL,
    [Apttus_QPConfig__LineType__c]                  NVARCHAR (255)  NULL,
    [Apttus_QPConfig__PriceRuleEntryId__c]          NCHAR (18)      NULL,
    [Apttus_QPConfig__PriceRuleId__c]               NCHAR (18)      NULL,
    [Apttus_QPConfig__SubType__c]                   NVARCHAR (255)  NULL,
    [Apttus_QPConfig__Type__c]                      NVARCHAR (255)  NULL,
    [ConnectionReceivedId]                          NCHAR (18)      NULL,
    [ConnectionSentId]                              NCHAR (18)      NULL,
    [CreatedById]                                   NCHAR (18)      NULL,
    [CreatedDate]                                   DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                               NVARCHAR (3)    NOT NULL,
    [Id]                                            NCHAR (18)      NOT NULL,
    [IsDeleted]                                     BIT             NOT NULL,
    [LastActivityDate]                              DATETIME2 (7)   NULL,
    [LastModifiedById]                              NCHAR (18)      NULL,
    [LastModifiedDate]                              DATETIME2 (7)   NOT NULL,
    [Name]                                          NVARCHAR (80)   NULL,
    [SystemModstamp]                                DATETIME2 (7)   NOT NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

