CREATE TABLE [SrcSFDC].[Apttus_Config2__OrderAdjustmentLineItem__c] (
    [LZBatchID]                                    INT             NOT NULL,
    [ADLSBatchID]                                  INT             NOT NULL,
    [ADLSTimestamp]                                DATETIME2 (0)   NOT NULL,
    [Adjustment_Amount_Custom__c]                  DECIMAL (18, 2) NULL,
    [Apttus_Config2__AdjustmentAmount__c]          DECIMAL (18, 5) NULL,
    [Apttus_Config2__AdjustmentAppliesTo__c]       NVARCHAR (255)  NULL,
    [Apttus_Config2__AdjustmentType__c]            NVARCHAR (255)  NULL,
    [Apttus_Config2__BenefitQuantity__c]           DECIMAL (18, 5) NULL,
    [Apttus_Config2__CouponCode__c]                NVARCHAR (6)    NULL,
    [Apttus_Config2__IncentiveAdjustmentAmount__c] DECIMAL (18, 5) NULL,
    [Apttus_Config2__IncentiveCode__c]             NVARCHAR (255)  NULL,
    [Apttus_Config2__IncentiveId__c]               NCHAR (18)      NULL,
    [Apttus_Config2__IsModifiable__c]              VARCHAR (5)     NULL,
    [Apttus_Config2__LineItemId__c]                NCHAR (18)      NULL,
    [Apttus_Config2__LineNumber__c]                DECIMAL (18)    NULL,
    [Apttus_Config2__LineType__c]                  NVARCHAR (255)  NULL,
    [Apttus_Config2__PriceRuleEntryId__c]          NCHAR (18)      NULL,
    [Apttus_Config2__PriceRuleId__c]               NCHAR (18)      NULL,
    [Apttus_Config2__SubType__c]                   NVARCHAR (255)  NULL,
    [Apttus_Config2__Type__c]                      NVARCHAR (255)  NULL,
    [ConnectionReceivedId]                         NCHAR (18)      NULL,
    [ConnectionSentId]                             NCHAR (18)      NULL,
    [CreatedById]                                  NCHAR (18)      NULL,
    [CreatedDate]                                  DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                              NVARCHAR (3)    NOT NULL,
    [Discount_Amount__c]                           DECIMAL (18, 2) NULL,
    [Discount_Percent1__c]                         DECIMAL (18, 2) NULL,
    [Discount_Percent__c]                          DECIMAL (18, 2) NULL,
    [Id]                                           NCHAR (18)      NOT NULL,
    [IsDeleted]                                    VARCHAR (5)     NOT NULL,
    [LastActivityDate]                             DATETIME2 (7)   NULL,
    [LastModifiedById]                             NCHAR (18)      NULL,
    [LastModifiedDate]                             DATETIME2 (7)   NOT NULL,
    [Name]                                         NVARCHAR (80)   NULL,
    [Revenue_Group__c]                             NVARCHAR (1300) NULL,
    [SystemModstamp]                               DATETIME2 (7)   NOT NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

