CREATE TABLE [SrcSFDC].[Apttus_Config2__Incentive__c] (
    [LZBatchID]                                        INT             NOT NULL,
    [ADLSBatchID]                                      INT             NOT NULL,
    [ADLSTimestamp]                                    DATETIME2 (0)   NOT NULL,
    [Account_Scope_Str__c]                             NVARCHAR (MAX)  NULL,
    [Approval_Status__c]                               NVARCHAR (255)  NULL,
    [Apttus_Config2__AccountScope__c]                  NVARCHAR (MAX)  NULL,
    [Apttus_Config2__AccountScopeOper__c]              NVARCHAR (255)  NULL,
    [Apttus_Config2__AccountTypeScope__c]              NVARCHAR (MAX)  NULL,
    [Apttus_Config2__AccountTypeScopeOper__c]          NVARCHAR (255)  NULL,
    [Apttus_Config2__Active__c]                        BIT             NULL,
    [Apttus_Config2__AmendmentEffectiveDate__c]        DATETIME2 (7)   NULL,
    [Apttus_Config2__AncestorId__c]                    NCHAR (18)      NULL,
    [Apttus_Config2__ApplicationMethod__c]             NVARCHAR (255)  NULL,
    [Apttus_Config2__AutoApply__c]                     BIT             NULL,
    [Apttus_Config2__ContextType__c]                   NVARCHAR (255)  NULL,
    [Apttus_Config2__CountryScope__c]                  NVARCHAR (MAX)  NULL,
    [Apttus_Config2__CountryScopeOper__c]              NVARCHAR (255)  NULL,
    [Apttus_Config2__CustomDisplaySetting__c]          NVARCHAR (255)  NULL,
    [Apttus_Config2__CycleEndDate__c]                  DATETIME2 (7)   NULL,
    [Apttus_Config2__CycleStartDate__c]                DATETIME2 (7)   NULL,
    [Apttus_Config2__Description__c]                   NVARCHAR (1000) NULL,
    [Apttus_Config2__Downgrade__c]                     NVARCHAR (255)  NULL,
    [Apttus_Config2__EffectiveDate__c]                 DATETIME2 (7)   NULL,
    [Apttus_Config2__EnableBenefitEffectivityDates__c] BIT             NULL,
    [Apttus_Config2__ExpirationDate__c]                DATETIME2 (7)   NULL,
    [Apttus_Config2__IncentiveCode__c]                 NVARCHAR (255)  NULL,
    [Apttus_Config2__IncentiveGroupId__c]              NCHAR (18)      NULL,
    [Apttus_Config2__IncentiveNumber__c]               NVARCHAR (1300) NULL,
    [Apttus_Config2__IncentiveNumberAuto__c]           NVARCHAR (30)   NULL,
    [Apttus_Config2__IncentiveNumberText__c]           NVARCHAR (10)   NULL,
    [Apttus_Config2__IsBundle__c]                      BIT             NULL,
    [Apttus_Config2__IsTaskPending__c]                 BIT             NULL,
    [Apttus_Config2__LoyaltyId__c]                     NCHAR (18)      NULL,
    [Apttus_Config2__OriginalEffectiveDate__c]         DATETIME2 (7)   NULL,
    [Apttus_Config2__PointAccrualLevel__c]             NVARCHAR (255)  NULL,
    [Apttus_Config2__PriceListScope__c]                NVARCHAR (MAX)  NULL,
    [Apttus_Config2__PriceListScopeOper__c]            NVARCHAR (255)  NULL,
    [Apttus_Config2__ProductFamilyScope__c]            NVARCHAR (MAX)  NULL,
    [Apttus_Config2__ProductFamilyScopeOper__c]        NVARCHAR (255)  NULL,
    [Apttus_Config2__ProductScope__c]                  NVARCHAR (MAX)  NULL,
    [Apttus_Config2__ProductScopeOper__c]              NVARCHAR (255)  NULL,
    [Apttus_Config2__RecurrenceFrequency__c]           NVARCHAR (255)  NULL,
    [Apttus_Config2__RegionScope__c]                   NVARCHAR (MAX)  NULL,
    [Apttus_Config2__RegionScopeOper__c]               NVARCHAR (255)  NULL,
    [Apttus_Config2__RenewalEffectiveDate__c]          DATETIME2 (7)   NULL,
    [Apttus_Config2__SearchField__c]                   NVARCHAR (255)  NULL,
    [Apttus_Config2__Sequence__c]                      DECIMAL (18)    NULL,
    [Apttus_Config2__Status__c]                        NVARCHAR (255)  NULL,
    [Apttus_Config2__StopProcessingMoreIncentives__c]  BIT             NULL,
    [Apttus_Config2__SubUseType__c]                    NVARCHAR (255)  NULL,
    [Apttus_Config2__Upgrade__c]                       NVARCHAR (255)  NULL,
    [Apttus_Config2__UseType__c]                       NVARCHAR (255)  NULL,
    [Apttus_Config2__VersionNumber__c]                 DECIMAL (18)    NULL,
    [Auto_Enroll__c]                                   BIT             NULL,
    [Bypass_Validations__c]                            BIT             NULL,
    [ConnectionReceivedId]                             NCHAR (18)      NULL,
    [ConnectionSentId]                                 NCHAR (18)      NULL,
    [CreatedById]                                      NCHAR (18)      NULL,
    [CreatedDate]                                      DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                                  NVARCHAR (3)    NOT NULL,
    [External_Event_Points_Limit__c]                   DECIMAL (18)    NULL,
    [External_ID__c]                                   NVARCHAR (18)   NULL,
    [Id]                                               NCHAR (18)      NOT NULL,
    [IDS_Expiration_Date__c]                           DATETIME2 (7)   NULL,
    [Incentive_Group_Name__c]                          NVARCHAR (1300) NULL,
    [Incentive_Name__c]                                NVARCHAR (255)  NULL,
    [Is_notes_attached__c]                             BIT             NULL,
    [IsDeleted]                                        BIT             NOT NULL,
    [LastActivityDate]                                 DATETIME2 (7)   NULL,
    [LastModifiedById]                                 NCHAR (18)      NULL,
    [LastModifiedDate]                                 DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]                               DATETIME2 (7)   NULL,
    [LastViewedDate]                                   DATETIME2 (7)   NULL,
    [Name]                                             NVARCHAR (80)   NULL,
    [Number_of_Coupons__c]                             DECIMAL (18)    NULL,
    [OwnerId]                                          NCHAR (18)      NOT NULL,
    [Pre_Enrollment_Period__c]                         DECIMAL (18)    NULL,
    [Preview_Status__c]                                NVARCHAR (255)  NULL,
    [Product_Scope_Str__c]                             NVARCHAR (MAX)  NULL,
    [Production_Effective_Date__c]                     DATETIME2 (7)   NULL,
    [Promotion_Approval_Region__c]                     NVARCHAR (1300) NULL,
    [Promotional_Point_Accrual__c]                     BIT             NULL,
    [Revenue_Group__c]                                 NVARCHAR (255)  NULL,
    [SystemModstamp]                                   DATETIME2 (7)   NOT NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

