CREATE TABLE [SrcSFDC].[Apttus_Config2__OrderLineItem__c] (
    [LZBatchID]                                    INT             NOT NULL,
    [ADLSBatchID]                                  INT             NOT NULL,
    [ADLSTimestamp]                                DATETIME2 (0)   NOT NULL,
    [Aligner_Qty__c]                               DECIMAL (18)    NULL,
    [Alternate_Qty__c]                             DECIMAL (18)    NULL,
    [Apttus_Config2__ActivatedDate__c]             DATETIME2 (7)   NULL,
    [Apttus_Config2__AdjustedPrice__c]             DECIMAL (18, 5) NULL,
    [Apttus_Config2__AdjustmentAmount__c]          DECIMAL (18, 5) NULL,
    [Apttus_Config2__CancelledDate__c]             DATETIME2 (7)   NULL,
    [Apttus_Config2__CouponCode__c]                NVARCHAR (6)    NULL,
    [Apttus_Config2__IncentiveAdjustmentAmount__c] DECIMAL (18, 5) NULL,
    [Apttus_Config2__IncentiveCode__c]             NVARCHAR (255)  NULL,
    [Apttus_Config2__IncentiveExtendedPrice__c]    DECIMAL (18, 5) NULL,
    [Apttus_Config2__IncentiveId__c]               NCHAR (18)      NULL,
    [Apttus_Config2__IncentiveType__c]             NVARCHAR (255)  NULL,
    [Apttus_Config2__IsAssetPricing__c]            BIT             NULL,
    [Apttus_Config2__IsCustomPricing__c]           BIT             NULL,
    [Apttus_Config2__IsPrimaryLine__c]             BIT             NULL,
    [Apttus_Config2__LineNumber__c]                DECIMAL (18)    NULL,
    [Apttus_Config2__LineStatus__c]                NVARCHAR (255)  NULL,
    [Apttus_Config2__LineType__c]                  NVARCHAR (255)  NULL,
    [Apttus_Config2__ListPrice__c]                 DECIMAL (18, 5) NULL,
    [Apttus_Config2__NetPrice__c]                  DECIMAL (18, 5) NULL,
    [Apttus_Config2__OrderId__c]                   NCHAR (18)      NOT NULL,
    [Apttus_Config2__PricingDate__c]               DATETIME2 (7)   NULL,
    [Apttus_Config2__PrimaryLineNumber__c]         DECIMAL (18)    NULL,
    [Apttus_Config2__Quantity__c]                  DECIMAL (18, 5) NULL,
    [Compliance_Indicator_Enabled__c]              BIT             NULL,
    [CurrencyIsoCode]                              NVARCHAR (3)    NULL,
    [Deliverable_Quantity__c]                      DECIMAL (18)    NULL,
    [Deliverable_Type__c]                          NVARCHAR (255)  NULL,
    [FOC_Aligner_Qty__c]                           DECIMAL (18)    NULL,
    [Id]                                           NCHAR (18)      NOT NULL,
    [LastModifiedDate]                             DATETIME2 (7)   NOT NULL,
    [Net_Price_Custom__c]                          DECIMAL (18, 2) NULL,
    [Number_of_Refinements_Used__c]                DECIMAL (18, 2) NULL,
    [Number_of_Replacements_Used__c]               DECIMAL (18, 2) NULL,
    [Pricing_Quantity__c]                          DECIMAL (18)    NULL,
    [Product_Code__c]                              NVARCHAR (1300) NULL,
    [Product_Code_Text__c]                         NVARCHAR (255)  NULL,
    [Study_ID__c]                                  NVARCHAR (255)  NULL,
    [SystemModstamp]                               DATETIME2 (7)   NOT NULL,
    [Total_Adjustment_Amount__c]                   DECIMAL (18, 2) NULL,
    [Total_Quantity__c]                            DECIMAL (18)    NULL,
    [Treated_Arch__c]                              NVARCHAR (255)  NULL,
    [Treatment_Category__c]                        NVARCHAR (1300) NULL,
    [Treatment_Option__c]                          NVARCHAR (255)  NULL,
    [Treatment_Quantity__c]                        DECIMAL (18)    NULL,
    [Treatment_ID__c]                              NCHAR (18)      NULL,
    [Quote_Order_Flag__c]                          NVARCHAR (255)  NULL,
    [Apttus_Config2__ChargeType__c]                NVARCHAR (255)  NULL,
    [Apttus_Config2__ProductId__c]                 NCHAR (18)      NULL,
    [Subscription_Package__c]                      NVARCHAR (255)  NULL,
    [Subscription_Program__c]                      NVARCHAR (255)  NULL,
    [Contract_Number__c]                           NVARCHAR (255)  NULL,
    [Within_RFD_Date__c]                           NVARCHAR (1300) NULL,
    [Within_TED_Date__c]                           NVARCHAR (1300) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Apttus_Config2__OrderId__c]));

