CREATE TABLE [SrcSFDC].[Apttus_Config2__OrderLoyaltyPointAccrualItem__c] (
    [LZBatchID]                           INT             NOT NULL,
    [ADLSBatchID]                         INT             NOT NULL,
    [ADLSTimestamp]                       DATETIME2 (0)   NOT NULL,
    [Apttus_Config2__AccrualDate__c]      DATETIME2 (7)   NULL,
    [Apttus_Config2__AccrualSummaryId__c] NCHAR (18)      NULL,
    [Apttus_Config2__IncentiveCode__c]    NVARCHAR (255)  NULL,
    [Apttus_Config2__IncentiveId__c]      NCHAR (18)      NULL,
    [Apttus_Config2__LineItemId__c]       NCHAR (18)      NULL,
    [Apttus_Config2__LineNumber__c]       DECIMAL (18)    NULL,
    [Apttus_Config2__LineType__c]         NVARCHAR (255)  NULL,
    [Apttus_Config2__Points__c]           DECIMAL (18)    NULL,
    [Apttus_Config2__PriceRuleEntryId__c] NCHAR (18)      NULL,
    [Apttus_Config2__PriceRuleId__c]      NCHAR (18)      NULL,
    [Apttus_Config2__Type__c]             NVARCHAR (255)  NULL,
    [ConnectionReceivedId]                NCHAR (18)      NULL,
    [ConnectionSentId]                    NCHAR (18)      NULL,
    [CreatedById]                         NCHAR (18)      NULL,
    [CreatedDate]                         DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                     NVARCHAR (3)    NOT NULL,
    [Id]                                  NCHAR (18)      NOT NULL,
    [IsDeleted]                           BIT             NOT NULL,
    [LastActivityDate]                    DATETIME2 (7)   NULL,
    [LastModifiedById]                    NCHAR (18)      NULL,
    [LastModifiedDate]                    DATETIME2 (7)   NOT NULL,
    [Name]                                NVARCHAR (80)   NULL,
    [Order_Date__c]                       DATETIME2 (7)   NULL,
    [Order_ID__c]                         NVARCHAR (1300) NULL,
    [Primary_Contact_ClinId__c]           NVARCHAR (1300) NULL,
    [Product_Code__c]                     NVARCHAR (1300) NULL,
    [SAP_Order_ID__c]                     NVARCHAR (1300) NULL,
    [SystemModstamp]                      DATETIME2 (7)   NOT NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

