CREATE TABLE [SrcSFDC].[Apttus_Config2__Order__c] (
    [LZBatchID]                                   INT                                             NOT NULL,
    [ADLSBatchID]                                 INT                                             NOT NULL,
    [ADLSTimestamp]                               DATETIME2 (0)                                   NOT NULL,
    [AMR_Product_Type__c]                         NVARCHAR (255)                                  NULL,
    [Apttus_Config2__BillToAccountId__c]          NCHAR (18)                                      NULL,
    [Apttus_Config2__CancelledDate__c]            DATETIME2 (7)                                   NULL,
    [Apttus_Config2__PrimaryContactId__c]         NCHAR (18)                                      NULL,
    [Apttus_Config2__ShipToAccountId__c]          NCHAR (18)                                      NULL,
    [Apttus_Config2__SoldToAccountId__c]          NCHAR (18)                                      NULL,
    [Apttus_Config2__Status__c]                   NVARCHAR (255)                                  NULL,
    [Area_Region__c]                              NVARCHAR (1300)                                 NULL,
    [Bill_To_Account_Number__c]                   NVARCHAR (1300)                                 NULL,
    [Cancellation_Reason_Code__c]                 NVARCHAR (255)                                  NULL,
    [Cancelled_Date1__c]                          DATETIME2 (7)                                   NULL,
    [CC_Modified_Date__c]                         DATETIME2 (7)                                   NULL,
    [CCA_Date1__c]                                DATETIME2 (7)                                   NULL,
    [CCA_Date__c]                                 DATETIME2 (7)                                   NULL,
    [Clincheck_Under_Dev__c]                      DATETIME2 (7)                                   NULL,
    [Clinical_Hold_Date__c]                       DATETIME2 (7)                                   NULL,
    [Clinicheck_Awaiting_Approval__c]             DATETIME2 (7)                                   NULL,
    [ClinId__c]                                   NVARCHAR (1300)                                 NULL,
    [Contact_Id__c]                               NVARCHAR (1300)                                 NULL,
    [CreatedDate]                                 DATETIME2 (7)                                   NOT NULL,
    [Doctor_Changed__c]                           BIT                                             NULL,
    [Expected_CC_Ready_Date__c]                   DATETIME2 (7)                                   NULL,
    [Financial_Payment_Plan_Offered_to_Patien__c] BIT                                             NULL,
    [Group_Account_Id__c]                         NVARCHAR (20)                                   NULL,
    [Id]                                          NCHAR (18)                                      NOT NULL,
    [IsDeleted]                                   BIT                                             NOT NULL,
    [LastModifiedDate]                            DATETIME2 (7)                                   NOT NULL,
    [Lower_Quantity__c]                           DECIMAL (18)                                    NULL,
    [Max_Stages__c]                               DECIMAL (18)                                    NULL,
    [Name]                                        NVARCHAR (80)                                   NULL,
    [Order_Status__c]                             NVARCHAR (1300)                                 NULL,
    [Order_Type__c]                               NVARCHAR (255)                                  NULL,
    [OwnerId]                                     NCHAR (18)                                      NOT NULL,
    [Patient_Type__c]                             NVARCHAR (1300)                                 NULL,
    [Patient_Type_Brand__c]                       NVARCHAR (255)                                  NULL,
    [Payer__c]                                    NVARCHAR (255)                                  NULL,
    [Pricing_Date__c]                             DATETIME2 (7)                                   NULL,
    [Product_Type__c]                             NVARCHAR (1300)                                 NULL,
    [Promotion_Region__c]                         NVARCHAR (1300)                                 NULL,
    [Receipt_Date1__c]                            DATETIME2 (7)                                   NULL,
    [Refinement_Fee_Date1__c]                     DATETIME2 (7)                                   NULL,
    [Rejected_Impressions_Date__c]                DATETIME2 (7)                                   NULL,
    [Restart__c]                                  BIT                                             NULL,
    [Rx_Submission_Date__c]                       DATETIME2 (7)                                   NULL,
    [Same_Quarter_Check__c]                       BIT                                             NULL,
    [SAP_Order_ID__c]                             NVARCHAR (255)                                  NULL,
    [Scan_Type__c]                                NVARCHAR (255)                                  NULL,
    [Scanner_Type__c]                             NVARCHAR (80)                                   NULL,
    [Ship_To_Account_Number__c]                   NVARCHAR (1300)                                 NULL,
    [Shipment_Scheduled__c]                       DATETIME2 (7)                                   NULL,
    [Shipped_Date1__c]                            DATETIME2 (7)                                   NULL,
    [Shipping_Tracking_No__c]                     NVARCHAR (255)                                  NULL,
    [Sold_To_Account_Number__c]                   NVARCHAR (1300)                                 NULL,
    [Stage_Date__c]                               DATETIME2 (7)                                   NULL,
    [SystemModstamp]                              DATETIME2 (7)                                   NOT NULL,
    [Treatment_Category__c]                       NVARCHAR (255)                                  NULL,
    [Treatment_Expiration_Date1__c]               DATETIME2 (7)                                   NULL,
    [Treatment_Location__c]                       NCHAR (18)                                      NULL,
    [VIP_Order_ID__c]                             NVARCHAR (255)                                  NULL,
    [Patient_Age_Year__c]                         DECIMAL (18)                                    NULL,
    [Treatment_ID_Number__c]                      NVARCHAR (1300)                                 NULL,
    [Treatment_ID__c]                             NVARCHAR (18)                                   NULL,
    [Treatment_Location_Number__c]                NVARCHAR (1300)                                 NULL,
    [Advantage_Qualification_Date1__c]            DATETIME2 (7)                                   NULL,
    [CurrencyIsoCode]                             NVARCHAR (3)                                    NOT NULL,
    [Patient_ID__c]                               NCHAR (18)                                      NULL,
    [Payment_Method__c]                           NVARCHAR (255)                                  NULL,
    [Payment_Term__c]                             NVARCHAR (255)                                  NULL,
    [Rx_Submission_Date1__c]                      DATETIME2 (7)                                   NULL,
    [Scan_Office_Account__c]                      NCHAR (18)                                      NULL,
    [Apttus_Config2__PriceListId__c]              NCHAR (18)                                      NULL,
    [Apttus_Config2__PricingDate__c]              DATETIME2 (7)                                   NULL,
    [Total_List_Price__c]                         DECIMAL (18, 2)                                 NULL,
    [Total_Net_Price__c]                          DECIMAL (18, 2)                                 NULL,
    [Apttus_Config2__RelatedOpportunityId__c]     NCHAR (18)                                      NULL,
    [Case_Submission_Territory_Manager__c]        NCHAR (18)                                      NULL,
    [Case_Submission_Territory_Name__c]           NVARCHAR (255)                                  NULL,
    [CCA_Territory_ID__c]                         NVARCHAR (255)                                  NULL,
    [CCA_Territory_Manager__c]                    NCHAR (18)                                      NULL,
    [CCA_Territory_Name__c]                       NVARCHAR (255)                                  NULL,
    [Delivery_Priority__c]                        NVARCHAR (255)                                  NULL,
    [IDS_Order_Status__c]                         NVARCHAR (255)                                  NULL,
    [MAF__c]                                      NVARCHAR (5)                                    NULL,
    [Professional_Category__c]                    NVARCHAR (255)                                  NULL,
    [Upper_Quantity__c]                           DECIMAL (18)                                    NULL,
    [Pricing_Group_Treatment_Location__c]         NVARCHAR (1300)                                 NULL,
    [Hold_Date__c]                                DATETIME2 (7)                                   NULL,
    [Hold_Reasons__c]                             NVARCHAR (255)                                  NULL,
    [Send_To_SAP_Type__c]                         NVARCHAR (255)                                  NULL,
    [AMR_Territory_ID__c]                         NVARCHAR (255)                                  NULL,
    [AMR_Territory_Manager__c]                    NCHAR (18)                                      NULL,
    [AMR_Territory_Name__c]                       NVARCHAR (255)                                  NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

