CREATE TABLE [SrcSFDC].[Asset] (
    [LZBatchID]                   INT             NOT NULL,
    [ADLSBatchID]                 INT             NOT NULL,
    [ADLSTimestamp]               DATETIME2 (0)   NOT NULL,
    [AccountId]                   NCHAR (18)      NULL,
    [Asset_Type__c]               NVARCHAR (255)  NULL,
    [ContactId]                   NCHAR (18)      NULL,
    [CreatedById]                 NCHAR (18)      NULL,
    [CreatedDate]                 DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]             NVARCHAR (3)    NOT NULL,
    [Description]                 NVARCHAR (4000) NULL,
    [Id]                          NCHAR (18)      NOT NULL,
    [InstallDate]                 DATETIME2 (7)   NULL,
    [Installed_At__c]             NCHAR (18)      NULL,
    [IsCompetitorProduct]         BIT             NOT NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [LastModifiedById]            NCHAR (18)      NULL,
    [LastModifiedDate]            DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]          DATETIME2 (7)   NULL,
    [LastViewedDate]              DATETIME2 (7)   NULL,
    [Name]                        NVARCHAR (255)  NOT NULL,
    [ParentId]                    NCHAR (18)      NULL,
    [Price]                       DECIMAL (18)    NULL,
    [Product2Id]                  NCHAR (18)      NULL,
    [PurchaseDate]                DATETIME2 (7)   NULL,
    [Quantity]                    DECIMAL (18, 2) NULL,
    [RootAssetId]                 NCHAR (18)      NULL,
    [SerialNumber]                NVARCHAR (80)   NULL,
    [Status]                      NVARCHAR (40)   NULL,
    [StockKeepingUnit]            NVARCHAR (180)  NULL,
    [SystemModstamp]              DATETIME2 (7)   NOT NULL,
    [Term_months__c]              NVARCHAR (255)  NULL,
    [UsageEndDate]                DATETIME2 (7)   NULL,
    [Ship_To_Account__c]          NVARCHAR (255)  NULL,
    [Ticket_Number__c]            NVARCHAR (60)   NULL,
    [SAP_Sales_Order_Text__c]     NVARCHAR (255)  NULL,
    [PGI_Date__c]                 DATETIME2 (7)   NULL,
    [Shipment_Tracking_Number__c] NVARCHAR (255)  NULL,
    [Asset_Kind__c]               NVARCHAR (255)  NULL,
    [Scanner_Software_Type__c]    NVARCHAR (255)  NULL,
    [Software_End_Date__c]        DATETIME2 (7)   NULL,
    [Payer_Account__c]            NVARCHAR (255)  NULL,
    [Bill_To_Account__c]          NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

