CREATE TABLE [SrcSFDC].[CampaignMember]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[AGD_Pace_number__c] [decimal](18, 0) NULL,
	[AMR_Event_date_days__c] [decimal](18, 0) NULL,
	[Assistant1_Status__c] [nvarchar](255) NULL,
	[Assistant1_Type__c] [nvarchar](80) NULL,
	[Assistant2_Status__c] [nvarchar](255) NULL,
	[Assistant2_Type__c] [nvarchar](80) NULL,
	[Assistant3_Status__c] [nvarchar](255) NULL,
	[Assistant3_Type__c] [nvarchar](80) NULL,
	[Assistant4_Status__c] [nvarchar](255) NULL,
	[Assistant4_Type__c] [nvarchar](80) NULL,
	[Assistant5_Status__c] [nvarchar](255) NULL,
	[Assistant5_Type__c] [nvarchar](80) NULL,
	[CampaignId] [nvarchar](18) NOT NULL,
	[CCA_Event_date_days__c] [decimal](18, 0) NULL,
	[CE_Hours__c] [decimal](18, 2) NULL,
	[City] [nvarchar](40) NULL,
	[Comments__c] [nvarchar](255) NULL,
	[CompanyOrAccount] [nvarchar](255) NULL,
	[ContactId] [nvarchar](18) NULL,
	[Country] [nvarchar](80) NULL,
	[Course_Completion_Date__c] [datetime2](7) NULL,
	[Createdby_Role__c] [nvarchar](1300) NULL,
	[Createdby_User__c] [nvarchar](1300) NULL,
	[CreatedById] [nvarchar](18) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CurrencyIsoCode] [nvarchar](3) NULL,
	[DID__c] [nvarchar](50) NULL,
	[DID_Number__c] [nvarchar](50) NULL,
	[Dietary_Restictions__c] [nvarchar](255) NULL,
	[DoNotCall] [nvarchar](5) NULL,
	[Email] [nvarchar](80) NULL,
	[Event_Date_Reference__c] [datetime2](7) NULL,
	[External_Campaign_Member_Id__c] [nvarchar](100) NULL,
	[Fax] [nvarchar](40) NULL,
	[Feedback__c] [nvarchar](255) NULL,
	[FirstName] [nvarchar](40) NULL,
	[FirstRespondedDate] [datetime2](7) NULL,
	[General_Customer_Support__c] [nvarchar](5) NULL,
	[HasOptedOutOfEmail] [nvarchar](5) NULL,
	[HasOptedOutOfFax] [nvarchar](5) NULL,
	[HasResponded] [nvarchar](5) NULL,
	[Hotel_Needed__c] [nvarchar](5) NULL,
	[Id] [nvarchar](18) NOT NULL,
	[In_Person_Education__c] [nvarchar](255) NULL,
	[Is_Attended__c] [nvarchar](5) NULL,
	[IsDeleted] [nvarchar](5) NULL,
	[Last_status_update_date__c] [datetime2](7) NULL,
	[LastModifiedById] [nvarchar](18) NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[LastName] [nvarchar](80) NULL,
	[LeadId] [nvarchar](18) NULL,
	[LeadOrContactId] [nvarchar](18) NULL,
	[LeadOrContactOwnerId] [nvarchar](18) NULL,
	[LeadSource] [nvarchar](80) NULL,
	[Legacy_Sf_Id__c] [nvarchar](18) NULL,
	[LID_Number__c] [nvarchar](18) NULL,
	[MobilePhone] [nvarchar](40) NULL,
	[Name] [nvarchar](255) NULL,
	[No_of_Assistants__c] [decimal](18, 0) NULL,
	[Online_Education__c] [nvarchar](255) NULL,
	[Order_Number__c] [nvarchar](40) NULL,
	[Original_Type__c] [nvarchar](50) NULL,
	[Part_Number_assistant__c] [nvarchar](1300) NULL,
	[Part_Number_Event__c] [nvarchar](20) NULL,
	[Phone] [nvarchar](40) NULL,
	[PostalCode] [nvarchar](20) NULL,
	[Product__c] [nvarchar](255) NULL,
	[Recent_Invisalign_Innovations__c] [nvarchar](5) NULL,
	[RecordTypeId] [nvarchar](18) NULL,
	[Salutation] [nvarchar](40) NULL,
	[Skip_notifications_on_create__c] [nvarchar](5) NULL,
	[Source__c] [nvarchar](255) NULL,
	[Staff_Registration_Only__c] [nvarchar](5) NULL,
	[State] [nvarchar](80) NULL,
	[Status] [nvarchar](40) NULL,
	[Status_Image__c] [nvarchar](1300) NULL,
	[Status_Reason__c] [nvarchar](255) NULL,
	[Street] [nvarchar](255) NULL,
	[System_Status__c] [nvarchar](255) NULL,
	[SystemModstamp] [datetime2](7) NULL,
	[Title] [nvarchar](128) NULL,
	[Training_Event_Type__c] [nvarchar](255) NULL,
	[Type] [nvarchar](40) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED INDEX
	(
		[Id] ASC
	)
)