CREATE TABLE [SrcSFDC].[Campaign]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Actual_Costs_of_Event__c] [decimal](18, 5) NULL,
	[ActualCost] [decimal](18, 5) NULL,
	[Additional_comment__c] [nvarchar](max) NULL,
	[Address__c] [nvarchar](max) NULL,
	[AmountAllOpportunities] [decimal](18, 5) NULL,
	[AmountWonOpportunities] [decimal](18, 5) NULL,
	[Assistant_Registrations__c] [decimal](18, 5) NULL,
	[Assistants_Evaluation_Link__c] [nvarchar](max) NULL,
	[Available_for_Region_Countries__c] [nvarchar](max) NULL,
	[Average_Seat_Price_ASP__c] [decimal](18, 5) NULL,
	[Booth_Build_Costs__c] [decimal](18, 5) NULL,
	[Booth_Build_PO__c] [nvarchar](256) NULL,
	[Budget_Actual__c] [decimal](18, 5) NULL,
	[Budget_Allocated__c] [decimal](18, 5) NULL,
	[Budget_Spend__c] [decimal](18, 5) NULL,
	[Budget_Utilization__c] [decimal](18, 5) NULL,
	[BudgetedCost] [decimal](18, 5) NULL,
	[Campaign_Type_iTero__c] [nvarchar](256) NULL,
	[CampaignImageId] [nvarchar](max) NULL,
	[CampaignMemberRecordTypeId] [nvarchar](max) NULL,
	[Capacity_Final__c] [decimal](18, 5) NULL,
	[Category__c] [nvarchar](max) NULL,
	[City__c] [nvarchar](256) NULL,
	[ClinEd_projects_Costs__c] [decimal](18, 5) NULL,
	[ClinEd_Projects_PO__c] [nvarchar](256) NULL,
	[Clinical_Advisor_Lead__c] [nvarchar](max) NULL,
	[Close_date_for_registrations__c] [datetime2](7) NULL,
	[Closed_date__c] [datetime2](7) NULL,
	[Comment_about_Event__c] [nvarchar](256) NULL,
	[Commission_State__c] [decimal](18, 5) NULL,
	[CONF_D_STAND__c] [nvarchar](256) NULL,
	[Confirmed_registrations__c] [decimal](18, 5) NULL,
	[Congress_Expected_Attendance__c] [decimal](18, 5) NULL,
	[Congress_Sponsorship_Costs__c] [decimal](18, 5) NULL,
	[Congress_Sponsorship_PO__c] [nvarchar](256) NULL,
	[Contact_Person__c] [nvarchar](256) NULL,
	[Costs_of_Event_Target__c] [decimal](18, 5) NULL,
	[Country__c] [nvarchar](256) NULL,
	[Coupon_code__c] [nvarchar](256) NULL,
	[Course_Modality__c] [nvarchar](256) NULL,
	[CreatedById] [nvarchar](max) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CurrencyIsoCode] [nvarchar](256) NULL,
	[Customer_Availability__c] [nvarchar](256) NULL,
	[Day_2__c] [nvarchar](max) NULL,
	[Day_3__c] [nvarchar](max) NULL,
	[Delivery_Address__c] [nvarchar](max) NULL,
	[Delivery_Address_CTCPers_Instructions__c] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
	[Doctor_Capacity__c] [decimal](18, 5) NULL,
	[Doctor_Type__c] [nvarchar](256) NULL,
	[Education_Program_description__c] [nvarchar](256) NULL,
	[Educational_Program_type__c] [nvarchar](256) NULL,
	[End_time__c] [nvarchar](256) NULL,
	[EndDate] [datetime2](7) NULL,
	[Estimated_allocated_budget_to_Event__c] [decimal](18, 5) NULL,
	[Estimated_Costs_of_Event__c] [decimal](18, 5) NULL,
	[eTrigue_id__c] [nvarchar](256) NULL,
	[Evaluation_Link__c] [nvarchar](256) NULL,
	[Event_Base_Price_CAD__c] [decimal](18, 5) NULL,
	[Event_Base_Price_USD__c] [decimal](18, 5) NULL,
	[Event_City__c] [nvarchar](256) NULL,
	[Event_Country__c] [nvarchar](256) NULL,
	[Event_Date__c] [datetime2](7) NULL,
	[Event_Fee__c] [decimal](18, 5) NULL,
	[Event_Sub_Type__c] [nvarchar](256) NULL,
	[Event_Type__c] [nvarchar](256) NULL,
	[Event_Type_Description__c] [nvarchar](max) NULL,
	[Event_type_name_standarized_Invoice__c] [nvarchar](256) NULL,
	[Event_Type_picklist__c] [nvarchar](256) NULL,
	[Event_Type_Process_Description__c] [nvarchar](max) NULL,
	[Expected_Quantity__c] [decimal](18, 5) NULL,
	[ExpectedResponse] [decimal](18, 5) NULL,
	[ExpectedRevenue] [decimal](18, 5) NULL,
	[External_Campaign_Id__c] [nvarchar](256) NULL,
	[Final_Attendance__c] [decimal](18, 5) NULL,
	[HierarchyActualCost] [decimal](18, 5) NULL,
	[HierarchyAmountAllOpportunities] [decimal](18, 5) NULL,
	[HierarchyAmountWonOpportunities] [decimal](18, 5) NULL,
	[HierarchyBudgetedCost] [decimal](18, 5) NULL,
	[HierarchyExpectedRevenue] [decimal](18, 5) NULL,
	[HierarchyNumberOfContacts] [int] NULL,
	[HierarchyNumberOfConvertedLeads] [int] NULL,
	[HierarchyNumberOfLeads] [int] NULL,
	[HierarchyNumberOfOpportunities] [int] NULL,
	[HierarchyNumberOfResponses] [int] NULL,
	[HierarchyNumberOfWonOpportunities] [int] NULL,
	[HierarchyNumberSent] [decimal](18, 5) NULL,
	[Hotel_Needed__c] [nvarchar](256) NULL,
	[Id] [nvarchar](50) NOT NULL,
	[IsActive] [nvarchar](max) NULL,
	[IsDeleted] [nvarchar](max) NULL,
	[iTero_Shipment_Costs__c] [decimal](18, 5) NULL,
	[iTero_Shipment_PO__c] [nvarchar](256) NULL,
	[JDE_Location_Id__c] [nvarchar](256) NULL,
	[Landing_Page_Needed__c] [nvarchar](256) NULL,
	[Language__c] [nvarchar](max) NULL,
	[LastActivityDate] [datetime2](7) NULL,
	[LastModifiedById] [nvarchar](max) NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[LastReferencedDate] [datetime2](7) NULL,
	[LastViewedDate] [datetime2](7) NULL,
	[Legacy_Sf_Id__c] [nvarchar](256) NULL,
	[Location__Latitude__s] [decimal](18, 5) NULL,
	[Location__Longitude__s] [decimal](18, 5) NULL,
	[Location_Desc__c] [nvarchar](max) NULL,
	[Location_Manager_Dost__c] [nvarchar](256) NULL,
	[Month__c] [nvarchar](256) NULL,
	[NA_EMT_Unique_Value__c] [nvarchar](256) NULL,
	[Name] [nvarchar](256) NULL,
	[NumberOfContacts] [int] NULL,
	[NumberOfConvertedLeads] [int] NULL,
	[NumberOfLeads] [int] NULL,
	[NumberOfOpportunities] [int] NULL,
	[NumberOfResponses] [int] NULL,
	[NumberOfWonOpportunities] [int] NULL,
	[NumberSent] [decimal](18, 5) NULL,
	[of_Campaign_Member__c] [decimal](18, 5) NULL,
	[Other_Category__c] [nvarchar](256) NULL,
	[OwnerId] [nvarchar](max) NULL,
	[Parent_NC_Campaign__c] [nvarchar](max) NULL,
	[ParentId] [nvarchar](max) NULL,
	[Participant_Registration_Source__c] [nvarchar](256) NULL,
	[Partner_Name__c] [nvarchar](256) NULL,
	[Payment_Required__c] [nvarchar](256) NULL,
	[Program_Name__c] [nvarchar](256) NULL,
	[Public__c] [varchar](5) NULL,
	[QTR__c] [nvarchar](256) NULL,
	[Reach__c] [nvarchar](256) NULL,
	[RecordTypeId] [nchar](18) NULL,
	[Registration_Link__c] [nvarchar](256) NULL,
	[Registration_Open_Date__c] [datetime2](7) NULL,
	[Registration_Page_Needed__c] [nvarchar](256) NULL,
	[Relations_Costs__c] [decimal](18, 5) NULL,
	[Relations_PO__c] [nvarchar](256) NULL,
	[remaining_seats__c] [decimal](18, 5) NULL,
	[Revenue__c] [decimal](18, 5) NULL,
	[Sales_Region__c] [nvarchar](256) NULL,
	[Sales_Variance__c] [decimal](18, 5) NULL,
	[Seat_Capacity__c] [decimal](18, 5) NULL,
	[Seat_Capacity_Assistants__c] [decimal](18, 5) NULL,
	[Seat_Capacity_Planned__c] [decimal](18, 5) NULL,
	[Send_Notifications_as_TM__c] [varchar](5) NULL,
	[Shipment_Tracking_Link__c] [nvarchar](256) NULL,
	[Shipment_Tracking_Number__c] [nvarchar](256) NULL,
	[Speaker1__c] [nchar](18) NULL,
	[Speaker__c] [nvarchar](256) NULL,
	[Speaker_fee__c] [decimal](18, 5) NULL,
	[Speaker_PO__c] [nvarchar](256) NULL,
	[Speaker_Travel__c] [decimal](18, 5) NULL,
	[Special_Delivery_Instructions__c] [nvarchar](256) NULL,
	[Stand_Size__c] [decimal](18, 5) NULL,
	[Start_time__c] [nvarchar](256) NULL,
	[StartDate] [datetime2](7) NULL,
	[State__c] [nvarchar](256) NULL,
	[Status] [nvarchar](256) NULL,
	[Study_Club__c] [nchar](18) NULL,
	[Study_Club_Type__c] [nvarchar](256) NULL,
	[Submit_Final_List__c] [varchar](5) NULL,
	[SystemModstamp] [datetime2](7) NULL,
	[Target__c] [nvarchar](256) NULL,
	[Target_Audience__c] [nvarchar](256) NULL,
	[Team_Capacity__c] [decimal](18, 5) NULL,
	[Team_Member_Price_CAD__c] [decimal](18, 5) NULL,
	[Team_Member_Price_USD__c] [decimal](18, 5) NULL,
	[Time_Zone__c] [nvarchar](256) NULL,
	[TM_Contact_1__c] [nchar](18) NULL,
	[TM_Contact_2__c] [nchar](18) NULL,
	[Total_Conformed_registrations__c] [decimal](18, 5) NULL,
	[Total_Spend__c] [decimal](18, 5) NULL,
	[Type] [nvarchar](256) NULL,
	[Venue__c] [nvarchar](max) NULL,
	[Venue_ID__c] [nvarchar](256) NULL,
	[Virtual_Event_Link__c] [nvarchar](256) NULL,
	[Year__c] [nvarchar](256) NULL,
	[Zip_Code__c] [nvarchar](256) NULL,
	[Event_Topic_Category__c] [nvarchar](max) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED INDEX
	(
		[Id] ASC
	)
)


