CREATE TABLE [SrcSFDC].[Case]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Action__c] [nvarchar](510) NULL,
	[Caller_Role__c] [nvarchar](510) NULL,
	[Caller_s_Name__c] [nvarchar](510) NULL,
	[Cancellation_Status__c] [nvarchar](510) NULL,
	[Cancelled_Date__c] [datetime2](7) NULL,
	[Carrier__c] [nvarchar](510) NULL,
	[CaseNumber] [nvarchar](60) NULL,
	[Category__c] [nvarchar](510) NULL,
	[ClosedDate] [datetime2](7) NULL,
	[Closure_Rational__c] [nvarchar](4000) NULL,
	[Complaint_Requestor__c] [nvarchar](510) NULL,
	[Complaint_Sub_Type__c] [nvarchar](510) NULL,
	[Contact_Language__c] [nvarchar](2600) NULL,
	[Contact_Timezone__c] [nvarchar](2600) NULL,
	[ContactEmail] [nvarchar](160) NULL,
	[ContactId] [nchar](36) NULL,
	[Id] [nchar](18) NOT NULL,
	[LastModifiedDate] [datetime2](7) NOT NULL,
	[Lead__c] [nchar](36) NULL,
	[Location__c] [nchar](36) NULL,
	[Lot_Name__c] [nvarchar](160) NULL,
	[MAT_Ticket_ID__c] [nvarchar](500) NULL,
	[OwnerId] [nchar](36) NOT NULL,
	[P_O_Number__c] [decimal](18, 0) NULL,
	[ParentId] [nchar](36) NULL,
	[RecordTypeId] [nchar](36) NULL,
	[Reopened__c] [bit] NULL,
	[RMA__c] [nvarchar](510) NULL,
	[RMA_for_Customer__c] [bit] NULL,
	[Root_Cause__c] [nvarchar](1200) NULL,
	[Scanner_Model__c] [nvarchar](510) NULL,
	[Scanner_Quantity__c] [decimal](18, 0) NULL,
	[Scheduled_Delivery_Delivered_Date__c] [datetime2](7) NULL,
	[Serial_Number__c] [nvarchar](500) NULL,
	[Service_Reason__c] [nvarchar](2600) NULL,
	[Service_Type__c] [nvarchar](2600) NULL,
	[Stage__c] [nvarchar](510) NULL,
	[Status] [nvarchar](80) NULL,
	[Subject] [nvarchar](510) NULL,
	[Symptom_Code__c] [nvarchar](510) NULL,
	[System_Issue__c] [nvarchar](510) NULL,
	[SystemModstamp] [datetime2](7) NOT NULL,
	[Ticket_Type__c] [nvarchar](510) NULL,
	[Total_Process_Time_Days__c] [decimal](18, 2) NULL,
	[Total_Purchase_Price__c] [decimal](18, 0) NULL,
	[Audit_completed_date__c] [datetime] NULL,
	[Manufacturing_Date__c] [datetime] NULL,
	[Contract_Signature_date__c] [datetime] NULL,
	[Date_First_Contact_Email__c] [datetime] NULL,
	[Date_Fourth_Contact__c] [datetime] NULL,
	[Date_MiM__c] [datetime] NULL,
	[Date_Notification_Sent_to_Trainer__c] [datetime] NULL,
	[Date_Third_Contact__c] [datetime] NULL,
	[Invoice_Date__c] [datetime] NULL,
	[Final_Received_Date__c] [datetime] NULL,
	[iTero_Scanner_Rev_Req_Date__c] [datetime] NULL,
	[Order_Status__c] [nvarchar](255) NULL,
	[Processing_completed_date__c] [datetime] NULL,
	[Shipped_Date__c] [datetime] NULL,
	[Request_Format__c] [nvarchar](255) NULL,
	[VCT_Training_Date__c] [datetime] NULL,
	[Audit_Time_Elapsed__c] [decimal](18, 2) NULL,
	[ProcessingTimeElapsed_V1__c] [decimal](18, 2) NULL,
	[Shipment_Time_Elapsed_V1__c] [decimal](18, 2) NULL,
	[Priority] [nvarchar](40) NULL,
	[Audit_Staus__c] [nvarchar](510) NULL,
	[Did_scanner_ship__c] [nvarchar](255) NULL,
	[Date_Issue_was_Found__c] [datetime2](7) NULL,
	[Duplicate__c] [bit] NULL,
	[Final_Status__c] [nvarchar](255) NULL,
	[CAPA__c] [nvarchar](40) NULL,
	[Country_Shipto__c] [nvarchar](18) NULL,
	[CreatedById] [nchar](18) NULL,
	[IsClosed] [bit] NOT NULL,
	[IsClosedOnCreate] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsEscalated] [bit] NOT NULL,
	[Is_RMA_needed__c] [nvarchar](255) NULL,
	[Issue_Type__c] [nvarchar](255) NULL,
	[Location_Status__c] [nvarchar](255) NULL,
	[New_iTero_customer__c] [nvarchar](255) NULL,
	[Origin] [nvarchar](50) NULL,
	[Processing_Stage_Status__c] [nvarchar](255) NULL,
	[Return_Type__c] [nvarchar](255) NULL,
	[Scanner_Rev_Req__c] [decimal](18, 2) NULL,
	[Shipping_Stage_Status__c] [nvarchar](255) NULL,
	[Sub_Issue_Type__c] [nvarchar](255) NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[Track_status__c] [nvarchar](1300) NULL,
	[Opportunity__c] [nchar](18) NULL,
	[AssetId] [nchar](18) NULL,
	[AccountID] [nchar](18) NULL,
	[Team_Function__c] [nvarchar](4000) NULL,
	[BusinessHoursId] [nchar](18) NULL,
	[Incoming_Tracking_Number__c] [nvarchar](255) NULL,
	[Incoming_Tracking_Status__c] [nvarchar](255) NULL,
	[Outgoing_Tracking_Number__c] [nvarchar](255) NULL,
	[Tracking_Number__c] [nvarchar](255) NULL,
	[UPS_Tracking_Number__c] [nvarchar](255) NULL,
	[UPS_Tracking_Status__c] [nvarchar](255) NULL,
	[Description] [nvarchar](max) NULL,
	[Next_Onboarding_Contact_Date__c] [datetime2](7) NULL,
	[Investigation_Details__c] [nvarchar](max) NULL,
	[First_Interaction_Resolution__c] [nvarchar](255) NULL,
	[Complaint_Type__c] [nvarchar](255) NULL,
	[Product_Safety__c] [nvarchar](255) NULL,
	[Is_Valid_Complaint__c] [nvarchar](255) NULL,
	[Manufacturing_Site__c] [nvarchar](255) NULL,
	[Effective_Shipment_date__c] [datetime2](7) NULL,
	[Product_Type__c] [nvarchar](255) NULL,
	[Quote_Proposal_ID__c] [nchar](18) NULL,
	[Region__c] [nvarchar](255) NULL,
	[Shipment__c] [nvarchar](255) NULL,
	[TX_Service_Center_Aligner__c] [nvarchar](1300) NULL,
	[Contract_Type__c] [nvarchar](255) NULL,
	[DistributorDSO_Name__c] [nvarchar](255) NULL,
	[Cancellation_received__c] [nvarchar](255) NULL,
	[iTero_Issue_Type__c] [nvarchar](255) NULL,
	[SO_number__c] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED INDEX
	(
		[Id] ASC
	)
)