CREATE TABLE [SrcSFDC].[Contact] (
    [LZBatchID]                            INT             NOT NULL,
    [ADLSBatchID]                          INT             NOT NULL,
    [ADLSTimestamp]                        DATETIME2 (0)   NOT NULL,
    [Account_Number__c]                    NVARCHAR (1300) NULL,
    [AccountId]                            NCHAR (18)      NULL,
    [Active__c]                            BIT             NULL,
    [Alumni_of_University__c]              NVARCHAR (255)  NULL,
    [Alumni_state__c]                      NVARCHAR (255)  NULL,
    [CE_Hours__c]                          NVARCHAR (5)    NULL,
    [Certification_Date__c]                DATETIME2 (7)   NULL,
    [Certification_Location__c]            NVARCHAR (80)   NULL,
    [Clinician_ID__c]                      NVARCHAR (50)   NULL,
    [Contact_ID__c]                        NVARCHAR (30)   NULL,
    [Contact_Role__c]                      NVARCHAR (255)  NULL,
    [Contact_Status__c]                    NVARCHAR (255)  NULL,
    [Contact_Type__c]                      NVARCHAR (255)  NULL,
    [CreatedById]                          NCHAR (18)      NULL,
    [CreatedDate]                          DATETIME2 (7)   NOT NULL,
    [Credit_Hold__c]                       NVARCHAR (1300) NULL,
    [CurrencyIsoCode]                      NVARCHAR (3)    NOT NULL,
    [Customer_Type_Name__c]                NVARCHAR (1300) NULL,
    [Email]                                NVARCHAR (80)   NULL,
    [Fax]                                  NVARCHAR (40)   NULL,
    [FirstName]                            NVARCHAR (40)   NULL,
    [Gender__c]                            NVARCHAR (255)  NULL,
    [Graduation_Year__c]                   NVARCHAR (255)  NULL,
    [HasOptedOutOfEmail]                   BIT             NOT NULL,
    [HasOptedOutOfFax]                     BIT             NOT NULL,
    [HDS_Medical_School_Country__c]        NVARCHAR (50)   NULL,
    [HDS_NPI_Number__c]                    NVARCHAR (10)   NULL,
    [HDS_Year_of_Birth__c]                 NVARCHAR (4)    NULL,
    [HDS_Year_Started_Practicing__c]       NVARCHAR (4)    NULL,
    [Id]                                   NCHAR (18)      NOT NULL,
    [LastModifiedById]                     NCHAR (18)      NULL,
    [LastModifiedDate]                     DATETIME2 (7)   NOT NULL,
    [LastName]                             NVARCHAR (80)   NOT NULL,
    [LeadSource]                           NVARCHAR (256)  NULL,
    [Lending_Point_Enrollment_Date__c]     DATETIME2 (7)   NULL,
    [Line_of_Business__c]                  NVARCHAR (1300) NULL,
    [Mail_Opt_Out__c]                      BIT             NULL,
    [Mailing_County__c]                    NVARCHAR (255)  NULL,
    [Mailing_Street_1__c]                  NVARCHAR (35)   NULL,
    [Mailing_Street_2__c]                  NVARCHAR (35)   NULL,
    [Mailing_Street_3__c]                  NVARCHAR (35)   NULL,
    [Mailing_Street_4__c]                  NVARCHAR (35)   NULL,
    [MailingCity]                          NVARCHAR (40)   NULL,
    [MailingCountry]                       NVARCHAR (80)   NULL,
    [MailingCountryCode]                   NVARCHAR (10)   NULL,
    [MobilePhone]                          NVARCHAR (40)   NULL,
    [Name]                                 NVARCHAR (121)  NOT NULL,
    [OtherPhone]                           NVARCHAR (40)   NULL,
    [OwnerId]                              NCHAR (18)      NOT NULL,
    [Phone]                                NVARCHAR (40)   NULL,
    [Private_Practice_ClinId__c]           NVARCHAR (25)   NULL,
    [Product_Eligibility__c]               NVARCHAR (1024) NULL,
    [Professional_Category__c]             NVARCHAR (255)  NULL,
    [RecordTypeId]                         NCHAR (18)      NULL,
    [Salutation]                           NVARCHAR (40)   NULL,
    [Status_Reason__c]                     NVARCHAR (255)  NULL,
    [SystemModstamp]                       DATETIME2 (7)   NOT NULL,
    [Teen_Provider__c]                     BIT             NULL,
    [Teen_Training__c]                     DATETIME2 (7)   NULL,
    [Time_Zone__c]                         NVARCHAR (80)   NULL,
    [TPS_Terms_and_Condition_flag__c]      BIT             NULL,
    [Translated_Alumni_of_University__c]   NVARCHAR (50)   NULL,
    [Translated_Certification_Location__c] NVARCHAR (80)   NULL,
    [Translated_Contact_Role__c]           NVARCHAR (50)   NULL,
    [Translated_First_Name__c]             NVARCHAR (40)   NULL,
    [Translated_Last_Name__c]              NVARCHAR (40)   NULL,
    [Translated_Mailing_City__c]           NVARCHAR (40)   NULL,
    [Translated_Mailing_Country__c]        NVARCHAR (50)   NULL,
    [Translated_Mailing_County__c]         NVARCHAR (25)   NULL,
    [Translated_Mailing_Postal_Code__c]    NVARCHAR (20)   NULL,
    [Translated_Mailing_State__c]          NVARCHAR (50)   NULL,
    [Translated_Mailing_Street_1__c]       NVARCHAR (35)   NULL,
    [Translated_Mailing_Street_2__c]       NVARCHAR (35)   NULL,
    [Translated_Mailing_Street_3__c]       NVARCHAR (35)   NULL,
    [Translated_Mailing_Street_4__c]       NVARCHAR (35)   NULL,
    [Translated_Name__c]                   NVARCHAR (35)   NULL,
    [Translated_Salutation__c]             NVARCHAR (50)   NULL,
    [DoNotCall]                            BIT             NULL,
    [MailingState]                         NVARCHAR (80)   NULL,
    [MailingPostalCode]                    NVARCHAR (20)   NULL,
    [Reactivation_Date__c]                 DATETIME2 (7)   NULL,
    [EPT_T_C__c]                           BIT             NULL,
    [Fusion_Contract_Date__c]              DATETIME2 (7)   NULL,
    [MAT_Contact_ID__c]                    NVARCHAR (50)   NULL,
    [CF_Training_Completion_Date__c]       DATETIME2 (7)   NULL,
    [EMEA_Segmentation__c]                 NVARCHAR (50)   NULL,
    [Doctor_Segment__c]                    NVARCHAR (50)   NULL,
    [Doctor_License_Number__c]             NVARCHAR (255)  NULL,
    [Doctor_Accepted_Programs__c]          VARCHAR (4000)  NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

