CREATE TABLE [SrcSFDC].[et4ae5__IndividualEmailResult__c] (
    [LZBatchID]                       INT            NOT NULL,
    [ADLSBatchID]                     INT            NOT NULL,
    [ADLSTimestamp]                   DATETIME2 (0)  NOT NULL,
    [Clinician_ID__c]                 NCHAR (18)     NULL,
    [ConnectionReceivedId]            NCHAR (18)     NULL,
    [ConnectionSentId]                NCHAR (18)     NULL,
    [Country__c]                      NVARCHAR (50)  NULL,
    [CreatedById]                     NCHAR (18)     NULL,
    [CreatedDate]                     DATETIME2 (7)  NULL,
    [CurrencyIsoCode]                 NVARCHAR (5)   NULL,
    [Doctor_Name__c]                  NVARCHAR (100) NULL,
    [et4ae5__Contact__c]              NVARCHAR (50)  NULL,
    [et4ae5__Contact_ID__c]           NCHAR (18)     NULL,
    [et4ae5__DateBounced__c]          DATETIME2 (7)  NULL,
    [et4ae5__DateOpened__c]           DATETIME2 (7)  NULL,
    [et4ae5__DateSent__c]             DATETIME2 (7)  NULL,
    [et4ae5__DateUnsubscribed__c]     DATETIME2 (7)  NULL,
    [et4ae5__Email__c]                NVARCHAR (100) NULL,
    [et4ae5__Email_Asset_ID__c]       NCHAR (18)     NULL,
    [et4ae5__Email_ID__c]             NCHAR (18)     NULL,
    [et4ae5__FromAddress__c]          NVARCHAR (50)  NULL,
    [et4ae5__FromName__c]             NVARCHAR (50)  NULL,
    [et4ae5__HardBounce__c]           NVARCHAR (10)  NULL,
    [et4ae5__Lead__c]                 NCHAR (18)     NULL,
    [et4ae5__NumberOfTotalClicks__c]  INT            NULL,
    [et4ae5__NumberOfUniqueClicks__c] INT            NULL,
    [et4ae5__Opened__c]               NVARCHAR (10)  NULL,
    [et4ae5__SendDefinition__c]       NVARCHAR (50)  NULL,
    [Id]                              NCHAR (18)     NULL,
    [IsDeleted]                       NVARCHAR (10)  NULL,
    [LastModifiedById]                NVARCHAR (50)  NULL,
    [LastModifiedDate]                DATETIME2 (7)  NULL,
    [Name]                            NVARCHAR (100) NULL,
    [Owner__c]                        NVARCHAR (50)  NULL,
    [OwnerId]                         NCHAR (18)     NULL,
    [Professional_Category__c]        NVARCHAR (50)  NULL,
    [Region__c]                       NVARCHAR (50)  NULL,
    [Sales_Region__c]                 NVARCHAR (50)  NULL,
    [SystemModstamp]                  DATETIME2 (7)  NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

