CREATE TABLE [SrcSFDC].[Event] (
    [LZBatchID]            INT             NOT NULL,
    [ADLSBatchID]          INT             NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)   NOT NULL,
    [AccountId]            NCHAR (36)      NULL,
    [Achieved__c]          BIT             NULL,
    [Activity_Comments__c] NVARCHAR (510)  NULL,
    [ActivityDate]         DATETIME2 (7)   NULL,
    [ActivityDateTime]     DATETIME2 (7)   NULL,
    [Archived__c]          BIT             NULL,
    [Attainment__c]        DECIMAL (18)    NULL,
    [Call_Activity__c]     NVARCHAR (510)  NULL,
    [Call_Counter__c]      DECIMAL (18)    NULL,
    [Call_Type__c]         NVARCHAR (510)  NULL,
    [Campaign__c]          NCHAR (36)      NULL,
    [Cancelled__c]         BIT             NULL,
    [Contact__c]           NCHAR (36)      NULL,
    [CreatedById]          NCHAR (36)      NULL,
    [CreatedDate]          DATETIME2 (7)   NOT NULL,
    [Doctor_Name__c]       NVARCHAR (200)  NULL,
    [DurationInMinutes]    INT             NULL,
    [EndDateTime]          DATETIME2 (7)   NULL,
    [Event__c]             NVARCHAR (510)  NULL,
    [Event_Detail__c]      NCHAR (36)      NULL,
    [Event_type__c]        NVARCHAR (510)  NULL,
    [Focus__c]             NVARCHAR (510)  NULL,
    [Id]                   NCHAR (18)      NOT NULL,
    [LastModifiedById]     NCHAR (36)      NULL,
    [LastModifiedDate]     DATETIME2 (7)   NOT NULL,
    [StartDateTime]        DATETIME2 (7)   NULL,
    [Status__c]            NVARCHAR (2600) NULL,
    [Subject]              NVARCHAR (510)  NULL,
    [SystemModstamp]       DATETIME2 (7)   NULL,
    [Unscheduled__c]       BIT             NULL,
    [WhatCount]            INT             NULL,
    [WhoCount]             INT             NULL,
    [WhoId]                NCHAR (36)      NULL,
    [IsDeleted]            VARCHAR (36)    NULL,
    [Primary_Focus__c]     NVARCHAR (510)  NULL,
    [WhatId]               NCHAR (36)      NULL,
    [OwnerId]              NCHAR (36)      NULL,
    [RecordTypeId]         NCHAR (36)      NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

