CREATE TABLE [SrcSFDC].[Invoice__C]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Billing_document_type__c] [nvarchar](2) NULL,
	[BillTo__c] [nchar](18) NULL,
	[BillTo_Number__c] [nvarchar](1300) NULL,
	[CC_Number__c] [nvarchar](25) NULL,
	[CC_Type__c] [nvarchar](4) NULL,
	[Clear_Doc__c] [nvarchar](10) NULL,
	[Clear_Text__c] [nvarchar](50) NULL,
	[Clearing_Amount__c] [nvarchar](20) NULL,
	[Clearing_Amount_Key__c] [nvarchar](20) NULL,
	[Clearing_Date__c] [datetime2](7) NULL,
	[Clearing_Document_Number__c] [nvarchar](18) NULL,
	[Clearing_Flag__c] [nvarchar](255) NULL,
	[Company_Code__c] [nvarchar](4) NULL,
	[ConnectionReceivedId] [nchar](18) NULL,
	[ConnectionSentId] [nchar](18) NULL,
	[CreatedById] [nchar](18) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CurrencyIsoCode] [nvarchar](3) NULL,
	[Customer_PO_number__c] [nvarchar](35) NULL,
	[Error_Code__c] [nvarchar](4) NULL,
	[Error_Description__c] [nvarchar](255) NULL,
	[External_Id__c] [nvarchar](40) NULL,
	[Fiscal_Year__c] [nvarchar](4) NULL,
	[Id] [nchar](18) NOT NULL,
	[Installment_Number__c] [decimal](18, 0) NULL,
	[Installment_Status__c] [nvarchar](255) NULL,
	[Invoice_Date__c] [datetime2](7) NULL,
	[Invoice_Date_Time1__c] [datetime2](7) NULL,
	[Invoice_Date_Time__c] [datetime2](7) NULL,
	[Invoice_Due_Date__c] [datetime2](7) NULL,
	[Invoice_Number__c] [nvarchar](10) NULL,
	[Invoice_PDF_Filename__c] [nvarchar](80) NULL,
	[Invoice_Posting_Date__c] [datetime2](7) NULL,
	[Is_Consolidated_Invoice__c] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[LastModifiedById] [nchar](18) NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[LastReferencedDate] [datetime2](7) NULL,
	[LastViewedDate] [datetime2](7) NULL,
	[Loan_ID__c] [nvarchar](100) NULL,
	[Merchant_ID__c] [nvarchar](15) NULL,
	[Name] [nvarchar](80) NULL,
	[Open_Invoice_Amount__c] [decimal](18, 2) NULL,
	[Original_Invoice_Amount__c] [decimal](18, 2) NULL,
	[Patient__c] [nchar](18) NULL,
	[Patient_Id__c] [nvarchar](36) NULL,
	[Patient_IDs__c] [nvarchar](500) NULL,
	[Payer__c] [nchar](18) NULL,
	[Payer_Number__c] [nvarchar](1300) NULL,
	[Payment_Amount__c] [decimal](18, 3) NULL,
	[Payment_Doc_Date_Time1__c] [datetime2](7) NULL,
	[Payment_Doc_Date_Time__c] [datetime2](7) NULL,
	[Payment_Option__c] [nvarchar](50) NULL,
	[Payment_Term__c] [nvarchar](10) NULL,
	[Remarks__c] [nvarchar](50) NULL,
	[Sales_Order_Type__c] [nvarchar](4) NULL,
	[SAP_Order_Number__c] [nvarchar](20) NULL,
	[Scheduled_Date__c] [datetime2](7) NULL,
	[SoldTo__c] [nchar](18) NULL,
	[SoldTo_Number__c] [nvarchar](1300) NULL,
	[SystemModstamp] [datetime2](7) NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED INDEX
	(
		[Id] ASC
	)
);


