CREATE TABLE [SrcSFDC].[Itero_Order_Product_Details__c] (
    [LZBatchID]             INT             NOT NULL,
    [ADLSBatchID]           INT             NOT NULL,
    [ADLSTimestamp]         DATETIME2 (0)   NOT NULL,
    [Asset__c]              NCHAR (18)      NULL,
    [Asset_Type__c]         NVARCHAR (255)  NULL,
    [ConnectionReceivedId]  NCHAR (18)      NULL,
    [ConnectionSentId]      NCHAR (18)      NULL,
    [CreatedDate]           DATETIME2 (7)   NULL,
    [Custom_Setting_No__c]  NVARCHAR (255)  NULL,
    [Expedite__c]           NVARCHAR (255)  NULL,
    [Id]                    NCHAR (18)      NULL,
    [Investigation__c]      NVARCHAR (255)  NULL,
    [IsDeleted]             VARCHAR (5)     NULL,
    [Item__c]               NVARCHAR (255)  NULL,
    [LastModifiedDate]      DATETIME2 (7)   NULL,
    [LastReferencedDate]    DATETIME2 (7)   NULL,
    [Material__c]           NVARCHAR (255)  NULL,
    [Name]                  NVARCHAR (80)   NULL,
    [Notes__c]              NVARCHAR (255)  NULL,
    [Physical_Damage__c]    NVARCHAR (255)  NULL,
    [Price__c]              DECIMAL (18, 2) NULL,
    [Product1__c]           NCHAR (18)      NULL,
    [Product__c]            NVARCHAR (255)  NULL,
    [Quantity__c]           DECIMAL (18, 2) NULL,
    [RecordTypeId]          NCHAR (18)      NULL,
    [Replacement_Reason__c] NVARCHAR (255)  NULL,
    [Sub_Totoal__c]         DECIMAL (18, 2) NULL,
    [SystemModstamp]        DATETIME2 (7)   NULL,
    [Ticket__c]             NCHAR (18)      NULL,
    [Serial_number__c]      NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

