CREATE TABLE [SrcSFDC].[Lead_Journey__C] (
    [LZBatchID]                                  INT            NOT NULL,
    [ADLSBatchID]                                INT            NOT NULL,
    [ADLSTimestamp]                              DATETIME2 (0)  NOT NULL,
    [Account2__c]                                NCHAR (72)     NULL,
    [Account3__c]                                NCHAR (72)     NULL,
    [Account__c]                                 NCHAR (72)     NULL,
    [Check_in_Time_Complete__c]                  DATETIME2 (7)  NULL,
    [Chief_Concern__c]                           NVARCHAR (510) NULL,
    [Condition_Type__c]                          NVARCHAR (100) NULL,
    [ConnectionReceivedId]                       NCHAR (72)     NULL,
    [ConnectionSentId]                           NCHAR (72)     NULL,
    [Corporate_Benefits_Partner__c]              NVARCHAR (510) NULL,
    [CreatedById]                                NCHAR (72)     NULL,
    [CreatedDate]                                DATETIME2 (7)  NOT NULL,
    [CurrencyIsoCode]                            NVARCHAR (6)   NULL,
    [Define_the_perfect_treatment_experience__c] NVARCHAR (100) NULL,
    [Heroku_External_Id__c]                      NVARCHAR (100) NULL,
    [How_did_you_hear_about_us__c]               NVARCHAR (510) NULL,
    [I_am__c]                                    NVARCHAR (510) NULL,
    [Id]                                         NCHAR (72)     NOT NULL,
    [IsDeleted]                                  VARCHAR (5)    NOT NULL,
    [LastActivityDate]                           DATETIME2 (7)  NULL,
    [LastModifiedById]                           NCHAR (72)     NULL,
    [LastModifiedDate]                           DATETIME2 (7)  NOT NULL,
    [Lead__c]                                    NCHAR (72)     NULL,
    [Lead_Status__c]                             NVARCHAR (510) NULL,
    [Lead_URL_Campaign__c]                       NVARCHAR (510) NULL,
    [Lead_URL_Medium__c]                         NVARCHAR (160) NULL,
    [Lead_URL_Source__c]                         NVARCHAR (160) NULL,
    [LeadSource__c]                              NVARCHAR (510) NULL,
    [Name]                                       NVARCHAR (160) NULL,
    [OwnerId]                                    NCHAR (72)     NOT NULL,
    [Parent__c]                                  NCHAR (72)     NULL,
    [Pilot_Partner__c]                           NVARCHAR (510) NULL,
    [Preferred_Doctor_1__c]                      NCHAR (72)     NULL,
    [Preferred_Doctor_2__c]                      NCHAR (72)     NULL,
    [Preferred_Doctor_3__c]                      NCHAR (72)     NULL,
    [Primary_Goal__c]                            NVARCHAR (510) NULL,
    [Primary_Source__c]                          NVARCHAR (510) NULL,
    [SA_Prospect_Status__c]                      NVARCHAR (510) NULL,
    [Scan_office_appointment_confirmed__c]       VARCHAR (5)    NULL,
    [SystemModstamp]                             DATETIME2 (7)  NOT NULL,
    [What_does_a_new_smile_mean_to_you__c]       NVARCHAR (510) NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

