CREATE TABLE [SrcSFDC].[Opportunity]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Account_Country__c] [nvarchar](5) NULL,
	[AccountId] [nchar](18) NULL,
	[Advantage_Eligible_Case__c] [bit] NULL,
	[Age__c] [decimal](18, 2) NULL,
	[Aging_from_first_CC_await__c] [decimal](18, 0) NULL,
	[Aging_on_modification__c] [decimal](18, 2) NULL,
	[Aging_Order_date__c] [decimal](18, 0) NULL,
	[Alert_Status_Date__c] [datetime2](7) NULL,
	[Amount] [decimal](18, 2) NULL,
	[Apttus_Proposal__Discount_Percent__c] [decimal](18, 2) NULL,
	[Baseline__c] [decimal](18, 0) NULL,
	[Bill_to__c] [nvarchar](80) NULL,
	[Billing_Part__c] [decimal](18, 0) NULL,
	[CampaignId] [nchar](18) NULL,
	[Cancellation_CFY__c] [decimal](18, 0) NULL,
	[Cancellation_Date__c] [datetime2](7) NULL,
	[Cancellation_PFY__c] [decimal](18, 0) NULL,
	[Cancelled__c] [decimal](18, 0) NULL,
	[cancelled_case__c] [decimal](18, 0) NULL,
	[Case_Transfer__c] [decimal](18, 0) NULL,
	[Case_VCT_Training_Date__c] [datetime2](7) NULL,
	[CC_awaiting_approval__c] [decimal](18, 0) NULL,
	[CC_modified__c] [decimal](18, 0) NULL,
	[CC_Modified_Date__c] [datetime2](7) NULL,
	[CFY_Current_Month_Case__c] [decimal](18, 0) NULL,
	[CFY_Current_Quarter_Case__c] [decimal](18, 0) NULL,
	[CFY_Previous_Month_Case__c] [decimal](18, 0) NULL,
	[CFY_Previous_Quarter_Case__c] [decimal](18, 0) NULL,
	[Child_Opportunity_Id__c] [nvarchar](18) NULL,
	[Clincheck_Accepted_Date__c] [datetime2](7) NULL,
	[Clincheck_Aging_Days__c] [decimal](18, 0) NULL,
	[Clincheck_Start_Date__c] [datetime2](7) NULL,
	[Clinical_Class__c] [nvarchar](255) NULL,
	[Clinical_Hold_Date__c] [datetime2](7) NULL,
	[Clinicheck_Awaiting_Approval__c] [datetime2](7) NULL,
	[Clinids__c] [nvarchar](4000) NULL,
	[Closed_By__c] [nchar](18) NULL,
	[Closed_Reason__c] [nvarchar](255) NULL,
	[Closed_Shipped__c] [bit] NULL,
	[CloseDate] [datetime2](7) NOT NULL,
	[Commission_Date__c] [datetime2](7) NULL,
	[Commissioned__c] [decimal](18, 0) NULL,
	[Company_ID__c] [nvarchar](10) NULL,
	[Competitor__c] [nvarchar](20) NULL,
	[Competitor_Involved__c] [nvarchar](255) NULL,
	[Competitor_Products__c] [nvarchar](255) NULL,
	[ConnectionReceivedId] [nchar](18) NULL,
	[ConnectionSentId] [nchar](18) NULL,
	[Contact__c] [nchar](18) NULL,
	[Contact_Zip_Postal_Code__c] [nvarchar](1300) NULL,
	[Contract_Loaded__c] [datetime2](7) NULL,
	[Contract_Loaded_Duration__c] [decimal](18, 0) NULL,
	[Contract_Loaded_to_Order_Entry__c] [decimal](18, 0) NULL,
	[Contract_Loaded_to_Shipping__c] [decimal](18, 0) NULL,
	[Contract_Signed__c] [datetime2](7) NULL,
	[Contract_Signed_Date__c] [datetime2](7) NULL,
	[Contract_Signed_to_Delivered__c] [decimal](18, 0) NULL,
	[ContractId] [nchar](18) NULL,
	[ContractLoaded_to_Order_Entry__c] [decimal](18, 0) NULL,
	[ContractLoaded_to_Shipping__c] [decimal](18, 0) NULL,
	[ContractSigned_to_Delivered__c] [decimal](18, 0) NULL,
	[Country__c] [nvarchar](1300) NULL,
	[CreatedById] [nchar](18) NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[Credit_Memo_Number__c] [decimal](18, 0) NULL,
	[CurrencyIsoCode] [nvarchar](3) NOT NULL,
	[Current_Invisalign_Adv_Programtier_level__c] [nvarchar](255) NULL,
	[Current_Month_Case__c] [decimal](18, 0) NULL,
	[Current_Quarter_Case__c] [decimal](18, 0) NULL,
	[Current_Year_Case__c] [decimal](18, 0) NULL,
	[Customer_Need__c] [nvarchar](255) NULL,
	[Days_Demo_to_Contract__c] [decimal](18, 0) NULL,
	[Days_from_Generated_to_Demo__c] [decimal](18, 0) NULL,
	[Dec_Jan_Offer__c] [bit] NULL,
	[DeepBiteFinal__c] [nvarchar](255) NULL,
	[DeepBiteInitial__c] [nvarchar](255) NULL,
	[Delivered_Date__c] [datetime2](7) NULL,
	[Delivery_to_VCT_Date__c] [decimal](18, 0) NULL,
	[Demo_Date__c] [datetime2](7) NULL,
	[Dep__c] [bit] NULL,
	[DEP_Points__c] [decimal](18, 2) NULL,
	[DEP_with_IPD_start_date__c] [bit] NULL,
	[Description] [nvarchar](4000) NULL,
	[diff_new_order__c] [decimal](18, 0) NULL,
	[Difficulty__c] [nvarchar](255) NULL,
	[Discount_Description__c] [nvarchar](255) NULL,
	[Discount_Type__c] [nvarchar](255) NULL,
	[Display_in_IDS__c] [bit] NULL,
	[Distributor__c] [nvarchar](255) NULL,
	[Downgrade_to_Express__c] [bit] NULL,
	[Drip_Marketing_Campaign__c] [nchar](18) NULL,
	[Duplicate_Cases__c] [decimal](18, 0) NULL,
	[EECD_Date__c] [datetime2](7) NULL,
	[Eligible_Date__c] [datetime2](7) NULL,
	[eTrigue_id__c] [nvarchar](100) NULL,
	[EU_Scanner_Contract_Loaded__c] [nvarchar](80) NULL,
	[Event__c] [nvarchar](255) NULL,
	[Expected_CC_Ready_Date__c] [datetime2](7) NULL,
	[ExpectedRevenue] [decimal](18, 2) NULL,
	[First_cc_awaiting_Approval__c] [datetime2](7) NULL,
	[First_CC_under_dev__c] [datetime2](7) NULL,
	[First_Materials_Pending_date__c] [datetime2](7) NULL,
	[Fiscal] [nvarchar](6) NULL,
	[FiscalQuarter] [int] NULL,
	[FiscalYear] [int] NULL,
	[ForecastCategory] [nvarchar](40) NOT NULL,
	[ForecastCategoryName] [nvarchar](40) NOT NULL,
	[Funding_Source__c] [nvarchar](255) NULL,
	[Fusion_Baseline__c] [decimal](18, 0) NULL,
	[Fusion_Cases__c] [nvarchar](255) NULL,
	[Fusion_Contract_Name__c] [nvarchar](255) NULL,
	[Fusion_Date__c] [datetime2](7) NULL,
	[Fusion_Stop_Date__c] [datetime2](7) NULL,
	[Fusion_Target__c] [nvarchar](4000) NULL,
	[Generated_By__c] [nchar](18) NULL,
	[Generated_by_Date__c] [datetime2](7) NULL,
	[Generated_by_Profile__c] [nvarchar](1300) NULL,
	[Group_Account_ID__c] [nvarchar](20) NULL,
	[HasOpenActivity] [bit] NOT NULL,
	[HasOpportunityLineItem] [bit] NOT NULL,
	[HasOverdueTask] [bit] NOT NULL,
	[Hold_Aging_Days__c] [decimal](18, 0) NULL,
	[Hold_Date__c] [datetime2](7) NULL,
	[Hold_Reason__c] [nvarchar](255) NULL,
	[Id] [nchar](18) NOT NULL,
	[Invoice_Amount__c] [decimal](18, 2) NULL,
	[Invoice_Number__c] [decimal](18, 0) NULL,
	[Invoiced_date__c] [datetime2](7) NULL,
	[IPD_Date__c] [datetime2](7) NULL,
	[is_Refurbished_Product__c] [bit] NULL,
	[IsClosed] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsExcludedFromTerritory2Filter] [bit] NOT NULL,
	[IsIOScan__c] [nvarchar](255) NULL,
	[isPrimaryTreatment__c] [bit] NULL,
	[IsPrivate] [bit] NOT NULL,
	[IsSplit] [bit] NOT NULL,
	[IsWon] [bit] NOT NULL,
	[JDE_Align_Part_N__c] [nvarchar](40) NULL,
	[JDE_Part_Number__c] [nvarchar](40) NULL,
	[Last_primary_order_date_for_pid__c] [datetime2](7) NULL,
	[LastActivityDate] [datetime2](7) NULL,
	[LastModifiedById] [nchar](18) NULL,
	[LastModifiedDate] [datetime2](7) NOT NULL,
	[LastReferencedDate] [datetime2](7) NULL,
	[LastViewedDate] [datetime2](7) NULL,
	[Latest_Refinement_Date__c] [datetime2](7) NULL,
	[Lead_Source__c] [nvarchar](50) NULL,
	[Lead_time__c] [decimal](18, 0) NULL,
	[LeadSource] [nvarchar](40) NULL,
	[Leadtime_Case_complete_CC_accepted__c] [decimal](18, 0) NULL,
	[Leasing_Pending_Date__c] [datetime2](7) NULL,
	[Leasing_Pending_Duration__c] [decimal](18, 0) NULL,
	[Legacy_Sf_Id__c] [nvarchar](18) NULL,
	[Location__c] [nchar](18) NULL,
	[Location_Number__c] [nvarchar](1300) NULL,
	[Lost_Reason__c] [nvarchar](255) NULL,
	[MAT_ID__c] [nvarchar](1300) NULL,
	[Material_Type__c] [nvarchar](80) NULL,
	[Name] [nvarchar](120) NOT NULL,
	[New_Invoice_Amount__c] [decimal](18, 2) NULL,
	[New_Invoice_Number__c] [decimal](18, 0) NULL,
	[New_Order_Date__c] [datetime2](7) NULL,
	[New_Order_Number__c] [nvarchar](20) NULL,
	[New_Order_Type__c] [nvarchar](5) NULL,
	[NextStep] [nvarchar](255) NULL,
	[Number_of_stages_in_the_order__c] [decimal](18, 0) NULL,
	[oldTreatmentLocation__c] [nvarchar](10) NULL,
	[Onboarding_Date__c] [datetime2](7) NULL,
	[Onboarding_Duration__c] [decimal](18, 0) NULL,
	[Opportunity_Number__c] [nvarchar](30) NULL,
	[Order_Age__c] [decimal](18, 0) NULL,
	[Order_Date__c] [datetime2](7) NULL,
	[Order_date_Receipt_date__c] [decimal](18, 0) NULL,
	[Order_Entry_Date__c] [datetime2](7) NULL,
	[Order_Entry_Duration__c] [decimal](18, 0) NULL,
	[Order_Number__c] [nvarchar](20) NULL,
	[Order_status__c] [nvarchar](255) NULL,
	[Order_Type__c] [nvarchar](10) NULL,
	[Other_Reason__c] [nvarchar](255) NULL,
	[Owner_Manager_Email__c] [nvarchar](80) NULL,
	[Owner_Match__c] [bit] NULL,
	[Owner_Override__c] [bit] NULL,
	[OwnerId] [nchar](18) NOT NULL,
	[Part_Number__c] [decimal](18, 0) NULL,
	[PartnerAccountId] [nchar](18) NULL,
	[Payment_Type__c] [nvarchar](80) NULL,
	[Pending_Information_Date__c] [datetime2](7) NULL,
	[Pending_Information_Duration__c] [decimal](18, 0) NULL,
	[PFY_Current_Month_Case__c] [decimal](18, 0) NULL,
	[PFY_Current_Quarter_Case__c] [decimal](18, 0) NULL,
	[PFY_Previous_Month_Case__c] [decimal](18, 0) NULL,
	[PFY_Previous_Quarter_Case__c] [decimal](18, 0) NULL,
	[Preferred_Contact_Lead_Notes__c] [nvarchar](255) NULL,
	[Previous_Month_Case__c] [decimal](18, 0) NULL,
	[Previous_Quarter__c] [decimal](18, 0) NULL,
	[Previous_Quarter_Case__c] [decimal](18, 0) NULL,
	[Previous_Year_Case__c] [decimal](18, 0) NULL,
	[Pricebook2Id] [nchar](18) NULL,
	[Probability] [decimal](18, 0) NOT NULL,
	[Product__c] [nchar](18) NULL,
	[Product_Option__c] [nvarchar](255) NULL,
	[Product_Text__c] [nvarchar](255) NULL,
	[Promotion__c] [nvarchar](255) NULL,
	[Rebate_Eligible_Cases__c] [bit] NULL,
	[Receipt_Date__c] [datetime2](7) NULL,
	[RecordTypeId] [nchar](18) NULL,
	[Refer_To__c] [nchar](18) NULL,
	[Refinement_Count__c] [decimal](18, 0) NULL,
	[Region__c] [nvarchar](1300) NULL,
	[Rejected_CC__c] [decimal](18, 0) NULL,
	[Rejected_Impressions_Date__c] [datetime2](7) NULL,
	[Research_case__c] [decimal](18, 0) NULL,
	[Rev_Rec_Date__c] [datetime2](7) NULL,
	[RMA__c] [nvarchar](50) NULL,
	[Sale_Type__c] [nvarchar](255) NULL,
	[Sales_Commission_Fiscal_Quarter__c] [nvarchar](1) NULL,
	[Sales_Commission_Fiscal_Year__c] [nvarchar](4) NULL,
	[Sales_Groups__c] [nvarchar](255) NULL,
	[Scanner_Demo_Date__c] [datetime2](7) NULL,
	[Scanner_SN__c] [nvarchar](250) NULL,
	[Secondary_Order_Type__c] [nvarchar](255) NULL,
	[Ship_To__c] [nvarchar](80) NULL,
	[Shipment_Scheduled__c] [datetime2](7) NULL,
	[Shipped_Date__c] [datetime2](7) NULL,
	[Shipped_Date_to_Delivered__c] [decimal](18, 0) NULL,
	[Shipped_invoiced_date__c] [datetime2](7) NULL,
	[ShippedDate_to_Delivered__c] [decimal](18, 0) NULL,
	[Shipping_Duration__c] [decimal](18, 0) NULL,
	[Split__c] [decimal](18, 0) NULL,
	[Split_With__c] [nchar](18) NULL,
	[Stage_age__c] [decimal](18, 0) NULL,
	[Stage_Date__c] [datetime2](7) NULL,
	[Stage_Description__c] [nvarchar](255) NULL,
	[StageName] [nvarchar](40) NOT NULL,
	[Status__c] [nvarchar](255) NULL,
	[Sub_Lead_Source__c] [nvarchar](255) NULL,
	[Submitted_Quarter__c] [decimal](18, 0) NULL,
	[Suspend_Notications__c] [bit] NULL,
	[SyncedQuoteId] [nchar](18) NULL,
	[SystemModstamp] [datetime2](7) NOT NULL,
	[Technician_assigned_to_order__c] [nvarchar](80) NULL,
	[Teen_Age__c] [decimal](18, 0) NULL,
	[Territory2Id] [nchar](18) NULL,
	[Territory_Coverage__c] [nchar](18) NULL,
	[This_Quarter__c] [decimal](18, 0) NULL,
	[Total_Amount__c] [decimal](18, 2) NULL,
	[Total_Quantity__c] [decimal](18, 2) NULL,
	[Total_Transfer_Quantity__c] [decimal](18, 0) NULL,
	[TotalOpportunityQuantity] [decimal](18, 2) NULL,
	[Tracking__c] [nvarchar](255) NULL,
	[Trade_In_Serial_Number__c] [nvarchar](255) NULL,
	[Training_Completed__c] [datetime2](7) NULL,
	[Treatment__c] [nchar](18) NULL,
	[Type] [nvarchar](40) NULL,
	[Unit_List_Price__c] [decimal](18, 2) NULL,
	[Unit_Sales_Price__c] [decimal](18, 2) NULL,
	[Upgrade_to_Full__c] [bit] NULL,
	[Vivera_Primary_Product__c] [nvarchar](50) NULL,
	[VOI_Order_Number__c] [nvarchar](80) NULL,
	[Year_1_Case_Count__c] [decimal](18, 0) NULL,
	[Year_1_Requirement__c] [decimal](18, 0) NULL,
	[Year_2_Case_Count__c] [decimal](18, 0) NULL,
	[Year_2_Requirement__c] [decimal](18, 0) NULL,
	[Year_3_Case_Count__c] [decimal](18, 0) NULL,
	[Year_3_Requirement__c] [decimal](18, 0) NULL,
	[Year_on_year_percentage_growth__c] [decimal](18, 0) NULL,
	[Years_of_subscription__c] [decimal](18, 0) NULL,
	[Yr_1_Incremental__c] [decimal](18, 0) NULL,
	[Yr_2_Incremental__c] [decimal](18, 0) NULL,
	[Yr_3_Incremental__c] [decimal](18, 0) NULL,
	[Cancellation_Cause__c] [nvarchar](255) NULL,
	[Scanner_Quantity__c] [int] NULL,
	[Cancellation_Status__c] [nvarchar](255) NULL,
	[Leasing_status_date__c] [datetime2](7) NULL,
	[Scanner_Sales_Channel__c] [nvarchar](50) NULL,
	[iTero_Type__c] [nvarchar](255) NULL,
	[Opportunity_Id__c] [nvarchar](1300) NULL,
	[Agreement_Effective_Date__c] [datetime2](7) NULL,
	[Align_Signature_Date__c] [datetime2](7) NULL,
	[Cancellation_Reason__c] [nvarchar](255) NULL,
	[Contract_type__c] [nvarchar](255) NULL,
	[Go_Digital__c] [varchar](5) NULL,
	[Go_Digital_Opp__c] [nchar](18) NULL,
	[Leasing_Company__c] [nvarchar](255) NULL,
	[Number_of_Scanners__c] [decimal](18, 0) NULL,
	[Request_Format__c] [nvarchar](255) NULL,
	[Routed_Date__c] [datetime2](7) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED COLUMNSTORE INDEX
)