CREATE TABLE [SrcSFDC].[OpportunityLineItem] (
    [LZBatchID]                 INT             NOT NULL,
    [ADLSBatchID]               INT             NOT NULL,
    [ADLSTimestamp]             DATETIME2 (0)   NOT NULL,
    [Aligner_Qty__c]            DECIMAL (18, 2) NULL,
    [ConnectionReceivedId]      NCHAR (18)      NULL,
    [ConnectionSentId]          NCHAR (18)      NULL,
    [CreatedById]               NCHAR (18)      NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]           NVARCHAR (3)    NOT NULL,
    [Description]               NVARCHAR (255)  NULL,
    [Discount_Amount__c]        DECIMAL (18, 2) NULL,
    [Id]                        NCHAR (18)      NOT NULL,
    [is_Refurbished_Product__c] BIT             NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [LastModifiedById]          NCHAR (18)      NULL,
    [LastModifiedDate]          DATETIME2 (7)   NOT NULL,
    [Legacy_Sf_Id__c]           NVARCHAR (18)   NULL,
    [ListPrice]                 DECIMAL (18, 2) NULL,
    [Lower_Aligners__c]         DECIMAL (18)    NULL,
    [Name]                      NVARCHAR (376)  NULL,
    [OpportunityId]             NCHAR (18)      NOT NULL,
    [Order_Number__c]           NVARCHAR (20)   NULL,
    [PricebookEntryId]          NCHAR (18)      NULL,
    [Product2Id]                NCHAR (18)      NULL,
    [ProductCode]               NVARCHAR (255)  NULL,
    [Quantity]                  DECIMAL (18, 2) NOT NULL,
    [ServiceDate]               DATETIME2 (7)   NULL,
    [SortOrder]                 INT             NULL,
    [SystemModstamp]            DATETIME2 (7)   NOT NULL,
    [TotalPrice]                DECIMAL (18, 2) NULL,
    [UnitPrice]                 DECIMAL (18, 2) NULL,
    [Upper_Aligners__c]         DECIMAL (18)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Id]));

