CREATE TABLE [SrcSFDC].[Product2] (
    [LZBatchID]                              INT             NOT NULL,
    [ADLSBatchID]                            INT             NOT NULL,
    [ADLSTimestamp]                          DATETIME2 (0)   NOT NULL,
    [Apttus_Config2__BundleInvoiceLevel__c]  NVARCHAR (255)  NULL,
    [Apttus_Config2__ConfigurationType__c]   NVARCHAR (255)  NULL,
    [Apttus_Config2__Customizable__c]        BIT             NULL,
    [Apttus_Config2__DiscontinuedDate__c]    DATETIME2 (7)   NULL,
    [Apttus_Config2__EffectiveDate__c]       DATETIME2 (7)   NULL,
    [Apttus_Config2__EffectiveStartDate__c]  DATETIME2 (7)   NULL,
    [Apttus_Config2__ExcludeFromSitemap__c]  BIT             NULL,
    [Apttus_Config2__ExpirationDate__c]      DATETIME2 (7)   NULL,
    [Apttus_Config2__HasAttributes__c]       BIT             NULL,
    [Apttus_Config2__HasDefaults__c]         BIT             NULL,
    [Apttus_Config2__HasOptions__c]          BIT             NULL,
    [Apttus_Config2__HasSearchAttributes__c] BIT             NULL,
    [Apttus_Config2__Icon__c]                NVARCHAR (1300) NULL,
    [Apttus_Config2__IconId__c]              NVARCHAR (32)   NULL,
    [Apttus_Config2__IconSize__c]            NVARCHAR (32)   NULL,
    [Apttus_Config2__LaunchDate__c]          DATETIME2 (7)   NULL,
    [Apttus_Config2__ProductType__c]         NVARCHAR (255)  NULL,
    [Apttus_Config2__Uom__c]                 NVARCHAR (255)  NULL,
    [Apttus_Config2__Version__c]             DECIMAL (18, 2) NULL,
    [Case_Factor__c]                         DECIMAL (18, 3) NULL,
    [Commission_Type__c]                     NVARCHAR (255)  NULL,
    [ConnectionReceivedId]                   NCHAR (18)      NULL,
    [ConnectionSentId]                       NCHAR (18)      NULL,
    [CreatedById]                            NCHAR (18)      NULL,
    [CreatedDate]                            DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                        NVARCHAR (3)    NOT NULL,
    [Description]                            NVARCHAR (4000) NULL,
    [Display_Name__c]                        NVARCHAR (255)  NULL,
    [DisplayUrl]                             NVARCHAR (1000) NULL,
    [ExternalDataSourceId]                   NCHAR (18)      NULL,
    [ExternalId]                             NVARCHAR (255)  NULL,
    [Family]                                 NVARCHAR (40)   NULL,
    [Id]                                     NCHAR (18)      NOT NULL,
    [IsActive]                               BIT             NOT NULL,
    [IsDeleted]                              BIT             NOT NULL,
    [Keywords__c]                            NVARCHAR (255)  NULL,
    [LastModifiedById]                       NCHAR (18)      NULL,
    [LastModifiedDate]                       DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]                     DATETIME2 (7)   NULL,
    [LastViewedDate]                         DATETIME2 (7)   NULL,
    [Legacy_Product_Code__c]                 NVARCHAR (255)  NULL,
    [Legacy_Salesforce_Id__c]                NVARCHAR (18)   NULL,
    [Maximum_Qty__c]                         DECIMAL (18)    NULL,
    [Minimum_Qty__c]                         DECIMAL (18)    NULL,
    [Name]                                   NVARCHAR (255)  NOT NULL,
    [Original_Price__c]                      DECIMAL (18)    NULL,
    [ProductCode]                            NVARCHAR (255)  NULL,
    [QuantityUnitOfMeasure]                  NVARCHAR (40)   NULL,
    [StockKeepingUnit]                       NVARCHAR (180)  NULL,
    [SystemModstamp]                         DATETIME2 (7)   NOT NULL,
    [Tax_Product_Category_Id__c]             NVARCHAR (80)   NULL,
    [UOM__c]                                 NVARCHAR (10)   NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

