CREATE TABLE [SrcSFDC].[Program_Registration__c] (
    [LZBatchID]                           INT             NOT NULL,
    [ADLSBatchID]                         INT             NOT NULL,
    [ADLSTimestamp]                       DATETIME2 (0)   NOT NULL,
    [CarryOverProcessed__c]               BIT             NULL,
    [ConnectionReceivedId]                NCHAR (18)      NULL,
    [ConnectionSentId]                    NCHAR (18)      NULL,
    [Contact__c]                          NCHAR (18)      NULL,
    [CreatedById]                         NCHAR (18)      NULL,
    [CreatedDate]                         DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                     NVARCHAR (3)    NOT NULL,
    [Current_Status__c]                   NVARCHAR (255)  NULL,
    [Discount__c]                         DECIMAL (18, 2) NULL,
    [Education_Points__c]                 DECIMAL (18)    NULL,
    [Eligibility_Status__c]               NVARCHAR (255)  NULL,
    [Email_Opt_Out__c]                    BIT             NULL,
    [External_Event_Points__c]            DECIMAL (18)    NULL,
    [External_Id__c]                      NVARCHAR (80)   NULL,
    [Id]                                  NCHAR (18)      NOT NULL,
    [IsDeleted]                           BIT             NOT NULL,
    [LastActivityDate]                    DATETIME2 (7)   NULL,
    [LastModifiedById]                    NCHAR (18)      NULL,
    [LastModifiedDate]                    DATETIME2 (7)   NOT NULL,
    [Name]                                NVARCHAR (80)   NULL,
    [NLP_Growth_SOC__c]                   DECIMAL (18, 2) NULL,
    [Opt_Out_of_Auto_Enrollment__c]       BIT             NULL,
    [Opt_Out_of_Promotional_Emails__c]    BIT             NULL,
    [OwnerId]                             NCHAR (18)      NOT NULL,
    [Pricing_Group__c]                    NCHAR (18)      NULL,
    [Pricing_Group_Treatment_Location__c] NCHAR (18)      NULL,
    [Program_Code__c]                     NVARCHAR (20)   NULL,
    [Sold_To__c]                          NCHAR (18)      NULL,
    [SystemModstamp]                      DATETIME2 (7)   NOT NULL,
    [T_Cs_Accepted_Date__c]               NVARCHAR (80)   NULL,
    [T_Cs_Declined_Date__c]               NVARCHAR (80)   NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

