CREATE TABLE [SrcSFDC].[ringdna105__Call__c]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Call_Connected__c] [varchar](5) NULL,
	[ConnectionReceivedId] [nchar](36) NULL,
	[ConnectionSentId] [nchar](36) NULL,
	[CreatedById] [nchar](36) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CurrencyIsoCode] [nvarchar](6) NULL,
	[Id] [nchar](36) NOT NULL,
	[IsDeleted] [varchar](5) NULL,
	[LastModifiedById] [nchar](36) NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[Name] [nvarchar](160) NULL,
	[OwnerId] [nchar](36) NULL,
	[ringdna105__Abandoned_Call__c] [varchar](5) NULL,
	[ringdna105__Account__c] [nchar](36) NULL,
	[ringdna105__ActivityDate__c] [datetime2](7) NULL,
	[ringdna105__Automated_Voicemail__c] [varchar](5) NULL,
	[ringdna105__Automated_Voicemail_Link__c] [nvarchar](510) NULL,
	[ringdna105__Automated_Voicemail_Used__c] [nvarchar](510) NULL,
	[ringdna105__Call_Connected__c] [varchar](5) NULL,
	[ringdna105__Call_Direction__c] [nvarchar](510) NULL,
	[ringdna105__Call_Disposition__c] [nvarchar](510) NULL,
	[ringdna105__Call_Duration__c] [decimal](18, 0) NULL,
	[ringdna105__Call_Duration_min__c] [decimal](18, 2) NULL,
	[ringdna105__Call_Hour_Of_Day_Agent__c] [decimal](18, 0) NULL,
	[ringdna105__Call_Hour_Of_Day_Local__c] [decimal](18, 0) NULL,
	[ringdna105__Call_Rating__c] [decimal](18, 0) NULL,
	[ringdna105__Call_Recording__c] [nvarchar](2600) NULL,
	[ringdna105__Call_Recording_URL__c] [nvarchar](510) NULL,
	[ringdna105__Call_Report__c] [varchar](5) NULL,
	[ringdna105__Call_Report_Category__c] [nvarchar](510) NULL,
	[ringdna105__Call_Report_Note__c] [nvarchar](max) NULL,
	[ringdna105__Call_Report_Time__c] [datetime2](7) NULL,
	[ringdna105__Call_Status__c] [nvarchar](510) NULL,
	[ringdna105__Called_Back__c] [varchar](5) NULL,
	[ringdna105__CallObject__c] [nvarchar](510) NULL,
	[ringdna105__Campaign__c] [nchar](36) NULL,
	[ringdna105__Contact__c] [nchar](36) NULL,
	[ringdna105__Created_by_RingDNA__c] [varchar](5) NULL,
	[ringdna105__Description__c] [nvarchar](max) NULL,
	[ringdna105__From_Number__c] [nvarchar](80) NULL,
	[ringdna105__Initiating_Record_ID__c] [nvarchar](510) NULL,
	[ringdna105__Lead__c] [nchar](36) NULL,
	[ringdna105__Local_Presence__c] [varchar](5) NULL,
	[ringdna105__Local_Presence_Num__c] [nvarchar](80) NULL,
	[ringdna105__Local_Presence_Num_Dialed__c] [nvarchar](510) NULL,
	[ringdna105__Local_Presence_Num_Dialed_Type__c] [nvarchar](510) NULL,
	[ringdna105__Local_Presence_Routing__c] [nvarchar](510) NULL,
	[ringdna105__Opportunity__c] [nchar](36) NULL,
	[ringdna105__OwnerId__c] [nchar](36) NULL,
	[ringdna105__Queue__c] [nvarchar](510) NULL,
	[ringdna105__Queue_Hold_Time__c] [decimal](18, 0) NULL,
	[ringdna105__Status__c] [nvarchar](510) NULL,
	[ringdna105__Subject__c] [nvarchar](510) NULL,
	[ringdna105__Subject_Link__c] [nvarchar](2600) NULL,
	[ringdna105__Supervisor_Notes__c] [nvarchar](max) NULL,
	[ringdna105__To_Number__c] [nvarchar](80) NULL,
	[ringdna105__Voicemail__c] [varchar](5) NULL,
	[SystemModstamp] [datetime2](7) NULL,
	[Time_of_day__c] [decimal](18, 2) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED INDEX
	(
		[Id] ASC
	)
)

