CREATE TABLE [SrcSFDC].[ServiceContract] (
    [LZBatchID]               INT              NOT NULL,
    [ADLSBatchID]             INT              NOT NULL,
    [ADLSTimestamp]           DATETIME2 (0)    NOT NULL,
    [AccountId]               NCHAR (36)       NULL,
    [ActivationDate]          DATETIME2 (7)    NULL,
    [ApprovalStatus]          NVARCHAR (80)    NULL,
    [BillingCity]             NVARCHAR (80)    NULL,
    [BillingCountry]          NVARCHAR (160)   NULL,
    [BillingCountryCode]      NVARCHAR (20)    NULL,
    [BillingGeocodeAccuracy]  NVARCHAR (510)   NULL,
    [BillingLatitude]         DECIMAL (18, 15) NULL,
    [BillingLongitude]        DECIMAL (18, 15) NULL,
    [BillingPostalCode]       NVARCHAR (40)    NULL,
    [BillingState]            NVARCHAR (160)   NULL,
    [BillingStateCode]        NVARCHAR (20)    NULL,
    [BillingStreet]           NVARCHAR (510)   NULL,
    [ContactId]               NCHAR (36)       NULL,
    [ContractNumber]          NVARCHAR (60)    NULL,
    [CreatedById]             NCHAR (36)       NULL,
    [CreatedDate]             DATETIME2 (7)    NOT NULL,
    [CurrencyIsoCode]         NVARCHAR (6)     NOT NULL,
    [Description]             NVARCHAR (4000)  NULL,
    [Discount]                DECIMAL (18, 2)  NULL,
    [EndDate]                 DATETIME2 (7)    NULL,
    [GrandTotal]              DECIMAL (18, 2)  NULL,
    [Id]                      NCHAR (18)       NOT NULL,
    [IsDeleted]               BIT              NOT NULL,
    [LastModifiedById]        NCHAR (36)       NULL,
    [LastModifiedDate]        DATETIME2 (7)    NOT NULL,
    [LastReferencedDate]      DATETIME2 (7)    NULL,
    [LastViewedDate]          DATETIME2 (7)    NULL,
    [LineItemCount]           INT              NULL,
    [Name]                    NVARCHAR (510)   NOT NULL,
    [OwnerId]                 NCHAR (36)       NOT NULL,
    [Pricebook2Id]            NCHAR (36)       NULL,
    [ShippingCity]            NVARCHAR (80)    NULL,
    [ShippingCountry]         NVARCHAR (160)   NULL,
    [ShippingCountryCode]     NVARCHAR (20)    NULL,
    [ShippingGeocodeAccuracy] NVARCHAR (510)   NULL,
    [ShippingHandling]        DECIMAL (18, 2)  NULL,
    [ShippingLatitude]        DECIMAL (18, 15) NULL,
    [ShippingLongitude]       DECIMAL (18, 15) NULL,
    [ShippingPostalCode]      NVARCHAR (40)    NULL,
    [ShippingState]           NVARCHAR (160)   NULL,
    [ShippingStateCode]       NVARCHAR (20)    NULL,
    [ShippingStreet]          NVARCHAR (510)   NULL,
    [SpecialTerms]            NVARCHAR (4000)  NULL,
    [StartDate]               DATETIME2 (7)    NULL,
    [Status]                  NVARCHAR (510)   NULL,
    [Subtotal]                DECIMAL (18, 2)  NULL,
    [SystemModstamp]          DATETIME2 (7)    NOT NULL,
    [Tax]                     DECIMAL (18, 2)  NULL,
    [Term]                    INT              NULL,
    [TotalPrice]              DECIMAL (18, 2)  NULL,
    [Type__c]                 NVARCHAR (64)    NULL,
    [ParentServiceContractId]         NCHAR (36)       NULL, 
    [Scanner_Serial_Number__c] NVARCHAR (200)   NULL,
    [Ship_To_Account__c]      NCHAR (36)       NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));


