CREATE TABLE [SrcSFDC].[Study_club__c]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Approved_By__c] [nvarchar](100) NULL,
	[Area__c] [nvarchar](255) NULL,
	[Area_Sales_Director__c] [nvarchar](1300) NULL,
	[ConnectionReceivedId] [nchar](18) NULL,
	[ConnectionSentId] [nchar](18) NULL,
	[CreatedById] [nchar](18) NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[CurrencyIsoCode] [nvarchar](3) NOT NULL,
	[Doctor_Fee__c] [nvarchar](255) NULL,
	[Estimated_Banquet_Expenses__c] [decimal](18, 2) NULL,
	[Event_City__c] [nvarchar](80) NULL,
	[Event_Country__c] [nvarchar](100) NULL,
	[Event_Date__c] [datetime2](7) NULL,
	[Event_Duration__c] [nvarchar](255) NULL,
	[Event_End_Time__c] [datetime2](7) NULL,
	[Event_Start_Time__c] [datetime2](7) NULL,
	[Event_State__c] [nvarchar](255) NULL,
	[Event_Status__c] [nvarchar](255) NULL,
	[Event_Time__c] [nvarchar](18) NULL,
	[Honorarium__c] [nvarchar](255) NULL,
	[Honorarium_Fee_confirm_amt_if_using_max__c] [decimal](18, 2) NULL,
	[Id] [nchar](18) NOT NULL,
	[Invitation_Only__c] [varchar](8) NULL,
	[IsDeleted] [varchar](5) NOT NULL,
	[LastModifiedById] [nchar](18) NULL,
	[LastModifiedDate] [datetime2](7) NOT NULL,
	[LastReferencedDate] [datetime2](7) NULL,
	[LastViewedDate] [datetime2](7) NULL,
	[Link_to_event_roster__c] [nvarchar](255) NULL,
	[Name] [nvarchar](80) NULL,
	[New_Speaker_Needs_to_be_Onboarded__c] [varchar](5) NULL,
	[Number_of_Attendees__c] [decimal](18, 0) NULL,
	[Number_of_CEs__c] [decimal](18, 0) NULL,
	[OwnerId] [nchar](18) NOT NULL,
	[Pilot_for_ClinEd_Event__c] [varchar](5) NULL,
	[Presentation_Approved__c] [nvarchar](255) NULL,
	[Presentation_Audience__c] [nvarchar](max) NULL,
	[Region_Manager_2__c] [nvarchar](100) NULL,
	[Regional_Manager__c] [nvarchar](1300) NULL,
	[Registration_Link__c] [nvarchar](255) NULL,
	[Revenue_Code_from_Active__c] [nvarchar](80) NULL,
	[Speaker__c] [nvarchar](255) NULL,
	[Speaker_Agreement_on_File__c] [nvarchar](255) NULL,
	[Speaker_Country__c] [nvarchar](255) NULL,
	[Speaker_Fee__c] [decimal](18, 0) NULL,
	[Speaker_First_Name__c] [nvarchar](80) NULL,
	[Speaker_Last_Name__c] [nvarchar](80) NULL,
	[Speaker_Type__c] [nvarchar](255) NULL,
	[Special_notes_or_instructions__c] [nvarchar](255) NULL,
	[Staff_Fee__c] [nvarchar](255) NULL,
	[Status__c] [nvarchar](255) NULL,
	[Study_Club_Category__c] [nvarchar](255) NULL,
	[Study_Club_Code__c] [nvarchar](30) NULL,
	[Study_Club_Format__c] [nvarchar](255) NULL,
	[Study_Club_Processed__c] [nvarchar](255) NULL,
	[Study_Club_Sub_Category__c] [nvarchar](255) NULL,
	[SystemModstamp] [datetime2](7) NOT NULL,
	[Type_of_event_to_determine_fee_structure__c] [nvarchar](255) NULL,
	[Venue_Address__c] [nvarchar](255) NULL,
	[Venue_Name__c] [nvarchar](150) NULL,
	[Zipcode__c] [nvarchar](10) NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	HEAP
)
GO