CREATE TABLE [SrcSFDC].[Training_Records__c] (
    [LZBatchID]                INT             NOT NULL,
    [ADLSBatchID]              INT             NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)   NOT NULL,
    [Account_Number__c]        NVARCHAR (10)   NULL,
    [CE_Hours__c]              DECIMAL (18, 1) NULL,
    [City__c]                  NVARCHAR (80)   NULL,
    [Comments__c]              NVARCHAR (255)  NULL,
    [ContactID__c]             NCHAR (18)      NULL,
    [Country__c]               NVARCHAR (40)   NULL,
    [CreatedDate]              DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]          NVARCHAR (3)    NOT NULL,
    [Event__c]                 NCHAR (18)      NULL,
    [Event_Date__c]            DATETIME2 (7)   NULL,
    [Event_Name__c]            NVARCHAR (1300) NULL,
    [Event_Type__c]            NVARCHAR (50)   NULL,
    [External_Campaign_Id__c]  NVARCHAR (255)  NULL,
    [Feedback__c]              NVARCHAR (255)  NULL,
    [Id]                       NCHAR (18)      NOT NULL,
    [Is_Points_Accrued__c]     BIT             NULL,
    [IsDeleted]                BIT             NOT NULL,
    [JDE_Location_Id__c]       NVARCHAR (10)   NULL,
    [LastModifiedById]         NCHAR (18)      NULL,
    [LastModifiedDate]         DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]       DATETIME2 (7)   NULL,
    [LastViewedDate]           DATETIME2 (7)   NULL,
    [Location_Description__c]  NVARCHAR (255)  NULL,
    [Name]                     NVARCHAR (80)   NULL,
    [Opt_Out_of_NCP__c]        BIT             NULL,
    [Promotion_Eligibility__c] BIT             NULL,
    [Speaker__c]               NVARCHAR (120)  NULL,
    [State__c]                 NVARCHAR (40)   NULL,
    [Study_Club__c]            NCHAR (18)      NULL,
    [SystemModstamp]           DATETIME2 (7)   NOT NULL,
    [Training_Location__c]     NCHAR (18)      NULL,
    [Training_Status__c]       NVARCHAR (255)  NULL,
    [Tuition_Fee__c]           DECIMAL (18)    NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

