CREATE TABLE [SrcSFDC].[Treatment__c] (
    [LZBatchID]                               INT                                             NOT NULL,
    [ADLSBatchID]                             INT                                             NOT NULL,
    [ADLSTimestamp]                           DATETIME2 (0)                                   NOT NULL,
    [Account__c]                              NCHAR (18)                                      NULL,
    [Additional_Aligner_Coverage_Date__c]     DATETIME2 (7)                                   NULL,
    [Additional_Aligner_Enabled__c]           BIT                                             NULL,
    [Adj_CCD_Date__c]                         DATETIME2 (7)                                   NULL,
    [ConnectionReceivedId]                    NCHAR (18)                                      NULL,
    [ConnectionSentId]                        NCHAR (18)                                      NULL,
    [Contact__c]                              NCHAR (18)                                      NULL,
    [CreatedById]                             NCHAR (18)                                      NULL,
    [CreatedDate]                             DATETIME2 (7)                                   NOT NULL,
    [CurrencyIsoCode]                         NVARCHAR (3)                                    NOT NULL,
    [DiscCode_Eligible_for_Free_Retainers__c] NVARCHAR (255)                                  NULL,
    [Doctor_Changed_Metal_Braces__c]          BIT                                             NULL,
    [EligibleFreeAA__c]                       DECIMAL (18)                                    NULL,
    [Estimated_Treatment_End_Date__c]         DATETIME2 (7)                                   NULL,
    [Id]                                      NCHAR (18)                                      NOT NULL,
    [IsDeleted]                               BIT                                             NOT NULL,
    [LastModifiedById]                        NCHAR (18)                                      NULL,
    [LastModifiedDate]                        DATETIME2 (7)                                   NOT NULL,
    [LastReferencedDate]                      DATETIME2 (7)                                   NULL,
    [LastViewedDate]                          DATETIME2 (7)                                   NULL,
    [MCC_Count__c]                            DECIMAL (18)                                    NULL,
    [Name]                                    NVARCHAR (80)                                   NULL,
    [Number_of_Additional_Aligners_Left__c]   DECIMAL (18, 2)                                 NULL,
    [Number_of_Free_Retainers_Remaining__c]   DECIMAL (18)                                    NULL,
    [Number_of_Refinements_Used__c]           DECIMAL (18)                                    NULL,
    [Number_of_Replacements_Used__c]          DECIMAL (18)                                    NULL,
    [Number_of_Retainers_Used__c]             DECIMAL (18)                                    NULL,
    [Patient__c]                              NCHAR (18)                                      NULL,
    [Refinement_Fee_Date__c]                  DATETIME2 (7)                                   NULL,
    [RFD_Adj_Date__c]                         DATETIME2 (7)                                   NULL,
    [Staff_Discount__c]                       BIT                                             NULL,
    [SystemModstamp]                          DATETIME2 (7)                                   NOT NULL,
    [TED_Adj_Date__c]                         DATETIME2 (7)                                   NULL,
    [Treated_Arches__c]                       NVARCHAR (255)                                  NULL,
    [Treatment_Closed_Date__c]                DATETIME2 (7)                                   NULL,
    [Treatment_Completion_Date__c]            DATETIME2 (7)                                   NULL,
    [Treatment_Expiration_Date__c]            DATETIME2 (7)                                   NULL,
    [Treatment_Id__c]                         NVARCHAR (40)                                   NULL,
    [Treatment_Start_Date__c]                 DATETIME2 (7)                                   NULL,
    [Treatment_Type__c]                       NVARCHAR (255)                                  NULL,
    [Number_of_Additional_Aligners_Used__c]   DECIMAL (18)                                    NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

