CREATE TABLE [SrcSFDC].[User] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [City]                 NVARCHAR (80)  NULL,
    [ContactId]            NCHAR (36)     NULL,
    [Country]              NVARCHAR (160) NULL,
    [CountryCode]          NVARCHAR (20)  NULL,
    [CreatedById]          NCHAR (36)     NULL,
    [CreatedDate]          DATETIME2 (7)  NOT NULL,
    [Email]                NVARCHAR (256) NOT NULL,
    [Hire_Date__c]         DATETIME2 (7)  NULL,
    [Id]                   NCHAR (18)     NOT NULL,
    [IsActive]             BIT            NOT NULL,
    [LastLoginDate]        DATETIME2 (7)  NULL,
    [LastModifiedById]     NCHAR (36)     NULL,
    [LastModifiedDate]     DATETIME2 (7)  NOT NULL,
    [LastName]             NVARCHAR (160) NOT NULL,
    [Name]                 NVARCHAR (242) NOT NULL,
    [Phone]                NVARCHAR (80)  NULL,
    [PostalCode]           NVARCHAR (40)  NULL,
    [UserRoleId]           NCHAR (36)     NULL,
    [UserType]             NVARCHAR (80)  NULL,
    [ManagerId]            VARCHAR (18)   NULL,
    [AccountId]            VARCHAR (18)   NULL,
    [Street]               NVARCHAR (255) NULL,
    [Alias]                NVARCHAR (10)  NULL,
    [CompanyName]          NVARCHAR (80)  NULL,
    [Department]           NVARCHAR (80)  NULL,
    [Division]             NVARCHAR (80)  NULL,
    [EmployeeNumber]       NVARCHAR (20)  NULL,
    [FirstName]            NVARCHAR (40)  NULL,
    [Is_iTero_Rep__c]      BIT            NULL,
    [Region__c]            NVARCHAR (100) NULL,
    [Role_On_Territory__c] NVARCHAR (255) NULL,
    [State]                NVARCHAR (80)  NULL,
    [Title]                NVARCHAR (80)  NULL,
    [Username]             NVARCHAR (80)  NULL,
    [AlignSalesRepId__c]   NVARCHAR (10)  NULL,
    [FederationIdentifier] NVARCHAR (512) NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

