CREATE TABLE [SrcSFDC].[VCT_Training__C] (
    [LZBatchID]                    INT             NOT NULL,
    [ADLSBatchID]                  INT             NOT NULL,
    [ADLSTimestamp]                DATETIME2 (0)   NOT NULL,
    [Additional_Topics_Covered__c] NVARCHAR (255)  NULL,
    [Basic__c]                     BIT             NULL,
    [Case__c]                      NCHAR (18)      NULL,
    [Clinic_Proficiency__c]        NVARCHAR (255)  NULL,
    [Completed__c]                 BIT             NULL,
    [ConnectionReceivedId]         NCHAR (18)      NULL,
    [ConnectionSentId]             NCHAR (18)      NULL,
    [CreatedById]                  NCHAR (18)      NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]              NVARCHAR (3)    NOT NULL,
    [FOC__c]                       BIT             NULL,
    [Id]                           NCHAR (18)      NOT NULL,
    [Invisalign__c]                BIT             NULL,
    [IsDeleted]                    BIT             NOT NULL,
    [Issues_Encountered__c]        NVARCHAR (255)  NULL,
    [LastActivityDate]             DATETIME2 (7)   NULL,
    [LastModifiedById]             NCHAR (18)      NULL,
    [LastModifiedDate]             DATETIME2 (7)   NOT NULL,
    [Method_of_Training__c]        NVARCHAR (255)  NULL,
    [Modules_Completed__c]         NVARCHAR (MAX)  NULL,
    [Name]                         NVARCHAR (80)   NULL,
    [no_of_Participants__c]        DECIMAL (18)    NULL,
    [Note_Invisalign__c]           NVARCHAR (255)  NULL,
    [Note_Ortho__c]                NVARCHAR (255)  NULL,
    [Note_Restorative__c]          NVARCHAR (255)  NULL,
    [Note_Tools__c]                NVARCHAR (255)  NULL,
    [Notes__c]                     NVARCHAR (255)  NULL,
    [Notes_Other_SW__c]            NVARCHAR (255)  NULL,
    [Onsite__c]                    BIT             NULL,
    [Ortho__c]                     BIT             NULL,
    [Other_SW__c]                  BIT             NULL,
    [Other_Training_Options__c]    NVARCHAR (MAX)  NULL,
    [Participant_Names__c]         NVARCHAR (200)  NULL,
    [RecordTypeId]                 NCHAR (18)      NULL,
    [Region__c]                    NVARCHAR (255)  NULL,
    [Restorative__c]               BIT             NULL,
    [Staff_Trained__c]             NVARCHAR (200)  NULL,
    [Status__c]                    NVARCHAR (255)  NULL,
    [SystemModstamp]               DATETIME2 (7)   NOT NULL,
    [Time_1__c]                    DECIMAL (18)    NULL,
    [Tools__c]                     BIT             NULL,
    [Total_Time__c]                DECIMAL (18, 1) NULL,
    [Total_Time_New__c]            DECIMAL (18, 1) NULL,
    [Total_Time_Picklist__c]       NVARCHAR (255)  NULL,
    [Trainer__c]                   NVARCHAR (100)  NULL,
    [Trainer_Look_up__c]           NCHAR (18)      NULL,
    [Training_Notes__c]            NVARCHAR (MAX)  NULL,
    [Type__c]                      NVARCHAR (255)  NULL,
    [VCT_Trainer__c]               NVARCHAR (255)  NULL,
    [VCT_Training_Date__c]         DATETIME2 (7)   NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

