CREATE TABLE [SrcSFDC].[Zip_Code_Territory__c] (
    [LZBatchID]               INT              NOT NULL,
    [ADLSBatchID]             INT              NOT NULL,
    [ADLSTimestamp]           DATETIME2 (0)    NOT NULL,
    [ACC__c]                  DECIMAL (18, 10) NULL,
    [ACCA__c]                 DECIMAL (18, 10) NULL,
    [Account__c]              NCHAR (18)       NULL,
    [AGR__c]                  DECIMAL (18, 10) NULL,
    [ASM__c]                  NVARCHAR (80)    NULL,
    [ASM_ID__c]               NVARCHAR (20)    NULL,
    [ASM_name__c]             NVARCHAR (1300)  NULL,
    [ASMs__c]                 NVARCHAR (1300)  NULL,
    [CCA__c]                  DECIMAL (18, 10) NULL,
    [ConnectionReceivedId]    NCHAR (18)       NULL,
    [ConnectionSentId]        NCHAR (18)       NULL,
    [Contact__c]              NCHAR (18)       NULL,
    [Country__c]              NVARCHAR (255)   NULL,
    [CreatedById]             NCHAR (18)       NULL,
    [CreatedDate]             DATETIME2 (7)    NOT NULL,
    [CurrencyIsoCode]         NVARCHAR (3)     NOT NULL,
    [Friendly_Name__c]        NVARCHAR (50)    NULL,
    [GM__c]                   NVARCHAR (80)    NULL,
    [GM_ID__c]                NVARCHAR (20)    NULL,
    [GM_Name__c]              NVARCHAR (1300)  NULL,
    [GMs__c]                  NVARCHAR (1300)  NULL,
    [Id]                      NCHAR (18)       NOT NULL,
    [IsDeleted]               VARCHAR (5)      NOT NULL,
    [iTero__c]                DECIMAL (18, 10) NULL,
    [iTero_Achieved__c]       DECIMAL (18, 10) NULL,
    [Itero_Territory_Code__c] NVARCHAR (30)    NULL,
    [LastModifiedById]        NCHAR (18)       NULL,
    [LastModifiedDate]        DATETIME2 (7)    NOT NULL,
    [LastReferencedDate]      DATETIME2 (7)    NULL,
    [LastViewedDate]          DATETIME2 (7)    NULL,
    [Legacy_SF_ID__c]         NVARCHAR (18)    NULL,
    [Mobile_Office__c]        VARCHAR (5)      NULL,
    [Name]                    NVARCHAR (80)    NULL,
    [No_of_Accounts__c]       DECIMAL (18, 10) NULL,
    [NR__c]                   DECIMAL (18, 10) NULL,
    [NUME_Territory_Code__c]  NVARCHAR (100)   NULL,
    [OwnerId]                 NCHAR (18)       NOT NULL,
    [PCS_DocLoc_Model__c]     VARCHAR (5)      NULL,
    [PCS_Finance__c]          VARCHAR (5)      NULL,
    [PCS_Territory__c]        NVARCHAR (100)   NULL,
    [Postal_Code__c]          NVARCHAR (MAX)   NULL,
    [Region__c]               NVARCHAR (100)   NULL,
    [SA_Territory__c]         NVARCHAR (100)   NULL,
    [Scan_Shop_Eligible__c]   VARCHAR (5)      NULL,
    [SVP__c]                  NVARCHAR (80)    NULL,
    [SystemModstamp]          DATETIME2 (7)    NOT NULL,
    [TAG__c]                  NVARCHAR (30)    NULL,
    [Territory_Code__c]       NVARCHAR (100)   NULL,
    [Territory_Manger__c]     NCHAR (18)       NULL,
    [TM__c]                   NVARCHAR (80)    NULL,
    [TM_ID__c]                NVARCHAR (20)    NULL,
    [TM_Name__c]              NVARCHAR (1300)  NULL,
    [TMs__c]                  NVARCHAR (1300)  NULL,
    [VP__c]                   NVARCHAR (80)    NULL,
    [VP_ID__c]                NVARCHAR (20)    NULL,
    [VP_Name__c]              NVARCHAR (1300)  NULL,
    [VPs__c]                  NVARCHAR (1300)  NULL,
    [Zip_Code__c]             NVARCHAR (20)    NULL
)
WITH (CLUSTERED INDEX([Id]), DISTRIBUTION = HASH([Id]));

