CREATE TABLE [SrcInvisalignAccessories].[spree_orders] (
    [LZBatchID]                    INT             NOT NULL,
    [ADLSBatchID]                  INT             NOT NULL,
    [ADLSTimestamp]                DATETIME2 (0)   NOT NULL,
    [id]                           INT             NOT NULL,
    [number]                       NVARCHAR (32)   NULL,
    [item_total]                   NUMERIC (10, 2) NOT NULL,
    [total]                        NUMERIC (10, 2) NOT NULL,
    [state]                        NVARCHAR (256)  NULL,
    [adjustment_total]             NUMERIC (10, 2) NOT NULL,
    [user_id]                      INT             NULL,
    [completed_at]                 DATETIME2 (7)   NULL,
    [bill_address_id]              INT             NULL,
    [ship_address_id]              INT             NULL,
    [payment_total]                NUMERIC (10, 2) NULL,
    [shipment_state]               NVARCHAR (256)  NULL,
    [payment_state]                NVARCHAR (256)  NULL,
    [email]                        NVARCHAR (256)  NULL,
    [special_instructions]         NVARCHAR (MAX)  NULL,
    [created_at]                   DATETIME2 (7)   NOT NULL,
    [updated_at]                   DATETIME2 (7)   NOT NULL,
    [currency]                     NVARCHAR (256)  NULL,
    [last_ip_address]              NVARCHAR (256)  NULL,
    [created_by_id]                INT             NULL,
    [shipment_total]               NUMERIC (10, 2) NOT NULL,
    [additional_tax_total]         NUMERIC (10, 2) NULL,
    [promo_total]                  NUMERIC (10, 2) NULL,
    [channel]                      NVARCHAR (256)  NULL,
    [included_tax_total]           NUMERIC (10, 2) NOT NULL,
    [item_count]                   INT             NULL,
    [approver_id]                  INT             NULL,
    [approved_at]                  DATETIME2 (7)   NULL,
    [confirmation_delivered]       BIT             NULL,
    [considered_risky]             BIT             NULL,
    [token]                        NVARCHAR (256)  NULL,
    [canceled_at]                  DATETIME2 (7)   NULL,
    [canceler_id]                  INT             NULL,
    [store_id]                     INT             NULL,
    [state_lock_version]           INT             NOT NULL,
    [taxable_adjustment_total]     NUMERIC (10, 2) NOT NULL,
    [non_taxable_adjustment_total] NUMERIC (10, 2) NOT NULL,
    [ga_tracked]                   BIT             NULL
)
WITH (CLUSTERED INDEX([id]), DISTRIBUTION = ROUND_ROBIN);

