CREATE VIEW [TABSAP].[DimSales Document] AS SELECT [ADLSTimestamp]
      ,[PartitionColumn]
      ,[Sales Document]
      ,[Sales Document Item]
      ,[OrderQuantity]
      ,[Sales Document Type]
      ,[Sales Document Category]
      ,[Item Category-Sales Document]
      ,[Billing Type]
      ,[Age Tier]
      ,[Order Stages]
      ,[Stage Bucket]
      ,[PatientType]
      ,[ProductType]
      ,[TreatingDoctor]
      ,[ShipTo]
      ,[SoldTo]
      ,[CCADate]
      ,[TreatmentCategory]
      ,[TreatmentLocation]
      ,[ClinID]
      ,[Is IO Scan]
      ,[Professional Category]
      ,[Advantage Tier]
      ,[Advantage Program Name]
      ,[MAF]
      ,[Sales Org]
      ,[Division]
      ,[Sales Order Key]
      ,[Compliance Indicator]
      ,[Free_Paid]
      ,[PO Number]
      ,[Treatment Option]
      ,[Deliverable Type]
      ,[IDSOrderID]
      ,[SFDCOrderID]
      ,[Material Group]
      ,[Material Number]
      ,[Material Group 1]
      ,[Material Group 2]
      ,[Material Group 3]
      ,[Material Group 4]
      ,[Material Group 5]
      ,[Distribution Channel]
      ,[Sales Group]
      ,[Sales Office]
      ,[Controlling Area]
      ,[Purchasing Org]
      ,[Base Unit of Measure]
      ,[Sales Unit]
      ,[Unit of Dimension for length/Width/Height]
      ,[Volume Unit]
      ,[Weight Unit]
      ,[Bill-to party]
      ,[Payer]
      ,[Country of ship-to party]
      ,[Customer Group1]
      ,[Customer Group2]
      ,[Customer Group3]
      ,[Customer Group4]
      ,[Customer Group5]
      ,[Equipment Serial Num]
      ,[Initiator Company Id]
      ,[AMR Date COPA]
      ,[Promotion Bucket]
      ,[Revenue Recognition]
      ,[Total Quantity]
      ,[Document Date]
      ,[Document Year]
      ,[UpperAlignerStartstage]
      ,[UpperAlignerEndStage]
      ,[LowerAlignerStartstage]
      ,[LowerAlignerEndStage]
      ,[CustomerGroupType]
      ,[IsDSOOrder]
      ,[Storage Location]
      ,[Align Retail]
      ,[Employee Responsible]
      ,[Financial Contact]
      ,[Junior Doctor]
      ,[Submitting Student]
      ,[Territory Manager]
      ,[AgeTierRange]
      ,[AgeTierDetail]
      ,[AgeSegment]
      ,[AgeCategory]
      ,[Material Text]
      ,[Bill-to party text]
      ,[ShipTo Text]
      ,[SoldTo Text]
      ,[TreatmentId]
      ,[Order Quantity]
  FROM [DWSAP].[DimSalesDocument];