CREATE VIEW [TABSAP].[DimTime] AS SELECT [SKDate]
      ,[KeyDate]
      ,[Date]
      ,[CalendarDay]
      ,[CalendarMonth]
      ,[CalendarQuarter]
      ,[CalendarYear]
      ,[DayNameLong]
      ,[DayNameShort]
      ,[DayNumberOfWeek]
      ,[DayNumberOfYear]
      ,[DaySuffix]
      ,'K4' [Fiscal Year Variant]
      ,CONCAT([CalendarYear],[CalendarQuarter]) [Calendar Year/Quarter]
      ,CONCAT([CalendarYear],DATEPART(week,KeyDate)) [Calendar Year/Week]
      ,DATEPART(week,KeyDate) as [Fiscal Week]
      ,MONTH(KeyDate) AS [Fiscal Period]
      ,CONCAT('Q', DATEPART ( quarter ,[Date] )) as [FiscalQuarter]
      ,Year(KeyDate) AS [Fiscal Year]
	  ,CONCAT(YEAR(KeyDate), MONTH(KeyDate)) AS [Fiscal Year/PeriodSort]
	  ,CONCAT([QuarterNameShort],' ',YEAR(KeyDate)) AS [Fiscal Year/Quarter]
	  ,CASE 
	  	WHEN MONTH(KeyDate)<=9 THEN CONCAT(YEAR(KeyDate),'-', 0,MONTH(KeyDate))
	  	WHEN MONTH(KeyDate)>=10 THEN CONCAT(YEAR(KeyDate), '-',MONTH(KeyDate))
	  	END [Fiscal Year/Period]
      ,[FirstDayOfMonth]
      ,[FirstDayOfQuarter]
      ,[FirstDayOfWeek]
      ,[FirstDayOfYear]
      ,[HolidayName]
      ,[IsHoliday]
      ,[IsLastDayOfMonth]
      ,[IsWeekday]
      ,[LastDayOfMonth]
      ,[LastDayOfQuarter]
      ,[LastDayOfWeek]
      ,[LastDayOfYear]
      ,[MonthNameLong]
      ,[MonthNameShort]
      ,[MonthYear]
      ,[QuarterNameLong]
      ,[QuarterNameShort]
      ,[WeekOfMonth]
      ,[WeekOfYear]
      ,CONCAT(CalendarYear,'-',CASE WHEN CalendarMonth <= 6 then 'H1' else 'H2' end) [FiscalHalfYear]
      ,CONCAT(CalendarYear,'-', QuarterNameShort) [Year/Quarter]
      ,CAST (CONCAT(CalendarYear,CalendarQuarter) as int )  as [FiscalYearQuarterSort] 
	  FROM [DW].[DimDate]
	  WHERE [MonthNameLong] <> 'NA' and [CalendarYear] > '2015' AND [CalendarYear] <= YEAR (GETDATE());