CREATE TABLE [SrcMES_FAB_MX2].[APP_GROUP] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [group_key]            BIGINT         NOT NULL,
    [group_name]           NVARCHAR (64)  NOT NULL,
    [display_name]         NVARCHAR (64)  NULL,
    [privilege]            INT            NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [creator_key]          BIGINT         NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modifier_key]    BIGINT         NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [xfr_insert_pid]       INT            NOT NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [xfr_update_pid]       INT            NOT NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [email_address]        NVARCHAR (255) NULL,
    [update_privilege_key] BIGINT         NULL,
    [delete_privilege_key] BIGINT         NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [udt_0]                DATETIME       NULL,
    [udt_0_u]              DATETIME       NULL,
    [udt_0_z]              NVARCHAR (64)  NULL,
    [udt_1]                DATETIME       NULL,
    [udt_1_u]              DATETIME       NULL,
    [udt_1_z]              NVARCHAR (64)  NULL,
    [udt_2]                DATETIME       NULL,
    [udt_2_u]              DATETIME       NULL,
    [udt_2_z]              NVARCHAR (64)  NULL,
    [shift_key]            BIGINT         NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

