CREATE TABLE [SrcMES_FAB_MX2].[APP_USER] (
    [LZBatchID]                  INT            NOT NULL,
    [ADLSBatchID]                INT            NOT NULL,
    [ADLSTimestamp]              DATETIME2 (0)  NOT NULL,
    [user_key]                   BIGINT         NOT NULL,
    [user_name]                  NVARCHAR (64)  NOT NULL,
    [first_name]                 NVARCHAR (64)  NULL,
    [last_name]                  NVARCHAR (64)  NULL,
    [description]                NVARCHAR (255) NULL,
    [category]                   NVARCHAR (50)  NULL,
    [password_modifiable]        INT            NOT NULL,
    [status]                     NVARCHAR (50)  NOT NULL,
    [status_change_time]         DATETIME       NOT NULL,
    [status_change_time_u]       DATETIME       NULL,
    [status_change_time_z]       NVARCHAR (64)  NULL,
    [password]                   NVARCHAR (64)  NOT NULL,
    [form_key]                   BIGINT         NULL,
    [image_key]                  BIGINT         NULL,
    [note_key]                   BIGINT         NULL,
    [user_expiration]            DATETIME       NULL,
    [user_expiration_u]          DATETIME       NULL,
    [user_expiration_z]          NVARCHAR (64)  NULL,
    [password_expiration]        DATETIME       NULL,
    [password_expiration_u]      DATETIME       NULL,
    [password_expiration_z]      NVARCHAR (64)  NULL,
    [password_duration]          INT            NULL,
    [password_history]           NVARCHAR (255) NULL,
    [creator_key]                BIGINT         NOT NULL,
    [creation_time]              DATETIME       NOT NULL,
    [creation_time_u]            DATETIME       NULL,
    [creation_time_z]            NVARCHAR (64)  NULL,
    [last_modifier_key]          BIGINT         NOT NULL,
    [last_modified_time]         DATETIME       NOT NULL,
    [last_modified_time_u]       DATETIME       NULL,
    [last_modified_time_z]       NVARCHAR (64)  NULL,
    [login_count]                INT            NULL,
    [email_address]              NVARCHAR (255) NULL,
    [uda_0]                      NVARCHAR (255) NULL,
    [uda_1]                      NVARCHAR (255) NULL,
    [uda_2]                      NVARCHAR (255) NULL,
    [uda_3]                      NVARCHAR (255) NULL,
    [uda_4]                      NVARCHAR (255) NULL,
    [xfr_insert_pid]             INT            NULL,
    [pd_xfr_update_pid]          INT            NOT NULL,
    [src_xfr_update_pid]         INT            NOT NULL,
    [xfr_update_pid]             INT            NULL,
    [security_mask]              NVARCHAR (64)  NULL,
    [failed_login_attempt_count] INT            NOT NULL,
    [trx_id]                     CHAR (38)      NOT NULL,
    [security_realm]             NVARCHAR (64)  NOT NULL,
    [unused_privilege]           INT            NULL,
    [update_privilege_key]       BIGINT         NULL,
    [delete_privilege_key]       BIGINT         NULL,
    [shift_key]                  BIGINT         NULL,
    [purged]                     INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

