CREATE TABLE [SrcMES_FAB_MX2].[AT_AT_PilotSupport] (
    [LZBatchID]                  INT            NOT NULL,
    [ADLSBatchID]                INT            NOT NULL,
    [ADLSTimestamp]              DATETIME2 (0)  NOT NULL,
    [atr_key]                    BIGINT         NOT NULL,
    [atr_name]                   NVARCHAR (64)  NOT NULL,
    [purge_status]               INT            NULL,
    [creation_time]              DATETIME       NULL,
    [creation_time_u]            DATETIME       NULL,
    [creation_time_z]            NVARCHAR (64)  NULL,
    [last_modified_time]         DATETIME       NULL,
    [last_modified_time_u]       DATETIME       NULL,
    [last_modified_time_z]       NVARCHAR (64)  NULL,
    [xfr_insert_pid]             INT            NULL,
    [xfr_update_pid]             INT            NULL,
    [trx_id]                     CHAR (38)      NOT NULL,
    [parent_key]                 BIGINT         NULL,
    [pd_xfr_update_pid]          INT            NULL,
    [src_xfr_update_pid]         INT            NULL,
    [description_S]              NVARCHAR (250) NULL,
    [fab_checklist_8]            BIGINT         NULL,
    [fab_cluster_S]              NVARCHAR (50)  NULL,
    [fab_instruction_S]          NVARCHAR (250) NULL,
    [ids_id_S]                   NVARCHAR (10)  NULL,
    [label_bag_S]                NVARCHAR (100) NULL,
    [label_box_S]                NVARCHAR (100) NULL,
    [name_S]                     NVARCHAR (100) NULL,
    [pilot_status_Y]             TINYINT        NULL,
    [treat_additional_process_Y] TINYINT        NULL,
    [treat_instruction_S]        NVARCHAR (250) NULL,
    [user_name_S]                NVARCHAR (80)  NULL,
    [purged]                     INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

