CREATE TABLE [SrcMES_FAB_MX2].[PARAMETER] (
    [LZBatchID]            INT             NOT NULL,
    [ADLSBatchID]          INT             NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)   NOT NULL,
    [parameter_key]        BIGINT          NOT NULL,
    [owner_key]            BIGINT          NOT NULL,
    [owner_type]           INT             NOT NULL,
    [parameter_name]       NVARCHAR (64)   NOT NULL,
    [category]             NVARCHAR (50)   NULL,
    [description]          NVARCHAR (255)  NULL,
    [parameter_group]      NVARCHAR (64)   NULL,
    [dcs_name]             NVARCHAR (26)   NULL,
    [specification_key]    BIGINT          NOT NULL,
    [unit_of_measure]      NVARCHAR (64)   NULL,
    [data_type]            INT             NOT NULL,
    [string_value]         NVARCHAR (1024) NULL,
    [decimal_value]        NUMERIC (23, 9) NULL,
    [decimal_scale]        INT             NULL,
    [time_value]           DATETIME        NULL,
    [time_value_u]         DATETIME        NULL,
    [time_value_z]         NVARCHAR (64)   NULL,
    [int_value]            BIGINT          NULL,
    [boolean_value]        INT             NULL,
    [object_key]           BIGINT          NULL,
    [uda_0]                NVARCHAR (255)  NULL,
    [uda_1]                NVARCHAR (255)  NULL,
    [uda_2]                NVARCHAR (255)  NULL,
    [creator_key]          BIGINT          NOT NULL,
    [creation_time]        DATETIME        NOT NULL,
    [creation_time_u]      DATETIME        NULL,
    [creation_time_z]      NVARCHAR (64)   NULL,
    [last_modifier_key]    BIGINT          NOT NULL,
    [last_modified_time]   DATETIME        NOT NULL,
    [last_modified_time_u] DATETIME        NULL,
    [last_modified_time_z] NVARCHAR (64)   NULL,
    [xfr_insert_pid]       INT             NOT NULL,
    [pd_xfr_update_pid]    INT             NOT NULL,
    [src_xfr_update_pid]   INT             NOT NULL,
    [xfr_update_pid]       INT             NOT NULL,
    [trx_id]               CHAR (38)       NOT NULL,
    [measured_value]       NVARCHAR (64)   NULL,
    [definition_key]       BIGINT          NULL,
    [purged]               INT             NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([owner_key]));

