CREATE TABLE [SrcMES_FAB_MX2].[UDA_Batch] (
    [LZBatchID]             INT            NOT NULL,
    [ADLSBatchID]           INT            NOT NULL,
    [ADLSTimestamp]         DATETIME2 (0)  NOT NULL,
    [object_key]            BIGINT         NOT NULL,
    [last_modifier_key]     BIGINT         NOT NULL,
    [last_modified_time]    DATETIME       NOT NULL,
    [last_modified_time_u]  DATETIME       NULL,
    [last_modified_time_z]  NVARCHAR (64)  NULL,
    [xfr_insert_pid]        INT            NULL,
    [xfr_update_pid]        INT            NULL,
    [trx_id]                CHAR (38)      NOT NULL,
    [list_key]              BIGINT         NULL,
    [pd_xfr_update_pid]     INT            NULL,
    [src_xfr_update_pid]    INT            NULL,
    [X_unitOfMeasure_91]    BIGINT         NULL,
    [X_productionDate_T]    DATETIME       NULL,
    [X_productionDate_u]    DATETIME       NULL,
    [X_productionDate_z]    NVARCHAR (64)  NULL,
    [X_retestDate_T]        DATETIME       NULL,
    [X_retestDate_u]        DATETIME       NULL,
    [X_retestDate_z]        NVARCHAR (64)  NULL,
    [X_conveyorName_S]      NVARCHAR (50)  NULL,
    [X_inFileName_S]        NVARCHAR (50)  NULL,
    [X_outputDirBff_S]      NVARCHAR (256) NULL,
    [X_trayFolder_S]        NVARCHAR (256) NULL,
    [X_dateCompleted_S]     NVARCHAR (20)  NULL,
    [X_orderNo_S]           NVARCHAR (80)  NULL,
    [X_partRev_S]           NVARCHAR (80)  NULL,
    [X_upperStart_S]        NVARCHAR (4)   NULL,
    [X_upperEnd_S]          NVARCHAR (4)   NULL,
    [X_lowerStart_S]        NVARCHAR (4)   NULL,
    [X_lowerEnd_S]          NVARCHAR (4)   NULL,
    [X_quantity_S]          NVARCHAR (20)  NULL,
    [X_pilotId_S]           NVARCHAR (100) NULL,
    [X_pilotFabCluster_S]   NVARCHAR (80)  NULL,
    [X_expediteFlag_S]      NVARCHAR (80)  NULL,
    [X_clinicalStudy_S]     NVARCHAR (80)  NULL,
    [X_materialId_S]        NVARCHAR (80)  NULL,
    [X_lotCreationTime_T]   DATETIME       NULL,
    [X_lotCreationTime_u]   DATETIME       NULL,
    [X_lotCreationTime_z]   NVARCHAR (64)  NULL,
    [X_promisedTime_T]      DATETIME       NULL,
    [X_promisedTime_u]      DATETIME       NULL,
    [X_promisedTime_z]      NVARCHAR (64)  NULL,
    [X_conveyerName_S]      NVARCHAR (80)  NULL,
    [X_partDesc_S]          NVARCHAR (256) NULL,
    [X_partType_S]          NVARCHAR (80)  NULL,
    [X_productLine_S]       NVARCHAR (80)  NULL,
    [X_routeName_S]         NVARCHAR (80)  NULL,
    [X_orderType_S]         NVARCHAR (4)   NULL,
    [purged]                INT            NULL,
    [X_country_S]           NVARCHAR (80)  NULL,
    [X_did_S]               NVARCHAR (80)  NULL,
    [X_diamondDoc_S]        NVARCHAR (80)  NULL,
    [X_reworkRequestTime_T] DATETIME       NULL,
    [X_reworkRequestTime_u] DATETIME       NULL,
    [X_reworkRequestTime_z] NVARCHAR (64)  NULL,
    [X_orderKey_I]          BIGINT         NULL,
    [X_orderItemKey_I]      BIGINT         NULL,
    [X_refPartNo_S]         NVARCHAR (80)  NULL,
    [X_orderCreationTime_T] DATETIME       NULL,
    [X_orderCreationTime_u] DATETIME       NULL,
    [X_orderCreationTime_z] NVARCHAR (64)  NULL,
    [X_deliveryType_S]      NVARCHAR (80)  NULL,
    [X_csvJobId_S]          NVARCHAR (80)  NULL,
    [X_specialDoctor_I]     BIGINT         NULL,
    [X_treatmentOption_S]   NVARCHAR (80)  NULL,
    [X_StorageLocation_S]   NVARCHAR (80)  NULL,
    [X_specialFeature_I]    BIGINT         NULL,
    [X_filterKey_I]         BIGINT         NULL,
    [X_targetConveyer_S]    NVARCHAR (64)  NULL,
    [X_failComment_S]       NVARCHAR (256) NULL,
    [X_maUpperStages_S]     NVARCHAR (512) NULL,
    [X_maLowerStages_S]     NVARCHAR (512) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));

