CREATE TABLE [SrcMES_FAB_MX2].[UDA_WorkCenter] (
    [LZBatchID]                  INT            NOT NULL,
    [ADLSBatchID]                INT            NOT NULL,
    [ADLSTimestamp]              DATETIME2 (0)  NOT NULL,
    [object_key]                 BIGINT         NOT NULL,
    [last_modifier_key]          BIGINT         NOT NULL,
    [last_modified_time]         DATETIME       NOT NULL,
    [last_modified_time_u]       DATETIME       NULL,
    [last_modified_time_z]       NVARCHAR (64)  NULL,
    [xfr_insert_pid]             INT            NULL,
    [xfr_update_pid]             INT            NULL,
    [trx_id]                     CHAR (38)      NOT NULL,
    [list_key]                   BIGINT         NULL,
    [pd_xfr_update_pid]          INT            NULL,
    [src_xfr_update_pid]         INT            NULL,
    [FS_WORK_CENTER_SUPPORT_168] BIGINT         NULL,
    [FS_FOUNDATION_OBJECT_S]     NVARCHAR (80)  NULL,
    [FS_TASK_GROUPS_S]           NVARCHAR (80)  NULL,
    [FS_FO_TYPE_I]               BIGINT         NULL,
    [FS_FO_CONTAINER_CAPACITY_I] BIGINT         NULL,
    [FS_FO_FILL_RULE_I]          BIGINT         NULL,
    [X_currentJobId_S]           NVARCHAR (20)  NULL,
    [X_slaJobStatus_S]           NVARCHAR (80)  NULL,
    [X_slaMachineStatus_S]       NVARCHAR (80)  NULL,
    [X_slaAction_S]              NVARCHAR (80)  NULL,
    [X_slaOnLayer_S]             NVARCHAR (80)  NULL,
    [X_slaLastLayer_S]           NVARCHAR (80)  NULL,
    [X_slaStartTime_T]           DATETIME       NULL,
    [X_slaStartTime_u]           DATETIME       NULL,
    [X_slaStartTime_z]           NVARCHAR (64)  NULL,
    [X_slaEstimatedEndTime_T]    DATETIME       NULL,
    [X_slaEstimatedEndTime_u]    DATETIME       NULL,
    [X_slaEstimatedEndTime_z]    NVARCHAR (64)  NULL,
    [X_slaLastUpdatedOn_T]       DATETIME       NULL,
    [X_slaLastUpdatedOn_u]       DATETIME       NULL,
    [X_slaLastUpdatedOn_z]       NVARCHAR (64)  NULL,
    [X_isEnabled_S]              NVARCHAR (5)   NULL,
    [X_capacityMaximum_I]        BIGINT         NULL,
    [X_capacityLowWarning_I]     BIGINT         NULL,
    [X_minutesPerJob_I]          BIGINT         NULL,
    [X_parameterFileURL_S]       NVARCHAR (256) NULL,
    [X_reprocessLocation_S]      NVARCHAR (80)  NULL,
    [purged]                     INT            NULL,
    [X_plant_S]                  NVARCHAR (80)  NULL,
    [X_reportingLocation_S]      NVARCHAR (80)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

