CREATE TABLE [SrcMES_FAB_MX2].[WORK_CENTER] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [wc_key]               BIGINT         NOT NULL,
    [wc_name]              NVARCHAR (64)  NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [location_key]         BIGINT         NULL,
    [image_key]            BIGINT         NULL,
    [inst_list_key]        BIGINT         NULL,
    [default_equip_key]    BIGINT         NULL,
    [creator_key]          BIGINT         NOT NULL,
    [last_modifier_key]    BIGINT         NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [udt_0]                DATETIME       NULL,
    [udt_0_u]              DATETIME       NULL,
    [udt_0_z]              NVARCHAR (64)  NULL,
    [udt_1]                DATETIME       NULL,
    [udt_1_u]              DATETIME       NULL,
    [udt_1_z]              NVARCHAR (64)  NULL,
    [udt_2]                DATETIME       NULL,
    [udt_2_u]              DATETIME       NULL,
    [udt_2_z]              NVARCHAR (64)  NULL,
    [xfr_insert_pid]       INT            NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [xfr_update_pid]       INT            NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [update_privilege_key] BIGINT         NULL,
    [delete_privilege_key] BIGINT         NULL,
    [capacity]             NVARCHAR (64)  NULL,
    [sublot_access_type]   INT            NULL,
    [work_schedule_key]    BIGINT         NULL,
    [sublot_capacity]      NVARCHAR (64)  NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

