CREATE TABLE [SrcDocLocEMEA].[tblDocLocLog] (
    [LZBatchID]               INT            NOT NULL,
    [ADLSBatchID]             INT            NOT NULL,
    [ADLSTimestamp]           DATETIME2 (0)  NOT NULL,
    [id]                      BIGINT         NULL,
    [log_time]                DATETIME       NULL,
    [log_type]                NVARCHAR (50)  NULL,
    [implementation_type]     NVARCHAR (5)   NULL,
    [search_type]             NVARCHAR (50)  NULL,
    [search_source]           NVARCHAR (50)  NULL,
    [search_duration]         INT            NULL,
    [search_name]             NVARCHAR (50)  NULL,
    [search_address]          NVARCHAR (250) NULL,
    [search_postal_code]      NVARCHAR (50)  NULL,
    [search_city]             NVARCHAR (50)  NULL,
    [search_state]            NVARCHAR (50)  NULL,
    [search_country]          NVARCHAR (50)  NULL,
    [search_filter]           NVARCHAR (200) NULL,
    [search_sort]             NVARCHAR (10)  NULL,
    [search_latitude]         FLOAT (53)     NULL,
    [search_longitude]        FLOAT (53)     NULL,
    [search_results]          INT            NULL,
    [search_status]           INT            NULL,
    [search_data]             NVARCHAR (MAX) NULL,
    [search_session_id]       NVARCHAR (50)  NULL,
    [search_context_id]       NVARCHAR (50)  NULL,
    [search_radius]           FLOAT (53)     NULL,
    [search_start_position]   INT            NULL,
    [search_effective_radius] FLOAT (53)     NULL,
    [search_end_position]     INT            NULL,
    [primary_docid]           INT            NULL,
    [geocode_source]          NVARCHAR (10)  NULL,
    [docid_list]              NVARCHAR (MAX) NULL,
    [client_ip]               NVARCHAR (50)  NULL,
    [viewer_id]               NVARCHAR (50)  NULL,
    [error_message]           NVARCHAR (MAX) NULL
)
WITH (CLUSTERED INDEX([id]), DISTRIBUTION = HASH([id]));

