CREATE TABLE [SrcDocLocEMEA].[tblDocLoc] (
    [LZBatchID]                INT            NOT NULL,
    [ADLSBatchID]              INT            NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)  NOT NULL,
    [doc_id]                   INT            NULL,
    [clin_id]                  NVARCHAR (50)  NULL,
    [first_name]               NVARCHAR (100) NULL,
    [last_name]                NVARCHAR (100) NULL,
    [full_name]                NVARCHAR (255) NULL,
    [business_name]            NVARCHAR (255) NULL,
    [line1]                    NVARCHAR (300) NULL,
    [line2]                    NVARCHAR (300) NULL,
    [line3]                    NVARCHAR (300) NULL,
    [line4]                    NVARCHAR (300) NULL,
    [city]                     NVARCHAR (100) NULL,
    [state]                    NVARCHAR (50)  NULL,
    [postal_code]              NVARCHAR (20)  NULL,
    [country]                  NVARCHAR (50)  NULL,
    [longitude]                FLOAT (53)     NULL,
    [latitude]                 FLOAT (53)     NULL,
    [accuracy]                 NVARCHAR (20)  NULL,
    [url]                      NVARCHAR (255) NULL,
    [email]                    NVARCHAR (100) NULL,
    [office_phone]             NVARCHAR (50)  NULL,
    [fax]                      NVARCHAR (50)  NULL,
    [doctor_type]              NVARCHAR (10)  NULL,
    [segment_code]             NVARCHAR (10)  NULL,
    [casecount_6_months]       INT            NULL,
    [is_preferred]             NVARCHAR (10)  NULL,
    [is_teen_doctor]           NVARCHAR (10)  NULL,
    [is_casepack_doctor]       NVARCHAR (10)  NULL,
    [has_additional_locations] NVARCHAR (10)  NULL,
    [annotation_list]          NVARCHAR (255) NULL,
    [flags]                    INT            NULL,
    [static_rank1]             INT            NULL,
    [static_rank2]             INT            NULL,
    [static_rank3]             INT            NULL,
    [group_id]                 INT            NULL,
    [is_itero_doctor]          NVARCHAR (10)  NULL,
    [has_profile]              NVARCHAR (10)  NULL,
    [contact_email]            NVARCHAR (255) NULL,
    [merged_clinids]           NVARCHAR (255) NULL,
    [language]                 NVARCHAR (50)  NULL
)
WITH (CLUSTERED INDEX([doc_id]), DISTRIBUTION = HASH([doc_id]));

