CREATE TABLE [DWTOPS].[DimPart] (
    [SKPart]                 INT           NOT NULL,
    [ADLSBatchID]            INT           NOT NULL,
    [ADLSTimestamp]          DATETIME2 (0) NOT NULL,
    [LZBatchID]              INT           NOT NULL,
    [DWBatchID]              INT           NOT NULL,
    [DWHash]                 CHAR (40)     NOT NULL,
    [KeyPart]                VARCHAR (129) NOT NULL,
    [PartNumber]             VARCHAR (64)  NOT NULL,
    [PartRevision]           VARCHAR (64)  NOT NULL,
    [PartDescription]        VARCHAR (255) NULL,
    [PartCategory]           VARCHAR (50)  NULL,
    [ImageKey]               BIGINT        NULL,
    [InstListKey]            BIGINT        NULL,
    [BOMName]                VARCHAR (64)  NULL,
    [BOMRevision]            VARCHAR (64)  NULL,
    [PartQuantity]           INT           NULL,
    [ConsumptionDuration]    INT           NULL,
    [ConsumptionType]        VARCHAR (50)  NOT NULL,
    [BOMTrackedMode]         INT           NULL,
    [Revived]                INT           NULL,
    [ShelfLife]              INT           NOT NULL,
    [WarrantyPeriod]         INT           NOT NULL,
    [UnitOfMeasure]          VARCHAR (64)  NULL,
    [PartExtRevision]        VARCHAR (64)  NOT NULL,
    [ReplacementType]        VARCHAR (64)  NULL,
    [CarrierClassKey]        BIGINT        NULL,
    [LogicallyEmptyQuantity] VARCHAR (64)  NULL,
    [MixingType]             INT           NULL,
    [StorageClassEnforced]   INT           NULL,
    [StorageUnitClassKey]    BIGINT        NULL
)
WITH (CLUSTERED INDEX([SKPart]), DISTRIBUTION = REPLICATE);

