CREATE TABLE [DWTOPS].[FactLotCurrent] (
    [ADLSBatchID]           INT            NOT NULL,
    [ADLSTimestamp]         DATETIME2 (0)  NOT NULL,
    [LZBatchID]             INT            NOT NULL,
    [DWBatchID]             INT            NULL,
    [DgnCreationDateTime]   DATETIME       NULL,
    [DgnCompleteDateTime]   DATETIME       NULL,
    [DgnExpirationDateTime] DATETIME       NULL,
    [DgnFinishedDateTime]   DATETIME       NULL,
    [DgnLotKey]             BIGINT         NOT NULL,
    [DgnLotName]            NVARCHAR (128) NOT NULL,
    [DgnPriority]           INT            NULL,
    [DgnLotOrderItemKey]    BIGINT         NOT NULL,
    [DgnPauseDateTime]      DATETIME       NULL,
    [DgnPromisedDateTime]   DATETIME       NULL,
    [DgnShippedDateTime]    DATETIME       NULL,
    [DgnStartDateTime]      DATETIME       NULL,
    [DgnStatus]             VARCHAR (9)    NOT NULL,
    [DgnTobjHistoryKey]     BIGINT         NULL,
    [DgnTobjStatusKey]      BIGINT         NOT NULL,
    [DgnWorkOrderKey]       BIGINT         NOT NULL,
    [DgnWorkOrderNumber]    NVARCHAR (64)  NOT NULL,
    [DgnQCPassFail]         VARCHAR (5)    NOT NULL,
    [SKTeamRegion]          INT            NOT NULL,
    [KeyTeamRegion]         NVARCHAR (255) NOT NULL,
    [SKCompleteReason]      INT            NOT NULL,
    [KeyCompleteReason]     NVARCHAR (64)  NOT NULL,
    [SKCompleteDate]        INT            NOT NULL,
    [SKCompleteTime]        INT            NOT NULL,
    [SKCreationDate]        INT            NOT NULL,
    [SKCreationTime]        INT            NOT NULL,
    [SKDoctor]              INT            NOT NULL,
    [KeyDoctor]             NVARCHAR (80)  NOT NULL,
    [SKExpirationDate]      INT            NOT NULL,
    [SKExpirationTime]      INT            NOT NULL,
    [SKFinishedDate]        INT            NOT NULL,
    [SKFinishedTime]        INT            NOT NULL,
    [SKOperation]           INT            NOT NULL,
    [KeyOperation]          BIGINT         NOT NULL,
    [SKPart]                INT            NOT NULL,
    [KeyPart]               NVARCHAR (129) NOT NULL,
    [SKPauseDate]           INT            NOT NULL,
    [SKPauseTime]           INT            NOT NULL,
    [SKPlantActual]         INT            NOT NULL,
    [KeyPlantActual]        NVARCHAR (80)  NOT NULL,
    [SKPlantOriginal]       INT            NOT NULL,
    [KeyPlantOriginal]      NVARCHAR (225) NOT NULL,
	[SKPlantPrevious]       INT            NOT NULL,
	[KeyPlantPrevious]      NVARCHAR (64)  NOT NULL,
    [SKRoute]               INT            NOT NULL,
    [KeyRoute]              BIGINT         NOT NULL,
    [SKRouteStep]           INT            NOT NULL,
    [KeyRouteStep]          BIGINT         NOT NULL,
    [SKPromisedDate]        INT            NOT NULL,
    [SKPromisedTime]        INT            NOT NULL,
    [SKShippedDate]         INT            NOT NULL,
    [SKShippedTime]         INT            NOT NULL,
    [SKStartDate]           INT            NOT NULL,
    [SKStartTime]           INT            NOT NULL,
    [LotAgingHours]         INT            NULL,
    [LotAgingDays]          INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([DgnLotKey]));

