CREATE TABLE [DWTOPS].[FactWorkOrder] (
    [ADLSBatchID]                    INT            NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)  NOT NULL,
    [LZBatchID]                      INT            NOT NULL,
    [DWBatchID]                      INT            NULL,
    [DgnAllMaterialReceivedDateTime] DATETIME2 (3)  NULL,
    [DgnVIPOrderNumber]              NVARCHAR (80)  NULL,
    [DgnWorkOrderKey]                BIGINT         NOT NULL,
    [DgnWorkOrderNumber]             NVARCHAR (64)  NOT NULL,
    [DgnIsRejectedImpression]        VARCHAR (3)    NOT NULL,
    [DgnIsIPLEnabled]                VARCHAR (3)    NOT NULL,
    [DgnIsScan]                      NVARCHAR (10)  NULL,
    [DgnIOScanType]                  NVARCHAR (64)  NULL,
    [DgnHardwareVersion]             NVARCHAR (50)  NULL,
    [DgnSoftwareVersion]             NVARCHAR (50)  NULL,
    [DgnDeliverableType]             NVARCHAR (225) NULL,
    [DgnTreatmentCategory]           NVARCHAR (225) NULL,
    [DgnStorageLocation]             NVARCHAR (80)  NULL,
	[DgnPilotDescription]            NVARCHAR (100) NULL,
    [DgnTreatmentFlow]               NVARCHAR (80)  NULL,
    [DgnProcessingType]              NVARCHAR (80)  NULL,
	[DgnMAFeature]                   BIGINT         NULL,
	[DgnIsMTPSend]                   BIGINT         NULL,
	[DgnSTPExecuted]                 BIGINT         NULL,
    [SKDoctor]                       INT            NOT NULL,
    [SKExpediteScope]                INT            NOT NULL,
    [SKMaterialReceivedDate]         INT            NOT NULL,
    [SKMaterialReceivedTime]         INT            NOT NULL,
    [SKOrderCreationDate]            INT            NOT NULL,
    [SKOrderCreationTime]            INT            NOT NULL,
    [SKPlantOrderEntry]              INT            NOT NULL,
    [SKCountry]                      INT            NOT NULL,
	[SKCancelReason]                 INT            NOT NULL,
	[SKCancelledDate]                INT            NOT NULL,
    [DurationToFinishedInMinutes]    INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([DgnWorkOrderKey]));

