CREATE TABLE [DWTOPS].[FactPatientOrder] (
    [ADLSBatchID]                       INT           NOT NULL,
    [ADLSTimestamp]                     DATETIME2 (0) NOT NULL,
    [LZBatchID]                         INT           NOT NULL,
    [DWBatchID]                         INT           NOT NULL,
    [DgnCurrentRowFlag]                 BIT           NOT NULL,
    [DgnCancelledDateTime]              DATETIME2 (3) NULL,
    [DgnCCAcceptDateTime]               DATETIME2 (3) NULL,
    [DgnCCModDateTime]                  DATETIME2 (3) NULL,
    [DgnCCExportDateTime]               DATETIME2 (3) NULL,
    [DgnCCExportID]                     INT           NULL,
    [DgnCCReferDateTime]                DATETIME2 (3) NULL,
    [DgnCCSwitchDateTime]               DATETIME2 (3) NULL,
    [DgnClincheckLabReferredDateTime]   DATETIME2 (3) NULL,
    [DgnHoldDateTime]                   DATETIME2 (3) NULL,
    [DgnWorkOrderNumber]                BIGINT        NULL,
    [DgnModifiedDateTime]               DATETIME2 (3) NULL,
    [DgnMTPID]                          VARCHAR (255) NULL,
    [DgnOrderStatusHistoryID]           INT           NULL,
    [DgnPlanNumber]                     INT           NULL,
    [DgnPromisedShipDateTime]           DATETIME2 (3) NULL,
    [DgnRCAllMaterialsReceivedDateTime] DATETIME2 (3) NULL,
    [DgnRecievedDateTime]               DATETIME2 (3) NULL,
    [DgnRMANumber]                      BIGINT        NULL,
    [DgnSSShipDateTime]                 DATETIME2 (3) NULL,
    [DgnSubmitDateTime]                 DATETIME2 (3) NULL,
    [DgnSSTrackingNumber]               VARCHAR (32)  NULL,
    [DgnVIPOrderID]                     INT           NOT NULL,
    [IsCCReviewRequired]                BIT           NULL,
    [IsRCBoxExpected]                   BIT           NULL,
    [SKCancelledDate]                   INT           NOT NULL,
    [SKCancelledTime]                   INT           NOT NULL,
    [SKCCAcceptDate]                    INT           NOT NULL,
    [SKCCAcceptTime]                    INT           NOT NULL,
    [SKCCExportDate]                    INT           NOT NULL,
    [SKCCExportTime]                    INT           NOT NULL,
    [SKCCModDate]                       INT           NOT NULL,
    [SKCCModTime]                       INT           NOT NULL,
    [SKCCReferDate]                     INT           NOT NULL,
    [SKCCReferTime]                     INT           NOT NULL,
    [SKCCSwitchDate]                    INT           NOT NULL,
    [SKCCSwitchTime]                    INT           NOT NULL,
    [SKClincheckLabReferredDate]        INT           NOT NULL,
    [SKClincheckLabReferredTime]        INT           NOT NULL,
    [SKEvent]                           INT           NOT NULL,
    [SKHoldDate]                        INT           NOT NULL,
    [SKHoldTime]                        INT           NOT NULL,
    [SKModifiedDate]                    INT           NOT NULL,
    [SKModifiedTime]                    INT           NOT NULL,
    [SKPromisedShipDate]                INT           NOT NULL,
    [SKPromisedShipTime]                INT           NOT NULL,
    [SKRCAllMaterialsReceivedDate]      INT           NOT NULL,
    [SKRCAllMaterialsReceivedTime]      INT           NOT NULL,
    [SKRecievedDate]                    INT           NOT NULL,
    [SKRecievedTime]                    INT           NOT NULL,
    [SKSSShipDate]                      INT           NOT NULL,
    [SKSSShipTime]                      INT           NOT NULL,
    [SKSubmitDate]                      INT           NOT NULL,
    [SKSubmitTime]                      INT           NOT NULL,
    [CCCount]                           INT           NULL,
    [CCModCount]                        INT           NULL,
    [OrderedBatches]                    VARCHAR (8)   NULL,
    [TreatedArches]                     INT           NULL,
    [DurationToReceivedInMinutes]       INT           NULL,
    [DurationToCCExportInMinutes]       INT           NULL,
    [DurationToCCAcceptInMinutes]       INT           NULL,
    [DurationToShippedInMinutes]        INT           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([DgnVIPOrderID]));

