CREATE PROC [DWSAP].[ScannerHistoryProcessingProc] @BatchID [int],@LastSuccessfullDWTimestamp [datetime2](0) AS
BEGIN

	declare @RowsInserted	int = 0
		,	@RowsUpdated	int = 0
		,	@IsFullLoad		bit = 0
SELECT [LZBatchID]
			  ,[ADLSBatchID]
			  ,[ADLSTimestamp]
			  ,@BatchID [DWBatchID]
			  ,@LastSuccessfullDWTimestamp [DWTimeStamp]
			  ,[DOC_NUMBER] [Sales Document]
			  ,[S_ORD_ITEM] [Item]
			  ,[FISCVARNT] [Fiscal Year Variant]
			  ,[CALQUARTER] [Cal. Year/Quarter]
			  ,[CALQUART1] [Quarter]
			  ,[CALWEEK] [Calender Year/Week]
			  ,[FISCYEAR] [Fiscal Year]
			  ,[FISCPER] [Fiscal Year/Period]
			  ,[FISCPER3] [Posting Period]
			  ,[/BIC/ZZSR_NO] [Equipment Serial Num]
			  ,[/BIC/INCOMID] [Initiator Company ID]
			  ,[/BIC/RREGION] [Reporting Region]
			  ,[/BIC/EVENTDATE] [Event Date]
			  ,[DOC_TYPE] [Document Type]
			  ,[DOC_CATEG] [Document Category]
			  ,[ITEM_CATEG] [Item Category]
			  ,[/BIC/DELI_TYPE] [Deliverable Type]
			  ,[/BIC/ZDELICATE] [Treatment Category]
			  ,[COMP_CODE] [Company Code]
			  ,[MATERIAL] [Material]
			  ,[PROD_HIER] [Product Hierarchy]
			  ,[/BIC/CA_PRIMRY] [CA_PRIMARY]
			  ,[/BIC/CA_SECNDR] [CA_SECONDARY]
			  ,[/BIC/CA_NONCAS] [CA_NONCAS]
			  ,[/BIC/CA_OTHERS] [CA_OTHERS]
			  ,[/BIC/CA_UNKOWN] [CA_UNKNOWN]
			  ,[/BIC/ITRO_SCNR] [ITRO_SCNR]
			  ,[/BIC/ITRO_SERV] [ITRO_SERV]
			  ,[/BIC/ABSTK] [Overall Rejection St]
			  ,[REASON_REJ] [Reason For Rejection]
			  ,[REJECTN_ST] [Rejection Status]
			  ,[/BIC/REJCT_DAT] [Rejection Date]
			  ,[/BIC/REJCT_TIM] [Rejection Time]
			  ,[DOC_DATE] [Document Date]
			  ,[CREATEDON] [Created On]
			  ,[/BIC/KNUMV] [Doc. Condition]
			  ,[/BIC/PAOBJNR] [Profit. Segment]
			  ,[COSTCENTER] [Cost Center]
			  ,[CO_AREA] [Controlling Area]
			  ,[PROFIT_CTR] [Profit Center]
			  ,[/BIC/ZCOSELMNT] [Cost Element(COPA)]
			  ,[/BIC/ZCOMP_IND] [Compliance Indicator]
			  ,[/BIC/ZAMR_DATE] [AMR DATE]
			  ,[/BIC/ZCCS_DATE] [CCS DATE]
			  ,[/BIC/ZCCA_DATE] [CCA DATE]
			  ,[/BIC/ZZEXT_PID] [External Patient ID]
			  ,[/BIC/ZZVIP_ORD] [Source System Order]
			  ,[/BIC/ZZPATIENT] [Patient ID]
			  ,[/BIC/ZSFDC_ORD] [SFDC Order ID]
			  ,[/BIC/ZZFRE_QTY] [FoC Quantity]
			  ,[/BIC/ZZTOT_QTY] [Deliverable Quantity]
			  ,[/BIC/TOT_QTY] [Deliverable Quantity for COPA]
			  ,[/BIC/TOTAL_QTY] [Total Quantity for COPA]
			  ,[SALES_UNIT] [Sales Unit]
			  ,[BASE_UOM]
			  ,[TARGET_QU]
			  ,[DOC_CURRCY] [Document Currency]
			  ,[CML_CF_QTY]
			  ,[CML_CD_QTY]
			  ,[CML_OR_QTY] [Order Quantity]
			  ,[TARGET_QTY] [Target Quantity]
			  ,[WITHDRWQTY] [Withdraw Quantity]
			  ,[NET_PRICE] [Net Price]
			  ,[NET_VALUE] [Net Value]
			  ,[/BIC/AGE_TIER] [Age Tier]
			  ,[/BIC/ZCHATREPO] [Reporting Channel]
			  ,[/BIC/FREE_PAID] [Free/Paid]
			  ,[SOLD_TO] [Sold-to Party]
			  ,[CUST_GRP1] [Customer Group 1]
			  ,[CUST_GRP2] [Customer Group 2]
			  ,[CUST_GRP3] [Customer Group 3]
			  ,[CUST_GRP4] [Customer Group 4]
			  ,[CUST_GRP5] [Customer Group 5]
			  ,[SALES_GRP] [Sales Group]
			  ,[SALESORG] [Sales Organization]
			  ,[DISTR_CHAN] [Distribution Channel]
			  ,[STOR_LOC] [Storage Location]
			  ,[PLANT] [Plant]
			  ,[MATL_GROUP] [Material Group]
			  ,[BILLTOPRTY] [Bill-to Party]
			  ,[SHIP_TO] [Ship-to Party]
			  ,[DIVISION] [Division]
			  ,[COUNTRY] [Country]
			  ,[/BIC/EXT_TXID] [External Treatment ID]
			  ,[/BIC/ZTREATOPT] [Treatment Option]
			  ,[/BIC/ZZTREAT] [Treatment ID]
			  ,[/BIC/ZZ_STAGES] [Max No Of Stages]
			  ,[/BIC/TRMNTLOC] [Treatment Location]
			  ,[/BIC/TRMNTDOC] [Treatment Doctor]
			  ,[/BIC/ORDSTAGES] [Order Stages]
			  ,[/BIC/STAGBUCKT] [Stages Bucket]
			  ,[MATL_GRP_1] [Material Group 1]
			  ,[MATL_GRP_2] [Material Group 2]
			  ,[MATL_GRP_3] [Material Group 3]
			  ,[MATL_GRP_4] [Material Group 4]
			  ,[MATL_GRP_5] [Material Group 5]
			  ,[/BIC/TERTRYMGR] [Territory Manager]
			  ,[/BIC/ALGNRETIL] [Align Retail]
			  ,[/BIC/FINCONTCT] [Financial Contact]
			  ,[/BIC/JR_DOCTOR] [Junior Doctor]
			  ,[/BIC/SUBSTUDNT] [Submitting Student]
			  ,[/BIC/EMP_RESP] [Employee Responsible]
			  ,[/BIC/ATNAM_UPR] [Characteristic-Upper]
			  ,[/BIC/ATNAM_LWR] [Characteristic-Lower]
			  ,[/BIC/ATWRT_UPR] [Charac. Value-Upper]
			  ,[/BIC/ATWRT_LWR] [Charac. Value-Lower]
			  ,[/BIC/ZCLINICAL]
			  ,[DELIV_NUMB]
			  ,[DELIV_ITEM]
			  ,[ACT_GI_DTE]
			  ,[ACT_DL_QTY]
			  ,[DLV_QTY]
			  ,[/BIC/SHPMNTCNT]
			  ,[/BIC/VOL_SEGMT]
			  ,[/BIC/VOL_COUNT]
			  ,[/BIC/VOL_QUANT]
			  ,[/BIC/SEGMENT]
			  ,[/BIC/VOLSSEGMT]
			  ,[/BIC/FILEYN]
			  ,[BILL_DATE]
			  ,[/BIC/IACTQTY]
			  ,[PAYER]
			  ,[VOLUMEUNIT]
			  ,[CREA_TIME]
			  ,[/BIC/ZALGNUSER] [ZALGNUSER]
			  ,[/BIC/ZFRE_QTY]
			  ,[/BIC/ZTOTALQT] [Total Quantity]
			  ,[/BIC/DELV_QTY]
			  ,[/BIC/PROMOBUC] [Promotion Bucket]
			  ,[/BIC/ZDATEMIM] [Data of MIM]
			  ,[/BIC/ZEVENT] [Event Description]
			  ,'Volume' [Process Name]
			  ,case when [PROD_HIER] like 'A1A1%' then 'CLEAR ALIGNER'
			  when [PROD_HIER] like 'A1S1%' then 'ITERO'
			  else null end as [Business Segment]
Into #temp_ScannerHistory
FROM [SrcSAPFile].[ScannerHistory]

IF (EXISTS (SELECT *
                 FROM INFORMATION_SCHEMA.TABLES
                 WHERE TABLE_SCHEMA = 'DWSAP'
                 AND  TABLE_NAME = 'ScannerHistoryProcessed'))
BEGIN

	TRUNCATE TABLE [DWSAP].[ScannerHistoryProcessed]
	INSERT INTO [DWSAP].[ScannerHistoryProcessed] SELECT * FROM #temp_ScannerHistory
END
ELSE
BEGIN
SELECT * INTO [DWSAP].[ScannerHistoryProcessed] FROM #temp_ScannerHistory
END

DROP TABLE #temp_ScannerHistory
-- exec CTRL.GetLastRowCount @Label = 'DWTOPS.LoadFactLotHistory_Delete', @rc = @RowsUpdated out
-- exec CTRL.GetLastRowCount @Label = 'DWTOPS.LoadFactLotHistory_Insert', @rc = @RowsInserted out
select @RowsInserted - @RowsUpdated as RowsInserted, @RowsUpdated as RowsUpdated
END