CREATE TABLE [SrcMESCorpNRT].[UDA_Order]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[object_key] [bigint] NOT NULL,
	[site_num] [int] NOT NULL,
	[last_modified_time] [datetime] NOT NULL,
	[at_DoctorID_S] [nvarchar](80) NULL,
	[at_JDEOrderType_S] [nvarchar](80) NULL,
	[at_JDERoutingType_S] [nvarchar](3) NULL,
	[at_TreatmentID_S] [nvarchar](15) NULL,
	[at_VipOrderNumber_S] [nvarchar](80) NULL,
	[at_IsICS_I] [bigint] NULL,
	[at_expedite_hold_status_I] [bigint] NULL,
	[at_expedite_scope_S] [nvarchar](64) NULL,
	[at_HasAssetScanLot_I] [bigint] NULL,
	[at_TreatedArch_S] [nvarchar](80) NULL,
	[last_modified_time_u] [datetime] NULL,
	[list_key] [bigint] NULL,
	[at_IsRejectedImpressions_I] [bigint] NULL,
	[at_IOScan_S] [nvarchar](10) NULL,
	[at_AllMaterialRecdTime_S] [nvarchar](225) NULL,
	[at_IsAMRSend_I] [bigint] NULL,
	[at_Pilot_S] [nvarchar](100) NULL,
	[at_MaintainStudy_S] [nvarchar](20) NULL,
	[at_IOScanType_S] [nvarchar](64) NULL,
	[at_IOScanHardwareVersion_S] [nvarchar](50) NULL,
	[at_IOScanSoftwareVersion_S] [nvarchar](50) NULL,
	[at_Submission_S] [nvarchar](64) NULL,
	[at_DeliverableType_S] [nvarchar](225) NULL,
	[at_PlantOA_S] [nvarchar](225) NULL,
	[at_ServiceLevel_S] [nvarchar](225) NULL,
	[at_Country_S] [nvarchar](225) NULL,
	[at_SOIMaterialNumber_I] [bigint] NULL,
	[at_TreatmentCategory_S] [nvarchar](225) NULL,
	[at_OrderType_S] [nvarchar](80) NULL,
	[at_ProductionOrderType_S] [nvarchar](80) NULL,
	[at_SalesOrderItem_S] [nvarchar](80) NULL,
	[at_externalTreatmentId_S] [nvarchar](80) NULL,
	[at_TreatmentOption_S] [nvarchar](225) NULL,
	[at_StorageLocation_S] [nvarchar](80) NULL,
	[at_DentalRecords_S] [nvarchar](80) NULL,
	[at_MAFeature_I] [bigint] NULL,
	[at_STPExecuted_I] [bigint] NULL,
	[at_IsSTPSend_I] [bigint] NULL,
	[at_ProcessingType_S] [nvarchar](80) NULL,
	[at_TreatmentFlow_S] [nvarchar](80) NULL,
	[at_PortingFlow_S] [nvarchar](80) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX,  DISTRIBUTION = HASH ( [object_key] ));