CREATE TABLE [SrcWebStore].[spree_orders]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[id] [int] NOT NULL,
	[number] [nvarchar](32) NULL,
	[item_total] [decimal](10, 2) NOT NULL,
	[total] [decimal](10, 2) NOT NULL,
	[state] [nvarchar](256) NULL,
	[adjustment_total] [decimal](10, 2) NOT NULL,
	[user_id] [int] NULL,
	[completed_at] [datetime2](6) NULL,
	[bill_address_id] [int] NULL,
	[ship_address_id] [int] NULL,
	[payment_total] [decimal](10, 2) NULL,
	[shipping_method_id] [int] NULL,
	[shipment_state] [nvarchar](256) NULL,
	[payment_state] [nvarchar](256) NULL,
	[email] [nvarchar](256) NULL,
	[special_instructions] [nvarchar](256) NULL,
	[created_at] [datetime2](6) NOT NULL,
	[updated_at] [datetime2](6) NOT NULL,
	[currency] [nvarchar](256) NULL,
	[last_ip_address] [nvarchar](256) NULL,
	[created_by_id] [int] NULL,
	[shipment_total] [decimal](10, 2) NOT NULL,
	[additional_tax_total] [decimal](10, 2) NULL,
	[promo_total] [decimal](10, 2) NULL,
	[channel] [nvarchar](256) NULL,
	[included_tax_total] [decimal](10, 2) NOT NULL,
	[item_count] [int] NULL,
	[approver_id] [int] NULL,
	[approved_at] [datetime2](6) NULL,
	[confirmation_delivered] [bit] NULL,
	[considered_risky] [bit] NULL,
	[guest_token] [nvarchar](256) NULL,
	[canceled_at] [datetime2](6) NULL,
	[canceler_id] [int] NULL,
	[store_id] [int] NULL,
	[state_lock_version] [int] NOT NULL,
	[sent_to_gilog] [bit] NULL,
	[sent_to_sap] [bit] NULL,
	[sap_order_number] [nvarchar](256) NULL,
	[sap_order_error] [nvarchar](256) NULL,
	[gilog_order_error] [nvarchar](256) NULL,
	[is_backend_order] [bit] NOT NULL,
	[order_type] [nvarchar](256) NULL,
	[backend_foc_order] [bit] NOT NULL,
	[comment] [nvarchar](256) NULL,
	[event_type] [nvarchar](256) NULL,
	[event_date] [datetime2](6) NULL,
	[temp_order_number] [nvarchar](256) NULL,
	[sfdc_ticket_no] [nvarchar](256) NULL,
	[serial_number] [nvarchar](256) NULL,
	[express_shipment] [bit] NOT NULL,
	[total_points] [int] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [id] ),
	CLUSTERED INDEX
	(
		[id] ASC
	)
)