CREATE TABLE [SrcWebStore].[spree_addresses]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[id] [int] NOT NULL,
	[firstname] [nvarchar](256) NULL,
	[lastname] [nvarchar](256) NULL,
	[address1] [nvarchar](256) NULL,
	[address2] [nvarchar](256) NULL,
	[city] [nvarchar](256) NULL,
	[zipcode] [nvarchar](256) NULL,
	[phone] [nvarchar](256) NULL,
	[state_name] [nvarchar](256) NULL,
	[alternative_phone] [nvarchar](256) NULL,
	[company] [nvarchar](256) NULL,
	[state_id] [int] NULL,
	[country_id] [int] NULL,
	[created_at] [datetime2](6) NOT NULL,
	[updated_at] [datetime2](6) NOT NULL,
	[ship_to] [bit] NULL,
	[bill_to] [bit] NULL,
	[pay_to] [bit] NULL,
	[sold_to] [bit] NULL,
	[primary] [bit] NULL,
	[email] [nvarchar](256) NULL,
	[address3] [nvarchar](256) NULL,
	[address4] [nvarchar](256) NULL,
	[salesforce_id] [nvarchar](256) NULL,
	[contact_id] [nvarchar](256) NULL,
	[account_number] [int] NULL,
	[invoice_preference] [nvarchar](256) NULL,
	[vat_id] [nvarchar](256) NULL,
	[mailing_name] [nvarchar](256) NULL,
	[active] [bit] NULL,
	[translated_address1] [nvarchar](256) NULL,
	[translated_address2] [nvarchar](256) NULL,
	[translated_address3] [nvarchar](256) NULL,
	[translated_city] [nvarchar](256) NULL,
	[translated_state] [nvarchar](256) NULL,
	[translated_country] [nvarchar](256) NULL,
	[translated_mailing_name] [nvarchar](256) NULL,
	[translated_name] [nvarchar](256) NULL,
	[is_alt_address] [bit] NULL,
	[altfullname] [nvarchar](256) NULL,
	[altstreetaddress1] [nvarchar](256) NULL,
	[altstreetaddress2] [nvarchar](256) NULL,
	[altstreetaddress3] [nvarchar](256) NULL,
	[altcity] [nvarchar](256) NULL,
	[altstate] [nvarchar](256) NULL,
	[altzipcode] [nvarchar](256) NULL,
	[altcountry] [nvarchar](256) NULL,
	[is_alt_delete] [bit] NULL,
	[altStreetNumber] [int] NULL,
	[altStreet] [nvarchar](256) NULL,
	[parent_account_number] [int] NULL,
	[account_type] [nvarchar](256) NULL,
	[is_at_contact_level] [bit] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [id] ),
	CLUSTERED INDEX
	(
		[id] ASC
	)
)