CREATE TABLE [SrcMAT].[Case_ExtendedInfo] (
    [LZBatchID]                   INT             NOT NULL,
    [ADLSBatchID]                 INT             NOT NULL,
    [ADLSTimestamp]               DATETIME2 (0)   NOT NULL,
    [OrderHeaderID]               INT             NOT NULL,
    [FileServer]                  VARCHAR (100)   NULL,
    [FilePath]                    VARCHAR (200)   NULL,
    [FileName]                    NVARCHAR (200)  NULL,
    [FileType]                    INT             NULL,
    [ShipToPartnerID]             INT             NOT NULL,
    [MillingSitePartnerID]        INT             NOT NULL,
    [CaseTypeID]                  SMALLINT        NULL,
    [Rush]                        BIT             NULL,
    [ShadeSystem]                 VARCHAR (50)    NULL,
    [NumModelsForLab]             TINYINT         NOT NULL,
    [DentistLicenseNumber]        NVARCHAR (100)  NULL,
    [Comments]                    NVARCHAR (4000) NULL,
    [ArrivalDate]                 DATETIME        NULL,
    [NumberOFPreps]               TINYINT         NOT NULL,
    [AcquisitionDate]             DATETIME        NULL,
    [FileVersion]                 VARCHAR (50)    NULL,
    [ScanningSitePartnerID]       INT             NOT NULL,
    [RxInfoHashCode]              INT             NOT NULL,
    [InterpretationSitePartnerID] INT             NOT NULL,
    [RowStatusID]                 TINYINT         NOT NULL,
    [DateCreated]                 DATETIME        NOT NULL,
    [CreatedByUserID]             INT             NOT NULL,
    [DateUpdated]                 DATETIME        NOT NULL,
    [UpdatedByUserID]             INT             NOT NULL,
    [LastWorkOrderID]             INT             NULL,
    [LastWorkOrderDateUpdated]    DATETIME        NULL,
    [LastSalesOrderDetailsID]     INT             NULL,
    [LastBillOfWorkID]            INT             NULL,
    [LastResourcePartnerID]       INT             NULL,
    [InstrCode]                   NVARCHAR (50)   NOT NULL,
    [RxID]                        NVARCHAR (4000) NULL,
    [IsDirectToLab]               BIT             NULL,
    [IsAlta]                      BIT             NOT NULL,
    [IsReturned]                  BIT             NOT NULL
)
WITH (CLUSTERED INDEX([OrderHeaderID]), DISTRIBUTION = HASH([OrderHeaderID]));

