CREATE TABLE [SrcMAT].[TicketComplaint] (
    [LZBatchID]                                       INT             NOT NULL,
    [ADLSBatchID]                                     INT             NOT NULL,
    [ADLSTimestamp]                                   DATETIME2 (0)   NOT NULL,
    [Id]                                              INT             NOT NULL,
    [TicketId]                                        INT             NOT NULL,
    [CustomerIssueDescription]                        NVARCHAR (4000) NOT NULL,
    [CustomerServiceInitialInvestigation]             NVARCHAR (4000) NOT NULL,
    [RootCause]                                       NVARCHAR (4000) NOT NULL,
    [ActionsTakenCorrections]                         NVARCHAR (4000) NOT NULL,
    [AdditionalInformation]                           NVARCHAR (4000) NOT NULL,
    [IsValidComplaint]                                BIT             NOT NULL,
    [DuplicateOf]                                     NVARCHAR (50)   NOT NULL,
    [IsRegulatoryNonConformance]                      BIT             NOT NULL,
    [IsSafetyOrPotentiallySafety]                     BIT             NOT NULL,
    [RiskAnalysisDOC]                                 NVARCHAR (50)   NOT NULL,
    [HazardSituation]                                 NVARCHAR (4000) NOT NULL,
    [EvaluationImpactLevel]                           NVARCHAR (4000) NOT NULL,
    [IsFurtherInvestigationNeeded]                    BIT             NOT NULL,
    [InvestigationCAPAReference]                      NVARCHAR (50)   NOT NULL,
    [RationaleForFurtherInvestigationCAPANotRequired] NVARCHAR (4000) NOT NULL,
    [InWhatCountry]                                   NVARCHAR (4000) NOT NULL,
    [DidEventResultIn]                                BIT             NOT NULL,
    [AreThereSpecialConsiderations]                   BIT             NOT NULL,
    [IsReportable]                                    BIT             NOT NULL,
    [JustificationReportSummary]                      NVARCHAR (4000) NOT NULL,
    [AdditionalCommentsOther]                         NVARCHAR (4000) NOT NULL,
    [ComplaintHandlingAndAssessmentDoneBy]            NVARCHAR (4000) NOT NULL,
    [OpenDate]                                        DATETIME        NOT NULL,
    [ClosureDate]                                     DATETIME        NULL,
    [RowStatusID]                                     TINYINT         NOT NULL,
    [UDI]                                             NVARCHAR (100)  NULL,
    [ScannerId]                                       INT             NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

