CREATE TABLE [SrcMES_AFAB_MX1].[DC_at_ACLDefect] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [dc_instance_key]      BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [creation_time]        DATETIME       NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time]   DATETIME       NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [is_finished]          TINYINT        NULL,
    [route_name]           NVARCHAR (64)  NULL,
    [route_key]            BIGINT         NULL,
    [route_step_name]      NVARCHAR (64)  NULL,
    [op_name]              NVARCHAR (64)  NULL,
    [user_name]            NVARCHAR (64)  NULL,
    [dscomment]            NVARCHAR (255) NULL,
    [dslocation]           NVARCHAR (64)  NULL,
    [object_key]           BIGINT         NULL,
    [object_name]          NVARCHAR (128) NULL,
    [object_type]          NVARCHAR (64)  NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [at_ACLDefectCode]     NVARCHAR (80)  NULL,
    [at_OrderNumber]       NVARCHAR (80)  NULL,
    [at_PID]               NVARCHAR (80)  NULL,
    [at_UnitSerialNumber]  NVARCHAR (80)  NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

