CREATE TABLE [SrcMES_AFAB_MX1].[ROUTE_STEP] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [route_step_key]       BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [route_key]            BIGINT         NOT NULL,
    [op_key]               BIGINT         NOT NULL,
    [route_step_name]      NVARCHAR (64)  NOT NULL,
    [route_step_type]      NVARCHAR (50)  NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [pixel_x]              INT            NULL,
    [pixel_y]              INT            NULL,
    [inst_list_key]        BIGINT         NULL,
    [dcs_list_key]         BIGINT         NULL,
    [form_key]             BIGINT         NULL,
    [label_width]          INT            NULL,
    [border_flag]          INT            NULL,
    [checklist_key]        BIGINT         NULL,
    [dependencies]         NVARCHAR (255) NULL,
    [enforcement]          INT            NULL,
    [reasons]              NVARCHAR (255) NULL,
    [cycle_duration]       INT            NULL,
    [cycle_duration_type]  INT            NULL,
    [failure]              INT            NULL,
    [value_added]          INT            NULL,
    [work_center_assigned] INT            NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

