CREATE VIEW [DWEloomi].[Users]
AS SELECT [id]
      ,[first_name]
      ,[last_name]
      ,[employee_id]
      ,[function]
      ,[generic_role]
      ,[title]
      ,[gender]
      ,[email]
      ,[country]
      ,[location]
      ,[activated]
      ,[activated_at]
      ,[deactivated_at]
      ,[start_of_employment_at]
      ,[end_of_employment_at]
  FROM [SrcEloomi].[users];

