
CREATE VIEW [DWInst].[InstSession]
AS 
SELECT [session_id]
      ,[WandVersion]
      ,[RxId]
      ,[ScanDate]
      ,[CaseType]
      ,[FirewallInfo]
      ,[StillTimeInSeconds]
      ,[SessionTime]
      ,[sessionDate]
      ,[DoctorName]
      ,[OcclusionColors]
      ,[ComputerName]
      ,[CrownInstallDate]
      ,[WandId]
      ,[CompanyId]
      ,[DoctorId]
      ,[InternetExplorerVersion]
      ,[InstrumentationCaseId]
      ,[CaseTypeId]
      ,[ApplicationName]
      ,[ApplicationVersion]
      ,[ApplicationLanguage]
      ,[ClinicianId]
      ,[DurationInMinutes]
  FROM [DWInst].[DimInstSession]


