CREATE VIEW [DWInst].[Session]
AS SELECT [session_id]
      ,[session_datetime]
      ,[parent_session_id]
      ,[auto_session_id]
      ,[machine_id]
      ,[application_name]
      ,[application_version]
      ,[application_language]
      ,[application_package]
      ,[clinician_id]
      ,[lcid]
      ,[timezone]
      ,[os_version]
      ,[os_service_pack]
      ,[os_product_type]
      ,[video_card_name]
      ,[video_card_version]
      ,[video_card_driver_date]
      ,[video_card_horizontal_resolution]
      ,[video_card_vertical_resolution]
      ,[video_card_bits_per_pixel]
      ,[physical_memory_free]
      ,[physical_memory_total]
      ,[processor_name]
      ,[processor_description]
      ,[system_model]
      ,[system_manufacturer]
      ,[baseboard_product]
      ,[baseboard_model]
      ,[baseboard_manufacturer]
      ,[mac_address]
      ,[is_user_local_admin]
      ,[is_UAC_on]
      ,[user_name]
  FROM [SrcINST].[Session];