CREATE TABLE [SrcShipExec].[SkipumData]
(
	LZBatchID int NOT NULL,
	ADLSBatchID int NOT NULL,
	ADLSTimestamp datetime2(0) NOT NULL,
	InvoiceNumber varchar(20) NULL,
	InvoiceLineItem varchar(50) NULL,
	Carrier varchar(20) NULL,
	CarrierService varchar(255) NULL,
	TrackingNumber varchar(255) NULL,
	CarrierAccount varchar(50) NULL,
	InvoiceDate datetime NULL,
	PrimaryChargeType varchar(255) NULL,
	SecondaryChargeType varchar(255) NULL,
	Amount decimal(18, 2) NULL,
	Currency varchar(10) NULL,
	BillingType varchar(50) NULL,
	PickUpDate datetime NULL,
	PaymentType varchar(50) NULL,
	CarrierPaymentPlan varchar(255) NULL,
	CarrierDeliveryZone varchar(20) NULL,
	FreightClass varchar(20) NULL,
	Amount_InvoiceTotal decimal(18, 2) NULL,
	Currency_Invoice varchar(10) NULL,
	LeadTrackingNumber varchar(255) NULL,
	InvoiceLineDescription varchar(255) NULL,
	DeliveryZone varchar(10) NULL,
	PackageReference1 varchar(255) NULL,
	PackageReference2 varchar(255) NULL,
	PackageReference3 varchar(255) NULL,
	PackageReference4 varchar(255) NULL,
	PackageReference5 varchar(255) NULL,
	Quantity int NULL,
	Origin_LocationText varchar(255) NULL,
	Origin_Address1 varchar(255) NULL,
	Origin_City varchar(50) NULL,
	Origin_Country varchar(10) NULL,
	Origin_Company varchar(255) NULL,
	Origin_PostalCode varchar(50) NULL,
	Origin_Region varchar(10) NULL,
	Destination_LocationText varchar(255) NULL,
	Destination_Address1 varchar(255) NULL,
	Destination_City varchar(50) NULL,
	Destination_Country varchar(10) NULL,
	Destination_Company varchar(255) NULL,
	Destination_PostalCode varchar(50) NULL,
	Destination_Region varchar(10) NULL,
	ShipmentReference1 varchar(255) NULL,
	ShipmentReference2 varchar(255) NULL,
	Amount_InvoiceLine decimal(18, 2) NULL,
	Currency_InvoiceLine varchar(10) NULL,
	InvoiceType varchar(50) NULL,
	InvoiceDueDate datetime NULL,
	BillingWeight decimal(18, 2) NULL,
	Unit_BillingWeight varchar(10) NULL,
	ScannedDimensions varchar(255) NULL,
	ShippedDimensions varchar(255) NULL,
	ShippingWeight decimal(18, 2) NULL,
	Unit_ShippingWeight varchar(10) NULL,
	CarrierCorrectedWeight decimal(18, 2) NULL,
	CarrierCorrectedWeightUnit varchar(10) NULL,
	Destination_Contact varchar(255) NULL,
	PrimaryChargeCategory varchar(50) NULL,
	PrimaryChargeCategoryDetail varchar(50) NULL,
	Id_Header varchar(20) NULL,
	Id_Item varchar(20) NULL,
	Id varchar(20) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO