CREATE VIEW [TABIRIS].[DimAccount]
AS SELECT
	ha.[SKAccount]										as [SK Account],
	ha.[KeyAccount]									as [Key Account],
	da.[AccountNumber]									as [Account Number],
	da.[AccountName]									as [Account Name],
	da.[AddressStreet1]								as [Address Street1],
	da.[ShippingCountryCode]							as [Shipping Country Code],
	da.[ShippingCity]									as [City],
	da.[ShippingState]									as [State],
	da.[ShippingStateCode]								as [State Code],
	da.[ShippingPostalCode]							as [Postal Code],
	da.[Email]											as [Email],
	da.[Phone]											as [Phone],
	da.[MATID]											as [MATID],
	da.[OwnerID]										as [OwnerID],
    da.[ParentAccountID]								as [ParentAccountID],
    da.[ParentAccountNumber]					        as ParentAccountNumber,
   da.[MailingName]									as [Mailing Name],
   da.[RecordType]									as [Record Type],
   da.[AccountType]									as [Account Type],
   da.[Fax]											as [Fax],
   da.[Website]										as [Website],
   da.[NotificationEmail]								as [Notification Email],
   da.[CustomerGroup]									as [Customer Group],
   da.[ShippingCity]									as [Shipping City],
   da.[ShippingCountry]								as [Shipping Country],
   da.[ShippingCountryGroup]						    as [Shipping Country Group],
   da.[ShippingRegionPC]								as [Shipping Region PC],
   da.[ShippingRegionGroup]						    as [Shipping Region Group],
   da.[ShippingGlobalRegion]					        as [Shipping Global Region],
   da.[ShippingCounty]							    as [Shipping County],
   da.[AddressStreet2]							    as [Address Street2],
   da.[AddressStreet3]							    as [Address Street3],
   da.[AddressStreet4]								as [Address Street4],
   da.[Currency]										as [Currency],
   da.[AccountStatus]									as [Account Status],
   da.[AccountStatusReason]					        as [Account Status Reason],
   da.[LineOfBusiness]								as [Line Of Business],
   da.[BusinessUnit]									as [Business Unit],
   da.[TreatTeam]									    as [Treat Team],
   da.[DoctorLocator]							        as [DoctorLocator],
   da.[IndirectCustomerNumber]					    as [Indirect CustomerNumber],
   da.[Longitude]										as [Longitude],
   da.[Lattitude]										as [Lattitude],
   da.[ScannerType]									as [ScannerType],
   da.[SubType]										as [SubType],
   da.[MSA]											as [MSA],
   da.[DMA]										    as [DMA],
   da.[GroupAccountIsTargetable]				        as [GroupAccountIsTargetable],
   da.[InvisalignChannel]								as [Invisalign Channel],
   da.[StudyGroupName]								as [Study GroupName],
   da.[PrivatePractice]								as [Private Practice],
   da.[TranslatedCity]								as [Translated City],
   da.[TranslatedState]							    as [Translated State],
   da.[TranslatedDoctorName]						    as [Translated DoctorName],
   da.[TranslatedName]								as [Translated Name],
   da.[SpecialAccount]								as [Special Account],
   da.[BillingLanguage]							    as [Billing Language],
   da.[CreatedDate]									as [Created Date],
   da.[ModifiedDate]									as [Modified Date],
   da.[ContactPreference]						        as [Contact Preference],
   da.[AccountSegmentation]							as [AccountSegmentation]
FROM [DW].HubAccount ha
inner join [DW].[DimAccount] da
	on ha.[SKAccount] = da.[SKAccount];