CREATE VIEW [TABIRIS].[DimAsset] AS SELECT
	da.[SKAsset]															as [SK Asset],
	da.[Id]																	as [Key Asset],
	da.[SerialNumber]															as [Serial Number],
	da.[WandNumber]															as [Wand Number],
	--convert(date, convert(varchar(8), [CreatedDateKey]), 112)				as [KeyDate Created],
	--convert(date, convert(varchar(8), [InstallDateKey]), 112)				as [KeyDate Install],
	--convert(date, convert(varchar(8), [LastReferencedDateKey]), 112)		as [KeyDate LastReferenced],
	--convert(date, convert(varchar(8), [PurchaseDateKey]), 112)			as [KeyDate Purchase],
	--convert(date, convert(varchar(8), [UsageEndDateKey]), 112)			as [KeyDate UsageEnd],
	--convert(date, convert(varchar(8), [FirstRegistrationDateKey]), 112)	as [KeyDate FirstRegistration],
	--convert(date, convert(varchar(8), [LastRegistrationDateKey]), 112)	as [KeyDate LastRegistration],
	convert(datetime, da.[CreatedDate])										as [Created Date Time],
	convert(datetime, da.[InstallDate])										as [Install Date Time],
	convert(datetime, da.[LastReferencedDate])									as [Last Referenced Date Time],
	convert(datetime, da.[PurchaseDate])										as [Purchase Date Time],
	convert(datetime, da.[UsageEndDate])										as [Usage End Date Time],
	convert(datetime, da.[FirstRegistrationDate])								as [First Registration Date Time],
	convert(datetime, da.[LastRegistrationDate])								as [Last Registration Date Time],
	da.AssetType																as [Asset Type],
	da.MATDescription															as [MAT Description],
	da.SKParent																as [SKParent],													
	da.AccountNumber															as [Account Number],
	da.SKAccount																as [SKAccount],
	da.IsActive																as [Is Active],
	da.AssetKind																as [Asset Kind],
	da.AssetNAme																as [Asset NAme],
	da.ScannerSoftwareType														as [Scanner Software Type],
	da.SoftwareEndDate															as [Software End Date],
	da.SourceSystem															as [SourceSystem],
	da.ProductId																as [ProductId],
	da.[Status]																	as [Status],
	da.[InstalledAccount]														as [Installed Account],

	da.[PGIDate]															as [PGI Date],
	da.[BillToAccount]														as [Bill To Account],
	da.[ShipToAccount]														as [Ship To Account],
	da.[TermMonths]															as [Term Months],
	da.[SAPSalesOrder]														as [SAP Sales Order],
	da.[OpportunityNumber]													as [Opportunity Number],
	da.[PayerAccount]														as [PayerAccount]
FROM [DWIRIS].[HubAsset] ha
inner join [DWIRIS].[DimAsset] da
	on ha.[SKAsset] = da.[SKAsset];