CREATE VIEW [TABIRIS].[DimEntitlement]
AS SELECT  [SKEntitlement]
      ,[KeyEntitlement]
      ,[SourceSystem]
      ,[AccountID]
      ,[SKAccount]
      ,[AssetID]
      ,[SKASset]
      ,[ContractLineItemID]
      ,[CreatedDate]
      ,[CreatedByID]
      ,[SKUserCreatedBy]
      ,[EndDate]
      ,[LastModifiedDate]
      ,[LastModifiedByID]
      ,[SKUserLastModifiedBy]
      ,[Name]
      ,[ServiceContractID]
      ,[StartDate]
      ,[Status]
      ,[Type]
  FROM [DWIRIS].[DimEntitlement];