CREATE VIEW [TABIRIS].[DimOpportunity]
AS select 
				dt.[KeyOpportunity],
				dt.[SKUser],
				dt.[SKAccount],
				dt.[OpportunityName],
				dt.[OpportunityNumber],
				dt.[CommissionDate],
				dt.[ShippedDate],
				dt.[SaleType],
				dt.[OpportunityId_C],
				dt.[GeneratedBy],
				dt.[CloseDate],
				dt.[Amount],
				dt.[ProductName],
				dt.[StageName],
				dt.[DemoDate],
				dt.[ContractLoadDate]
				,dt.[AgreementEffectiveDate]
				,dt.[AlertStatusDate]
				,dt.[AlignSignatureDate]
				,dt.[CancellationDate]
				,dt.[CancellationReason]
				,dt.[CancellationStatus]
				,dt.[Cancelled]
				,dt.[ChildOpportunityId]
				,dt.[ClosedReason]
				,dt.[CompetitorInvolved]
				,dt.[Contact]
				,dt.[ContractSignedDate]
				,dt.[Contracttype]
				,dt.[Country]
				,dt.[CreatedById]
				,dt.[CreatedDate]
				,dt.[CurrencyIsoCode]
				,dt.[DeliveredDate]
				,dt.[Dep]
				,dt.[Description]
				,dt.[Distributor]
				,dt.[ExpectedRevenue]
				,dt.[FundingSource]
				,dt.[GoDigital]
				,dt.[GoDigitalOpp]
				,dt.[HasOpportunityLineItem]
				,dt.[isRefurbishedProduct]
				,dt.[IsDeleted]
				,dt.[iTeroType]
				,dt.[LastModifiedDate]
				,dt.[LeadSource]
				,dt.[LeasingCompany]
				,dt.[Name]
				,dt.[NumberofScanners]
				,dt.[PaymentType]
				,dt.[Probability]
				,dt.[ProductOption]
				,dt.[Promotion]
				,dt.[RecordTypeId]
				,dt.[RequestFormat]
				,dt.[ScannerDemoDate]
				,dt.[ScannerQuantity]
				,dt.[ScannerSalesChannel]
				,dt.[ScannerSN]
				,dt.[SubLeadSource]
				,dt.[SystemModstamp]
				,dt.[TotalQuantity]
				,dt.[TotalOpportunityQuantity]
				,dt.[TradeInSerialNumber]
				,dt.[RoutedDate]
				,dt.[ParentOpportunity]

from DWIRIS.DimOpportunity dt
inner join DWIRIS.HubOpportunity ht
on ht.SKOpportunity = dt.SKOpportunity;