CREATE VIEW [TABIRIS].[DimProposal]
AS select 
	[AccountNumber],
	[ApprovalStage],
	[ProposalPrimary],
	[PrimaryContactId],
	[CreatedDate],
	[ProposalElementScannerType],
	[ProposalName],
	[ServiceFeesPAV],
	[ProposalId],
	[TreatmentCategory],
	[ProposalLastModifiedDate],
	[OpportunityId],
	[ProductName],
	[Quantity1],
	[ProposalQuantity],
	[IsPrimaryLine],
	[LineItemElementScannerType],
	[LineItemName],
	[LineItemLastModifiedDate],
	[ProductCode],
	[OpportunityNumber],
	[IncentiveCode],
	[ListPrice],
	[NetPrice],
	[IsDeleted]
from DWIRIS.DimProposal;