CREATE VIEW [TABIRIS].[DimServiceContract] AS SELECT
	 dt.[SKServiceContract]
	,dt.[KeyServiceContract]
				,dt.[KeyAsset]
				,dt.[KeyAccount]
				,dt.[LineItemNumber]
				,dt.[KeyProduct]
				,dt.[Quantity]
				,dt.[ContractNumber]
				,dt.[Discount]
				,dt.[StartDate]
				,dt.[EndDate]
				,dt.[GrandTotal]
				,dt.[Name]
				,dt.[ParentServiceContractId]
				,dt.[ScannerSerialNumber]
				,dt.[ShipToAccount]
				,dt.[ShippingHandling]
				,dt.[Status]
				,dt.[SubTotal]
				,dt.[Tax]
				,dt.[Term]
				,dt.[TotalPrice]
				,dt.[Type]
FROM [DWIRIS].[HubServiceContract] ht
inner join [DWIRIS].[DimServiceContract] dt
	on ht.[SKServiceContract] = dt.[SKServiceContract]