CREATE VIEW [TABIRIS].[DimTicketComplaint]
AS select	t.[SKTicketComplaint]									as [SK Ticket Complaint]
	,	t.[KeyTicketComplaint]									as [Key Ticket Complaint]
	--,	t.[KeyParentTicket]										as [Key Parent Ticket]
	,	t.[CreatedDate]											as [Created Date]
	,	t.[ClosedDate]											as [Closed Date]
	,	t.[ResolvedDate]										as [Resolved Date]
	,	t.[CancelledDate]										as [Cancelled Date]
	,	t.[ContactFullName]										as [Contact Full Name]
	,	t.[IssueType]											as [Issue Type]
	,	t.[SubIssueType]										as [Sub Issue Type]
	,	t.[IssueAsset]											as [Issue Asset]
	,	t.[LastModifiedDate]									as [Last Modified Date]
	,	t.[Origin]												as [Origin]
	,	t.[Priority]											as [Priority]
	,	t.[Status]												as [Status]
	,	t.[TicketType]											as [Ticket Type]
	,	t.[TicketNumber]										as [Ticket Number]
	,	t.[RecordType]											as [Record Type]
	,	t.[TicketAssignedTo]									as [Ticket Assigned To]
	,	t.[TicketOpenedBy]										as [Ticket Opened By]
	,	t.[AdditionalCommentsOther]								as [Additional Comments Other]
	,	t.[AdditionalInformation]								as [Additional Information]
	,	t.[ComplaintHandlingAndAssessmentDoneBy]				as [Complaint Handling And Assessment Done By]
	,	t.[ComplaintStatus]										as [Complaint Status]
	,	t.[CustomerIssueDescription]							as [Customer Issue Description]
	,	t.[CustomerServiceInitialInvestigation]					as [Customer Service Initial Investigation]
	,	t.[DidEventResultIn]									as [DidEvent Result In]
	,	t.[DuplicateOf]											as [Duplicate Of]
	,	t.[EvaluationImpactLevel]								as [Evaluation Impact Level]
	,	t.[HazardSituation]										as [Hazard Situation]
	,	t.[InvestigationCAPAReference]							as [Investigation CAPA Reference]
	,	t.[InWhatCountry]										as [In What Country]
	,	t.[IsFurtherInvestigationNeeded]						as [Is Further Investigation Needed]
	,	t.[IsRegulatoryNonConformance]							as [Is Regulatory Non Conformance]
	,	t.[IsReportable]										as [Is Reportable]
	,	t.[IsSafety]											as [Is Safety]
	,	t.[IsSafetyOrPotentially]								as [Is Safety Or Potentially]
	,	t.[IsValidComplaint]									as [Is Valid Complaint]
	,	t.[JustificationReportSummary]							as [Justification Report Summary]
	,	t.[RationaleForFurtherInvestigationCAPANotRequired]		as [Rationale For Further Investigation CAPA Not Required]
	,	t.[RiskAnalysisDOC]										as [Risk Analysis DOC]
	,	t.[RootCause]											as [Root Cause]
	,	t.[Category]											as [Category]
	,	t.[ComplaintType]										as [Complaint Type]
	,	t.[ComplaintSubType]									as [Complaint SubType]
from [DWIRIS].[DimTicketComplaint] t
INNER JOIN [DWIRIS].[HubTicketComplaint] ht
	on ht.[SKTicketComplaint] = t.[SKTicketComplaint];