CREATE VIEW [TABIRIS].[DimUser] AS SELECT
	du.[SKUser]										as [SK User],
	du.[KeyUser]									as [Key User],
	du.[UserName]									as [User Name],
	du.[UserType]									as [User Type],
	du.[SourceSystem]								as [Source System],
	du.[FirstName]									as [FirstName],
	du.[LastName]									as [LastName],
	du.[Name]										as [Name],
	du.[Email]										as [Email],
	du.[Alias]										as [Alias],
	du.[Title]										as [Title],
	du.[EmployeeNumber]								as [Employee Number],
	du.[CompanyName]								as [Company Name],
	du.[Department]									as [Department],
	du.[Division]									as [Division],
	du.[EmpHireDate]								as [Employee Hire Date],
	du.[City]										as [City],
	du.[Country]									as [Country],
	du.[Region]										as [Region],
	du.[State]										as [State],
	du.[PostalCode]									as [Postal Code],
	du.[Address]									as [Address],
	du.[Phone]										as [Phone],
	du.[CreatedDate]								as [Created Date],
	du.[AccountId]									as [Account Id],
	du.[MAT_ID]										as [MAT ID],
	du.[IsiTeroRep]									as [Is iTero Rep],
	du.[ManagerId]									as [Manager Id],
	du.[RoleOnTerritory]							as [Role On Territory],
	du.[IsActive]									as [Is Active]
FROM [DWIRIS].[DimUser] du
INNER JOIN [DWIRIS].[HubUser] hu
	on du.[SKUser] = hu.[SKUser];