CREATE VIEW [TABIRIS].[FactTicketComplaint]
AS select	[SKTicketComplaint]												as [SK Ticket Complaint]
	,	[KeyTicketComplaint]											as [Key Ticket Complaint]
	,	[SKAccount]														as [SK Account]
	,	[SKAsset]														as [SK Asset]
	,	[SKUser]														as [SK User]
	,	[SKTeam]														as [SK Team]
	--,	[KeyParentTicket]												as [Key Parent Ticket]
	,	convert(date, convert(varchar(8), nullif([CreatedDateKey], -1)), 112)		as [Created Date]
	,	convert(date, convert(varchar(8), nullif([ClosedDateKey], -1)), 112)		as [Closed Date]
	,	convert(date, convert(varchar(8), nullif([ResolvedDateKey], -1)), 112)		as [Resolved Date]
	,	convert(date, convert(varchar(8), nullif([CancelledDateKey], -1)), 112)		as [Cancelled Date]
	,	[ContactFullName]												as [Contact Full Name]
	,	[ComplaintCount]												as [Complaint Count]
from DWIRIS.DimTicketComplaint;