CREATE TABLE [DW].[DimAccount] (
    [SKAccount]                INT            NOT NULL,
    [ADLSBatchID]              INT            NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)  NOT NULL,
    [LZBatchID]                INT            NOT NULL,
    [DWBatchID]                INT            NOT NULL,
    [DWHash]                   CHAR (40)      NOT NULL,
    [KeyAccount]               NCHAR (18)     NOT NULL,
    [AccountNumber]            NVARCHAR (40)  NULL,
    [AccountName]              NVARCHAR (255) NOT NULL,
    [OwnerID]                  NCHAR (18)     NOT NULL,
    [ParentAccountID]          NCHAR (18)     NULL,
    [ParentAccountNumber]      NVARCHAR (40)  NULL,
    [MailingName]              NVARCHAR (35)  NULL,
    [RecordType]               NVARCHAR (40)  NOT NULL,
    [AccountType]              NVARCHAR (40)  NULL,
    [Phone]                    NVARCHAR (40)  NULL,
    [Fax]                      NVARCHAR (40)  NULL,
    [Website]                  NVARCHAR (255) NULL,
    [Email]                    NVARCHAR (80)  NULL,
    [NotificationEmail]        NVARCHAR (80)  NULL,
    [CustomerGroup]            NVARCHAR (255) NULL,
    [ShippingCity]             NVARCHAR (40)  NULL,
    [ShippingCountry]          NVARCHAR (80)  NULL,
    [ShippingCountryCode]      NVARCHAR (10)  NULL,
    [ShippingStateCode]        NVARCHAR (10)  NULL,
    [ShippingState]            NVARCHAR (80)  NULL,
    [ShippingPostalCode]       NVARCHAR (20)  NULL,
    [ShippingCountryGroup]     NVARCHAR (50)  NULL,
    [ShippingRegionPC]         NVARCHAR (50)  NULL,
    [ShippingRegionGroup]      NVARCHAR (50)  NULL,
    [ShippingGlobalRegion]     NVARCHAR (50)  NULL,
    [ShippingCounty]           NVARCHAR (80)  NULL,
    [AddressStreet1]           NVARCHAR (35)  NULL,
    [AddressStreet2]           NVARCHAR (35)  NULL,
    [AddressStreet3]           NVARCHAR (35)  NULL,
    [AddressStreet4]           NVARCHAR (35)  NULL,
    [Currency]                 NVARCHAR (35)  NULL,
    [AccountStatus]            NVARCHAR (255) NULL,
    [AccountStatusReason]      NVARCHAR (255) NULL,
    [LineOfBusiness]           NVARCHAR (256) NULL,
    [BusinessUnit]             NVARCHAR (255) NULL,
    [TreatTeam]                NVARCHAR (255) NULL,
    [DoctorLocator]            NVARCHAR (255) NULL,
    [IndirectCustomerNumber]   NVARCHAR (50)  NULL,
    [Longitude]                NVARCHAR (40)  NULL,
    [Lattitude]                NVARCHAR (40)  NULL,
    [ScannerType]              NVARCHAR (256) NULL,
    [MATID]                    NVARCHAR (25)  NULL,
    [SubType]                  NVARCHAR (255) NULL,
    [MSA]                      NVARCHAR (50)  NULL,
    [DMA]                      NVARCHAR (100) NULL,
    [GroupAccountIsTargetable] NVARCHAR (255) NULL,
    [InvisalignChannel]        NVARCHAR (255) NULL,
    [StudyGroupName]           NCHAR (18)     NULL,
    [PrivatePractice]          VARCHAR (5)    NULL,
    [TranslatedCity]           NVARCHAR (35)  NULL,
    [TranslatedState]          NVARCHAR (50)  NULL,
    [TranslatedDoctorName]     NVARCHAR (35)  NULL,
    [TranslatedName]           NVARCHAR (35)  NULL,
    [SpecialAccount]           NVARCHAR (255) NULL,
    [BillingLanguage]          NVARCHAR (255) NULL,
    [CreatedDate]              DATETIME2 (7)  NOT NULL,
    [ModifiedDate]             DATETIME2 (7)  NOT NULL,
    [ContactPreference]        NVARCHAR (255) NULL,
    [PricingGroupC]            NCHAR (18)     NULL,
    [SecRegion]                VARCHAR (10)   NULL,
    [AccountSegmentation]      NVARCHAR (510) NULL,
    [AcceptedPrograms]         VARCHAR (4000) NULL,
	[SKParentLevel1]		   INT			  NULL,
	[SKParentLevel2]           INT            NULL,
	[SKParentLevel3]           INT            NULL,
	[InvTerritoryL1]		   NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL1]      NVARCHAR (121) NULL,
	[InvTerritoryL2]           NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL2]      NVARCHAR (121) NULL,
	[InvTerritoryL3]           NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL3]      NVARCHAR (121) NULL,
	[InvTerritoryL4]           NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL4]      NVARCHAR (121) NULL,
	[InvTerritoryL5]           NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL5]      NVARCHAR (121) NULL,
	[InvTerritoryL6]           NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL6]      NVARCHAR (121) NULL,
	[InvTerritoryL7]           NVARCHAR (25)  NULL,
	[InvTerritoryOwnerL7]      NVARCHAR (121) NULL
)
WITH (CLUSTERED INDEX([SKAccount]), DISTRIBUTION = REPLICATE);

