CREATE TABLE [DW].[DimContact] (
    [SKContact]                       INT            NOT NULL,
    [ADLSBatchID]                     INT            NOT NULL,
    [ADLSTimestamp]                   DATETIME2 (0)  NOT NULL,
    [LZBatchID]                       INT            NOT NULL,
    [DWBatchID]                       INT            NOT NULL,
    [DWHash]                          CHAR (40)      NOT NULL,
    [KeyContact]                      NCHAR (18)     NOT NULL,
    [PrimarySKAccount]                INT            NULL,
    [PrimaryAccountID]                NCHAR (18)     NULL,
    [PrimaryAccountNumber]            NVARCHAR (40)  NULL,
    [ContactNumber]                   NVARCHAR (40)  NULL,
    [OwnerID]                         NCHAR (18)     NOT NULL,
    [ContactName]                     NVARCHAR (121) NOT NULL,
    [RecordType]                      NVARCHAR (50)  NULL,
    [ContactType]                     NVARCHAR (255) NULL,
    [LineofBusiness]                  NVARCHAR (50)  NULL,
    [Salutation]                      NVARCHAR (40)  NULL,
    [ContactFirstName]                NVARCHAR (40)  NULL,
    [ContactLastName]                 NVARCHAR (80)  NOT NULL,
    [ProfessionalCategory]            NVARCHAR (50)  NULL,
    [Status]                          NVARCHAR (255) NULL,
    [StatusReason]                    NVARCHAR (255) NULL,
    [LeadSource]                      NVARCHAR (256) NULL,
    [Phone]                           NVARCHAR (40)  NULL,
    [Mobile]                          NVARCHAR (40)  NULL,
    [Fax]                             NVARCHAR (40)  NULL,
    [OtherPhone]                      NVARCHAR (40)  NULL,
    [Email]                           NVARCHAR (80)  NULL,
    [EmailOptout]                     BIT            NULL,
    [DoNotCall]                       BIT            NULL,
    [FaxOptOut]                       BIT            NULL,
    [MailOptOut]                      BIT            NULL,
    [MailingStreet1]                  NVARCHAR (35)  NULL,
    [MailingStreet2]                  NVARCHAR (35)  NULL,
    [MailingStreet3]                  NVARCHAR (35)  NULL,
    [MailingCity]                     NVARCHAR (40)  NULL,
    [MailingState]                    NVARCHAR (50)  NULL,
    [MailingPostalCode]               NVARCHAR (20)  NULL,
    [MailingCountry]                  NVARCHAR (50)  NULL,
    [MailingCountryCode]              NVARCHAR (10)  NULL,
    [MailingCountryGroup]             NVARCHAR (50)  NULL,
    [MailingRegionPC]                 NVARCHAR (50)  NULL,
    [MailingRegionGroup]              NVARCHAR (50)  NULL,
    [MailingGlobalRegion]             NVARCHAR (32)  NULL,
    [AlumniStateCode]                 NVARCHAR (2)   NULL,
    [AlumniUniversity]                NVARCHAR (255) NULL,
    [CEHours]                         INT            NULL,
    [CertificationDate]               DATE           NULL,
    [CertificationLocation]           NVARCHAR (80)  NULL,
    [ClinID]                          NVARCHAR (50)  NULL,
    [Gender]                          NVARCHAR (8)   NULL,
    [GraduationYear]                  INT            NULL,
    [ReactivationDate]                DATE           NULL,
    [ProductEligibility]              NVARCHAR (255) NULL,
    [TimeZone]                        NVARCHAR (80)  NULL,
    [CreatedDate]                     DATETIME2 (7)  NOT NULL,
    [ModifiedDate]                    DATETIME2 (7)  NOT NULL,
    [TeenProviderFlag]                NVARCHAR (8)   NULL,
    [AdvCurrentAdvantageProgram]      NVARCHAR (255) NULL,
    [AdvCurrentAdvantageLevel]        NVARCHAR (255) NULL,
    [AdvCurrentAdvantagePoints]       DECIMAL (18)   NULL,
    [AdvAdditionalPointsForNextLevel] DECIMAL (18)   NULL,
    [AdvRegistrationStatus]           NVARCHAR (64)  NULL,
    [AdvCumulativeTier]               NVARCHAR (30)  NULL,
    [ClincheckLab]                    NVARCHAR (100) NULL,
    [IOScanEnabledDate]               DATE           NULL,
    [EPTOptIn]                        NVARCHAR (10)  NULL,
    [iTeroFusionContractDate]         DATE           NULL,
    [PrivatePracticeClinID]           NVARCHAR (25)  NULL,
    [TPSTermsCondition]               INT            NULL,
    [ProfileCreationDate]             DATETIME2 (7)  NULL,
    [MATContactID]                    NVARCHAR (50)  NULL,
    [EMEASegmentation]                NVARCHAR (50)  NULL,
    [DoctorSegment]                   NVARCHAR (50)  NULL,
    [SecRegion]                       VARCHAR (10)   NULL,
    [AcceptedPrograms]                VARCHAR (4000) NULL,
    CONSTRAINT [PK_DimContact] PRIMARY KEY NONCLUSTERED ([SKContact] ASC) NOT ENFORCED,
    CONSTRAINT [UQ_DimContact_KeyContact] UNIQUE NONCLUSTERED ([KeyContact] ASC) NOT ENFORCED
)
WITH (CLUSTERED INDEX([SKContact]), DISTRIBUTION = REPLICATE);


GO
CREATE NONCLUSTERED INDEX [IX_DimContact_KeyContact]
    ON [DW].[DimContact]([KeyContact] ASC);

