CREATE TABLE [DW].[DimGroupAccount](
	[SKAccount] 			[INT] 				NOT NULL,
	[AccountNumber] 		[NVARCHAR](40)  	NOT NULL,
	[DWBatchId] 			[INT] 				NOT NULL,
	[DWHash]    			[CHAR] (40)      	NOT NULL,
	[SKDSOAccount] 			[INT] 				NOT NULL,
	[DSOAccountNumber] 		[NVARCHAR](40) 		NOT NULL,
	[DSOAccountName] 		[NVARCHAR](128) 	NOT NULL,
	[BDM] 					[NVARCHAR](150)  	NULL,
	[RM] 					[NVARCHAR](150)  	NULL,
	[SM] 					[NVARCHAR](150) 		NULL,
	[ASD] 					[NVARCHAR](150)  	NULL,
	[BDMTerritoryName] 		[NVARCHAR](50)  	NULL,
	[RMTerritoryName] 		[NVARCHAR](50)  	NULL,
	[SMTerritoryName] 		[NVARCHAR](50) 		NULL,
	[ASDTerritoryName] 		[NVARCHAR](50)  	NULL,
	[BDMConcat] 			[NVARCHAR](150)  	NULL,
	[RMConcat] 				[NVARCHAR](150)  	NULL,
	[SMConcat] 				[NVARCHAR](150) 	NULL,
	[ASDConcat] 			[NVARCHAR](150)  	NULL,
	[SKBDMUser]				[INT]				NULL,
	[BDMUserId] 			[NVARCHAR](18) 		NULL,
	[SKRMUser]				[INT]				NULL,
	[RMUserId] 				[NVARCHAR](18) 		NULL,
	[SKSMUser]				[INT]				NULL,
	[SMUserId] 				[NVARCHAR](18) 		NULL,
	[SKASDUser]				[INT]				NULL,
	[ASDUserId] 			[NVARCHAR](18) 		NULL,
	[BDMIdentifier] 		[NVARCHAR](32)  	NULL,
	[RMIdentifier] 			[NVARCHAR](32)  	NULL,
	[ASDIdentifier] 		[NVARCHAR](32)  	NULL,
	[SMIdentifier] 			[NVARCHAR](32) 		NULL,
	[CreatedDate] 			[DATETIME2](0)		NOT	 NULL,
	[ModifiedDate] 			[DATETIME2](0)		NOT	 NULL
)
WITH (CLUSTERED INDEX([SKAccount]), DISTRIBUTION = REPLICATE);
