CREATE TABLE [DW].[DimOrderIDS] (
    [SKOrder]                       BIGINT                                           NOT NULL,
    [ADLSBatchID]                   INT                                              NOT NULL,
    [ADLSTimestamp]                 DATETIME2 (0)                                    NOT NULL,
    [LZBatchID]                     INT                                              NOT NULL,
    [DWBatchID]                     INT                                              NOT NULL,
    [DWHash]                        CHAR (40)                                        NOT NULL,
    [DWHashMainSubset]              CHAR (40)                                            NULL,
    [KeyOrder]                      BIGINT                                           NOT NULL,
    [IDSOrderNumber]                BIGINT                                           NOT NULL,
    [SKContact]                     INT                                              NOT NULL,
    [OrderType]                     VARCHAR (40)                                     NULL,
    [DeliverableType]               VARCHAR (40)                                     NULL,
    [TreatmentCategory]             VARCHAR (40)                                     NULL,
    [TreatmentType]                 VARCHAR (40)                                     NULL,
    [PatientCurrentStageLowerArch]  INT                                              NULL,
    [PatientCurrentStageUpperArch]  INT                                              NULL,
    [LastStaffDiscountUtilizedDate] DATETIME2 (7)                                    NULL,
    [CancelReasonCode]              NVARCHAR (3)                                     NULL,
    [TreatedArches]                 INT                                              NULL,
    [IsIOScan]                      NVARCHAR (3)                                     NULL,
    [ScanType]                      VARCHAR (20)                                     NULL,
    [CaseCode]                      NVARCHAR (50)                                    NULL,
    [SubmissionType]                VARCHAR (6)                                      NULL,
    [SubmitDate]                    DATETIME2 (0)                                    NULL,
    [AMRDate]                       DATETIME2 (0)                                    NULL,
    [FirstCCUDDate]                 DATETIME2 (0)                                    NULL,
    [LastCCUDDate]                  DATETIME2 (0)                                    NULL,
    [FirstCCAADate]                 DATETIME2 (0)                                    NULL,
    [LastCCAADate]                  DATETIME2 (0)                                    NULL,
    [FirstCCMODDate]                DATETIME2 (0)                                    NULL,
    [LastCCMODDate]                 DATETIME2 (0)                                    NULL,
    [CCADate]                       DATETIME2 (0)                                    NULL,
    [ShipmentScheduledDate]         DATETIME2 (0)                                    NULL,
    [ShipmentDate]                  DATETIME2 (0)                                    NULL,
    [CancellationDate]              DATETIME2 (0)                                    NULL,
    [FirstMaterialsRequiredDate]    DATETIME2 (0)                                    NULL,
    [LastMaterialsRequiredDate]     DATETIME2 (0)                                    NULL,
    [ClinicalHoldDate]              DATETIME2 (0)                                    NULL,
    [UnknownOrderConvertedDate]     DATETIME2 (0)                                    NULL,
    [ProductSwitchDate]             DATETIME2 (0)                                    NULL,
    [FirstGenerateMTPDate]          DATETIME2 (0)                                    NULL,
    [LastGenerateMTPDate]           DATETIME2 (0)                                    NULL,
    [TreatmentID]                   INT                                              NULL,
    [EECDDate]                      DATETIME2 (0)                                    NULL,
    [ArchConversion]                VARCHAR (32)                                     NULL,
    [PatientVIPID]                  INT                                              NULL,
    [PatientGender]                 VARCHAR (7)                                      NULL,
    [PatientIsArchived]             VARCHAR (8)                                      NULL,
    [HoldReason]                    NVARCHAR (256)                                   NULL,
    [LoanNumber]                    NVARCHAR (35)                                    NULL,
    [LoanTreatmentFee]              FLOAT (53)                                       NULL,
    [LoanApproveAmount]             FLOAT (53)                                       NULL,
    [ScanOfficeContactSFID]         NVARCHAR (18)                                    NULL,
    [SKAccount]                     INT                                              DEFAULT ((-1)) NOT NULL,
    [SecRegion]                     NVARCHAR (20)                                    DEFAULT ('') NOT NULL,
    ReClinCheckCount                INT                                              NULL,
	[LastAMRDate]                   DATETIME2 (0)                                    NULL,
	[LastCCADate]                   DATETIME2 (0)                                    NULL,
	[TreatmentFeature]				NVARCHAR (50)		                             NULL,
	[OrderCompleteDate]				DATE											 NULL,
	[CCAAAgeing]					VARCHAR (16) 									 NULL,
	[MTP]						    VARCHAR (20) 									 NULL,
	[FullOrPartial]					VARCHAR (10) 									 NULL,
	[_Region]						VARCHAR (32)									 NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([SKOrder]));


GO
CREATE NONCLUSTERED INDEX [IX_DimOrderIDS_KeyOrder]
    ON [DW].[DimOrderIDS]([KeyOrder] ASC);

