CREATE TABLE [DW].[DimOrderSFDC] (
    [SKOrder]                      BIGINT                                             NOT NULL,
    [ADLSBatchID]                  INT                                                NOT NULL,
    [ADLSTimestamp]                DATETIME2 (0)                                      NOT NULL,
    [LZBatchID]                    INT                                                NOT NULL,
    [DWBatchID]                    INT                                                NOT NULL,
    [DWHash]                       CHAR (40)                                          NOT NULL,
    [KeyOrder]                     BIGINT                                             NOT NULL,
    [SFDCOrderNumber]              NCHAR (18)                                         NOT NULL,
    [SFDCOrderName]                NVARCHAR (80)                                      NULL,
    [AMRDate]                      DATE                                               NULL,
    [CancellationDate]             DATE                                               NULL,
    [CCADate]                      DATE                                               NULL,
    [ShipmentDate]                 DATE                                               NULL,
    [SubmitDate]                   DATE                                               NULL,
    [RejectedImpressionsDate]      DATETIME2 (0)                                      NULL,
    [CCUDDate]                     DATETIME2 (0)                                      NULL,
    [CCAADate]                     DATETIME2 (0)                                      NULL,
    [ClinicalHoldDate]             DATETIME2 (0)                                      NULL,
    [ProductType]                  NVARCHAR (128)                                     NULL,
    [AdvantageRebatePeriod]        DATETIME2 (7)                                      NULL,
    [AdvantageRebateQualifiedFlag] VARCHAR (10)                                       NULL,
    [TreatmentCategory]            NVARCHAR (30)                                      NULL,
    [SKContact]                    INT                                                NOT NULL,
    [SKAccountTreatmentLocation]   INT                                                NOT NULL,
    [SKAccountShipTo]              INT                                                NOT NULL,
    [SKAccountBillTo]              INT                                                NOT NULL,
    [SKAccountSoldTo]              INT                                                NOT NULL,
    [SKAccountScanOffice]          INT                                                NOT NULL,
    [SKAccountPayer]               INT                                                NOT NULL,
    [PatientSFDCID]                NCHAR (18)                                         NULL,
    [PatientGender]                NVARCHAR (32)                                      NULL,
    [PatientAge]                   Decimal(18, 0)                                     NULL,
    [PatientIsArchived]            VARCHAR (8)                                        NULL,
    [RefinementFeeDate]            DATE                                               NULL,
    [ListPrice]                    DECIMAL (18, 2)                                    NULL,
    [NetPrice]                     DECIMAL (18, 2)                                    NULL,
    [DiscountAmount]               DECIMAL (19, 2)                                    NULL,
    [TreatmentID]                  NVARCHAR (18)                                      NULL,
    [CurrencyCode]                 NVARCHAR (3)                                       NOT NULL,
    [LICaseSetupDeliverableType]   NVARCHAR (30)                                      NULL,
    [LICaseSetupTreatmentOption]   NVARCHAR (30)                                      NULL,
    [LIAlignerDeliverableType]     NVARCHAR (30)                                      NULL,
    [LIAlignerTreatmentOption]     NVARCHAR (30)                                      NULL,
    [LIAlignerQtyFromSFDC]         DECIMAL (18)                                       NULL,
    [USListPrice]                  DECIMAL (18, 5)                                    NULL,
    [PaymentTerms]                 NVARCHAR (30)                                      NULL,
    [PaymentMethod]                NVARCHAR (30)                                      NULL,
    [HasComplianceIdicator]        NVARCHAR (10)                                      NULL,
    [PatientTypeBrand]             NVARCHAR (10)                                      NULL,
    [PatientType]                  NVARCHAR (32)                                      NULL,
    [ScanType]                     NVARCHAR (255)                                     NULL,
    [AdditionalAlignersUsed]       DECIMAL (18)                                       NULL,
    [TreatmentExpiryDate]          DATE                                               NULL,
    [TreatedArches]                NVARCHAR (255)                                     NULL,
    [UpperQuantity]                DECIMAL (18)                                       NULL,
    [LowerQuantity]                DECIMAL (18)                                       NULL,
    [MAF]                          NVARCHAR (5)                                       NULL,
    [IDSOrderStatus]               NVARCHAR (255)                                     NULL,
    [SKPricingGroupTreatLoc]       INT                                                NULL,
    [SubscriptionPackage]          NVARCHAR (255)                                     NULL,
    [SubscriptionProgram]          NVARCHAR (255)                                     NULL,
    [LICaseSetupProductCode]       NVARCHAR (1300)                                    NULL,
    [LIAlignerProductCode]         NVARCHAR (1300)                                    NULL,
    [ContractNumber]               NVARCHAR (255)                                     NULL,
    [WithinRFDDate]                NVARCHAR (1300)                                    NULL,
    [WithinTEDDate]                NVARCHAR (1300)                                    NULL,
    [HoldReason]                   NVARCHAR (255)                                     NULL,
    [HoldDate]                     DATETIME2 (7)                                      NULL,
    [AARefinementsUsed]            DECIMAL (18, 2)                                    NULL,
    [ReplacementsUsed]             DECIMAL (18, 2)                                    NULL,
    [SecRegion]                    VARCHAR (10)                                       NULL,
	[FirstAMRDate]                 DATE                                               NULL,
	[LastAMRDate]                  DATE                                               NULL,
	[FirstCCADate]                 DATE                                               NULL,
	[LastCCADate]                  DATE                                               NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([SKOrder]));


GO
CREATE NONCLUSTERED INDEX [IX_DimOrderSFDC_KeyOrder]
    ON [DW].[DimOrderSFDC]([KeyOrder] ASC);

