CREATE TABLE [DW].[DimTerritoryHierarchySCD] (
    [SKTerritory]     INT            NOT NULL,
    [KeyTerritory]    NCHAR (18)     NOT NULL,
    [ADLSBatchID]     INT            NOT NULL,
    [ADLSTimestamp]   DATETIME2 (0)  NOT NULL,
    [LZBatchID]       INT            NOT NULL,
    [DWBatchID]       INT            NOT NULL,
    [DWHash]          CHAR (40)      NOT NULL,
    [StartDateSCD]    DATE           NOT NULL,
    [EndDateSCD]      DATE           NOT NULL,
    [TerritoryName]   NVARCHAR (25)  NOT NULL,
    [TerritoryType]   NVARCHAR (80)  NOT NULL,
    [SKUserOwner]     INT            NOT NULL,
    [OwnerUserName]   NVARCHAR (121) NOT NULL,
    [SKTerritoryL7]   INT            NOT NULL,
    [TerritoryNameL7] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL7]   INT            NOT NULL,
    [OwnerUserNameL7] NVARCHAR (121) NOT NULL,
    [SKTerritoryL6]   INT            NOT NULL,
    [TerritoryNameL6] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL6]   INT            NOT NULL,
    [OwnerUserNameL6] NVARCHAR (121) NOT NULL,
    [SKTerritoryL5]   INT            NOT NULL,
    [TerritoryNameL5] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL5]   INT            NOT NULL,
    [OwnerUserNameL5] NVARCHAR (121) NOT NULL,
    [SKTerritoryL4]   INT            NOT NULL,
    [TerritoryNameL4] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL4]   INT            NOT NULL,
    [OwnerUserNameL4] NVARCHAR (121) NOT NULL,
    [SKTerritoryL3]   INT            NOT NULL,
    [TerritoryNameL3] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL3]   INT            NOT NULL,
    [OwnerUserNameL3] NVARCHAR (121) NOT NULL,
    [SKTerritoryL2]   INT            NOT NULL,
    [TerritoryNameL2] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL2]   INT            NOT NULL,
    [OwnerUserNameL2] NVARCHAR (121) NOT NULL,
    [SKTerritoryL1]   INT            NOT NULL,
    [TerritoryNameL1] NVARCHAR (25)  NOT NULL,
    [SKUserOwnerL1]   INT            NOT NULL,
    [OwnerUserNameL1] NVARCHAR (121) NOT NULL,
    CONSTRAINT [PK_DimTerritoryHierarchySCD] PRIMARY KEY NONCLUSTERED ([SKTerritory] ASC, [StartDateSCD] ASC) NOT ENFORCED
)
WITH (CLUSTERED INDEX([SKTerritory]), DISTRIBUTION = REPLICATE);

