CREATE TABLE [SrcINST].[Session] (
    [LZBatchID]                        INT              NOT NULL,
    [ADLSBatchID]                      INT              NOT NULL,
    [ADLSTimestamp]                    DATETIME2 (0)    NOT NULL,
    [session_id]                       UNIQUEIDENTIFIER NOT NULL,
    [session_datetime]                 DATETIME         NULL,
    [parent_session_id]                UNIQUEIDENTIFIER NULL,
    [auto_session_id]                  INT              NOT NULL,
    [machine_id]                       UNIQUEIDENTIFIER NULL,
    [application_name]                 NVARCHAR (255)   NOT NULL,
    [application_version]              NVARCHAR (127)   NULL,
    [application_language]             NVARCHAR (10)    NULL,
    [application_package]              NVARCHAR (10)    NULL,
    [clinician_id]                     NVARCHAR (127)   NULL,
    [lcid]                             INT              NULL,
    [timezone]                         NVARCHAR (6)     NULL,
    [os_version]                       NVARCHAR (127)   NULL,
    [os_service_pack]                  INT              NULL,
    [os_product_type]                  NVARCHAR (255)   NULL,
    [video_card_name]                  NVARCHAR (255)   NULL,
    [video_card_version]               NVARCHAR (255)   NULL,
    [video_card_driver_date]           DATETIME         NULL,
    [video_card_horizontal_resolution] INT              NULL,
    [video_card_vertical_resolution]   INT              NULL,
    [video_card_bits_per_pixel]        INT              NULL,
    [physical_memory_free]             INT              NULL,
    [physical_memory_total]            INT              NULL,
    [processor_name]                   NVARCHAR (255)   NULL,
    [processor_description]            NVARCHAR (255)   NULL,
    [system_model]                     NVARCHAR (255)   NULL,
    [system_manufacturer]              NVARCHAR (255)   NULL,
    [baseboard_product]                NVARCHAR (255)   NULL,
    [baseboard_model]                  NVARCHAR (255)   NULL,
    [baseboard_manufacturer]           NVARCHAR (255)   NULL,
    [mac_address]                      NVARCHAR (30)    NULL,
    [is_user_local_admin]              BIT              NULL,
    [is_UAC_on]                        BIT              NULL,
    [user_name]                        NVARCHAR (255)   NULL,
    [BatchId]                          INT              NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([session_id]));

