CREATE TABLE [SrcMES_FAB_MX1].[AT_AT_REWORK_REASON_CODES] (
    [LZBatchID]                 INT           NOT NULL,
    [ADLSBatchID]               INT           NOT NULL,
    [ADLSTimestamp]             DATETIME2 (0) NOT NULL,
    [atr_key]                   BIGINT        NOT NULL,
    [atr_name]                  NVARCHAR (64) NOT NULL,
    [purge_status]              INT           NULL,
    [creation_time]             DATETIME      NULL,
    [creation_time_u]           DATETIME      NULL,
    [creation_time_z]           NVARCHAR (64) NULL,
    [last_modified_time]        DATETIME      NULL,
    [last_modified_time_u]      DATETIME      NULL,
    [last_modified_time_z]      NVARCHAR (64) NULL,
    [xfr_insert_pid]            INT           NULL,
    [xfr_update_pid]            INT           NULL,
    [trx_id]                    CHAR (38)     NOT NULL,
    [parent_key]                BIGINT        NULL,
    [pd_xfr_update_pid]         INT           NULL,
    [src_xfr_update_pid]        INT           NULL,
    [jobId_S]                   NVARCHAR (80) NULL,
    [lotId_S]                   NVARCHAR (80) NULL,
    [rejectReason_S]            NVARCHAR (80) NULL,
    [reworkDetectionLocation_S] NVARCHAR (80) NULL,
    [unitId_S]                  NVARCHAR (80) NULL,
    [purged]                    INT           NULL,
    [reportingLocation_S]       NVARCHAR (80) NULL,
    [plant_S]                   NVARCHAR (80) NULL,
    [unitCount_I]               BIGINT        NULL,
    [userName_S]                NVARCHAR (80) NULL,
    [deliveryType_S]            NVARCHAR (80) NULL,
    [deliveryTypeCode_I]        BIGINT        NULL,
    [defectCode_I]              BIGINT        NULL,
    [userKey_I]                 BIGINT        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([unitId_S]));

