CREATE TABLE [SrcMES_FAB_MX1].[BATCH] (
    [LZBatchID]              INT            NOT NULL,
    [ADLSBatchID]            INT            NOT NULL,
    [ADLSTimestamp]          DATETIME2 (0)  NOT NULL,
    [batch_key]              BIGINT         NOT NULL,
    [batch_name]             NVARCHAR (128) NOT NULL,
    [container_key]          BIGINT         NULL,
    [container_type]         NVARCHAR (50)  NULL,
    [expiration_time]        DATETIME       NULL,
    [expiration_time_u]      DATETIME       NULL,
    [expiration_time_z]      NVARCHAR (64)  NULL,
    [potency]                NVARCHAR (64)  NULL,
    [quantity]               NVARCHAR (64)  NULL,
    [sublot_sequence_number] INT            NOT NULL,
    [part_key]               BIGINT         NOT NULL,
    [complete]               INT            NOT NULL,
    [category]               NVARCHAR (50)  NULL,
    [description]            NVARCHAR (255) NULL,
    [creator_key]            BIGINT         NOT NULL,
    [creation_time]          DATETIME       NOT NULL,
    [creation_time_u]        DATETIME       NULL,
    [creation_time_z]        NVARCHAR (64)  NULL,
    [last_modifier_key]      BIGINT         NOT NULL,
    [last_modified_time]     DATETIME       NOT NULL,
    [last_modified_time_u]   DATETIME       NULL,
    [last_modified_time_z]   NVARCHAR (64)  NULL,
    [xfr_insert_pid]         INT            NOT NULL,
    [pd_xfr_update_pid]      INT            NOT NULL,
    [src_xfr_update_pid]     INT            NOT NULL,
    [xfr_update_pid]         INT            NOT NULL,
    [trx_id]                 CHAR (38)      NOT NULL,
    [removed_time]           DATETIME       NULL,
    [removed_time_u]         DATETIME       NULL,
    [removed_time_z]         NVARCHAR (64)  NULL,
    [management_style]       INT            NULL,
    [object_type]            INT            NULL,
    [withdraw_batch_name]    NVARCHAR (128) NULL,
    [withdraw_sublot_prefix] NVARCHAR (64)  NULL,
    [working_sublot_prefix]  NVARCHAR (64)  NULL,
    [purged]                 INT            NULL
)
WITH (HEAP, DISTRIBUTION = HASH([batch_key]));

