CREATE TABLE [SrcMES_FAB_MX1].[CARRIER] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [carrier_key]          BIGINT         NOT NULL,
    [carrier]              NVARCHAR (128) NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [image_key]            BIGINT         NULL,
    [capacity]             INT            NULL,
    [quantity]             INT            NULL,
    [location]             NVARCHAR (64)  NULL,
    [parent]               NVARCHAR (128) NULL,
    [parent_compartment]   NVARCHAR (64)  NULL,
    [dscomment]            NVARCHAR (255) NULL,
    [creator_key]          BIGINT         NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modifier_key]    BIGINT         NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [xfr_insert_pid]       INT            NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [xfr_update_pid]       INT            NULL,
    [parent_key]           BIGINT         NULL,
    [carrier_type]         INT            NOT NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [box_count]            INT            NULL,
    [carrier_count]        INT            NULL,
    [lot_count]            INT            NULL,
    [partial_lot_count]    INT            NULL,
    [unit_count]           INT            NULL,
    [update_privilege_key] BIGINT         NULL,
    [delete_privilege_key] BIGINT         NULL,
    [sublot_access_type]   INT            NULL,
    [sublot_capacity]      NVARCHAR (64)  NULL,
    [purged]               INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([carrier_key]));

