CREATE TABLE [SrcMES_FAB_MX1].[DC_LF_QA_SpecialInspection] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [dc_instance_key]      BIGINT         NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time]   DATETIME       NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [is_finished]          TINYINT        NULL,
    [route_name]           NVARCHAR (64)  NULL,
    [route_key]            BIGINT         NULL,
    [route_step_name]      NVARCHAR (64)  NULL,
    [op_name]              NVARCHAR (64)  NULL,
    [user_name]            NVARCHAR (64)  NULL,
    [dscomment]            NVARCHAR (255) NULL,
    [dslocation]           NVARCHAR (64)  NULL,
    [object_key]           BIGINT         NOT NULL,
    [object_name]          NVARCHAR (128) NULL,
    [object_type]          NVARCHAR (64)  NOT NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [pd_xfr_update_pid]    INT            NULL,
    [src_xfr_update_pid]   INT            NULL,
    [AlignerType]          NVARCHAR (256) NULL,
    [approved_by]          NVARCHAR (64)  NULL,
    [approved_comment]     NVARCHAR (255) NULL,
    [Arch]                 NVARCHAR (256) NULL,
    [Defect]               NVARCHAR (64)  NULL,
    [equip_key]            BIGINT         NULL,
    [equip_name]           NVARCHAR (100) NULL,
    [InspectionType]       NVARCHAR (256) NULL,
    [limit_check]          NVARCHAR (8)   NULL,
    [Quantity]             BIGINT         NULL,
    [Shift]                NVARCHAR (256) NULL,
    [updated_by]           NVARCHAR (64)  NULL,
    [updated_comment]      NVARCHAR (255) NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

