CREATE TABLE [SrcMES_FAB_MX1].[DCS] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [dcs_key]              BIGINT         NOT NULL,
    [dcs_name]             NVARCHAR (26)  NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [image_key]            BIGINT         NULL,
    [author]               NVARCHAR (64)  NULL,
    [collection_level]     INT            NOT NULL,
    [inst_list_key]        BIGINT         NULL,
    [creator_key]          BIGINT         NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modifier_key]    BIGINT         NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [version]              INT            NOT NULL,
    [access_level]         INT            NOT NULL,
    [checkout_user_key]    BIGINT         NULL,
    [xfr_insert_pid]       INT            NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [xfr_update_pid]       INT            NULL,
    [static_data]          INT            NOT NULL,
    [rt_dcs_name]          NVARCHAR (30)  NOT NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [update_privilege_key] BIGINT         NULL,
    [delete_privilege_key] BIGINT         NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

