CREATE TABLE [SrcMES_FAB_MX1].[DCS_PARM] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [dcs_key]              BIGINT         NOT NULL,
    [parm]                 NVARCHAR (30)  NOT NULL,
    [type]                 NVARCHAR (50)  NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [image_key]            BIGINT         NULL,
    [text_length]          INT            NULL,
    [text_mask]            NVARCHAR (50)  NULL,
    [upper_boundary]       FLOAT (53)     NULL,
    [upper_spec]           FLOAT (53)     NULL,
    [upper_control]        FLOAT (53)     NULL,
    [target]               FLOAT (53)     NULL,
    [lower_control]        FLOAT (53)     NULL,
    [lower_spec]           FLOAT (53)     NULL,
    [lower_boundary]       FLOAT (53)     NULL,
    [prompt]               NVARCHAR (255) NULL,
    [mandatory]            INT            NOT NULL,
    [inst_list_key]        BIGINT         NULL,
    [xfr_insert_pid]       INT            NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [xfr_update_pid]       INT            NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

