CREATE TABLE [SrcMES_FAB_MX1].[UDA_Sublot] (
    [LZBatchID]             INT           NOT NULL,
    [ADLSBatchID]           INT           NOT NULL,
    [ADLSTimestamp]         DATETIME2 (0) NOT NULL,
    [object_key]            BIGINT        NOT NULL,
    [last_modifier_key]     BIGINT        NOT NULL,
    [last_modified_time]    DATETIME      NOT NULL,
    [last_modified_time_u]  DATETIME      NULL,
    [last_modified_time_z]  NVARCHAR (64) NULL,
    [xfr_insert_pid]        INT           NULL,
    [xfr_update_pid]        INT           NULL,
    [trx_id]                CHAR (38)     NOT NULL,
    [list_key]              BIGINT        NULL,
    [pd_xfr_update_pid]     INT           NULL,
    [src_xfr_update_pid]    INT           NULL,
    [X_jaw_S]               NVARCHAR (5)  NULL,
    [X_type_S]              NVARCHAR (1)  NULL,
    [X_stage_I]             BIGINT        NULL,
    [X_isRework_I]          BIGINT        NULL,
    [X_trayJobId_S]         NVARCHAR (80) NULL,
    [X_parentId_S]          NVARCHAR (20) NULL,
    [purged]                INT           NULL,
    [X_plant_S]             NVARCHAR (20) NULL,
    [X_trayJobKey_I]        BIGINT        NULL,
    [X_parentKey_I]         BIGINT        NULL,
    [X_orderCreationTime_T] DATETIME      NULL,
    [X_orderCreationTime_u] DATETIME      NULL,
    [X_orderCreationTime_z] NVARCHAR (64) NULL,
    [X_deliveryTypeCode_I]  BIGINT        NULL,
    [X_deliveryType_S]      NVARCHAR (80) NULL,
    [X_intJaw_I]            BIGINT        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));

