CREATE TABLE [SrcMES_FAB_MX1].[UDA_Carrier] (
    [LZBatchID]                     INT            NOT NULL,
    [ADLSBatchID]                   INT            NOT NULL,
    [ADLSTimestamp]                 DATETIME2 (0)  NOT NULL,
    [object_key]                    BIGINT         NOT NULL,
    [last_modifier_key]             BIGINT         NOT NULL,
    [last_modified_time]            DATETIME       NOT NULL,
    [last_modified_time_u]          DATETIME       NULL,
    [last_modified_time_z]          NVARCHAR (64)  NULL,
    [xfr_insert_pid]                INT            NULL,
    [xfr_update_pid]                INT            NULL,
    [trx_id]                        CHAR (38)      NOT NULL,
    [list_key]                      BIGINT         NULL,
    [pd_xfr_update_pid]             INT            NULL,
    [src_xfr_update_pid]            INT            NULL,
    [FS_CARRIER_SUPPORT_168]        BIGINT         NULL,
    [FS_FOUNDATION_OBJECT_S]        NVARCHAR (80)  NULL,
    [FS_CARRIER_STORAGE_TYPE_S]     NVARCHAR (80)  NULL,
    [FS_CARRIER_AREA_171]           BIGINT         NULL,
    [FS_CARRIER_PROD_LINE_23]       BIGINT         NULL,
    [FS_CARRIER_WORK_CENTER_51]     BIGINT         NULL,
    [FS_CARRIER_MATERIAL_21]        BIGINT         NULL,
    [FS_CARRIER_ACCESS_TYPE_S]      NVARCHAR (80)  NULL,
    [FS_CARRIER_CAPACITY_V]         NVARCHAR (64)  NULL,
    [FS_CARRIER_EQUIPMENT_12]       BIGINT         NULL,
    [X_conveyorName_S]              NVARCHAR (80)  NULL,
    [X_dateCompleted_S]             NVARCHAR (20)  NULL,
    [X_inFileName_S]                NVARCHAR (80)  NULL,
    [X_outputDirBff_S]              NVARCHAR (256) NULL,
    [X_trayFolder_S]                NVARCHAR (256) NULL,
    [X_slaName_S]                   NVARCHAR (80)  NULL,
    [X_priority_I]                  BIGINT         NULL,
    [X_fabOrderQueryFileLocation_S] NVARCHAR (256) NULL,
    [X_fabUnitCount_I]              BIGINT         NULL,
    [X_fabOrderQueryFileName_S]     NVARCHAR (80)  NULL,
    [X_slaAlert_I]                  BIGINT         NULL,
    [X_isOrphan_I]                  BIGINT         NULL,
    [X_breakdownTray_I]             BIGINT         NULL,
    [purged]                        INT            NULL,
    [X_isCaseJob_I]                 BIGINT         NULL,
    [X_isRework_I]                  BIGINT         NULL,
    [X_plant_S]                     NVARCHAR (20)  NULL,
    [X_gCutType_S]                  NVARCHAR (30)  NULL,
    [X_jobType_I]                   BIGINT         NULL,
    [X_oldestOrderDate_T]           DATETIME       NULL,
    [X_oldestOrderDate_u]           DATETIME       NULL,
    [X_oldestOrderDate_z]           NVARCHAR (64)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));

