CREATE VIEW [DWGlobal].[vDate]
AS SELECT  [SKDate]
      ,[KeyDate]
      ,[Date]
      ,[CalendarDay]
      ,[CalendarMonth]
      ,[CalendarQuarter]
      ,[CalendarYear]
      ,[DayNameLong]
      ,[DayNameShort]
      ,[DayNumberOfWeek]
      ,[DayNumberOfYear]
      ,[DaySuffix]
      ,[FiscalWeek]
      ,[FiscalMonth]
      ,[FiscalQuarter]
      ,[FiscalYear]
      ,[FirstDayOfMonth]
      ,[FirstDayOfQuarter]
      ,[FirstDayOfWeek]
      ,[FirstDayOfYear]
      ,[HolidayName]
      ,[IsHoliday]
      ,[IsLastDayOfMonth]
      ,[IsWeekday]
      ,[LastDayOfMonth]
      ,[LastDayOfQuarter]
      ,[LastDayOfWeek]
      ,[LastDayOfYear]
      ,[MonthNameLong]
      ,[MonthNameShort]
      ,[MonthYear]
      ,[QuarterNameLong]
      ,[QuarterNameShort]
      ,[WeekOfMonth]
      ,[WeekOfYear]
  FROM [DW].[DimDate];