CREATE TABLE [SrcIDS].[tblpuorderstatushistory] (
    [LZBatchID]                      INT            NOT NULL,
    [ADLSBatchID]                    INT            NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)  NOT NULL,
    [order_status_history_id]        INT            NOT NULL,
    [vip_order_id]                   INT            NOT NULL,
    [vip_order_type]                 INT            NOT NULL,
    [treatment_id]                   INT            NOT NULL,
    [event_type]                     NVARCHAR (33)  NULL,
    [tx_submit_date]                 DATETIME2 (7)  NULL,
    [rc_all_materials_received_date] DATETIME2 (7)  NULL,
    [modified_date]                  DATETIME2 (7)  NOT NULL,
    [cc_mod_date]                    DATETIME2 (7)  NULL,
    [cc_accept_date]                 DATETIME2 (7)  NULL,
    [promised_ship_date]             DATETIME2 (7)  NULL,
    [ss_ship_date]                   DATETIME2 (7)  NULL,
    [cancelled_date]                 DATETIME2 (7)  NULL,
    [cancelled_reason]               NVARCHAR (8)   NULL,
    [hold_date]                      DATETIME2 (7)  NULL,
    [hold_reason]                    NVARCHAR (256) NULL,
    [rx_form_id]                     INT            NULL,
    [tx_treated_arches]              INT            NULL,
    [cc_export_id]                   INT            NULL,
    [event_id]                       INT            NULL,
    [cc_mod_count]                   SMALLINT       NULL,
    [tx_ordered_batches]             VARCHAR (8)    NULL,
    [rc_box_expected]                BIT            NULL,
    [rc_received_date]               DATETIME2 (7)  NULL,
    [cc_review_flag]                 INT            NOT NULL,
    [cc_export_date]                 DATETIME2 (7)  NULL,
    [cc_switch_date]                 DATETIME2 (7)  NULL,
    [cc_refer_date]                  DATETIME2 (7)  NULL,
    [ss_tracking_number]             VARCHAR (32)   NULL,
    [cc_count]                       SMALLINT       NULL,
    [rma_number]                     BIGINT         NULL,
    [clincheck_lab_referred_date]    DATETIME2 (7)  NULL,
    [plan_number]                    INT            NULL,
    [mtp_id]                         VARCHAR (255)  NULL,
	[treatment_feature]				 NVARCHAR (50)  NULL,
	[clinstudy_id]				     INT            NULL,
	[clinstudy_status]				 SMALLINT       NULL,
	[event_source]				     NVARCHAR (100) NULL,
	[refined_promised_ship_date]	 DATETIME2 (7)  NULL,
    [_Region]                        VARCHAR (32)   NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([vip_order_id]));

