CREATE TABLE [SrcGoogleBigQuery].[GA_Sessions_LATAM]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](0) NOT NULL,
	[Id] [nvarchar](50) NOT NULL,
	[ClientId] [nvarchar](75) NULL,
	[FullVisitorId] [nvarchar](30) NOT NULL,
	[VisitNumber] [bigint] NULL,
	[VisitId] [bigint] NULL,
	[VisitStartTime] [bigint] NULL,
	[VisitStartDateTime] [datetime] NULL,
	[VisitDate] [datetime] NULL,
	[Visits] [bigint] NULL,
	[NewVisits] [bigint] NULL,
	[hits] [bigint] NULL,
	[PageViews] [bigint] NULL,
	[ScreenViews] [bigint] NULL,
	[TimeonSite] [bigint] NULL,
	[Bounces] [bigint] NULL,
	[AdContent] [nvarchar](4000) NULL,
	[AdGroupId] [bigint] NULL,
	[AdNetworkType] [nvarchar](30) NULL,
	[CampaignId] [bigint] NULL,
	[CreativeId] [bigint] NULL,
	[CriteriaId] [bigint] NULL,
	[CriteriaParameters] [nvarchar](100) NULL,
	[CustomerId] [bigint] NULL,
	[GclId] [nvarchar](150) NULL,
	[IsVideoAd] [bit] NULL,
	[Page] [bigint] NULL,
	[Slot] [nvarchar](50) NULL,
	[BoomUserlistId] [bigint] NULL,
	[Campaign] [nvarchar](400) NULL,
	[CampaignCode] [nvarchar](50) NULL,
	[IsTrueDirect] [bit] NULL,
	[Keyword] [nvarchar](1000) NULL,
	[Medium] [nvarchar](50) NULL,
	[ReferralPath] [nvarchar](4000) NULL,
	[Source] [nvarchar](250) NULL,
	[ChannelGrouping] [nvarchar](50) NULL,
	[SocialEngagementType] [nvarchar](50) NULL,
	[Continent] [nvarchar](20) NULL,
	[SubContinent] [nvarchar](25) NULL,
	[Country] [nvarchar](50) NULL,
	[Region] [nvarchar](100) NULL,
	[Metro] [nvarchar](75) NULL,
	[City] [nvarchar](75) NULL,
	[Latitude] [nvarchar](15) NULL,
	[Longitude] [nvarchar](15) NULL,
	[Browser] [nvarchar](100) NULL,
	[BrowserSize] [nvarchar](25) NULL,
	[BrowserVersion] [nvarchar](50) NULL,
	[DeviceCategory] [nvarchar](25) NULL,
	[MobileDeviceInfo] [nvarchar](100) NULL,
	[MobileDeviceMarketingName] [nvarchar](75) NULL,
	[MobileDeviceModel] [nvarchar](75) NULL,
	[MobileInputSelector] [nvarchar](25) NULL,
	[OperatingSystem] [nvarchar](25) NULL,
	[OperatingSystemVersion] [nvarchar](40) NULL,
	[MobileDeviceBranding] [nvarchar](40) NULL,
	[Language] [nvarchar](60) NULL,
	[ScreenResolution] [nvarchar](25) NULL,
	[Index] [bigint] NULL,
	[Value] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Id] ),
	CLUSTERED COLUMNSTORE INDEX
)