CREATE TABLE [SrcGoogleBigQuery].[GA_Sessionhits_APAC] (
    [LZBatchID]               INT             NOT NULL,
    [ADLSBatchID]             INT             NOT NULL,
    [ADLSTimestamp]           DATETIME2 (0)   NOT NULL,
    [Id]                      NVARCHAR (50)   NOT NULL,
    [ClientId]                NVARCHAR (75)   NULL,
    [FullVisitorId]           NVARCHAR (30)   NOT NULL,
    [VisitNumber]             INT             NULL,
    [VisitId]                 BIGINT          NULL,
    [VisitStartTime]          BIGINT          NULL,
    [VisitStartDateTime]      DATETIME        NULL,
    [VisitDate]               DATETIME        NULL,
    [DataSource]              NVARCHAR (30)   NULL,
    [ExperimentId]            NVARCHAR (30)   NULL,
    [ExperimentVariant]       NVARCHAR (10)   NULL,
    [HitNumber]               INT             NULL,
    [Hour]                    INT             NULL,
    [IsEntrance]              BIT             NULL,
    [IsExit]                  BIT             NULL,
    [IsInteraction]           BIT             NULL,
    [Minute]                  INT             NULL,
    [Time]                    INT             NULL,
    [Referer]                 NVARCHAR (4000) NULL,
    [HasSocialSourceReferral] NVARCHAR (10)   NULL,
    [SocialInteractionAction] NVARCHAR (30)   NULL,
    [SocialNetwork]           NVARCHAR (30)   NULL,
    [Type]                    NVARCHAR (10)   NULL,
    [PagePath]                NVARCHAR (4000) NULL,
    [PagePathLevel1]          NVARCHAR (4000) NULL,
    [PagePathLevel2]          NVARCHAR (4000) NULL,
    [PagePathLevel3]          NVARCHAR (4000) NULL,
    [PagePathLevel4]          NVARCHAR (4000) NULL,
    [Hostname]                NVARCHAR (100)  NULL,
    [PageTitle]               NVARCHAR (2000) NULL,
    [SearchKeyword]           NVARCHAR (200)  NULL,
    [EventCategory]           NVARCHAR (50)   NULL,
    [EventAction]             NVARCHAR (200)  NULL,
    [EventLabel]              NVARCHAR (400)  NULL,
    [EventValue]              INT             NULL,
    [Index]                   INT             NULL,
    [Value]                   NVARCHAR (200)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Id]));

