CREATE TABLE [SrcGoogleBigQuery].[GA_Sessions_US] (
    [LZBatchID]                 INT             NOT NULL,
    [ADLSBatchID]               INT             NOT NULL,
    [ADLSTimestamp]             DATETIME2 (0)   NOT NULL,
    [Id]                        NVARCHAR (50)   NOT NULL,
    [ClientId]                  NVARCHAR (75)   NULL,
    [FullVisitorId]             NVARCHAR (30)   NOT NULL,
    [VisitNumber]               BIGINT          NULL,
    [VisitId]                   BIGINT          NULL,
    [VisitStartTime]            BIGINT          NULL,
    [VisitStartDateTime]        DATETIME        NULL,
    [VisitDate]                 DATETIME        NULL,
    [Visits]                    BIGINT          NULL,
    [NewVisits]                 BIGINT          NULL,
    [hits]                      BIGINT          NULL,
    [PageViews]                 BIGINT          NULL,
    [ScreenViews]               BIGINT          NULL,
    [TimeonSite]                BIGINT          NULL,
    [Bounces]                   BIGINT          NULL,
    [AdContent]                 NVARCHAR (4000) NULL,
    [AdGroupId]                 BIGINT          NULL,
    [AdNetworkType]             NVARCHAR (30)   NULL,
    [CampaignId]                BIGINT          NULL,
    [CreativeId]                BIGINT          NULL,
    [CriteriaId]                BIGINT          NULL,
    [CriteriaParameters]        NVARCHAR (100)  NULL,
    [CustomerId]                BIGINT          NULL,
    [GclId]                     NVARCHAR (150)  NULL,
    [IsVideoAd]                 BIT             NULL,
    [Page]                      BIGINT          NULL,
    [Slot]                      NVARCHAR (50)   NULL,
    [BoomUserlistId]            BIGINT          NULL,
    [Campaign]                  NVARCHAR (400)  NULL,
    [CampaignCode]              NVARCHAR (50)   NULL,
    [IsTrueDirect]              BIT             NULL,
    [Keyword]                   NVARCHAR (1000) NULL,
    [Medium]                    NVARCHAR (50)   NULL,
    [ReferralPath]              NVARCHAR (4000) NULL,
    [Source]                    NVARCHAR (250)  NULL,
    [ChannelGrouping]           NVARCHAR (50)   NULL,
    [SocialEngagementType]      NVARCHAR (50)   NULL,
    [Continent]                 NVARCHAR (20)   NULL,
    [SubContinent]              NVARCHAR (25)   NULL,
    [Country]                   NVARCHAR (50)   NULL,
    [Region]                    NVARCHAR (100)  NULL,
    [Metro]                     NVARCHAR (75)   NULL,
    [City]                      NVARCHAR (75)   NULL,
    [Latitude]                  NVARCHAR (15)   NULL,
    [Longitude]                 NVARCHAR (15)   NULL,
    [Browser]                   NVARCHAR (100)  NULL,
    [BrowserSize]               NVARCHAR (25)   NULL,
    [BrowserVersion]            NVARCHAR (50)   NULL,
    [DeviceCategory]            NVARCHAR (25)   NULL,
    [MobileDeviceInfo]          NVARCHAR (100)  NULL,
    [MobileDeviceMarketingName] NVARCHAR (75)   NULL,
    [MobileDeviceModel]         NVARCHAR (75)   NULL,
    [MobileInputSelector]       NVARCHAR (25)   NULL,
    [OperatingSystem]           NVARCHAR (25)   NULL,
    [OperatingSystemVersion]    NVARCHAR (40)   NULL,
    [MobileDeviceBranding]      NVARCHAR (40)   NULL,
    [Language]                  NVARCHAR (60)   NULL,
    [ScreenResolution]          NVARCHAR (25)   NULL,
    [Index]                     BIGINT          NULL,
    [Value]                     NVARCHAR (4000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Id]));

