CREATE TABLE [SrcGoogleBigQuery].[InsightiPadAppEvents] (
    [LZBatchID]                                  INT            NOT NULL,
    [ADLSBatchID]                                INT            NOT NULL,
    [ADLSTimestamp]                              DATETIME2 (0)  NOT NULL,
    [event_date]                                 NVARCHAR (255) NULL,
    [event_timestamp]                            BIGINT         NOT NULL,
    [event_name]                                 NVARCHAR (255) NOT NULL,
    [event_params_appVersion]                    NVARCHAR (255) NULL,
    [event_params_assetAction]                   NVARCHAR (255) NULL,
    [event_params_assetCategory]                 NVARCHAR (255) NULL,
    [event_params_assetId]                       NVARCHAR (255) NULL,
    [event_params_assetName]                     NVARCHAR (255) NULL,
    [event_params_businessType]                  NVARCHAR (255) NULL,
    [event_params_content_string]                NVARCHAR (255) NULL,
    [event_params_content_type]                  NVARCHAR (255) NULL,
    [event_params_dashboard]                     NVARCHAR (255) NULL,
    [event_params_dataFetchTime]                 NVARCHAR (255) NULL,
    [event_params_dataFetchTimeInSeconds]        BIGINT         NULL,
    [event_params_dateAndTime]                   NVARCHAR (255) NULL,
    [event_params_downloadTime]                  BIGINT         NULL,
    [event_params_engaged_session_event]         BIGINT         NULL,
    [event_params_engagement_time_msec]          BIGINT         NULL,
    [event_params_entrances]                     BIGINT         NULL,
    [event_params_error_value]                   NVARCHAR (255) NULL,
    [event_params_eventId]                       NVARCHAR (255) NULL,
    [event_params_fatal]                         BIGINT         NULL,
    [event_params_firebase_conversion]           BIGINT         NULL,
    [event_params_firebase_error]                BIGINT         NULL,
    [event_params_firebase_event_origin]         NVARCHAR (255) NULL,
    [event_params_firebase_previous_class]       NVARCHAR (255) NULL,
    [event_params_firebase_previous_id]          BIGINT         NULL,
    [event_params_firebase_previous_screen]      NVARCHAR (255) NULL,
    [event_params_firebase_screen]               NVARCHAR (255) NULL,
    [event_params_firebase_screen_class]         NVARCHAR (255) NULL,
    [event_params_firebase_screen_id]            BIGINT         NULL,
    [event_params_format]                        NVARCHAR (255) NULL,
    [event_params_ga_session_id]                 BIGINT         NULL,
    [event_params_ga_session_number]             BIGINT         NULL,
    [event_params_hyperlink]                     NVARCHAR (255) NULL,
    [event_params_lastRefreshTime]               NVARCHAR (255) NULL,
    [event_params_location]                      NVARCHAR (255) NULL,
    [event_params_message_device_time]           BIGINT         NULL,
    [event_params_message_id]                    NVARCHAR (255) NULL,
    [event_params_message_name]                  NVARCHAR (255) NULL,
    [event_params_network]                       NVARCHAR (255) NULL,
    [event_params_networkType]                   NVARCHAR (255) NULL,
    [event_params_Operation]                     NVARCHAR (255) NULL,
    [event_params_page_name]                     NVARCHAR (255) NULL,
    [event_params_previous_app_version]          NVARCHAR (255) NULL,
    [event_params_previous_first_open_count]     BIGINT         NULL,
    [event_params_previous_os_version]           NVARCHAR (255) NULL,
    [event_params_profileType]                   NVARCHAR (255) NULL,
    [event_params_report]                        NVARCHAR (255) NULL,
    [event_params_reportName]                    NVARCHAR (255) NULL,
    [event_params_session_engaged]               BIGINT         NULL,
    [event_params_shareType]                     NVARCHAR (255) NULL,
    [event_params_specialMarketsDocumentType]    NVARCHAR (255) NULL,
    [event_params_timeDuration]                  NVARCHAR (255) NULL,
    [event_params_timePeriod]                    NVARCHAR (255) NULL,
    [event_params_timestamp]                     BIGINT         NULL,
    [event_params_type]                          NVARCHAR (255) NULL,
    [event_params_update_with_analytics]         BIGINT         NULL,
    [event_params_User_Info_AppVersion]          NVARCHAR (255) NULL,
    [event_params_User_Info_CountryName]         NVARCHAR (255) NULL,
    [event_params_User_Info_Username]            NVARCHAR (255) NULL,
    [event_params_userCountry]                   NVARCHAR (255) NULL,
    [event_params_userId]                        NVARCHAR (255) NULL,
    [event_params_userRegion]                    NVARCHAR (255) NULL,
    [event_params_value]                         BIGINT         NULL,
    [event_previous_timestamp]                   BIGINT         NULL,
    [event_value_in_usd]                         NVARCHAR (255) NULL,
    [event_bundle_sequence_id]                   BIGINT         NULL,
    [event_server_timestamp_offset]              BIGINT         NULL,
    [user_id]                                    NVARCHAR (255) NULL,
    [user_pseudo_id]                             NVARCHAR (255) NOT NULL,
    [user_properties_firebase_last_notification] NVARCHAR (255) NULL,
    [user_properties_first_open_time]            BIGINT         NULL,
    [user_properties_ga_session_id]              BIGINT         NULL,
    [user_properties_ga_session_number]          BIGINT         NULL,
    [user_properties_InsightAppVersion]          NVARCHAR (255) NULL,
    [user_properties_SFuserId]                   NVARCHAR (255) NULL,
    [user_properties_user_id]                    NVARCHAR (255) NULL,
    [user_properties_UserCountry]                NVARCHAR (255) NULL,
    [user_properties_UserName]                   NVARCHAR (255) NULL,
    [user_properties_UserProfile]                NVARCHAR (255) NULL,
    [user_properties_UserRegion]                 NVARCHAR (255) NULL,
    [user_properties_UserRole]                   NVARCHAR (255) NULL,
    [user_first_touch_timestamp]                 BIGINT         NULL,
    [revenue]                                    NVARCHAR (255) NULL,
    [category]                                   NVARCHAR (255) NULL,
    [mobile_brand_name]                          NVARCHAR (255) NULL,
    [mobile_model_name]                          NVARCHAR (255) NULL,
    [mobile_os_hardware_model]                   NVARCHAR (255) NULL,
    [operating_system]                           NVARCHAR (255) NULL,
    [operating_system_version]                   NVARCHAR (255) NULL,
    [vendor_id]                                  NVARCHAR (255) NULL,
    [language]                                   NVARCHAR (255) NULL,
    [is_limited_ad_tracking]                     NVARCHAR (255) NULL,
    [time_zone_offset_seconds]                   INT            NULL,
    [continent]                                  NVARCHAR (255) NULL,
    [country]                                    NVARCHAR (255) NULL,
    [region]                                     NVARCHAR (255) NULL,
    [city]                                       NVARCHAR (255) NULL,
    [sub_continent]                              NVARCHAR (255) NULL,
    [metro]                                      NVARCHAR (255) NULL,
    [id]                                         NVARCHAR (255) NULL,
    [version]                                    NVARCHAR (255) NULL,
    [firebase_app_id]                            NVARCHAR (255) NULL,
    [install_source]                             NVARCHAR (255) NULL,
    [name]                                       NVARCHAR (255) NULL,
    [medium]                                     NVARCHAR (255) NULL,
    [source]                                     NVARCHAR (255) NULL,
    [stream_id]                                  NVARCHAR (255) NULL,
    [platform]                                   NVARCHAR (255) NULL,
    [_count]                                     INT            NOT NULL,
    [event_params_valuePropContactId]            NVARCHAR (255) NULL,
    [event_params_valuePropPdfName]              NVARCHAR (255) NULL,
    [event_params_valuePropDoctorCategory]       NVARCHAR (255) NULL,
    [event_params_valuePropAssetName]            NVARCHAR (255) NULL,
    [event_params_valuePropAssetAction]          NVARCHAR (255) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

