CREATE TABLE [SrcGoogleBigQuery].[MyInvisalignAppOther] (
    [LZBatchID]                          INT             NOT NULL,
    [ADLSBatchID]                        INT             NOT NULL,
    [ADLSTimestamp]                      DATETIME2 (0)   NOT NULL,
    [event_timestamp]                    BIGINT          NOT NULL,
    [event_name]                         NVARCHAR (50)   NOT NULL,
    [user_pseudo_id]                     NVARCHAR (50)   NOT NULL,
    [_count]                             INT             NOT NULL,
    [event_date]                         NVARCHAR (20)   NULL,
    [event_params]                       NVARCHAR (4000) NULL,
    [event_previous_timestamp]           BIGINT          NULL,
    [event_value_in_usd]                 NVARCHAR (50)   NULL,
    [event_bundle_sequence_id]           INT             NULL,
    [event_server_timestamp_offset]      BIGINT          NULL,
    [user_id]                            NVARCHAR (50)   NULL,
    [user_properties]                    NVARCHAR (4000) NULL,
    [user_first_touch_timestamp]         BIGINT          NULL,
    [user_ltv]                           NVARCHAR (4000) NULL,
    [device]                             NVARCHAR (4000) NULL,
    [geo]                                NVARCHAR (4000) NULL,
    [app_info]                           NVARCHAR (4000) NULL,
    [traffic_source]                     NVARCHAR (4000) NULL,
    [stream_id]                          NVARCHAR (50)   NULL,
    [platform]                           NVARCHAR (50)   NULL,
    [event_dimensions]                   NVARCHAR (4000) NULL,
    [ecommerce]                          NVARCHAR (4000) NULL,
    [items]                              NVARCHAR (4000) NULL,
    [event_params_firebase_screen_class] NVARCHAR (250)  NULL,
    [event_params_category]              NVARCHAR (250)  NULL,
    [event_params_firebase_screen]       NVARCHAR (250)  NULL,
    [event_params_ga_session_id]         BIGINT          NULL
)
WITH (CLUSTERED INDEX([event_timestamp]), DISTRIBUTION = ROUND_ROBIN);

