CREATE TABLE [SrcGoogleBigQuery].[TakingPhotoEvents] (
    [LZBatchID]                          INT            NOT NULL,
    [ADLSBatchID]                        INT            NOT NULL,
    [ADLSTimestamp]                      DATETIME2 (0)  NOT NULL,
    [event_timestamp]                    BIGINT         NOT NULL,
    [event_name]                         NVARCHAR (255) NOT NULL,
    [user_pseudo_id]                     NVARCHAR (255) NOT NULL,
    [_count]                             INT            NOT NULL,
    [event_date]                         DATE           NULL,
    [event_params_firebase_screen_id]    BIGINT         NULL,
    [event_params_firebase_event_origin] NVARCHAR (255) NULL,
    [event_params_firebase_screen_class] NVARCHAR (255) NULL,
    [event_params_Category]              NVARCHAR (255) NULL,
    [session_id]                         NVARCHAR (255) NULL,
    [did_request_full_session]           BIT            NULL,
    [total_photo_count]                  INT            NULL,
    [retake_photo_type]                  NVARCHAR (255) NULL,
    [stage_id]                           NVARCHAR (255) NULL,
    [timer_started_count]                INT            NULL,
    [seconds_elapsed_before_first_hit]   INT            NULL,
    [overall_seconds_elapsed]            INT            NULL,
    [did_complete_successfully]          BIT            NULL,
    [did_use_front_camera]               BIT            NULL,
    [reasons_seconds_average]            NVARCHAR (255) NULL,
    [reasons_seconds_overall]            NVARCHAR (255) NULL,
    [top_reason_average]                 NVARCHAR (255) NULL,
    [top_reason_overall]                 NVARCHAR (255) NULL,
    [captured_photo_count]               INT            NULL,
    [did_complete_full_session]          BIT            NULL,
    [abandoned_photo_type]               NVARCHAR (255) NULL,
    [event_server_timestamp_offset]      BIGINT         NULL,
    [device_category]                    NVARCHAR (255) NULL,
    [device_mobile_brand_name]           NVARCHAR (255) NULL,
    [device_mobile_model_name]           NVARCHAR (255) NULL,
    [device_mobile_marketing_name]       NVARCHAR (255) NULL,
    [device_mobile_os_hardware_model]    NVARCHAR (255) NULL,
    [device_operating_system]            NVARCHAR (255) NULL,
    [device_operating_system_version]    NVARCHAR (255) NULL,
    [device_vendor_id]                   NVARCHAR (255) NULL,
    [device_advertising_id]              NVARCHAR (255) NULL,
    [device_language]                    NVARCHAR (255) NULL,
    [device_is_limited_ad_tracking]      NVARCHAR (255) NULL,
    [device_time_zone_offset_seconds]    BIGINT         NULL,
    [geo_continent]                      NVARCHAR (255) NULL,
    [geo_country]                        NVARCHAR (255) NULL,
    [geo_region]                         NVARCHAR (255) NULL,
    [geo_city]                           NVARCHAR (255) NULL,
    [geo_sub_continent]                  NVARCHAR (255) NULL,
    [geo_metro]                          NVARCHAR (255) NULL,
    [app_info_id]                        NVARCHAR (255) NULL,
    [app_info_version]                   NVARCHAR (255) NULL,
    [app_info_firebase_app_id]           NVARCHAR (255) NULL,
    [app_info_install_source]            NVARCHAR (255) NULL,
    [traffic_source_name]                NVARCHAR (255) NULL,
    [traffic_source_medium]              NVARCHAR (255) NULL,
    [traffic_source_source]              NVARCHAR (255) NULL,
    [stream_id]                          NVARCHAR (255) NULL,
    [platform]                           NVARCHAR (255) NULL
)
WITH (CLUSTERED INDEX([event_timestamp]), DISTRIBUTION = ROUND_ROBIN);

