--BI-12996 New View
CREATE VIEW [TABSAP].[FactShipments_Materialized_Performance] AS 
SELECT 
  [ADLSTimestamp], 
  [PartitionColumn], 
  [Delivery], 
  [DeliveryItem], 
  [Deliverable Type], 
  [Value Type], 
  [Plant], 
  [Volume unit], 
  [Item Category], 
  [Company Code], 
  [Sales Organization], 
  [DIVISION_KEY], 
  [Shipment Date], 
  [Product Hierarchy], 
  [PROFIT_CENTER_KEY], 
  [Delivered Quantity], 
  [Sales Order Number], 
  [Sales Order Item Number], 
  [Sales Order Key], 
  [Deliverable Quantity], 
  [Total Quantity], 
  [Deliverable Category], 
  [Business Segment], 
  [TotalOrderQuantity], 
  [Volume Segment], 
  [Volume Sub - Segment], 
  [Volume Account], 
  [Volume Quantity], 
  [Volume Quantity Undivided], 
  [Shipment Count], 
  [Volume Count], 
  [Order Quantity], 
  [Order Quantity Undivided], 
  [Order Count], 
  [FoC Quantity], 
  [Segment], 
  [COST_ELMNT_KEY], 
  [VolumeFlag], 
  [Date of MIM], 
  [Reporting Channel], 
  [Reporting Region], 
  [Promotion Bucket], 
  [Equipment Serial Num], 
  [Initiator Company ID], 
  [Material Group 1], 
  [Material Group 2], 
  [Material Group 3], 
  [Material Group 4], 
  [Material Group 5], 
  [Base Unit of Measure], 
  [Sales Unit], 
  [Weight Unit], 
  [Revenue Recognition], 
  [Document Date], 
  [Storage Location], 
  [Treatment Option], 
  [Delete Flag], 
  [Free_Paid], 
  [Material Number], 
  [Compliance Indicator] 
FROM 
  [DWSAP].[FactShipments_Materialized_Performance] 
WHERE 
  [DELETE FLAG] IS NULL;
