CREATE VIEW [TABTOPS].[FactPatientOrder]
AS select	ADLSBatchID
	,	ADLSTimestamp
	,	LZBatchID
	,	DWBatchID
	,	DgnCurrentRowFlag
	,	DgnCancelledDateTime
	,	DgnCCAcceptDateTime
	,	DgnCCModDateTime
	,	DgnCCExportDateTime
	,	DgnCCExportID
	,	DgnCCReferDateTime
	,	DgnCCSwitchDateTime
	,	DgnClincheckLabReferredDateTime
	,	DgnHoldDateTime
	,	DgnWorkOrderNumber
	,	DgnModifiedDateTime
	,	DgnMTPID
	,	DgnOrderStatusHistoryID
	,	DgnPlanNumber
	,	DgnPromisedShipDateTime
	,	DgnRCAllMaterialsReceivedDateTime
	,	DgnRecievedDateTime
	,	DgnRMANumber
	,	DgnSSShipDateTime
	,	DgnSubmitDateTime
	,	DgnSSTrackingNumber
	,	DgnVIPOrderID
	,	IsCCReviewRequired
	,	IsRCBoxExpected
	,	SKCancelledDate
	,	SKCancelledTime
	,	SKCCAcceptDate
	,	SKCCAcceptTime
	,	SKCCExportDate
	,	SKCCExportTime
	,	SKCCModDate
	,	SKCCModTime
	,	SKCCReferDate
	,	SKCCReferTime
	,	SKCCSwitchDate
	,	SKCCSwitchTime
	,	SKClincheckLabReferredDate
	,	SKClincheckLabReferredTime
	,	SKEvent
	,	SKHoldDate
	,	SKHoldTime
	,	SKModifiedDate
	,	SKModifiedTime
	,	SKPromisedShipDate
	,	SKPromisedShipTime
	,	SKRCAllMaterialsReceivedDate
	,	SKRCAllMaterialsReceivedTime
	,	SKRecievedDate
	,	SKRecievedTime
	,	SKSSShipDate
	,	SKSSShipTime
	,	SKSubmitDate
	,	SKSubmitTime
	,	CCCount
	,	CCModCount
	,	OrderedBatches
	,	TreatedArches
	,	DurationToReceivedInMinutes
	,	DurationToCCExportInMinutes
	,	DurationToCCAcceptInMinutes
	,	DurationToShippedInMinutes
from DWTOPS.FactPatientOrder;