CREATE TABLE [SrcMES_Itero].[DC_isr_CI_RTH_Paring] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [dc_instance_key]      BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time]   DATETIME       NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [is_finished]          TINYINT        NULL,
    [route_name]           NVARCHAR (64)  NULL,
    [route_key]            BIGINT         NULL,
    [route_step_name]      NVARCHAR (64)  NULL,
    [op_name]              NVARCHAR (64)  NULL,
    [user_name]            NVARCHAR (64)  NULL,
    [dscomment]            NVARCHAR (255) NULL,
    [dslocation]           NVARCHAR (64)  NULL,
    [object_key]           BIGINT         NOT NULL,
    [object_name]          NVARCHAR (128) NULL,
    [object_type]          NVARCHAR (64)  NOT NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [status]               NVARCHAR (80)  NULL,
    [testComment]          NVARCHAR (80)  NULL,
    [testDescription]      NVARCHAR (80)  NULL,
    [testStatus]           NVARCHAR (80)  NULL,
    [testedDate]           NVARCHAR (80)  NULL,
    [paringUnit]           NVARCHAR (80)  NULL,
    [hiPot]                NVARCHAR (500) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

