CREATE TABLE [SrcMES_Itero].[PART] (
    [LZBatchID]                INT             NOT NULL,
    [ADLSBatchID]              INT             NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)   NOT NULL,
    [part_key]                 BIGINT          NOT NULL,
    [site_num]                 INT             NOT NULL,
    [part_number]              NVARCHAR (64)   NOT NULL,
    [part_revision]            NVARCHAR (64)   NOT NULL,
    [description]              NVARCHAR (255)  NULL,
    [category]                 NVARCHAR (50)   NULL,
    [bom_name]                 NVARCHAR (64)   NULL,
    [bom_revision]             NVARCHAR (64)   NULL,
    [creation_time]            DATETIME        NOT NULL,
    [creation_time_u]          DATETIME        NULL,
    [last_modified_time]       DATETIME        NOT NULL,
    [last_modified_time_u]     DATETIME        NULL,
    [image_key]                BIGINT          NULL,
    [inst_list_key]            BIGINT          NULL,
    [quantity]                 INT             NULL,
    [consumption_duration]     INT             NULL,
    [consumption_type]         NVARCHAR (50)   NULL,
    [bom_tracked_mode]         INT             NULL,
    [creator_key]              BIGINT          NULL,
    [creation_time_z]          NVARCHAR (64)   NULL,
    [last_modifier_key]        BIGINT          NULL,
    [last_modified_time_z]     NVARCHAR (64)   NULL,
    [revived]                  INT             NULL,
    [uda_0]                    NVARCHAR (255)  NULL,
    [uda_1]                    NVARCHAR (255)  NULL,
    [uda_2]                    NVARCHAR (255)  NULL,
    [uda_3]                    NVARCHAR (255)  NULL,
    [uda_4]                    NVARCHAR (255)  NULL,
    [uda_5]                    NVARCHAR (255)  NULL,
    [uda_6]                    NVARCHAR (255)  NULL,
    [uda_7]                    NVARCHAR (255)  NULL,
    [uda_8]                    NVARCHAR (255)  NULL,
    [uda_9]                    NVARCHAR (255)  NULL,
    [xfr_insert_pid]           INT             NULL,
    [xfr_update_pid]           INT             NULL,
    [effectivity_start]        DATETIME        NULL,
    [effectivity_start_u]      DATETIME        NULL,
    [effectivity_start_z]      NVARCHAR (64)   NULL,
    [effectivity_end]          DATETIME        NULL,
    [effectivity_end_u]        DATETIME        NULL,
    [effectivity_end_z]        NVARCHAR (64)   NULL,
    [bill_account_key]         BIGINT          NULL,
    [build_account_key]        BIGINT          NULL,
    [ship_account_key]         BIGINT          NULL,
    [user_account_0]           BIGINT          NULL,
    [shelf_life]               INT             NULL,
    [warranty_period]          INT             NULL,
    [unit_of_measure]          NVARCHAR (64)   NULL,
    [standard_cost]            NUMERIC (23, 9) NULL,
    [trx_id]                   CHAR (38)       NULL,
    [update_privilege_key]     BIGINT          NULL,
    [delete_privilege_key]     BIGINT          NULL,
    [part_ext_revision]        NVARCHAR (64)   NULL,
    [replacement_type]         NVARCHAR (64)   NULL,
    [mixing_type]              INT             NULL,
    [carrier_class_key]        BIGINT          NULL,
    [storage_class_enforced]   INT             NULL,
    [logically_empty_quantity] NVARCHAR (64)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

