CREATE TABLE [SrcMES_Itero].[UNIT] (
    [LZBatchID]                      INT            NOT NULL,
    [ADLSBatchID]                    INT            NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)  NOT NULL,
    [unit_key]                       BIGINT         NOT NULL,
    [site_num]                       INT            NOT NULL,
    [lifecycle]                      NVARCHAR (64)  NOT NULL,
    [serial_number]                  NVARCHAR (128) NOT NULL,
    [lot_key]                        BIGINT         NOT NULL,
    [order_key]                      BIGINT         NOT NULL,
    [order_item_key]                 BIGINT         NOT NULL,
    [promised_time]                  DATETIME       NULL,
    [promised_time_u]                DATETIME       NULL,
    [promised_time_z]                NVARCHAR (64)  NULL,
    [est_remaining_consume_duration] INT            NULL,
    [est_unit_remaining_duration]    INT            NULL,
    [finished_time]                  DATETIME       NULL,
    [finished_time_u]                DATETIME       NULL,
    [finished_time_z]                NVARCHAR (64)  NULL,
    [shipped_time]                   DATETIME       NULL,
    [shipped_time_u]                 DATETIME       NULL,
    [shipped_time_z]                 NVARCHAR (64)  NULL,
    [inst_list_key]                  BIGINT         NULL,
    [note_key]                       BIGINT         NULL,
    [part_number]                    NVARCHAR (64)  NOT NULL,
    [part_revision]                  NVARCHAR (64)  NULL,
    [description]                    NVARCHAR (255) NULL,
    [dscomment]                      NVARCHAR (255) NULL,
    [rework_count]                   INT            NOT NULL,
    [rework_flag]                    INT            NOT NULL,
    [parent_site_num]                INT            NULL,
    [parent_unit_key]                BIGINT         NULL,
    [tbom_key]                       BIGINT         NULL,
    [revived]                        INT            NULL,
    [old_lifecycle]                  INT            NULL,
    [historical_site_num]            INT            NULL,
    [historical_unit_key]            BIGINT         NULL,
    [historical_tbom_key]            BIGINT         NULL,
    [has_revisited_step]             INT            NOT NULL,
    [original_site_num]              INT            NOT NULL,
    [original_unit_key]              BIGINT         NOT NULL,
    [uda_0]                          NVARCHAR (255) NULL,
    [uda_1]                          NVARCHAR (255) NULL,
    [uda_2]                          NVARCHAR (255) NULL,
    [uda_3]                          NVARCHAR (255) NULL,
    [uda_4]                          NVARCHAR (255) NULL,
    [uda_5]                          NVARCHAR (255) NULL,
    [uda_6]                          NVARCHAR (255) NULL,
    [uda_7]                          NVARCHAR (255) NULL,
    [uda_8]                          NVARCHAR (255) NULL,
    [uda_9]                          NVARCHAR (255) NULL,
    [udt_0]                          DATETIME       NULL,
    [udt_0_u]                        DATETIME       NULL,
    [udt_0_z]                        NVARCHAR (64)  NULL,
    [udt_1]                          DATETIME       NULL,
    [udt_1_u]                        DATETIME       NULL,
    [udt_1_z]                        NVARCHAR (64)  NULL,
    [udt_2]                          DATETIME       NULL,
    [udt_2_u]                        DATETIME       NULL,
    [udt_2_z]                        NVARCHAR (64)  NULL,
    [xfr_insert_pid]                 INT            NULL,
    [xfr_update_pid]                 INT            NULL,
    [creation_time]                  DATETIME       NOT NULL,
    [creation_time_u]                DATETIME       NULL,
    [creation_time_z]                NVARCHAR (64)  NULL,
    [last_modified_time]             DATETIME       NOT NULL,
    [last_modified_time_u]           DATETIME       NULL,
    [last_modified_time_z]           NVARCHAR (64)  NULL,
    [stand_alone]                    INT            NOT NULL,
    [bill_account_key]               BIGINT         NULL,
    [build_account_key]              BIGINT         NULL,
    [ship_account_key]               BIGINT         NULL,
    [user_account_0]                 BIGINT         NULL,
    [original_parent_site_num]       INT            NULL,
    [original_parent_unit_key]       BIGINT         NULL,
    [container_key]                  BIGINT         NULL,
    [container_name]                 NVARCHAR (128) NULL,
    [container_type]                 NVARCHAR (50)  NULL,
    [container_sub_type]             INT            NULL,
    [priority]                       INT            NULL,
    [pre_serialized_lot_site_num]    INT            NOT NULL,
    [pre_serialized_lot_key]         BIGINT         NOT NULL,
    [inventory_status]               INT            NOT NULL,
    [on_hand_status]                 INT            NOT NULL,
    [owner_account_key]              BIGINT         NOT NULL,
    [supplier_account_key]           BIGINT         NOT NULL,
    [is_consumed]                    INT            NOT NULL,
    [location]                       NVARCHAR (64)  NULL,
    [tobj_status_key]                BIGINT         NOT NULL,
    [parent_lot_key]                 BIGINT         NULL,
    [trx_id]                         CHAR (38)      NOT NULL,
    [expiration_time]                DATETIME       NULL,
    [expiration_time_u]              DATETIME       NULL,
    [expiration_time_z]              NVARCHAR (64)  NULL
)
WITH (CLUSTERED INDEX([unit_key]), DISTRIBUTION = HASH([unit_key]));

