CREATE TABLE [SrcSAP].[/OPT/VIM_T112] (
    [LZBatchID]       INT           NOT NULL,
    [ADLSBatchID]     INT           NOT NULL,
    [ADLSTimestamp]   DATETIME2 (0) NOT NULL,
    [MANDT]           NVARCHAR (3)  NOT NULL,
    [DUP_GROUPID]     NVARCHAR (4)  NOT NULL,
    [DUP_CHECKTYPE]   NVARCHAR (1)  NOT NULL,
    [DUP_CHECKFM]     NVARCHAR (30) NOT NULL,
    [DUP_CHECKFM_EXT] NVARCHAR (30) NOT NULL,
    [EXTERNAL_SYS]    NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [DUP_GROUPID]), DISTRIBUTION = HASH([DUP_GROUPID]));

