CREATE TABLE [SrcSAP].[/OPT/VIM_T113] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [DUP_GROUPID]   NVARCHAR (4)  NOT NULL,
    [DUP_STEPID]    NVARCHAR (4)  NOT NULL,
    [FIELDNAME]     NVARCHAR (30) NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [DUP_GROUPID], [DUP_STEPID], [FIELDNAME]), DISTRIBUTION = HASH([DUP_GROUPID]));

