CREATE TABLE [SrcSAP].[AFPO]
(
	[LZBatchID] [int] NOT NULL,
	[ADLSBatchID] [int] NOT NULL,
	[ADLSTimestamp] [datetime2](7) NOT NULL,
	[MANDT] [nvarchar](15) NULL,
	[AUFNR] [nvarchar](20) NOT NULL,
	[POSNR] [nvarchar](25) NULL,
	[PSOBS] [nvarchar](10) NULL,
	[QUNUM] [nvarchar](15) NULL,
	[QUPOS] [nvarchar](25) NULL,
	[PROJN] [nvarchar](25) NULL,
	[PLNUM] [nvarchar](15) NULL,
	[STRMP] [nvarchar](15) NULL,
	[ETRMP] [nvarchar](15) NULL,
	[KDAUF] [nvarchar](15) NULL,
	[KDPOS] [nvarchar](25) NULL,
	[KDEIN] [nvarchar](25) NULL,
	[BESKZ] [nvarchar](10) NULL,
	[PSAMG] [decimal](13, 3) NULL,
	[PSMNG] [decimal](13, 3) NULL,
	[WEMNG] [decimal](13, 3) NULL,
	[IAMNG] [decimal](13, 3) NULL,
	[AMEIN] [nvarchar](25) NULL,
	[MEINS] [nvarchar](25) NULL,
	[MATNR] [nvarchar](25) NULL,
	[PAMNG] [decimal](13, 3) NULL,
	[PGMNG] [decimal](13, 3) NULL,
	[KNTTP] [nvarchar](15) NULL,
	[TPAUF] [nvarchar](15) NULL,
	[LTRMI] [nvarchar](15) NULL,
	[LTRMP] [nvarchar](15) NULL,
	[KALNR] [nvarchar](25) NULL,
	[UEBTO] [decimal](10, 2) NULL,
	[UEBTK] [nvarchar](15) NULL,
	[UNTTO] [decimal](10, 2) NULL,
	[INSMK] [nvarchar](15) NULL,
	[WEPOS] [nvarchar](15) NULL,
	[BWTAR] [nvarchar](15) NULL,
	[BWTTY] [nvarchar](15) NULL,
	[PWERK] [nvarchar](15) NULL,
	[LGORT] [nvarchar](15) NULL,
	[UMREZ] [decimal](10, 2) NULL,
	[UMREN] [decimal](10, 2) NULL,
	[WEBAZ] [decimal](10, 2) NULL,
	[ELIKZ] [nvarchar](10) NULL,
	[SAFNR] [nvarchar](15) NULL,
	[VERID] [nvarchar](10) NULL,
	[SERNR] [nvarchar](15) NULL,
	[TECHS] [nvarchar](15) NULL,
	[DWERK] [nvarchar](10) NULL,
	[DAUTY] [nvarchar](25) NULL,
	[DAUAT] [nvarchar](10) NULL,
	[DGLTP] [nvarchar](15) NULL,
	[DGLTS] [nvarchar](15) NULL,
	[DFREI] [nvarchar](100) NULL,
	[DNREL] [nvarchar](10) NULL,
	[VERTO] [nvarchar](10) NULL,
	[SOBKZ] [nvarchar](10) NULL,
	[KZVBR] [nvarchar](10) NULL,
	[WEWRT] [decimal](20, 3) NULL,
	[WEUNB] [nvarchar](10) NULL,
	[ABLAD] [nvarchar](40) NULL,
	[WEMPF] [nvarchar](15) NULL,
	[CHARG] [nvarchar](15) NULL,
	[GSBER] [nvarchar](10) NULL,
	[WEAED] [nvarchar](10) NULL,
	[CUOBJ] [nvarchar](25) NULL,
	[KBNKZ] [nvarchar](10) NULL,
	[ARSNR] [nvarchar](25) NULL,
	[ARSPS] [nvarchar](25) NULL,
	[KRSNR] [nvarchar](25) NULL,
	[KRSPS] [nvarchar](25) NULL,
	[KCKEY] [nvarchar](30) NULL,
	[RTP01] [nvarchar](10) NULL,
	[RTP02] [nvarchar](10) NULL,
	[RTP03] [nvarchar](10) NULL,
	[RTP04] [nvarchar](10) NULL,
	[KSVON] [nvarchar](15) NULL,
	[KSBIS] [nvarchar](15) NULL,
	[OBJNP] [nvarchar](30) NULL,
	[NDISR] [nvarchar](10) NULL,
	[VFMNG] [decimal](20, 3) NULL,
	[GSBTR] [nvarchar](15) NULL,
	[KZAVC] [nvarchar](10) NULL,
	[KZBWS] [nvarchar](10) NULL,
	[XLOEK] [nvarchar](10) NULL,
	[SERNP] [nvarchar](10) NULL,
	[ANZSN] [nvarchar](25) NULL,
	[OBJTYPE] [nvarchar](10) NULL,
	[CH_PROC] [nvarchar](10) NULL,
	[FXPRU] [nvarchar](10) NULL,
	[CUOBJ_ROOT] [nvarchar](25) NULL,
	[BERID] [nvarchar](15) NULL,
	[TECHS_COPY] [nvarchar](15) NULL,
	[SGT_SCAT] [nvarchar](20) NULL,
	[KUNNR2] [nvarchar](15) NULL,
	[MILL_OC_AUFNR_U] [nvarchar](15) NULL,
	[MILL_OC_RUMNG] [decimal](20, 3) NULL,
	[MILL_OC_SORT] [nvarchar](25) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)