CREATE TABLE [SrcSAP].[AGR_USERS] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [AGR_NAME]      NVARCHAR (30) NOT NULL,
    [UNAME]         NVARCHAR (12) NOT NULL,
    [FROM_DAT]      NVARCHAR (8)  NOT NULL,
    [TO_DAT]        NVARCHAR (8)  NOT NULL,
    [EXCLUDE]       NVARCHAR (1)  NOT NULL,
    [CHANGE_DAT]    NVARCHAR (8)  NOT NULL,
    [CHANGE_TIM]    NVARCHAR (6)  NOT NULL,
    [CHANGE_TST]    DECIMAL (15)  NOT NULL,
    [ORG_FLAG]      NVARCHAR (1)  NOT NULL,
    [COL_FLAG]      NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [AGR_NAME], [UNAME], [FROM_DAT], [TO_DAT]), DISTRIBUTION = HASH([AGR_NAME]));

