CREATE TABLE [SrcSAP].[ANKB] (
    [LZBatchID]     INT            NOT NULL,
    [ADLSBatchID]   INT            NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)  NOT NULL,
    [MANDT]         NVARCHAR (3)   NOT NULL,
    [ANLKL]         NVARCHAR (8)   NOT NULL,
    [AFAPL]         NVARCHAR (4)   NOT NULL,
    [AFABE]         NVARCHAR (2)   NOT NULL,
    [BDATU]         NVARCHAR (8)   NOT NULL,
    [ADATU]         NVARCHAR (8)   NOT NULL,
    [ERNAM]         NVARCHAR (12)  NOT NULL,
    [ERDAT]         NVARCHAR (8)   NOT NULL,
    [AENAM]         NVARCHAR (12)  NOT NULL,
    [AEDAT]         NVARCHAR (8)   NOT NULL,
    [XSPEB]         NVARCHAR (1)   NOT NULL,
    [XLOEV]         NVARCHAR (1)   NOT NULL,
    [FELEI]         NVARCHAR (4)   NOT NULL,
    [KTOGR]         NVARCHAR (8)   NOT NULL,
    [XNEGA]         NVARCHAR (1)   NOT NULL,
    [XGWGK]         NVARCHAR (1)   NOT NULL,
    [MINDJ]         NVARCHAR (3)   NOT NULL,
    [MINDP]         NVARCHAR (3)   NOT NULL,
    [MAXDJ]         NVARCHAR (3)   NOT NULL,
    [MAXDP]         NVARCHAR (3)   NOT NULL,
    [INVSL]         NVARCHAR (2)   NOT NULL,
    [AFASL]         NVARCHAR (4)   NOT NULL,
    [NDJAR]         NVARCHAR (3)   NOT NULL,
    [NDPER]         NVARCHAR (3)   NOT NULL,
    [NAPRZ]         DECIMAL (7, 4) NOT NULL,
    [SAPRZ]         DECIMAL (7, 4) NOT NULL,
    [WBIND]         NVARCHAR (5)   NOT NULL,
    [ALIND]         NVARCHAR (5)   NOT NULL,
    [APROP]         DECIMAL (7, 4) NOT NULL,
    [XUNTA]         NVARCHAR (1)   NOT NULL,
    [XAFBE]         NVARCHAR (1)   NOT NULL,
    [ANLGR]         NVARCHAR (12)  NOT NULL,
    [J_1AARVKEY]    NVARCHAR (4)   NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [ANLKL], [AFAPL], [AFABE], [BDATU]), DISTRIBUTION = HASH([ANLKL]));

