CREATE TABLE [SrcSAP].[CABN] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [ATINN]         NVARCHAR (10) NOT NULL,
    [ADZHL]         NVARCHAR (4)  NOT NULL,
    [ATNAM]         NVARCHAR (30) NOT NULL,
    [ATIDN]         NVARCHAR (2)  NOT NULL,
    [ATFOR]         NVARCHAR (4)  NOT NULL,
    [ANZST]         SMALLINT      NOT NULL,
    [ANZDZ]         SMALLINT      NOT NULL,
    [ATVOR]         NVARCHAR (1)  NOT NULL,
    [ATSCH]         NVARCHAR (30) NOT NULL,
    [ATKLE]         NVARCHAR (1)  NOT NULL,
    [ATKON]         NVARCHAR (5)  NOT NULL,
    [ATEND]         NVARCHAR (1)  NOT NULL,
    [ATAEN]         NVARCHAR (1)  NOT NULL,
    [ATKLA]         NVARCHAR (10) NOT NULL,
    [ATERF]         NVARCHAR (1)  NOT NULL,
    [ATEIN]         NVARCHAR (1)  NOT NULL,
    [ATAME]         NVARCHAR (1)  NOT NULL,
    [ATWME]         NVARCHAR (1)  NOT NULL,
    [MSEHI]         NVARCHAR (3)  NOT NULL,
    [ATDIM]         SMALLINT      NOT NULL,
    [ATGLO]         NVARCHAR (1)  NOT NULL,
    [ATGLA]         NVARCHAR (1)  NOT NULL,
    [ATINT]         NVARCHAR (1)  NOT NULL,
    [ATUNS]         NVARCHAR (1)  NOT NULL,
    [ATSON]         NVARCHAR (1)  NOT NULL,
    [ATTAB]         NVARCHAR (30) NOT NULL,
    [ATFEL]         NVARCHAR (30) NOT NULL,
    [ATTEI]         NVARCHAR (30) NOT NULL,
    [ATPRT]         NVARCHAR (30) NOT NULL,
    [ATPRR]         NVARCHAR (40) NOT NULL,
    [ATPRF]         NVARCHAR (30) NOT NULL,
    [ATWRD]         NVARCHAR (1)  NOT NULL,
    [ATFOD]         NVARCHAR (1)  NOT NULL,
    [ATHIE]         NVARCHAR (1)  NOT NULL,
    [ATDEX]         NVARCHAR (1)  NOT NULL,
    [ATFGA]         NVARCHAR (1)  NOT NULL,
    [ATVSC]         NVARCHAR (1)  NOT NULL,
    [ANAME]         NVARCHAR (12) NOT NULL,
    [ADATU]         NVARCHAR (8)  NOT NULL,
    [VNAME]         NVARCHAR (12) NOT NULL,
    [VDATU]         NVARCHAR (8)  NOT NULL,
    [ATXAC]         NVARCHAR (1)  NOT NULL,
    [ATYAC]         NVARCHAR (1)  NOT NULL,
    [ATMST]         NVARCHAR (1)  NOT NULL,
    [ATWSO]         NVARCHAR (1)  NOT NULL,
    [ATBSO]         NVARCHAR (1)  NOT NULL,
    [DATUV]         NVARCHAR (8)  NOT NULL,
    [TECHV]         NVARCHAR (12) NOT NULL,
    [AENNR]         NVARCHAR (12) NOT NULL,
    [LKENZ]         NVARCHAR (1)  NOT NULL,
    [ATWRI]         NVARCHAR (1)  NOT NULL,
    [DOKAR]         NVARCHAR (3)  NOT NULL,
    [DOKNR]         NVARCHAR (25) NOT NULL,
    [DOKVR]         NVARCHAR (2)  NOT NULL,
    [DOKTL]         NVARCHAR (3)  NOT NULL,
    [KNOBJ]         NVARCHAR (18) NOT NULL,
    [ATINP]         NVARCHAR (1)  NOT NULL,
    [ATVIE]         NVARCHAR (1)  NOT NULL,
    [WERKS]         NVARCHAR (4)  NOT NULL,
    [KATALOGART]    NVARCHAR (1)  NOT NULL,
    [AUSWAHLMGE]    NVARCHAR (8)  NOT NULL,
    [ATHKA]         NVARCHAR (1)  NOT NULL,
    [ATHKO]         NVARCHAR (1)  NOT NULL,
    [CLINT]         NVARCHAR (10) NOT NULL,
    [ATTOL]         NVARCHAR (1)  NOT NULL,
    [ATZUS]         NVARCHAR (1)  NOT NULL,
    [ATVPL]         NVARCHAR (1)  NOT NULL,
    [ATAUTH]        NVARCHAR (3)  NOT NULL,
    [COUNTRYGRP]    NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [ATINN], [ADZHL]), DISTRIBUTION = HASH([ADZHL]));

