CREATE TABLE [SrcSAP].[CE110US_D] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [HZDAT]         NVARCHAR (8)    NOT NULL,
    [USNAM]         NVARCHAR (12)   NOT NULL,
    [GJAHR]         NVARCHAR (4)    NOT NULL,
    [PERDE]         NVARCHAR (3)    NOT NULL,
    [WADAT]         NVARCHAR (8)    NOT NULL,
    [FADAT]         NVARCHAR (8)    NOT NULL,
    [BUDAT]         NVARCHAR (8)    NOT NULL,
    [ALTPERIO]      NVARCHAR (7)    NOT NULL,
    [PAPAOBJNR]     NVARCHAR (10)   NOT NULL,
    [PAPASUBNR]     NVARCHAR (4)    NOT NULL,
    [KNDNR]         NVARCHAR (10)   NOT NULL,
    [ARTNR]         NVARCHAR (18)   NOT NULL,
    [FKART]         NVARCHAR (4)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [KURSF]         DECIMAL (9, 5)  NOT NULL,
    [KURSBK]        DECIMAL (9, 5)  NOT NULL,
    [KURSKZ]        DECIMAL (9, 5)  NOT NULL,
    [REC_WAERS]     NVARCHAR (5)    NOT NULL,
    [KAUFN]         NVARCHAR (10)   NOT NULL,
    [KDPOS]         NVARCHAR (6)    NOT NULL,
    [RKAUFNR]       NVARCHAR (12)   NOT NULL,
    [SKOST]         NVARCHAR (10)   NOT NULL,
    [PRZNR]         NVARCHAR (12)   NOT NULL,
    [BUKRS]         NVARCHAR (4)    NOT NULL,
    [KOKRS]         NVARCHAR (4)    NOT NULL,
    [WERKS]         NVARCHAR (4)    NOT NULL,
    [GSBER]         NVARCHAR (4)    NOT NULL,
    [VKORG]         NVARCHAR (4)    NOT NULL,
    [VTWEG]         NVARCHAR (2)    NOT NULL,
    [SPART]         NVARCHAR (2)    NOT NULL,
    [HRKFT]         NVARCHAR (4)    NOT NULL,
    [PLIKZ]         NVARCHAR (1)    NOT NULL,
    [KSTAR]         NVARCHAR (10)   NOT NULL,
    [PSPNR]         NVARCHAR (8)    NOT NULL,
    [KSTRG]         NVARCHAR (12)   NOT NULL,
    [RBELN]         NVARCHAR (10)   NOT NULL,
    [RPOSN]         NVARCHAR (6)    NOT NULL,
    [STO_BELNR]     NVARCHAR (10)   NOT NULL,
    [STO_POSNR]     NVARCHAR (6)    NOT NULL,
    [PRCTR]         NVARCHAR (10)   NOT NULL,
    [PPRCTR]        NVARCHAR (10)   NOT NULL,
    [RKESTATU]      NVARCHAR (10)   NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [COPA_AWTYP]    NVARCHAR (5)    NOT NULL,
    [COPA_AWORG]    NVARCHAR (10)   NOT NULL,
    [COPA_BWZPT]    NVARCHAR (1)    NOT NULL,
    [COPA_AWSYS]    NVARCHAR (10)   NOT NULL,
    [BESKZ]         NVARCHAR (1)    NOT NULL,
    [KDGRP]         NVARCHAR (2)    NOT NULL,
    [KUNRE]         NVARCHAR (10)   NOT NULL,
    [KUNWE]         NVARCHAR (10)   NOT NULL,
    [LAND1]         NVARCHAR (3)    NOT NULL,
    [PSTYV]         NVARCHAR (4)    NOT NULL,
    [VKBUR]         NVARCHAR (4)    NOT NULL,
    [VRTNR]         NVARCHAR (8)    NOT NULL,
    [WWCST]         NVARCHAR (3)    NOT NULL,
    [WWCH2]         NVARCHAR (3)    NOT NULL,
    [WWSIZ]         NVARCHAR (3)    NOT NULL,
    [WWICI]         NVARCHAR (1)    NOT NULL,
    [COPA_KOSTL]    NVARCHAR (10)   NOT NULL,
    [PRODH]         NVARCHAR (18)   NOT NULL,
    [VKGRP]         NVARCHAR (3)    NOT NULL,
    [WW010]         NVARCHAR (2)    NOT NULL,
    [WW021]         NVARCHAR (30)   NOT NULL,
    [WW022]         NVARCHAR (12)   NOT NULL,
    [PLTYP]         NVARCHAR (2)    NOT NULL,
    [MATKL]         NVARCHAR (9)    NOT NULL,
    [BZIRK]         NVARCHAR (6)    NOT NULL,
    [WW023]         NVARCHAR (10)   NOT NULL,
    [KVGR1]         NVARCHAR (3)    NOT NULL,
    [KVGR2]         NVARCHAR (3)    NOT NULL,
    [WW015]         NVARCHAR (2)    NOT NULL,
    [WW025]         NVARCHAR (10)   NOT NULL,
    [WWA01]         NVARCHAR (10)   NOT NULL,
    [WWA02]         NVARCHAR (10)   NOT NULL,
    [AUART]         NVARCHAR (4)    NOT NULL,
    [WW027]         NVARCHAR (10)   NOT NULL,
    [WW028]         NVARCHAR (10)   NOT NULL,
    [WWFT1]         NVARCHAR (18)   NOT NULL,
    [WWFT2]         NVARCHAR (18)   NOT NULL,
    [WWFT3]         NVARCHAR (18)   NOT NULL,
    [WWFT4]         NVARCHAR (18)   NOT NULL,
    [WWFT5]         NVARCHAR (18)   NOT NULL,
    [WWFT6]         NVARCHAR (18)   NOT NULL,
    [WWFT7]         NVARCHAR (18)   NOT NULL,
    [WWFT8]         NVARCHAR (18)   NOT NULL,
    [WWFT9]         NVARCHAR (18)   NOT NULL,
    [AUGRU]         NVARCHAR (3)    NOT NULL,
    [ABGRU]         NVARCHAR (2)    NOT NULL,
    [ABSMG_ME]      NVARCHAR (3)    NOT NULL,
    [ABSMG]         DECIMAL (15, 3) NOT NULL,
    [ERLOS]         DECIMAL (15, 2) NOT NULL,
    [KWKDRB]        DECIMAL (15, 2) NOT NULL,
    [KWMARB]        DECIMAL (15, 2) NOT NULL,
    [MRABA]         DECIMAL (15, 2) NOT NULL,
    [KWMKPR]        DECIMAL (15, 2) NOT NULL,
    [VVOCF]         DECIMAL (15, 2) NOT NULL,
    [VVIPV]         DECIMAL (15, 2) NOT NULL,
    [VVIQV]         DECIMAL (15, 2) NOT NULL,
    [VVRES]         DECIMAL (15, 2) NOT NULL,
    [VVREM]         DECIMAL (15, 2) NOT NULL,
    [VVLSV]         DECIMAL (15, 2) NOT NULL,
    [VVMDI]         DECIMAL (15, 2) NOT NULL,
    [VVMPV]         DECIMAL (15, 2) NOT NULL,
    [VVOPV]         DECIMAL (15, 2) NOT NULL,
    [VVRVA]         DECIMAL (15, 2) NOT NULL,
    [VVFGS]         DECIMAL (15, 2) NOT NULL,
    [RABAT]         DECIMAL (15, 2) NOT NULL,
    [KWSKTO]        DECIMAL (15, 2) NOT NULL,
    [VVMAT]         DECIMAL (15, 2) NOT NULL,
    [VVMEP]         DECIMAL (15, 2) NOT NULL,
    [VVLCV]         DECIMAL (15, 2) NOT NULL,
    [VVMCV]         DECIMAL (15, 2) NOT NULL,
    [VVOCV]         DECIMAL (15, 2) NOT NULL,
    [VVLCF]         DECIMAL (15, 2) NOT NULL,
    [VVMCF]         DECIMAL (15, 2) NOT NULL,
    [VVSCR]         DECIMAL (15, 2) NOT NULL,
    [VWGK]          DECIMAL (15, 2) NOT NULL,
    [VTRGK]         DECIMAL (15, 2) NOT NULL,
    [VVMSK]         DECIMAL (15, 2) NOT NULL,
    [VVRDC]         DECIMAL (15, 2) NOT NULL,
    [VVN10]         DECIMAL (15, 2) NOT NULL,
    [VVN20]         DECIMAL (15, 2) NOT NULL,
    [VVN30]         DECIMAL (15, 2) NOT NULL,
    [VRPRS]         DECIMAL (15, 2) NOT NULL,
    [VV970]         DECIMAL (15, 2) NOT NULL,
    [KWBONI]        DECIMAL (15, 2) NOT NULL,
    [VVY01]         DECIMAL (15, 2) NOT NULL,
    [VVWAR]         DECIMAL (15, 2) NOT NULL,
    [VVMAR]         DECIMAL (15, 2) NOT NULL,
    [VVAPR]         DECIMAL (15, 2) NOT NULL,
    [PRABA]         DECIMAL (15, 2) NOT NULL,
    [VV011]         DECIMAL (15, 2) NOT NULL,
    [VV012]         DECIMAL (15, 2) NOT NULL,
    [VV013]         DECIMAL (15, 2) NOT NULL,
    [VV014]         DECIMAL (15, 2) NOT NULL,
    [VV015]         DECIMAL (15, 2) NOT NULL,
    [VV021]         DECIMAL (15, 2) NOT NULL,
    [VV022]         DECIMAL (15, 2) NOT NULL,
    [VV023]         DECIMAL (15, 2) NOT NULL,
    [VV024]         DECIMAL (15, 2) NOT NULL,
    [VV040]         DECIMAL (15, 2) NOT NULL,
    [STDPR]         DECIMAL (15, 2) NOT NULL,
    [VV061]         DECIMAL (15, 2) NOT NULL,
    [VV062]         DECIMAL (15, 2) NOT NULL,
    [VV063]         DECIMAL (15, 2) NOT NULL,
    [VV064]         DECIMAL (15, 2) NOT NULL,
    [VV065]         DECIMAL (15, 2) NOT NULL,
    [VV071]         DECIMAL (15, 2) NOT NULL,
    [VV072]         DECIMAL (15, 2) NOT NULL,
    [VV073]         DECIMAL (15, 2) NOT NULL,
    [VV074]         DECIMAL (15, 2) NOT NULL,
    [VV075]         DECIMAL (15, 2) NOT NULL,
    [VV076]         DECIMAL (15, 2) NOT NULL,
    [VV077]         DECIMAL (15, 2) NOT NULL,
    [VV078]         DECIMAL (15, 2) NOT NULL,
    [VV002]         DECIMAL (15, 2) NOT NULL,
    [VV010]         DECIMAL (15, 2) NOT NULL,
    [VV016]         DECIMAL (15, 2) NOT NULL,
    [VV019]         DECIMAL (15, 2) NOT NULL,
    [VV020]         DECIMAL (15, 2) NOT NULL,
    [VV031]         DECIMAL (15, 2) NOT NULL,
    [VV032]         DECIMAL (15, 2) NOT NULL,
    [VV033]         DECIMAL (15, 2) NOT NULL,
    [VV034]         DECIMAL (15, 2) NOT NULL,
    [VV035]         DECIMAL (15, 2) NOT NULL,
    [VV036]         DECIMAL (15, 2) NOT NULL,
    [VV041]         DECIMAL (15, 2) NOT NULL,
    [VV042]         DECIMAL (15, 2) NOT NULL,
    [VV043]         DECIMAL (15, 2) NOT NULL,
    [VV044]         DECIMAL (15, 2) NOT NULL,
    [VV066]         DECIMAL (15, 2) NOT NULL,
    [VV067]         DECIMAL (15, 2) NOT NULL,
    [VV068]         DECIMAL (15, 2) NOT NULL,
    [VV069]         DECIMAL (15, 2) NOT NULL,
    [VV070]         DECIMAL (15, 2) NOT NULL,
    [VV910]         DECIMAL (15, 2) NOT NULL,
    [VV950]         DECIMAL (15, 2) NOT NULL,
    [VV081]         DECIMAL (15, 2) NOT NULL,
    [VV082]         DECIMAL (15, 2) NOT NULL,
    [VVD21]         DECIMAL (15, 2) NOT NULL,
    [VVD22]         DECIMAL (15, 2) NOT NULL,
    [VVG21]         DECIMAL (15, 2) NOT NULL,
    [VVR02]         DECIMAL (15, 2) NOT NULL,
    [VV060]         DECIMAL (15, 2) NOT NULL,
    [VVR21]         DECIMAL (15, 2) NOT NULL,
    [VVR10]         DECIMAL (15, 2) NOT NULL,
    [VV051]         DECIMAL (15, 2) NOT NULL,
    [VV052]         DECIMAL (15, 2) NOT NULL,
    [VV053]         DECIMAL (15, 2) NOT NULL,
    [VV054]         DECIMAL (15, 2) NOT NULL,
    [VV055]         DECIMAL (15, 2) NOT NULL,
    [VV056]         DECIMAL (15, 2) NOT NULL,
    [VV057]         DECIMAL (15, 2) NOT NULL,
    [VV058]         DECIMAL (15, 2) NOT NULL,
    [VV059]         DECIMAL (15, 2) NOT NULL,
    [ADLSBatchID]   INT             NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

