CREATE TABLE [SrcSAP].[CE110US_TABLE3] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [ABSMG_ME]      NVARCHAR (3)    NOT NULL,
    [ABSMG]         DECIMAL (15, 3) NOT NULL,
    [ERLOS]         DECIMAL (15, 2) NOT NULL,
    [KWKDRB]        DECIMAL (15, 2) NOT NULL,
    [KWMARB]        DECIMAL (15, 2) NOT NULL,
    [MRABA]         DECIMAL (15, 2) NOT NULL,
    [KWMKPR]        DECIMAL (15, 2) NOT NULL,
    [ABGRU]         NVARCHAR (2)    NOT NULL,
    [AUART]         NVARCHAR (4)    NOT NULL,
    [WW027]         NVARCHAR (10)   NOT NULL,
    [WW028]         NVARCHAR (10)   NOT NULL,
    [WWFT1]         NVARCHAR (18)   NOT NULL,
    [WWFT2]         NVARCHAR (18)   NOT NULL,
    [WWFT3]         NVARCHAR (18)   NOT NULL,
    [WWFT4]         NVARCHAR (18)   NOT NULL,
    [WWFT5]         NVARCHAR (18)   NOT NULL,
    [WWFT6]         NVARCHAR (18)   NOT NULL,
    [WWFT7]         NVARCHAR (18)   NOT NULL,
    [WWFT8]         NVARCHAR (18)   NOT NULL,
    [WWFT9]         NVARCHAR (18)   NOT NULL,
    [AUGRU]         NVARCHAR (3)    NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

