CREATE TABLE [SrcSAP].[CE110US_TABLE1] (
    [LZBatchID]     INT            NOT NULL,
    [ADLSBatchID]   INT            NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)  NOT NULL,
    [MANDT]         NVARCHAR (3)   NOT NULL,
    [PALEDGER]      NVARCHAR (2)   NOT NULL,
    [VRGAR]         NVARCHAR (1)   NOT NULL,
    [VERSI]         NVARCHAR (3)   NOT NULL,
    [PERIO]         NVARCHAR (7)   NOT NULL,
    [PAOBJNR]       NVARCHAR (10)  NOT NULL,
    [PASUBNR]       NVARCHAR (4)   NOT NULL,
    [BELNR]         NVARCHAR (10)  NOT NULL,
    [POSNR]         NVARCHAR (6)   NOT NULL,
    [HZDAT]         NVARCHAR (8)   NOT NULL,
    [USNAM]         NVARCHAR (12)  NOT NULL,
    [GJAHR]         NVARCHAR (4)   NOT NULL,
    [PERDE]         NVARCHAR (3)   NOT NULL,
    [WADAT]         NVARCHAR (8)   NOT NULL,
    [FADAT]         NVARCHAR (8)   NOT NULL,
    [BUDAT]         NVARCHAR (8)   NOT NULL,
    [ALTPERIO]      NVARCHAR (7)   NOT NULL,
    [PAPAOBJNR]     NVARCHAR (10)  NOT NULL,
    [PAPASUBNR]     NVARCHAR (4)   NOT NULL,
    [KNDNR]         NVARCHAR (10)  NOT NULL,
    [ARTNR]         NVARCHAR (18)  NOT NULL,
    [FKART]         NVARCHAR (4)   NOT NULL,
    [FRWAE]         NVARCHAR (5)   NOT NULL,
    [KURSF]         DECIMAL (9, 5) NOT NULL,
    [KURSBK]        DECIMAL (9, 5) NOT NULL,
    [KURSKZ]        DECIMAL (9, 5) NOT NULL,
    [REC_WAERS]     NVARCHAR (5)   NOT NULL,
    [KAUFN]         NVARCHAR (10)  NOT NULL,
    [KDPOS]         NVARCHAR (6)   NOT NULL,
    [RKAUFNR]       NVARCHAR (12)  NOT NULL,
    [SKOST]         NVARCHAR (10)  NOT NULL,
    [PRZNR]         NVARCHAR (12)  NOT NULL,
    [BUKRS]         NVARCHAR (4)   NOT NULL,
    [KOKRS]         NVARCHAR (4)   NOT NULL,
    [WERKS]         NVARCHAR (4)   NOT NULL,
    [GSBER]         NVARCHAR (4)   NOT NULL,
    [VKORG]         NVARCHAR (4)   NOT NULL,
    [VTWEG]         NVARCHAR (2)   NOT NULL,
    [SPART]         NVARCHAR (2)   NOT NULL,
    [HRKFT]         NVARCHAR (4)   NOT NULL,
    [PLIKZ]         NVARCHAR (1)   NOT NULL,
    [KSTAR]         NVARCHAR (10)  NOT NULL,
    [PSPNR]         NVARCHAR (8)   NOT NULL,
    [KSTRG]         NVARCHAR (12)  NOT NULL,
    [RBELN]         NVARCHAR (10)  NOT NULL,
    [RPOSN]         NVARCHAR (6)   NOT NULL,
    [STO_BELNR]     NVARCHAR (10)  NOT NULL,
    [STO_POSNR]     NVARCHAR (6)   NOT NULL,
    [PRCTR]         NVARCHAR (10)  NOT NULL,
    [PPRCTR]        NVARCHAR (10)  NOT NULL,
    [RKESTATU]      NVARCHAR (10)  NOT NULL,
    [TIMESTMP]      DECIMAL (16)   NOT NULL,
    [COPA_AWTYP]    NVARCHAR (5)   NOT NULL,
    [COPA_AWORG]    NVARCHAR (10)  NOT NULL,
    [COPA_BWZPT]    NVARCHAR (1)   NOT NULL,
    [COPA_AWSYS]    NVARCHAR (10)  NOT NULL,
    [BESKZ]         NVARCHAR (1)   NOT NULL,
    [KDGRP]         NVARCHAR (2)   NOT NULL,
    [KUNRE]         NVARCHAR (10)  NOT NULL,
    [KUNWE]         NVARCHAR (10)  NOT NULL,
    [LAND1]         NVARCHAR (3)   NOT NULL,
    [PSTYV]         NVARCHAR (4)   NOT NULL,
    [VKBUR]         NVARCHAR (4)   NOT NULL,
    [VRTNR]         NVARCHAR (8)   NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

