CREATE TABLE [SrcSAP].[CE110US_TABLE5] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [VVSCR]         DECIMAL (15, 2) NOT NULL,
    [VWGK]          DECIMAL (15, 2) NOT NULL,
    [VTRGK]         DECIMAL (15, 2) NOT NULL,
    [VVMSK]         DECIMAL (15, 2) NOT NULL,
    [VVRDC]         DECIMAL (15, 2) NOT NULL,
    [VVN10]         DECIMAL (15, 2) NOT NULL,
    [VVN20]         DECIMAL (15, 2) NOT NULL,
    [VVN30]         DECIMAL (15, 2) NOT NULL,
    [VRPRS]         DECIMAL (15, 2) NOT NULL,
    [VV970]         DECIMAL (15, 2) NOT NULL,
    [KWBONI]        DECIMAL (15, 2) NOT NULL,
    [VVY01]         DECIMAL (15, 2) NOT NULL,
    [VVWAR]         DECIMAL (15, 2) NOT NULL,
    [VVMAR]         DECIMAL (15, 2) NOT NULL,
    [VVAPR]         DECIMAL (15, 2) NOT NULL,
    [PRABA]         DECIMAL (15, 2) NOT NULL,
    [VV011]         DECIMAL (15, 2) NOT NULL,
    [VV012]         DECIMAL (15, 2) NOT NULL,
    [VV013]         DECIMAL (15, 2) NOT NULL,
    [VV014]         DECIMAL (15, 2) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

