CREATE TABLE [SrcSAP].[CE110US_TABLE4] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [VVFGS]         DECIMAL (15, 2) NOT NULL,
    [RABAT]         DECIMAL (15, 2) NOT NULL,
    [KWSKTO]        DECIMAL (15, 2) NOT NULL,
    [VVMAT]         DECIMAL (15, 2) NOT NULL,
    [VVMEP]         DECIMAL (15, 2) NOT NULL,
    [VVLCV]         DECIMAL (15, 2) NOT NULL,
    [VVMCV]         DECIMAL (15, 2) NOT NULL,
    [VVOCV]         DECIMAL (15, 2) NOT NULL,
    [VVLCF]         DECIMAL (15, 2) NOT NULL,
    [VVMCF]         DECIMAL (15, 2) NOT NULL,
    [VVOCF]         DECIMAL (15, 2) NOT NULL,
    [VVIPV]         DECIMAL (15, 2) NOT NULL,
    [VVIQV]         DECIMAL (15, 2) NOT NULL,
    [VVRES]         DECIMAL (15, 2) NOT NULL,
    [VVREM]         DECIMAL (15, 2) NOT NULL,
    [VVLSV]         DECIMAL (15, 2) NOT NULL,
    [VVMDI]         DECIMAL (15, 2) NOT NULL,
    [VVMPV]         DECIMAL (15, 2) NOT NULL,
    [VVOPV]         DECIMAL (15, 2) NOT NULL,
    [VVRVA]         DECIMAL (15, 2) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

