CREATE TABLE [SrcSAP].[CE110US_TABLE6] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [VV015]         DECIMAL (15, 2) NOT NULL,
    [VV021]         DECIMAL (15, 2) NOT NULL,
    [VV022]         DECIMAL (15, 2) NOT NULL,
    [VV023]         DECIMAL (15, 2) NOT NULL,
    [VV024]         DECIMAL (15, 2) NOT NULL,
    [VV040]         DECIMAL (15, 2) NOT NULL,
    [STDPR]         DECIMAL (15, 2) NOT NULL,
    [VV061]         DECIMAL (15, 2) NOT NULL,
    [VV062]         DECIMAL (15, 2) NOT NULL,
    [VV063]         DECIMAL (15, 2) NOT NULL,
    [VV064]         DECIMAL (15, 2) NOT NULL,
    [VV065]         DECIMAL (15, 2) NOT NULL,
    [VV071]         DECIMAL (15, 2) NOT NULL,
    [VV072]         DECIMAL (15, 2) NOT NULL,
    [VV073]         DECIMAL (15, 2) NOT NULL,
    [VV074]         DECIMAL (15, 2) NOT NULL,
    [VV075]         DECIMAL (15, 2) NOT NULL,
    [VV076]         DECIMAL (15, 2) NOT NULL,
    [VV077]         DECIMAL (15, 2) NOT NULL,
    [VV078]         DECIMAL (15, 2) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

