CREATE TABLE [SrcSAP].[CE110US_TABLE7] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [VV002]         DECIMAL (15, 2) NOT NULL,
    [VV010]         DECIMAL (15, 2) NOT NULL,
    [VV016]         DECIMAL (15, 2) NOT NULL,
    [VV019]         DECIMAL (15, 2) NOT NULL,
    [VV020]         DECIMAL (15, 2) NOT NULL,
    [VV031]         DECIMAL (15, 2) NOT NULL,
    [VV032]         DECIMAL (15, 2) NOT NULL,
    [VV033]         DECIMAL (15, 2) NOT NULL,
    [VV034]         DECIMAL (15, 2) NOT NULL,
    [VV035]         DECIMAL (15, 2) NOT NULL,
    [VV036]         DECIMAL (15, 2) NOT NULL,
    [VV041]         DECIMAL (15, 2) NOT NULL,
    [VV042]         DECIMAL (15, 2) NOT NULL,
    [VV043]         DECIMAL (15, 2) NOT NULL,
    [VV044]         DECIMAL (15, 2) NOT NULL,
    [VV066]         DECIMAL (15, 2) NOT NULL,
    [VV067]         DECIMAL (15, 2) NOT NULL,
    [VV068]         DECIMAL (15, 2) NOT NULL,
    [VV069]         DECIMAL (15, 2) NOT NULL,
    [VV070]         DECIMAL (15, 2) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

