CREATE TABLE [SrcSAP].[CE110US_TABLE8] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [PALEDGER]      NVARCHAR (2)    NOT NULL,
    [VRGAR]         NVARCHAR (1)    NOT NULL,
    [VERSI]         NVARCHAR (3)    NOT NULL,
    [PERIO]         NVARCHAR (7)    NOT NULL,
    [PAOBJNR]       NVARCHAR (10)   NOT NULL,
    [PASUBNR]       NVARCHAR (4)    NOT NULL,
    [BELNR]         NVARCHAR (10)   NOT NULL,
    [POSNR]         NVARCHAR (6)    NOT NULL,
    [FRWAE]         NVARCHAR (5)    NOT NULL,
    [TIMESTMP]      DECIMAL (16)    NOT NULL,
    [VV910]         DECIMAL (15, 2) NOT NULL,
    [VV950]         DECIMAL (15, 2) NOT NULL,
    [VV081]         DECIMAL (15, 2) NOT NULL,
    [VV082]         DECIMAL (15, 2) NOT NULL,
    [VVD21]         DECIMAL (15, 2) NOT NULL,
    [VVD22]         DECIMAL (15, 2) NOT NULL,
    [VVG21]         DECIMAL (15, 2) NOT NULL,
    [VVR02]         DECIMAL (15, 2) NOT NULL,
    [VV060]         DECIMAL (15, 2) NOT NULL,
    [VVR21]         DECIMAL (15, 2) NOT NULL,
    [VVR10]         DECIMAL (15, 2) NOT NULL,
    [VV051]         DECIMAL (15, 2) NOT NULL,
    [VV052]         DECIMAL (15, 2) NOT NULL,
    [VV053]         DECIMAL (15, 2) NOT NULL,
    [VV054]         DECIMAL (15, 2) NOT NULL,
    [VV055]         DECIMAL (15, 2) NOT NULL,
    [VV056]         DECIMAL (15, 2) NOT NULL,
    [VV057]         DECIMAL (15, 2) NOT NULL,
    [VV058]         DECIMAL (15, 2) NOT NULL,
    [VV059]         DECIMAL (15, 2) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([BELNR]));

