CREATE TABLE [SrcSAP].[EKKN] (
    [LZBatchID]       INT             NOT NULL,
    [ADLSBatchID]     INT             NOT NULL,
    [ADLSTimestamp]   DATETIME2 (0)   NOT NULL,
    [MANDT]           NVARCHAR (3)    NOT NULL,
    [EBELN]           NVARCHAR (10)   NOT NULL,
    [EBELP]           NVARCHAR (5)    NOT NULL,
    [ZEKKN]           NVARCHAR (2)    NOT NULL,
    [LOEKZ]           NVARCHAR (1)    NOT NULL,
    [AEDAT]           NVARCHAR (8)    NOT NULL,
    [KFLAG]           NVARCHAR (1)    NOT NULL,
    [MENGE]           DECIMAL (13, 3) NOT NULL,
    [VPROZ]           DECIMAL (3, 1)  NOT NULL,
    [NETWR]           DECIMAL (13, 2) NOT NULL,
    [SAKTO]           NVARCHAR (10)   NOT NULL,
    [GSBER]           NVARCHAR (4)    NOT NULL,
    [KOSTL]           NVARCHAR (10)   NOT NULL,
    [PROJN]           NVARCHAR (16)   NOT NULL,
    [VBELN]           NVARCHAR (10)   NOT NULL,
    [VBELP]           NVARCHAR (6)    NOT NULL,
    [VETEN]           NVARCHAR (4)    NOT NULL,
    [KZBRB]           NVARCHAR (1)    NOT NULL,
    [ANLN1]           NVARCHAR (12)   NOT NULL,
    [ANLN2]           NVARCHAR (4)    NOT NULL,
    [AUFNR]           NVARCHAR (12)   NOT NULL,
    [WEMPF]           NVARCHAR (12)   NOT NULL,
    [ABLAD]           NVARCHAR (25)   NOT NULL,
    [KOKRS]           NVARCHAR (4)    NOT NULL,
    [XBKST]           NVARCHAR (1)    NOT NULL,
    [XBAUF]           NVARCHAR (1)    NOT NULL,
    [XBPRO]           NVARCHAR (1)    NOT NULL,
    [EREKZ]           NVARCHAR (1)    NOT NULL,
    [KSTRG]           NVARCHAR (12)   NOT NULL,
    [PAOBJNR]         NVARCHAR (10)   NOT NULL,
    [PRCTR]           NVARCHAR (10)   NOT NULL,
    [PS_PSP_PNR]      NVARCHAR (8)    NOT NULL,
    [NPLNR]           NVARCHAR (12)   NOT NULL,
    [AUFPL]           NVARCHAR (10)   NOT NULL,
    [IMKEY]           NVARCHAR (8)    NOT NULL,
    [APLZL]           NVARCHAR (8)    NOT NULL,
    [VPTNR]           NVARCHAR (10)   NOT NULL,
    [FIPOS]           NVARCHAR (14)   NOT NULL,
    [RECID]           NVARCHAR (2)    NOT NULL,
    [FISTL]           NVARCHAR (16)   NOT NULL,
    [GEBER]           NVARCHAR (10)   NOT NULL,
    [FKBER]           NVARCHAR (16)   NOT NULL,
    [DABRZ]           NVARCHAR (8)    NOT NULL,
    [AUFPL_ORD]       NVARCHAR (10)   NOT NULL,
    [APLZL_ORD]       NVARCHAR (8)    NOT NULL,
    [MWSKZ]           NVARCHAR (2)    NOT NULL,
    [TXJCD]           NVARCHAR (15)   NOT NULL,
    [NAVNW]           DECIMAL (13, 2) NOT NULL,
    [KBLNR]           NVARCHAR (10)   NOT NULL,
    [KBLPOS]          NVARCHAR (3)    NOT NULL,
    [LSTAR]           NVARCHAR (6)    NOT NULL,
    [PRZNR]           NVARCHAR (12)   NOT NULL,
    [GRANT_NBR]       NVARCHAR (20)   NOT NULL,
    [BUDGET_PD]       NVARCHAR (10)   NOT NULL,
    [FM_SPLIT_BATCH]  NVARCHAR (3)    NOT NULL,
    [FM_SPLIT_BEGRU]  NVARCHAR (4)    NOT NULL,
    [AA_FINAL_IND]    NVARCHAR (1)    NOT NULL,
    [AA_FINAL_REASON] NVARCHAR (2)    NOT NULL,
    [AA_FINAL_QTY]    DECIMAL (13, 3) NOT NULL,
    [AA_FINAL_QTY_F]  DECIMAL (15)    NOT NULL,
    [MENGE_F]         DECIMAL (15)    NOT NULL,
    [FMFGUS_KEY]      NVARCHAR (22)   NOT NULL,
    [EGRUP]           NVARCHAR (3)    NOT NULL,
    [VNAME]           NVARCHAR (6)    NOT NULL,
    [TCOBJNR]         NVARCHAR (22)   NOT NULL,
    [DATEOFSERVICE]   NVARCHAR (8)    NOT NULL,
    [NOTAXCORR]       NVARCHAR (1)    NOT NULL,
    [DIFFOPTRATE]     DECIMAL (9, 6)  NOT NULL,
    [HASDIFFOPTRATE]  NVARCHAR (1)    NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [EBELN], [EBELP], [ZEKKN]), DISTRIBUTION = HASH([EBELN]));

