CREATE TABLE [SrcSAP].[EKKO] (
    [LZBatchID]        INT             NOT NULL,
    [ADLSBatchID]      INT             NOT NULL,
    [ADLSTimestamp]    DATETIME2 (0)   NOT NULL,
    [MANDT]            NVARCHAR (3)    NOT NULL,
    [EBELN]            NVARCHAR (10)   NOT NULL,
    [BUKRS]            NVARCHAR (4)    NOT NULL,
    [BSTYP]            NVARCHAR (1)    NOT NULL,
    [BSART]            NVARCHAR (4)    NOT NULL,
    [BSAKZ]            NVARCHAR (1)    NOT NULL,
    [LOEKZ]            NVARCHAR (1)    NOT NULL,
    [STATU]            NVARCHAR (1)    NOT NULL,
    [AEDAT]            NVARCHAR (8)    NOT NULL,
    [ERNAM]            NVARCHAR (12)   NOT NULL,
    [PINCR]            NVARCHAR (5)    NOT NULL,
    [LPONR]            NVARCHAR (5)    NOT NULL,
    [LIFNR]            NVARCHAR (10)   NOT NULL,
    [SPRAS]            NVARCHAR (1)    NOT NULL,
    [ZTERM]            NVARCHAR (4)    NOT NULL,
    [ZBD1T]            DECIMAL (3)     NOT NULL,
    [ZBD2T]            DECIMAL (3)     NOT NULL,
    [ZBD3T]            DECIMAL (3)     NOT NULL,
    [ZBD1P]            DECIMAL (5, 3)  NOT NULL,
    [ZBD2P]            DECIMAL (5, 3)  NOT NULL,
    [EKORG]            NVARCHAR (4)    NOT NULL,
    [EKGRP]            NVARCHAR (3)    NOT NULL,
    [WAERS]            NVARCHAR (5)    NOT NULL,
    [WKURS]            DECIMAL (9, 5)  NOT NULL,
    [KUFIX]            NVARCHAR (1)    NOT NULL,
    [BEDAT]            NVARCHAR (8)    NOT NULL,
    [KDATB]            NVARCHAR (8)    NOT NULL,
    [KDATE]            NVARCHAR (8)    NOT NULL,
    [BWBDT]            NVARCHAR (8)    NOT NULL,
    [ANGDT]            NVARCHAR (8)    NOT NULL,
    [BNDDT]            NVARCHAR (8)    NOT NULL,
    [GWLDT]            NVARCHAR (8)    NOT NULL,
    [AUSNR]            NVARCHAR (10)   NOT NULL,
    [ANGNR]            NVARCHAR (10)   NOT NULL,
    [IHRAN]            NVARCHAR (8)    NOT NULL,
    [IHREZ]            NVARCHAR (12)   NOT NULL,
    [VERKF]            NVARCHAR (30)   NOT NULL,
    [TELF1]            NVARCHAR (16)   NOT NULL,
    [LLIEF]            NVARCHAR (10)   NOT NULL,
    [KUNNR]            NVARCHAR (10)   NOT NULL,
    [KONNR]            NVARCHAR (10)   NOT NULL,
    [ABGRU]            NVARCHAR (2)    NOT NULL,
    [AUTLF]            NVARCHAR (1)    NOT NULL,
    [WEAKT]            NVARCHAR (1)    NOT NULL,
    [RESWK]            NVARCHAR (4)    NOT NULL,
    [LBLIF]            NVARCHAR (10)   NOT NULL,
    [INCO1]            NVARCHAR (3)    NOT NULL,
    [INCO2]            NVARCHAR (28)   NOT NULL,
    [KTWRT]            DECIMAL (15, 2) NOT NULL,
    [SUBMI]            NVARCHAR (10)   NOT NULL,
    [KNUMV]            NVARCHAR (10)   NOT NULL,
    [KALSM]            NVARCHAR (6)    NOT NULL,
    [STAFO]            NVARCHAR (6)    NOT NULL,
    [LIFRE]            NVARCHAR (10)   NOT NULL,
    [EXNUM]            NVARCHAR (10)   NOT NULL,
    [UNSEZ]            NVARCHAR (12)   NOT NULL,
    [LOGSY]            NVARCHAR (10)   NOT NULL,
    [UPINC]            NVARCHAR (5)    NOT NULL,
    [STAKO]            NVARCHAR (1)    NOT NULL,
    [FRGGR]            NVARCHAR (2)    NOT NULL,
    [FRGSX]            NVARCHAR (2)    NOT NULL,
    [FRGKE]            NVARCHAR (1)    NOT NULL,
    [FRGZU]            NVARCHAR (8)    NOT NULL,
    [FRGRL]            NVARCHAR (1)    NOT NULL,
    [LANDS]            NVARCHAR (3)    NOT NULL,
    [LPHIS]            NVARCHAR (1)    NOT NULL,
    [ADRNR]            NVARCHAR (10)   NOT NULL,
    [STCEG_L]          NVARCHAR (3)    NOT NULL,
    [STCEG]            NVARCHAR (20)   NOT NULL,
    [ABSGR]            NVARCHAR (2)    NOT NULL,
    [ADDNR]            NVARCHAR (10)   NOT NULL,
    [KORNR]            NVARCHAR (1)    NOT NULL,
    [MEMORY]           NVARCHAR (1)    NOT NULL,
    [PROCSTAT]         NVARCHAR (2)    NOT NULL,
    [RLWRT]            DECIMAL (15, 2) NOT NULL,
    [REVNO]            NVARCHAR (8)    NOT NULL,
    [SCMPROC]          NVARCHAR (1)    NOT NULL,
    [REASON_CODE]      NVARCHAR (4)    NOT NULL,
    [MEMORYTYPE]       NVARCHAR (1)    NOT NULL,
    [RETTP]            NVARCHAR (1)    NOT NULL,
    [RETPC]            DECIMAL (5, 2)  NOT NULL,
    [DPTYP]            NVARCHAR (4)    NOT NULL,
    [DPPCT]            DECIMAL (5, 2)  NOT NULL,
    [DPAMT]            DECIMAL (11, 2) NOT NULL,
    [DPDAT]            NVARCHAR (8)    NOT NULL,
    [MSR_ID]           NVARCHAR (10)   NOT NULL,
    [HIERARCHY_EXISTS] NVARCHAR (1)    NOT NULL,
    [THRESHOLD_EXISTS] NVARCHAR (1)    NOT NULL,
    [LEGAL_CONTRACT]   NVARCHAR (40)   NOT NULL,
    [DESCRIPTION]      NVARCHAR (40)   NOT NULL,
    [RELEASE_DATE]     NVARCHAR (8)    NOT NULL,
    [VSART]            NVARCHAR (2)    NOT NULL,
    [HANDOVERLOC]      NVARCHAR (10)   NOT NULL,
    [SHIPCOND]         NVARCHAR (2)    NOT NULL,
    [FORCE_ID]         NVARCHAR (32)   NOT NULL,
    [FORCE_CNT]        NVARCHAR (6)    NOT NULL,
    [RELOC_ID]         NVARCHAR (10)   NOT NULL,
    [RELOC_SEQ_ID]     NVARCHAR (4)    NOT NULL,
    [SOURCE_LOGSYS]    NVARCHAR (10)   NOT NULL,
    [ZAPCGK]           NVARCHAR (4)    NOT NULL,
    [APCGK_EXTEND]     NVARCHAR (10)   NOT NULL,
    [ZBAS_DATE]        NVARCHAR (8)    NOT NULL,
    [ZADATTYP]         NVARCHAR (1)    NOT NULL,
    [ZSTART_DAT]       NVARCHAR (8)    NOT NULL,
    [Z_DEV]            DECIMAL (6, 3)  NOT NULL,
    [ZINDANX]          NVARCHAR (1)    NOT NULL,
    [ZLIMIT_DAT]       NVARCHAR (8)    NOT NULL,
    [NUMERATOR]        NVARCHAR (20)   NOT NULL,
    [HASHCAL_BDAT]     NVARCHAR (8)    NOT NULL,
    [HASHCAL]          NVARCHAR (1)    NOT NULL,
    [NEGATIVE]         NVARCHAR (1)    NOT NULL,
    [HASHCAL_EXISTS]   NVARCHAR (4)    NOT NULL,
    [KNOWN_INDEX]      NVARCHAR (1)    NOT NULL,
    [PLC]              NVARCHAR (1)    NOT NULL,
    [SMB]              NVARCHAR (6)    NOT NULL,
    [ECC]              NVARCHAR (7)    NOT NULL,
    [IPP]              NVARCHAR (9)    NOT NULL,
    [CUR]              NVARCHAR (3)    NOT NULL,
    [ECO]              NVARCHAR (13)   NOT NULL,
    [PCO]              NVARCHAR (3)    NOT NULL,
    [DPT]              NVARCHAR (15)   NOT NULL,
    [TOP]              NVARCHAR (2)    NOT NULL,
    [SUS]              NVARCHAR (5)    NOT NULL,
    [PCN]              NVARCHAR (16)   NOT NULL,
    [TRU]              NVARCHAR (20)   NOT NULL,
    [PCY]              NVARCHAR (3)    NOT NULL,
    [PCD]              NVARCHAR (2)    NOT NULL,
    [PBN]              NVARCHAR (14)   NOT NULL,
    [AMN]              NVARCHAR (3)    NOT NULL,
    [DNO]              NVARCHAR (12)   NOT NULL,
    [POSTAT]           NVARCHAR (1)    NOT NULL,
    [VZSKZ]            NVARCHAR (2)    NOT NULL,
    [POHF_TYPE]        NVARCHAR (1)    NOT NULL,
    [EQ_EINDT]         NVARCHAR (8)    NOT NULL,
    [EQ_WERKS]         NVARCHAR (4)    NOT NULL,
    [FIXPO]            NVARCHAR (1)    NOT NULL,
    [EKGRP_ALLOW]      NVARCHAR (1)    NOT NULL,
    [WERKS_ALLOW]      NVARCHAR (1)    NOT NULL,
    [CONTRACT_ALLOW]   NVARCHAR (1)    NOT NULL,
    [PSTYP_ALLOW]      NVARCHAR (1)    NOT NULL,
    [FIXPO_ALLOW]      NVARCHAR (1)    NOT NULL,
    [KEY_ID_ALLOW]     NVARCHAR (1)    NOT NULL,
    [AUREL_ALLOW]      NVARCHAR (1)    NOT NULL,
    [DELPER_ALLOW]     NVARCHAR (1)    NOT NULL,
    [EINDT_ALLOW]      NVARCHAR (1)    NOT NULL,
    [LTSNR_ALLOW]      NVARCHAR (1)    NOT NULL,
    [OTB_LEVEL]        NVARCHAR (1)    NOT NULL,
    [OTB_COND_TYPE]    NVARCHAR (4)    NOT NULL,
    [KEY_ID]           NVARCHAR (16)   NOT NULL,
    [OTB_VALUE]        DECIMAL (17, 2) NOT NULL,
    [OTB_CURR]         NVARCHAR (5)    NOT NULL,
    [OTB_RES_VALUE]    DECIMAL (17, 2) NOT NULL,
    [OTB_SPEC_VALUE]   DECIMAL (17, 2) NOT NULL,
    [SPR_RSN_PROFILE]  NVARCHAR (4)    NOT NULL,
    [BUDG_TYPE]        NVARCHAR (2)    NOT NULL,
    [OTB_STATUS]       NVARCHAR (1)    NOT NULL,
    [OTB_REASON]       NVARCHAR (3)    NOT NULL,
    [CHECK_TYPE]       NVARCHAR (1)    NOT NULL,
    [CON_OTB_REQ]      NVARCHAR (1)    NOT NULL,
    [CON_PREBOOK_LEV]  NVARCHAR (1)    NOT NULL,
    [CON_DISTR_LEV]    NVARCHAR (1)    NOT NULL,
    [ZZCOMMENTS]       NVARCHAR (1)    NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [EBELN]), DISTRIBUTION = HASH([EBELN]));

