CREATE TABLE [SrcSAP].[KONV] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [KNUMV]         NVARCHAR (10)   NOT NULL,
    [KPOSN]         NVARCHAR (6)    NOT NULL,
    [STUNR]         NVARCHAR (3)    NOT NULL,
    [ZAEHK]         NVARCHAR (2)    NOT NULL,
    [KAPPL]         NVARCHAR (2)    NOT NULL,
    [KSCHL]         NVARCHAR (4)    NOT NULL,
    [KDATU]         NVARCHAR (8)    NOT NULL,
    [KRECH]         NVARCHAR (1)    NOT NULL,
    [KAWRT]         DECIMAL (15, 2) NOT NULL,
    [KBETR]         DECIMAL (11, 2) NOT NULL,
    [WAERS]         NVARCHAR (5)    NOT NULL,
    [KKURS]         DECIMAL (9, 5)  NOT NULL,
    [KPEIN]         DECIMAL (5)     NOT NULL,
    [KMEIN]         NVARCHAR (3)    NOT NULL,
    [KUMZA]         DECIMAL (5)     NOT NULL,
    [KUMNE]         DECIMAL (5)     NOT NULL,
    [KNTYP]         NVARCHAR (1)    NOT NULL,
    [KSTAT]         NVARCHAR (1)    NOT NULL,
    [KNPRS]         NVARCHAR (1)    NOT NULL,
    [KRUEK]         NVARCHAR (1)    NOT NULL,
    [KRELI]         NVARCHAR (1)    NOT NULL,
    [KHERK]         NVARCHAR (1)    NOT NULL,
    [KGRPE]         NVARCHAR (1)    NOT NULL,
    [KOUPD]         NVARCHAR (1)    NOT NULL,
    [KOLNR]         NVARCHAR (2)    NOT NULL,
    [KNUMH]         NVARCHAR (10)   NOT NULL,
    [KOPOS]         NVARCHAR (2)    NOT NULL,
    [KVSL1]         NVARCHAR (3)    NOT NULL,
    [SAKN1]         NVARCHAR (10)   NOT NULL,
    [MWSK1]         NVARCHAR (2)    NOT NULL,
    [KVSL2]         NVARCHAR (3)    NOT NULL,
    [SAKN2]         NVARCHAR (10)   NOT NULL,
    [MWSK2]         NVARCHAR (2)    NOT NULL,
    [LIFNR]         NVARCHAR (10)   NOT NULL,
    [KUNNR]         NVARCHAR (10)   NOT NULL,
    [KDIFF]         DECIMAL (5, 2)  NOT NULL,
    [KWERT]         DECIMAL (13, 2) NOT NULL,
    [KSTEU]         NVARCHAR (1)    NOT NULL,
    [KINAK]         NVARCHAR (1)    NOT NULL,
    [KOAID]         NVARCHAR (1)    NOT NULL,
    [ZAEKO]         NVARCHAR (2)    NOT NULL,
    [KMXAW]         NVARCHAR (1)    NOT NULL,
    [KMXWR]         NVARCHAR (1)    NOT NULL,
    [KFAKTOR]       NVARCHAR (15)   NOT NULL,
    [KDUPL]         NVARCHAR (1)    NOT NULL,
    [KFAKTOR1]      NVARCHAR (15)   NOT NULL,
    [KZBZG]         NVARCHAR (1)    NOT NULL,
    [KSTBS]         DECIMAL (15, 2) NOT NULL,
    [KONMS]         NVARCHAR (3)    NOT NULL,
    [KONWS]         NVARCHAR (5)    NOT NULL,
    [KAWRT_K]       DECIMAL (15, 2) NOT NULL,
    [KWAEH]         NVARCHAR (5)    NOT NULL,
    [KWERT_K]       DECIMAL (13, 2) NOT NULL,
    [KFKIV]         NVARCHAR (1)    NOT NULL,
    [KVARC]         NVARCHAR (1)    NOT NULL,
    [KMPRS]         NVARCHAR (1)    NOT NULL,
    [PRSQU]         NVARCHAR (1)    NOT NULL,
    [VARCOND]       NVARCHAR (26)   NOT NULL,
    [STUFE]         DECIMAL (2)     NOT NULL,
    [WEGXX]         DECIMAL (4)     NOT NULL,
    [KTREL]         NVARCHAR (1)    NOT NULL,
    [MDFLG]         NVARCHAR (1)    NOT NULL,
    [TXJLV]         NVARCHAR (1)    NOT NULL,
    [KBFLAG]        NVARCHAR (100)  NOT NULL,
    [KOLNR3]        NVARCHAR (3)    NOT NULL,
    [CPF_GUID]      NVARCHAR (32)   NOT NULL,
    [KAQTY]         NVARCHAR (60)   NOT NULL,
    [/IDT/AUNA]     NVARCHAR (20)   NULL,
    [/IDT/ETC]      NVARCHAR (6)    NULL,
    [/IDT/UUID]     NVARCHAR (36)   NULL,
    [/IDT/NOT]      NVARCHAR (1)    NULL,
    [/IDT/ITEM]     NVARCHAR (8)    NULL,
    [/IDT/HDCT]     NVARCHAR (2)    NULL,
    [/IDT/DOT]      NVARCHAR (1)    NULL,
    [/IDT/TTYP]     NVARCHAR (2)    NULL,
    [/IDT/GROSS]    DECIMAL (15, 2) NULL,
    [/IDT/AUEA]     DECIMAL (15, 2) NULL,
    [/IDT/BSUP]     NVARCHAR (1)    NULL,
    [/IDT/NTAXB]    DECIMAL (15, 2) NULL,
    [/IDT/AUTY]     NVARCHAR (10)   NULL,
    [/IDT/IE]       NVARCHAR (1)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([KNUMV]));

