CREATE TABLE [SrcSAP].[RBKP] (
    [LZBatchID]        INT              NOT NULL,
    [ADLSBatchID]      INT              NOT NULL,
    [ADLSTimestamp]    DATETIME2 (0)    NOT NULL,
    [MANDT]            NVARCHAR (3)     NOT NULL,
    [BELNR]            NVARCHAR (10)    NOT NULL,
    [GJAHR]            NVARCHAR (4)     NOT NULL,
    [BLART]            NVARCHAR (2)     NOT NULL,
    [BLDAT]            NVARCHAR (8)     NOT NULL,
    [BUDAT]            NVARCHAR (8)     NOT NULL,
    [USNAM]            NVARCHAR (12)    NOT NULL,
    [TCODE]            NVARCHAR (20)    NOT NULL,
    [CPUDT]            NVARCHAR (8)     NOT NULL,
    [CPUTM]            NVARCHAR (6)     NOT NULL,
    [VGART]            NVARCHAR (2)     NOT NULL,
    [XBLNR]            NVARCHAR (16)    NOT NULL,
    [BUKRS]            NVARCHAR (4)     NOT NULL,
    [LIFNR]            NVARCHAR (10)    NOT NULL,
    [WAERS]            NVARCHAR (5)     NOT NULL,
    [KURSF]            DECIMAL (9, 5)   NOT NULL,
    [RMWWR]            DECIMAL (13, 2)  NOT NULL,
    [BEZNK]            DECIMAL (13, 2)  NOT NULL,
    [WMWST1]           DECIMAL (13, 2)  NOT NULL,
    [MWSKZ1]           NVARCHAR (2)     NOT NULL,
    [WMWST2]           DECIMAL (13, 2)  NOT NULL,
    [MWSKZ2]           NVARCHAR (2)     NOT NULL,
    [ZTERM]            NVARCHAR (4)     NOT NULL,
    [ZBD1T]            DECIMAL (3)      NOT NULL,
    [ZBD1P]            DECIMAL (5, 3)   NOT NULL,
    [ZBD2T]            DECIMAL (3)      NOT NULL,
    [ZBD2P]            DECIMAL (5, 3)   NOT NULL,
    [ZBD3T]            DECIMAL (3)      NOT NULL,
    [WSKTO]            DECIMAL (13, 2)  NOT NULL,
    [XRECH]            NVARCHAR (1)     NOT NULL,
    [BKTXT]            NVARCHAR (25)    NOT NULL,
    [SAPRL]            NVARCHAR (4)     NOT NULL,
    [LOGSYS]           NVARCHAR (10)    NOT NULL,
    [XMWST]            NVARCHAR (1)     NOT NULL,
    [STBLG]            NVARCHAR (10)    NOT NULL,
    [STJAH]            NVARCHAR (4)     NOT NULL,
    [MWSKZ_BNK]        NVARCHAR (2)     NOT NULL,
    [TXJCD_BNK]        NVARCHAR (15)    NOT NULL,
    [IVTYP]            NVARCHAR (1)     NOT NULL,
    [XRBTX]            NVARCHAR (1)     NOT NULL,
    [REPART]           NVARCHAR (1)     NOT NULL,
    [RBSTAT]           NVARCHAR (1)     NOT NULL,
    [KNUMVE]           NVARCHAR (10)    NOT NULL,
    [KNUMVL]           NVARCHAR (10)    NOT NULL,
    [ARKUEN]           DECIMAL (13, 2)  NOT NULL,
    [ARKUEMW]          DECIMAL (13, 2)  NOT NULL,
    [MAKZN]            DECIMAL (13, 2)  NOT NULL,
    [MAKZMW]           DECIMAL (13, 2)  NOT NULL,
    [LIEFFN]           DECIMAL (13, 2)  NOT NULL,
    [LIEFFMW]          DECIMAL (13, 2)  NOT NULL,
    [XAUTAKZ]          NVARCHAR (1)     NOT NULL,
    [ESRNR]            NVARCHAR (11)    NOT NULL,
    [ESRPZ]            NVARCHAR (2)     NOT NULL,
    [ESRRE]            NVARCHAR (27)    NOT NULL,
    [QSSHB]            DECIMAL (13, 2)  NOT NULL,
    [QSFBT]            DECIMAL (13, 2)  NOT NULL,
    [QSSKZ]            NVARCHAR (2)     NOT NULL,
    [DIEKZ]            NVARCHAR (1)     NOT NULL,
    [LANDL]            NVARCHAR (3)     NOT NULL,
    [LZBKZ]            NVARCHAR (3)     NOT NULL,
    [TXKRS]            DECIMAL (9, 5)   NOT NULL,
    [EMPFB]            NVARCHAR (10)    NOT NULL,
    [BVTYP]            NVARCHAR (4)     NOT NULL,
    [HBKID]            NVARCHAR (5)     NOT NULL,
    [ZUONR]            NVARCHAR (18)    NOT NULL,
    [ZLSPR]            NVARCHAR (1)     NOT NULL,
    [ZLSCH]            NVARCHAR (1)     NOT NULL,
    [ZFBDT]            NVARCHAR (8)     NOT NULL,
    [KIDNO]            NVARCHAR (30)    NOT NULL,
    [REBZG]            NVARCHAR (10)    NOT NULL,
    [REBZJ]            NVARCHAR (4)     NOT NULL,
    [XINVE]            NVARCHAR (1)     NOT NULL,
    [EGMLD]            NVARCHAR (3)     NOT NULL,
    [XEGDR]            NVARCHAR (1)     NOT NULL,
    [VATDATE]          NVARCHAR (8)     NOT NULL,
    [HKONT]            NVARCHAR (10)    NOT NULL,
    [J_1BNFTYPE]       NVARCHAR (2)     NOT NULL,
    [BRNCH]            NVARCHAR (4)     NOT NULL,
    [ERFPR]            NVARCHAR (12)    NOT NULL,
    [SECCO]            NVARCHAR (4)     NOT NULL,
    [NAME1]            NVARCHAR (35)    NOT NULL,
    [NAME2]            NVARCHAR (35)    NOT NULL,
    [NAME3]            NVARCHAR (35)    NOT NULL,
    [NAME4]            NVARCHAR (35)    NOT NULL,
    [PSTLZ]            NVARCHAR (10)    NOT NULL,
    [ORT01]            NVARCHAR (35)    NOT NULL,
    [LAND1]            NVARCHAR (3)     NOT NULL,
    [STRAS]            NVARCHAR (35)    NOT NULL,
    [PFACH]            NVARCHAR (10)    NOT NULL,
    [PSTL2]            NVARCHAR (10)    NOT NULL,
    [PSKTO]            NVARCHAR (16)    NOT NULL,
    [BANKN]            NVARCHAR (18)    NOT NULL,
    [BANKL]            NVARCHAR (15)    NOT NULL,
    [BANKS]            NVARCHAR (3)     NOT NULL,
    [STCD1]            NVARCHAR (16)    NOT NULL,
    [STCD2]            NVARCHAR (11)    NOT NULL,
    [STKZU]            NVARCHAR (1)     NOT NULL,
    [STKZA]            NVARCHAR (1)     NOT NULL,
    [REGIO]            NVARCHAR (3)     NOT NULL,
    [BKONT]            NVARCHAR (2)     NOT NULL,
    [DTAWS]            NVARCHAR (2)     NOT NULL,
    [DTAMS]            NVARCHAR (1)     NOT NULL,
    [SPRAS]            NVARCHAR (1)     NOT NULL,
    [XCPDK]            NVARCHAR (1)     NOT NULL,
    [EMPFG]            NVARCHAR (16)    NOT NULL,
    [FITYP]            NVARCHAR (2)     NOT NULL,
    [STCDT]            NVARCHAR (2)     NOT NULL,
    [STKZN]            NVARCHAR (1)     NOT NULL,
    [STCD3]            NVARCHAR (18)    NOT NULL,
    [STCD4]            NVARCHAR (18)    NOT NULL,
    [BKREF]            NVARCHAR (20)    NOT NULL,
    [J_1KFREPRE]       NVARCHAR (10)    NOT NULL,
    [J_1KFTBUS]        NVARCHAR (30)    NOT NULL,
    [J_1KFTIND]        NVARCHAR (30)    NOT NULL,
    [ANRED]            NVARCHAR (15)    NOT NULL,
    [STCEG]            NVARCHAR (20)    NOT NULL,
    [ERNAME]           NVARCHAR (12)    NOT NULL,
    [REINDAT]          NVARCHAR (8)     NOT NULL,
    [UZAWE]            NVARCHAR (2)     NOT NULL,
    [FDLEV]            NVARCHAR (2)     NOT NULL,
    [FDTAG]            NVARCHAR (8)     NOT NULL,
    [ZBFIX]            NVARCHAR (1)     NOT NULL,
    [FRGKZ]            NVARCHAR (1)     NOT NULL,
    [ERFNAM]           NVARCHAR (12)    NOT NULL,
    [BUPLA]            NVARCHAR (4)     NOT NULL,
    [FILKD]            NVARCHAR (10)    NOT NULL,
    [GSBER]            NVARCHAR (4)     NOT NULL,
    [LOTKZ]            NVARCHAR (10)    NOT NULL,
    [SGTXT]            NVARCHAR (50)    NOT NULL,
    [INV_TRAN]         NVARCHAR (1)     NOT NULL,
    [PREPAY_STATUS]    NVARCHAR (1)     NOT NULL,
    [PREPAY_AWKEY]     NVARCHAR (20)    NOT NULL,
    [ASSIGN_STATUS]    NVARCHAR (1)     NOT NULL,
    [ASSIGN_NEXT_DATE] NVARCHAR (8)     NOT NULL,
    [ASSIGN_END_DATE]  NVARCHAR (8)     NOT NULL,
    [COPY_BY_BELNR]    NVARCHAR (10)    NOT NULL,
    [COPY_BY_YEAR]     NVARCHAR (4)     NOT NULL,
    [COPY_TO_BELNR]    NVARCHAR (10)    NOT NULL,
    [COPY_TO_YEAR]     NVARCHAR (4)     NOT NULL,
    [COPY_USER]        NVARCHAR (12)    NOT NULL,
    [KURSX]            DECIMAL (28, 14) NOT NULL,
    [WWERT]            NVARCHAR (8)     NOT NULL,
    [XREF3]            NVARCHAR (20)    NOT NULL,
    [J_1TPBUPL]        NVARCHAR (5)     NOT NULL,
    [ANXTYPE]          NVARCHAR (1)     NOT NULL,
    [ANXAMNT]          DECIMAL (13, 2)  NOT NULL,
    [ANXPERC]          DECIMAL (6, 3)   NOT NULL,
    [ZVAT_INDC]        NVARCHAR (8)     NOT NULL,
    [/ILE/PARK]        NVARCHAR (1)     NOT NULL,
    [/ILE/HOLD]        NVARCHAR (1)     NOT NULL,
    [/ILE/BAPI_SAVE]   NVARCHAR (1)     NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [BELNR], [GJAHR]), DISTRIBUTION = HASH([BELNR]));

