CREATE TABLE [SrcSAP].[RSEG] (
    [LZBatchID]        INT             NOT NULL,
    [ADLSBatchID]      INT             NOT NULL,
    [ADLSTimestamp]    DATETIME2 (0)   NOT NULL,
    [MANDT]            NVARCHAR (3)    NOT NULL,
    [BELNR]            NVARCHAR (10)   NOT NULL,
    [GJAHR]            NVARCHAR (4)    NOT NULL,
    [BUZEI]            NVARCHAR (6)    NOT NULL,
    [EBELN]            NVARCHAR (10)   NOT NULL,
    [EBELP]            NVARCHAR (5)    NOT NULL,
    [ZEKKN]            NVARCHAR (2)    NOT NULL,
    [MATNR]            NVARCHAR (18)   NOT NULL,
    [BWKEY]            NVARCHAR (4)    NOT NULL,
    [BWTAR]            NVARCHAR (10)   NOT NULL,
    [BUKRS]            NVARCHAR (4)    NOT NULL,
    [WERKS]            NVARCHAR (4)    NOT NULL,
    [WRBTR]            DECIMAL (13, 2) NOT NULL,
    [SHKZG]            NVARCHAR (1)    NOT NULL,
    [MWSKZ]            NVARCHAR (2)    NOT NULL,
    [TXJCD]            NVARCHAR (15)   NOT NULL,
    [MENGE]            DECIMAL (13, 3) NOT NULL,
    [BSTME]            NVARCHAR (3)    NOT NULL,
    [BPMNG]            DECIMAL (13, 3) NOT NULL,
    [BPRME]            NVARCHAR (3)    NOT NULL,
    [LBKUM]            DECIMAL (13, 3) NOT NULL,
    [VRKUM]            DECIMAL (13, 3) NOT NULL,
    [MEINS]            NVARCHAR (3)    NOT NULL,
    [PSTYP]            NVARCHAR (1)    NOT NULL,
    [KNTTP]            NVARCHAR (1)    NOT NULL,
    [BKLAS]            NVARCHAR (4)    NOT NULL,
    [EREKZ]            NVARCHAR (1)    NOT NULL,
    [EXKBE]            NVARCHAR (1)    NOT NULL,
    [XEKBZ]            NVARCHAR (1)    NOT NULL,
    [TBTKZ]            NVARCHAR (1)    NOT NULL,
    [SPGRP]            NVARCHAR (1)    NOT NULL,
    [SPGRM]            NVARCHAR (1)    NOT NULL,
    [SPGRT]            NVARCHAR (1)    NOT NULL,
    [SPGRG]            NVARCHAR (1)    NOT NULL,
    [SPGRV]            NVARCHAR (1)    NOT NULL,
    [SPGRQ]            NVARCHAR (1)    NOT NULL,
    [SPGRS]            NVARCHAR (1)    NOT NULL,
    [SPGRC]            NVARCHAR (1)    NOT NULL,
    [SPGREXT]          NVARCHAR (1)    NOT NULL,
    [BUSTW]            NVARCHAR (4)    NOT NULL,
    [XBLNR]            NVARCHAR (16)   NOT NULL,
    [XRUEB]            NVARCHAR (1)    NOT NULL,
    [BNKAN]            DECIMAL (13, 2) NOT NULL,
    [KSCHL]            NVARCHAR (4)    NOT NULL,
    [SALK3]            DECIMAL (13, 2) NOT NULL,
    [VMSAL]            DECIMAL (13, 2) NOT NULL,
    [XLIFO]            NVARCHAR (1)    NOT NULL,
    [LFBNR]            NVARCHAR (10)   NOT NULL,
    [LFGJA]            NVARCHAR (4)    NOT NULL,
    [LFPOS]            NVARCHAR (4)    NOT NULL,
    [MATBF]            NVARCHAR (18)   NOT NULL,
    [RBMNG]            DECIMAL (13, 3) NOT NULL,
    [BPRBM]            DECIMAL (13, 3) NOT NULL,
    [RBWWR]            DECIMAL (13, 2) NOT NULL,
    [LFEHL]            NVARCHAR (1)    NOT NULL,
    [GRICD]            NVARCHAR (2)    NOT NULL,
    [GRIRG]            NVARCHAR (3)    NOT NULL,
    [GITYP]            NVARCHAR (2)    NOT NULL,
    [PACKNO]           NVARCHAR (10)   NOT NULL,
    [INTROW]           NVARCHAR (10)   NOT NULL,
    [SGTXT]            NVARCHAR (50)   NOT NULL,
    [XSKRL]            NVARCHAR (1)    NOT NULL,
    [KZMEK]            NVARCHAR (1)    NOT NULL,
    [MRMOK]            NVARCHAR (1)    NOT NULL,
    [STUNR]            NVARCHAR (3)    NOT NULL,
    [ZAEHK]            NVARCHAR (2)    NOT NULL,
    [STOCK_POSTING]    DECIMAL (13, 2) NOT NULL,
    [STOCK_POSTING_PP] DECIMAL (13, 2) NOT NULL,
    [STOCK_POSTING_PY] DECIMAL (13, 2) NOT NULL,
    [WEREC]            NVARCHAR (1)    NOT NULL,
    [LIFNR]            NVARCHAR (10)   NOT NULL,
    [FRBNR]            NVARCHAR (16)   NOT NULL,
    [XHISTMA]          NVARCHAR (1)    NOT NULL,
    [COMPLAINT_REASON] NVARCHAR (2)    NOT NULL,
    [RETAMT_FC]        DECIMAL (13, 2) NOT NULL,
    [RETPC]            DECIMAL (5, 2)  NOT NULL,
    [RETDUEDT]         NVARCHAR (8)    NOT NULL,
    [XRETTAXNET]       NVARCHAR (1)    NOT NULL,
    [RE_ACCOUNT]       NVARCHAR (10)   NOT NULL,
    [ERP_CONTRACT_ID]  NVARCHAR (10)   NOT NULL,
    [ERP_CONTRACT_ITM] NVARCHAR (5)    NOT NULL,
    [SRM_CONTRACT_ID]  NVARCHAR (10)   NOT NULL,
    [SRM_CONTRACT_ITM] NVARCHAR (10)   NOT NULL,
    [CONT_PSTYP]       NVARCHAR (1)    NOT NULL,
    [SRVMAPKEY]        NVARCHAR (10)   NOT NULL,
    [CHARG]            NVARCHAR (10)   NOT NULL,
    [INV_ITM_ORIGIN]   NVARCHAR (1)    NOT NULL,
    [INVREL]           NVARCHAR (6)    NOT NULL,
    [XDINV]            NVARCHAR (1)    NOT NULL,
    [DIFF_AMOUNT]      DECIMAL (13, 2) NOT NULL,
    [XCPRF]            NVARCHAR (1)    NOT NULL,
    [/NFM/SPGRK]       NVARCHAR (1)    NOT NULL,
    [EFKOR]            NVARCHAR (1)    NOT NULL,
    [LICNO]            NVARCHAR (10)   NOT NULL,
    [ZEILE]            NVARCHAR (4)    NOT NULL,
    [SGT_SCAT]         NVARCHAR (16)   NOT NULL,
    [WRF_CHARSTC1]     NVARCHAR (18)   NOT NULL,
    [WRF_CHARSTC2]     NVARCHAR (18)   NOT NULL,
    [WRF_CHARSTC3]     NVARCHAR (18)   NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [BELNR], [GJAHR], [BUZEI]), DISTRIBUTION = HASH([BELNR]));

