CREATE TABLE [SrcSAP].[SETHEADERTRANS] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [SETCLASS]      NVARCHAR (4)  NOT NULL,
    [SUBCLASS]      NVARCHAR (12) NOT NULL,
    [SETNAME]       NVARCHAR (24) NOT NULL,
    [TRKORR]        NVARCHAR (20) NOT NULL,
    [TRDATE]        NVARCHAR (8)  NOT NULL,
    [TRTIME]        NVARCHAR (6)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [SETCLASS], [SUBCLASS], [SETNAME]), DISTRIBUTION = HASH([SETNAME]));

