CREATE TABLE [SrcSAP].[SETLEAF] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [SETCLASS]      NVARCHAR (4)  NOT NULL,
    [SUBCLASS]      NVARCHAR (12) NOT NULL,
    [SETNAME]       NVARCHAR (24) NOT NULL,
    [LINEID]        NVARCHAR (10) NOT NULL,
    [VALSIGN]       NVARCHAR (1)  NOT NULL,
    [VALOPTION]     NVARCHAR (2)  NOT NULL,
    [VALFROM]       NVARCHAR (24) NOT NULL,
    [VALTO]         NVARCHAR (24) NOT NULL,
    [SEQNR]         INT           NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [SETCLASS], [SUBCLASS], [SETNAME], [LINEID]), DISTRIBUTION = HASH([SETNAME]));

