CREATE TABLE [SrcSAP].[SETLINET] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [SETCLASS]      NVARCHAR (4)  NOT NULL,
    [SUBCLASS]      NVARCHAR (12) NOT NULL,
    [SETNAME]       NVARCHAR (24) NOT NULL,
    [LANGU]         NVARCHAR (1)  NOT NULL,
    [LINEID]        NVARCHAR (10) NOT NULL,
    [DESCRIPT]      NVARCHAR (40) NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [SETCLASS], [SUBCLASS], [SETNAME], [LANGU], [LINEID]), DISTRIBUTION = HASH([SETNAME]));

