CREATE TABLE [SrcSAP].[SETNODE] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [SETCLASS]      NVARCHAR (4)  NOT NULL,
    [SUBCLASS]      NVARCHAR (12) NOT NULL,
    [SETNAME]       NVARCHAR (24) NOT NULL,
    [LINEID]        NVARCHAR (10) NOT NULL,
    [SUBSETCLS]     NVARCHAR (4)  NOT NULL,
    [SUBSETSCLS]    NVARCHAR (12) NOT NULL,
    [SUBSETNAME]    NVARCHAR (24) NOT NULL,
    [SEQNR]         INT           NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [SETCLASS], [SUBCLASS], [SETNAME], [LINEID]), DISTRIBUTION = HASH([SETNAME]));

