CREATE TABLE [SrcSAP].[SKB1] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [BUKRS]         NVARCHAR (4)  NOT NULL,
    [SAKNR]         NVARCHAR (10) NOT NULL,
    [BEGRU]         NVARCHAR (4)  NOT NULL,
    [BUSAB]         NVARCHAR (2)  NOT NULL,
    [DATLZ]         NVARCHAR (8)  NOT NULL,
    [ERDAT]         NVARCHAR (8)  NOT NULL,
    [ERNAM]         NVARCHAR (12) NOT NULL,
    [FDGRV]         NVARCHAR (10) NOT NULL,
    [FDLEV]         NVARCHAR (2)  NOT NULL,
    [FIPLS]         NVARCHAR (3)  NOT NULL,
    [FSTAG]         NVARCHAR (4)  NOT NULL,
    [HBKID]         NVARCHAR (5)  NOT NULL,
    [HKTID]         NVARCHAR (5)  NOT NULL,
    [KDFSL]         NVARCHAR (4)  NOT NULL,
    [MITKZ]         NVARCHAR (1)  NOT NULL,
    [MWSKZ]         NVARCHAR (2)  NOT NULL,
    [STEXT]         NVARCHAR (50) NOT NULL,
    [VZSKZ]         NVARCHAR (2)  NOT NULL,
    [WAERS]         NVARCHAR (5)  NOT NULL,
    [WMETH]         NVARCHAR (2)  NOT NULL,
    [XGKON]         NVARCHAR (1)  NOT NULL,
    [XINTB]         NVARCHAR (1)  NOT NULL,
    [XKRES]         NVARCHAR (1)  NOT NULL,
    [XLOEB]         NVARCHAR (1)  NOT NULL,
    [XNKON]         NVARCHAR (1)  NOT NULL,
    [XOPVW]         NVARCHAR (1)  NOT NULL,
    [XSPEB]         NVARCHAR (1)  NOT NULL,
    [ZINDT]         NVARCHAR (8)  NOT NULL,
    [ZINRT]         NVARCHAR (2)  NOT NULL,
    [ZUAWA]         NVARCHAR (3)  NOT NULL,
    [ALTKT]         NVARCHAR (10) NOT NULL,
    [XMITK]         NVARCHAR (1)  NOT NULL,
    [RECID]         NVARCHAR (2)  NOT NULL,
    [FIPOS]         NVARCHAR (14) NOT NULL,
    [XMWNO]         NVARCHAR (1)  NOT NULL,
    [XSALH]         NVARCHAR (1)  NOT NULL,
    [BEWGP]         NVARCHAR (10) NOT NULL,
    [INFKY]         NVARCHAR (8)  NOT NULL,
    [TOGRU]         NVARCHAR (4)  NOT NULL,
    [XLGCLR]        NVARCHAR (1)  NOT NULL,
    [MCAKEY]        NVARCHAR (5)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [BUKRS], [SAKNR]), DISTRIBUTION = HASH([BUKRS]));

