CREATE TABLE [SrcSAP].[T000] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [MTEXT]         NVARCHAR (25) NOT NULL,
    [ORT01]         NVARCHAR (25) NOT NULL,
    [MWAER]         NVARCHAR (5)  NOT NULL,
    [ADRNR]         NVARCHAR (10) NOT NULL,
    [CCCATEGORY]    NVARCHAR (1)  NOT NULL,
    [CCCORACTIV]    NVARCHAR (1)  NOT NULL,
    [CCNOCLIIND]    NVARCHAR (1)  NOT NULL,
    [CCCOPYLOCK]    NVARCHAR (1)  NOT NULL,
    [CCNOCASCAD]    NVARCHAR (1)  NOT NULL,
    [CCSOFTLOCK]    NVARCHAR (1)  NOT NULL,
    [CCORIGCONT]    NVARCHAR (1)  NOT NULL,
    [CCIMAILDIS]    NVARCHAR (1)  NOT NULL,
    [CCTEMPLOCK]    NVARCHAR (1)  NOT NULL,
    [CHANGEUSER]    NVARCHAR (12) NOT NULL,
    [CHANGEDATE]    NVARCHAR (8)  NOT NULL,
    [LOGSYS]        NVARCHAR (10) NOT NULL
)
WITH (CLUSTERED INDEX([MANDT]), DISTRIBUTION = HASH([MANDT]));

