CREATE TABLE [SrcSAP].[T093] (
    [LZBatchID]      INT           NOT NULL,
    [ADLSBatchID]    INT           NOT NULL,
    [ADLSTimestamp]  DATETIME2 (0) NOT NULL,
    [MANDT]          NVARCHAR (3)  NOT NULL,
    [AFAPL]          NVARCHAR (4)  NOT NULL,
    [AFABER]         NVARCHAR (2)  NOT NULL,
    [XSTORE]         NVARCHAR (1)  NOT NULL,
    [ABVOR1]         NVARCHAR (1)  NOT NULL,
    [AFABE1]         NVARCHAR (2)  NOT NULL,
    [ANTEI1]         NVARCHAR (1)  NOT NULL,
    [ABVOR2]         NVARCHAR (1)  NOT NULL,
    [AFABE2]         NVARCHAR (2)  NOT NULL,
    [ANTEI2]         NVARCHAR (1)  NOT NULL,
    [ABVOR3]         NVARCHAR (1)  NOT NULL,
    [AFABE3]         NVARCHAR (2)  NOT NULL,
    [ANTEI3]         NVARCHAR (1)  NOT NULL,
    [ABVOR4]         NVARCHAR (1)  NOT NULL,
    [AFABE4]         NVARCHAR (2)  NOT NULL,
    [ANTEI4]         NVARCHAR (1)  NOT NULL,
    [VZANSW]         NVARCHAR (1)  NOT NULL,
    [VZREST]         NVARCHAR (1)  NOT NULL,
    [BUHBKT]         NVARCHAR (1)  NOT NULL,
    [VIEW0]          NVARCHAR (1)  NOT NULL,
    [VIEW1]          NVARCHAR (1)  NOT NULL,
    [VIEW2]          NVARCHAR (1)  NOT NULL,
    [VIEW3]          NVARCHAR (1)  NOT NULL,
    [VIEW4]          NVARCHAR (1)  NOT NULL,
    [VIEW5]          NVARCHAR (1)  NOT NULL,
    [VIEW6]          NVARCHAR (1)  NOT NULL,
    [VZINVZ]         NVARCHAR (1)  NOT NULL,
    [VZAWMA]         NVARCHAR (1)  NOT NULL,
    [VZNAFA]         NVARCHAR (1)  NOT NULL,
    [VZSAFA]         NVARCHAR (1)  NOT NULL,
    [VZAAFA]         NVARCHAR (1)  NOT NULL,
    [VZINDW]         NVARCHAR (1)  NOT NULL,
    [VZZINS]         NVARCHAR (1)  NOT NULL,
    [VZINDA]         NVARCHAR (1)  NOT NULL,
    [AFABEO]         NVARCHAR (1)  NOT NULL,
    [XBEREP]         NVARCHAR (1)  NOT NULL,
    [CORRBE]         NVARCHAR (2)  NOT NULL,
    [GAFABER]        NVARCHAR (2)  NOT NULL,
    [LDGRP_GL]       NVARCHAR (4)  NOT NULL,
    [XAFABER]        NVARCHAR (1)  NOT NULL,
    [ABWBER]         NVARCHAR (2)  NOT NULL,
    [AREA_USAGE_IND] NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [AFAPL], [AFABER]), DISTRIBUTION = HASH([AFAPL]));

