CREATE TABLE [SrcSAP].[T156] (
    [LZBatchID]      INT           NOT NULL,
    [ADLSBatchID]    INT           NOT NULL,
    [ADLSTimestamp]  DATETIME2 (0) NOT NULL,
    [MANDT]          NVARCHAR (3)  NOT NULL,
    [BWART]          NVARCHAR (3)  NOT NULL,
    [SHKZG]          NVARCHAR (1)  NOT NULL,
    [KZWES]          NVARCHAR (1)  NOT NULL,
    [KZVBU]          NVARCHAR (1)  NOT NULL,
    [KZDRU]          NVARCHAR (1)  NOT NULL,
    [KZKON]          NVARCHAR (1)  NOT NULL,
    [CHNEU]          NVARCHAR (1)  NOT NULL,
    [KZZDE]          NVARCHAR (1)  NOT NULL,
    [RSTYP]          NVARCHAR (1)  NOT NULL,
    [SELPA]          NVARCHAR (10) NOT NULL,
    [XLAUT]          NVARCHAR (1)  NOT NULL,
    [KZSTR]          NVARCHAR (1)  NOT NULL,
    [KZGRU]          NVARCHAR (1)  NOT NULL,
    [XINVB]          NVARCHAR (1)  NOT NULL,
    [QSSBW]          NVARCHAR (1)  NOT NULL,
    [KZBWA]          NVARCHAR (2)  NOT NULL,
    [XSTBW]          NVARCHAR (1)  NOT NULL,
    [XPBED]          NVARCHAR (1)  NOT NULL,
    [XWSBR]          NVARCHAR (1)  NOT NULL,
    [KZMHD]          NVARCHAR (1)  NOT NULL,
    [KZCLA]          NVARCHAR (1)  NOT NULL,
    [XKOKO]          NVARCHAR (1)  NOT NULL,
    [XKCFC]          NVARCHAR (1)  NOT NULL,
    [XNEBE]          NVARCHAR (1)  NOT NULL,
    [J_1BNFREL]      NVARCHAR (1)  NOT NULL,
    [J_1BNFTYPE]     NVARCHAR (2)  NOT NULL,
    [J_1BITMTYP]     NVARCHAR (2)  NOT NULL,
    [J_1BSPCSTO]     NVARCHAR (2)  NOT NULL,
    [J_1BPARTYP]     NVARCHAR (1)  NOT NULL,
    [J_1BPARVW]      NVARCHAR (2)  NOT NULL,
    [RULES]          NVARCHAR (4)  NOT NULL,
    [J_1AREVIDX]     NVARCHAR (1)  NOT NULL,
    [J_1ADOCCL]      NVARCHAR (1)  NOT NULL,
    [J_1AEXPKZ]      NVARCHAR (1)  NOT NULL,
    [XOARC]          NVARCHAR (1)  NOT NULL,
    [BUSTR]          NVARCHAR (3)  NOT NULL,
    [KZDIR]          NVARCHAR (1)  NOT NULL,
    [OIJ1BNFFI]      NVARCHAR (1)  NOT NULL,
    [MILL_CPCONF]    NVARCHAR (1)  NOT NULL,
    [CO_WIPB_CPCONF] NVARCHAR (1)  NOT NULL,
    [XWIPB]          NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [BWART]), DISTRIBUTION = HASH([BWART]));

