CREATE TABLE [SrcSAP].[T179] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [PRODH]         NVARCHAR (18) NOT NULL,
    [STUFE]         NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [PRODH]), DISTRIBUTION = HASH([PRODH]));

