CREATE TABLE [SrcSAP].[T691F] (
    [LZBatchID]     INT             NOT NULL,
    [ADLSBatchID]   INT             NOT NULL,
    [ADLSTimestamp] DATETIME2 (0)   NOT NULL,
    [MANDT]         NVARCHAR (3)    NOT NULL,
    [KKBER]         NVARCHAR (4)    NOT NULL,
    [CTLPC]         NVARCHAR (3)    NOT NULL,
    [CRMGR]         NVARCHAR (2)    NOT NULL,
    [CRDBI]         NVARCHAR (1)    NOT NULL,
    [CRPRC]         NVARCHAR (3)    NOT NULL,
    [CRCRE]         NVARCHAR (1)    NOT NULL,
    [DKLIM]         DECIMAL (15, 2) NOT NULL,
    [SEAAF]         NVARCHAR (3)    NOT NULL,
    [TAGEF]         NVARCHAR (3)    NOT NULL,
    [CMPAA]         NVARCHAR (1)    NOT NULL,
    [STVAW]         NVARCHAR (1)    NOT NULL,
    [STVLW]         NVARCHAR (1)    NOT NULL,
    [STREA]         NVARCHAR (1)    NOT NULL,
    [STSET]         NVARCHAR (1)    NOT NULL,
    [CMPAB]         NVARCHAR (1)    NOT NULL,
    [WOVLW]         NVARCHAR (1)    NOT NULL,
    [WSWIN]         NVARCHAR (3)    NOT NULL,
    [WSREA]         NVARCHAR (1)    NOT NULL,
    [WLSET]         NVARCHAR (1)    NOT NULL,
    [CMPAC]         NVARCHAR (1)    NOT NULL,
    [MAVAL]         DECIMAL (15, 2) NOT NULL,
    [MAREA]         NVARCHAR (1)    NOT NULL,
    [MASET]         NVARCHAR (1)    NOT NULL,
    [CMPAD]         NVARCHAR (1)    NOT NULL,
    [FSREA]         NVARCHAR (1)    NOT NULL,
    [FSSET]         NVARCHAR (1)    NOT NULL,
    [CMPAE]         NVARCHAR (1)    NOT NULL,
    [RVTOL]         NVARCHAR (3)    NOT NULL,
    [RSREA]         NVARCHAR (1)    NOT NULL,
    [RESET]         NVARCHAR (1)    NOT NULL,
    [CMPAF]         NVARCHAR (1)    NOT NULL,
    [PDMAX]         NVARCHAR (3)    NOT NULL,
    [PDTOL]         NVARCHAR (3)    NOT NULL,
    [PDREA]         NVARCHAR (1)    NOT NULL,
    [PDSET]         NVARCHAR (1)    NOT NULL,
    [CMPAG]         NVARCHAR (1)    NOT NULL,
    [OITOL]         NVARCHAR (3)    NOT NULL,
    [OIREA]         NVARCHAR (1)    NOT NULL,
    [OISET]         NVARCHAR (1)    NOT NULL,
    [CMPAH]         NVARCHAR (1)    NOT NULL,
    [DUNNG]         NVARCHAR (1)    NOT NULL,
    [DNREA]         NVARCHAR (1)    NOT NULL,
    [DNSET]         NVARCHAR (1)    NOT NULL,
    [CMPAI]         NVARCHAR (1)    NOT NULL,
    [SPVAL]         DECIMAL (15, 2) NOT NULL,
    [SPREA]         NVARCHAR (1)    NOT NULL,
    [SPSET]         NVARCHAR (1)    NOT NULL,
    [CMPAJ]         NVARCHAR (1)    NOT NULL,
    [PJREA]         NVARCHAR (1)    NOT NULL,
    [PJSET]         NVARCHAR (1)    NOT NULL,
    [CMPAK]         NVARCHAR (1)    NOT NULL,
    [PKREA]         NVARCHAR (1)    NOT NULL,
    [PKSET]         NVARCHAR (1)    NOT NULL,
    [CMPAL]         NVARCHAR (1)    NOT NULL,
    [PLREA]         NVARCHAR (1)    NOT NULL,
    [PLSET]         NVARCHAR (1)    NOT NULL,
    [USRPR0]        NVARCHAR (1)    NOT NULL,
    [USR0REA]       NVARCHAR (1)    NOT NULL,
    [USR0SET]       NVARCHAR (1)    NOT NULL,
    [USRPR1]        NVARCHAR (1)    NOT NULL,
    [USR1REA]       NVARCHAR (1)    NOT NULL,
    [USR1SET]       NVARCHAR (1)    NOT NULL,
    [USRPR2]        NVARCHAR (1)    NOT NULL,
    [USR2REA]       NVARCHAR (1)    NOT NULL,
    [USR2SET]       NVARCHAR (1)    NOT NULL,
    [CMPAM]         NVARCHAR (1)    NOT NULL,
    [PMREA]         NVARCHAR (1)    NOT NULL,
    [PMSET]         NVARCHAR (1)    NOT NULL,
    [CECKI]         NVARCHAR (1)    NOT NULL,
    [REGUL]         NVARCHAR (1)    NOT NULL,
    [GRPNO]         NVARCHAR (3)    NOT NULL,
    [DVSEA]         NVARCHAR (8)    NOT NULL,
    [DBSEA]         NVARCHAR (8)    NOT NULL,
    [ERLTA]         NVARCHAR (2)    NOT NULL,
    [ERLST]         NVARCHAR (2)    NOT NULL,
    [SEAAFPM]       NVARCHAR (1)    NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [KKBER], [CTLPC], [CRMGR]), DISTRIBUTION = HASH([KKBER]));

