CREATE TABLE [SrcSAP].[TFKB] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [MANDT]         NVARCHAR (3)  NOT NULL,
    [FKBER]         NVARCHAR (16) NOT NULL,
    [AUTHGRP]       NVARCHAR (10) NOT NULL,
    [STR_ID]        NVARCHAR (10) NOT NULL,
    [FNSUB1]        NVARCHAR (10) NOT NULL,
    [FNSUB2]        NVARCHAR (10) NOT NULL,
    [FNSUB3]        NVARCHAR (10) NOT NULL,
    [CREATED_BY]    NVARCHAR (12) NOT NULL,
    [CREATED_ON]    NVARCHAR (8)  NOT NULL,
    [CREATED_AT]    NVARCHAR (6)  NOT NULL,
    [MODIFIED_BY]   NVARCHAR (12) NOT NULL,
    [MODIFIED_ON]   NVARCHAR (8)  NOT NULL,
    [MODIFIED_AT]   NVARCHAR (6)  NOT NULL,
    [DATAB]         NVARCHAR (8)  NOT NULL,
    [DATBIS]        NVARCHAR (8)  NOT NULL,
    [DATE_EXP]      NVARCHAR (8)  NOT NULL
)
WITH (CLUSTERED INDEX([MANDT], [FKBER]), DISTRIBUTION = HASH([FKBER]));

