CREATE TABLE [SrcSAP].[TRDIR] (
    [LZBatchID]     INT           NOT NULL,
    [ADLSBatchID]   INT           NOT NULL,
    [ADLSTimestamp] DATETIME2 (0) NOT NULL,
    [NAME]          NVARCHAR (40) NOT NULL,
    [SQLX]          NVARCHAR (1)  NOT NULL,
    [EDTX]          NVARCHAR (1)  NOT NULL,
    [VARCL]         NVARCHAR (1)  NOT NULL,
    [DBAPL]         NVARCHAR (1)  NOT NULL,
    [DBNA]          NVARCHAR (2)  NOT NULL,
    [CLAS]          NVARCHAR (4)  NOT NULL,
    [TYPE]          NVARCHAR (3)  NOT NULL,
    [OCCURS]        NVARCHAR (1)  NOT NULL,
    [SUBC]          NVARCHAR (1)  NOT NULL,
    [APPL]          NVARCHAR (1)  NOT NULL,
    [SECU]          NVARCHAR (8)  NOT NULL,
    [CNAM]          NVARCHAR (12) NOT NULL,
    [CDAT]          NVARCHAR (8)  NOT NULL,
    [UNAM]          NVARCHAR (12) NOT NULL,
    [UDAT]          NVARCHAR (8)  NOT NULL,
    [VERN]          NVARCHAR (6)  NOT NULL,
    [LEVL]          NVARCHAR (4)  NOT NULL,
    [RSTAT]         NVARCHAR (1)  NOT NULL,
    [RMAND]         NVARCHAR (3)  NOT NULL,
    [RLOAD]         NVARCHAR (1)  NOT NULL,
    [FIXPT]         NVARCHAR (1)  NOT NULL,
    [SSET]          NVARCHAR (1)  NOT NULL,
    [SDATE]         NVARCHAR (8)  NOT NULL,
    [STIME]         NVARCHAR (6)  NOT NULL,
    [IDATE]         NVARCHAR (8)  NOT NULL,
    [ITIME]         NVARCHAR (6)  NOT NULL,
    [LDBNAME]       NVARCHAR (20) NOT NULL,
    [UCCHECK]       NVARCHAR (1)  NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([NAME]));

