CREATE TABLE [SrcSAP].[User2Company] (
    [EmpID]   NVARCHAR (12) NOT NULL,
    [SAPRole] NVARCHAR (30) NOT NULL,
    [VARBL]   NVARCHAR (40) NOT NULL,
    [BUKRS]   NVARCHAR (40) NOT NULL,
    [ADName]  NVARCHAR (50) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([EmpID]));

