CREATE TABLE [SrcSAP].[VBAP] (
    [LZBatchID]           INT             NOT NULL,
    [ADLSBatchID]         INT             NOT NULL,
    [ADLSTimestamp]       DATETIME2 (0)   NOT NULL,
    [MANDT]               NVARCHAR (3)    NOT NULL,
    [VBELN]               NVARCHAR (10)   NOT NULL,
    [POSNR]               NVARCHAR (6)    NOT NULL,
    [MATNR]               NVARCHAR (18)   NOT NULL,
    [MATWA]               NVARCHAR (18)   NOT NULL,
    [PMATN]               NVARCHAR (18)   NOT NULL,
    [CHARG]               NVARCHAR (10)   NOT NULL,
    [MATKL]               NVARCHAR (9)    NOT NULL,
    [ARKTX]               NVARCHAR (40)   NOT NULL,
    [PSTYV]               NVARCHAR (4)    NOT NULL,
    [POSAR]               NVARCHAR (1)    NOT NULL,
    [LFREL]               NVARCHAR (1)    NOT NULL,
    [FKREL]               NVARCHAR (1)    NOT NULL,
    [UEPOS]               NVARCHAR (6)    NOT NULL,
    [GRPOS]               NVARCHAR (6)    NOT NULL,
    [ABGRU]               NVARCHAR (2)    NOT NULL,
    [PRODH]               NVARCHAR (18)   NOT NULL,
    [ZWERT]               DECIMAL (13, 2) NOT NULL,
    [ZMENG]               DECIMAL (13, 3) NOT NULL,
    [ZIEME]               NVARCHAR (3)    NOT NULL,
    [UMZIZ]               DECIMAL (5)     NOT NULL,
    [UMZIN]               DECIMAL (5)     NOT NULL,
    [MEINS]               NVARCHAR (3)    NOT NULL,
    [SMENG]               DECIMAL (13, 3) NOT NULL,
    [ABLFZ]               DECIMAL (13, 3) NOT NULL,
    [ABDAT]               NVARCHAR (8)    NOT NULL,
    [ABSFZ]               DECIMAL (13, 3) NOT NULL,
    [POSEX]               NVARCHAR (6)    NOT NULL,
    [KDMAT]               NVARCHAR (35)   NOT NULL,
    [KBVER]               DECIMAL (3)     NOT NULL,
    [KEVER]               DECIMAL (3)     NOT NULL,
    [VKGRU]               NVARCHAR (3)    NOT NULL,
    [VKAUS]               NVARCHAR (3)    NOT NULL,
    [GRKOR]               NVARCHAR (3)    NOT NULL,
    [FMENG]               NVARCHAR (1)    NOT NULL,
    [UEBTK]               NVARCHAR (1)    NOT NULL,
    [UEBTO]               DECIMAL (3, 1)  NOT NULL,
    [UNTTO]               DECIMAL (3, 1)  NOT NULL,
    [FAKSP]               NVARCHAR (2)    NOT NULL,
    [ATPKZ]               NVARCHAR (1)    NOT NULL,
    [RKFKF]               NVARCHAR (1)    NOT NULL,
    [SPART]               NVARCHAR (2)    NOT NULL,
    [GSBER]               NVARCHAR (4)    NOT NULL,
    [NETWR]               DECIMAL (15, 2) NOT NULL,
    [WAERK]               NVARCHAR (5)    NOT NULL,
    [ANTLF]               DECIMAL (1)     NOT NULL,
    [KZTLF]               NVARCHAR (1)    NOT NULL,
    [CHSPL]               NVARCHAR (1)    NOT NULL,
    [KWMENG]              DECIMAL (15, 3) NOT NULL,
    [LSMENG]              DECIMAL (15, 3) NOT NULL,
    [KBMENG]              DECIMAL (15, 3) NOT NULL,
    [KLMENG]              DECIMAL (15, 3) NOT NULL,
    [VRKME]               NVARCHAR (3)    NOT NULL,
    [UMVKZ]               DECIMAL (5)     NOT NULL,
    [UMVKN]               DECIMAL (5)     NOT NULL,
    [BRGEW]               DECIMAL (15, 3) NOT NULL,
    [NTGEW]               DECIMAL (15, 3) NOT NULL,
    [GEWEI]               NVARCHAR (3)    NOT NULL,
    [VOLUM]               DECIMAL (15, 3) NOT NULL,
    [VOLEH]               NVARCHAR (3)    NOT NULL,
    [VBELV]               NVARCHAR (10)   NOT NULL,
    [POSNV]               NVARCHAR (6)    NOT NULL,
    [VGBEL]               NVARCHAR (10)   NOT NULL,
    [VGPOS]               NVARCHAR (6)    NOT NULL,
    [VOREF]               NVARCHAR (1)    NOT NULL,
    [UPFLU]               NVARCHAR (1)    NOT NULL,
    [ERLRE]               NVARCHAR (1)    NOT NULL,
    [LPRIO]               NVARCHAR (2)    NOT NULL,
    [WERKS]               NVARCHAR (4)    NOT NULL,
    [LGORT]               NVARCHAR (4)    NOT NULL,
    [VSTEL]               NVARCHAR (4)    NOT NULL,
    [ROUTE]               NVARCHAR (6)    NOT NULL,
    [STKEY]               NVARCHAR (1)    NOT NULL,
    [STDAT]               NVARCHAR (8)    NOT NULL,
    [STLNR]               NVARCHAR (8)    NOT NULL,
    [STPOS]               DECIMAL (5)     NOT NULL,
    [AWAHR]               NVARCHAR (3)    NOT NULL,
    [ERDAT]               NVARCHAR (8)    NOT NULL,
    [ERNAM]               NVARCHAR (12)   NOT NULL,
    [ERZET]               NVARCHAR (6)    NOT NULL,
    [TAXM1]               NVARCHAR (1)    NOT NULL,
    [TAXM2]               NVARCHAR (1)    NOT NULL,
    [TAXM3]               NVARCHAR (1)    NOT NULL,
    [TAXM4]               NVARCHAR (1)    NOT NULL,
    [TAXM5]               NVARCHAR (1)    NOT NULL,
    [TAXM6]               NVARCHAR (1)    NOT NULL,
    [TAXM7]               NVARCHAR (1)    NOT NULL,
    [TAXM8]               NVARCHAR (1)    NOT NULL,
    [TAXM9]               NVARCHAR (1)    NOT NULL,
    [VBEAF]               DECIMAL (5, 2)  NOT NULL,
    [VBEAV]               DECIMAL (5, 2)  NOT NULL,
    [VGREF]               NVARCHAR (1)    NOT NULL,
    [NETPR]               DECIMAL (11, 2) NOT NULL,
    [KPEIN]               DECIMAL (5)     NOT NULL,
    [KMEIN]               NVARCHAR (3)    NOT NULL,
    [SHKZG]               NVARCHAR (1)    NOT NULL,
    [SKTOF]               NVARCHAR (1)    NOT NULL,
    [MTVFP]               NVARCHAR (2)    NOT NULL,
    [SUMBD]               NVARCHAR (1)    NOT NULL,
    [KONDM]               NVARCHAR (2)    NOT NULL,
    [KTGRM]               NVARCHAR (2)    NOT NULL,
    [BONUS]               NVARCHAR (2)    NOT NULL,
    [PROVG]               NVARCHAR (2)    NOT NULL,
    [EANNR]               NVARCHAR (13)   NOT NULL,
    [PRSOK]               NVARCHAR (1)    NOT NULL,
    [BWTAR]               NVARCHAR (10)   NOT NULL,
    [BWTEX]               NVARCHAR (1)    NOT NULL,
    [XCHPF]               NVARCHAR (1)    NOT NULL,
    [XCHAR]               NVARCHAR (1)    NOT NULL,
    [LFMNG]               DECIMAL (13, 3) NOT NULL,
    [STAFO]               NVARCHAR (6)    NOT NULL,
    [WAVWR]               DECIMAL (13, 2) NOT NULL,
    [KZWI1]               DECIMAL (13, 2) NOT NULL,
    [KZWI2]               DECIMAL (13, 2) NOT NULL,
    [KZWI3]               DECIMAL (13, 2) NOT NULL,
    [KZWI4]               DECIMAL (13, 2) NOT NULL,
    [KZWI5]               DECIMAL (13, 2) NOT NULL,
    [KZWI6]               DECIMAL (13, 2) NOT NULL,
    [STCUR]               DECIMAL (9, 5)  NOT NULL,
    [AEDAT]               NVARCHAR (8)    NOT NULL,
    [EAN11]               NVARCHAR (18)   NOT NULL,
    [FIXMG]               NVARCHAR (1)    NOT NULL,
    [PRCTR]               NVARCHAR (10)   NOT NULL,
    [MVGR1]               NVARCHAR (3)    NOT NULL,
    [MVGR2]               NVARCHAR (3)    NOT NULL,
    [MVGR3]               NVARCHAR (3)    NOT NULL,
    [MVGR4]               NVARCHAR (3)    NOT NULL,
    [MVGR5]               NVARCHAR (3)    NOT NULL,
    [KMPMG]               DECIMAL (13, 3) NOT NULL,
    [SUGRD]               NVARCHAR (4)    NOT NULL,
    [SOBKZ]               NVARCHAR (1)    NOT NULL,
    [VPZUO]               NVARCHAR (1)    NOT NULL,
    [PAOBJNR]             NVARCHAR (10)   NOT NULL,
    [PS_PSP_PNR]          NVARCHAR (8)    NOT NULL,
    [AUFNR]               NVARCHAR (12)   NOT NULL,
    [VPMAT]               NVARCHAR (18)   NOT NULL,
    [VPWRK]               NVARCHAR (4)    NOT NULL,
    [PRBME]               NVARCHAR (3)    NOT NULL,
    [UMREF]               DECIMAL (15)    NOT NULL,
    [KNTTP]               NVARCHAR (1)    NOT NULL,
    [KZVBR]               NVARCHAR (1)    NOT NULL,
    [SERNR]               NVARCHAR (8)    NOT NULL,
    [OBJNR]               NVARCHAR (22)   NOT NULL,
    [ABGRS]               NVARCHAR (6)    NOT NULL,
    [BEDAE]               NVARCHAR (4)    NOT NULL,
    [CMPRE]               DECIMAL (11, 2) NOT NULL,
    [CMTFG]               NVARCHAR (1)    NOT NULL,
    [CMPNT]               NVARCHAR (1)    NOT NULL,
    [CMKUA]               DECIMAL (9, 5)  NOT NULL,
    [CUOBJ]               NVARCHAR (18)   NOT NULL,
    [CUOBJ_CH]            NVARCHAR (18)   NOT NULL,
    [CEPOK]               NVARCHAR (1)    NOT NULL,
    [KOUPD]               NVARCHAR (1)    NOT NULL,
    [SERAIL]              NVARCHAR (4)    NOT NULL,
    [ANZSN]               INT             NOT NULL,
    [NACHL]               NVARCHAR (1)    NOT NULL,
    [MAGRV]               NVARCHAR (4)    NOT NULL,
    [MPROK]               NVARCHAR (1)    NOT NULL,
    [VGTYP]               NVARCHAR (1)    NOT NULL,
    [PROSA]               NVARCHAR (1)    NOT NULL,
    [UEPVW]               NVARCHAR (1)    NOT NULL,
    [KALNR]               NVARCHAR (12)   NOT NULL,
    [KLVAR]               NVARCHAR (4)    NOT NULL,
    [SPOSN]               NVARCHAR (4)    NOT NULL,
    [KOWRR]               NVARCHAR (1)    NOT NULL,
    [STADAT]              NVARCHAR (8)    NOT NULL,
    [EXART]               NVARCHAR (2)    NOT NULL,
    [PREFE]               NVARCHAR (1)    NOT NULL,
    [KNUMH]               NVARCHAR (10)   NOT NULL,
    [CLINT]               NVARCHAR (10)   NOT NULL,
    [CHMVS]               NVARCHAR (3)    NOT NULL,
    [STLTY]               NVARCHAR (1)    NOT NULL,
    [STLKN]               NVARCHAR (8)    NOT NULL,
    [STPOZ]               NVARCHAR (8)    NOT NULL,
    [STMAN]               NVARCHAR (1)    NOT NULL,
    [ZSCHL_K]             NVARCHAR (6)    NOT NULL,
    [KALSM_K]             NVARCHAR (6)    NOT NULL,
    [KALVAR]              NVARCHAR (4)    NOT NULL,
    [KOSCH]               NVARCHAR (18)   NOT NULL,
    [UPMAT]               NVARCHAR (18)   NOT NULL,
    [UKONM]               NVARCHAR (2)    NOT NULL,
    [MFRGR]               NVARCHAR (8)    NOT NULL,
    [PLAVO]               NVARCHAR (4)    NOT NULL,
    [KANNR]               NVARCHAR (35)   NOT NULL,
    [CMPRE_FLT]           DECIMAL (15)    NOT NULL,
    [ABFOR]               NVARCHAR (2)    NOT NULL,
    [ABGES]               DECIMAL (15)    NOT NULL,
    [J_1BCFOP]            NVARCHAR (10)   NOT NULL,
    [J_1BTAXLW1]          NVARCHAR (3)    NOT NULL,
    [J_1BTAXLW2]          NVARCHAR (3)    NOT NULL,
    [J_1BTXSDC]           NVARCHAR (2)    NOT NULL,
    [WKTNR]               NVARCHAR (10)   NOT NULL,
    [WKTPS]               NVARCHAR (6)    NOT NULL,
    [SKOPF]               NVARCHAR (18)   NOT NULL,
    [KZBWS]               NVARCHAR (1)    NOT NULL,
    [WGRU1]               NVARCHAR (18)   NOT NULL,
    [WGRU2]               NVARCHAR (18)   NOT NULL,
    [KNUMA_PI]            NVARCHAR (10)   NOT NULL,
    [KNUMA_AG]            NVARCHAR (10)   NOT NULL,
    [KZFME]               NVARCHAR (1)    NOT NULL,
    [LSTANR]              NVARCHAR (1)    NOT NULL,
    [TECHS]               NVARCHAR (12)   NOT NULL,
    [MWSBP]               DECIMAL (13, 2) NOT NULL,
    [BERID]               NVARCHAR (10)   NOT NULL,
    [PCTRF]               NVARCHAR (10)   NOT NULL,
    [LOGSYS_EXT]          NVARCHAR (10)   NOT NULL,
    [J_1BTAXLW3]          NVARCHAR (3)    NOT NULL,
    [J_1BTAXLW4]          NVARCHAR (3)    NOT NULL,
    [J_1BTAXLW5]          NVARCHAR (3)    NOT NULL,
    [STOCKLOC]            NVARCHAR (20)   NOT NULL,
    [SLOCTYPE]            NVARCHAR (4)    NOT NULL,
    [MSR_RET_REASON]      NVARCHAR (3)    NOT NULL,
    [MSR_REFUND_CODE]     NVARCHAR (3)    NOT NULL,
    [MSR_APPROV_BLOCK]    NVARCHAR (1)    NOT NULL,
    [NRAB_KNUMH]          NVARCHAR (10)   NOT NULL,
    [TRMRISK_RELEVANT]    NVARCHAR (2)    NOT NULL,
    [SGT_RCAT]            NVARCHAR (16)   NOT NULL,
    [HANDOVERLOC]         NVARCHAR (10)   NOT NULL,
    [HANDOVERDATE]        NVARCHAR (8)    NOT NULL,
    [HANDOVERTIME]        NVARCHAR (6)    NOT NULL,
    [TC_AUT_DET]          NVARCHAR (2)    NOT NULL,
    [MANUAL_TC_REASON]    NVARCHAR (2)    NOT NULL,
    [FISCAL_INCENTIVE]    NVARCHAR (4)    NOT NULL,
    [TAX_SUBJECT_ST]      NVARCHAR (1)    NOT NULL,
    [FISCAL_INCENTIVE_ID] NVARCHAR (4)    NOT NULL,
    [SPCSTO]              NVARCHAR (2)    NOT NULL,
    [/BEV1/SRFUND]        NVARCHAR (2)    NOT NULL,
    [ZAPCGKI]             NVARCHAR (4)    NOT NULL,
    [APCGK_EXTENDI]       NVARCHAR (10)   NOT NULL,
    [ZABDATI]             NVARCHAR (8)    NOT NULL,
    [AUFPL_OLC]           NVARCHAR (10)   NOT NULL,
    [APLZL_OLC]           NVARCHAR (8)    NOT NULL,
    [PLAUFZ]              NVARCHAR (3)    NOT NULL,
    [PLAUEZ]              NVARCHAR (1)    NOT NULL,
    [CONTNBR]             NVARCHAR (10)   NOT NULL,
    [CONTITM]             NVARCHAR (6)    NOT NULL,
    [AUDAT]               NVARCHAR (8)    NOT NULL,
    [AD01PROFNR]          NVARCHAR (8)    NOT NULL,
    [ADMOI]               NVARCHAR (4)    NOT NULL,
    [ADICC]               NVARCHAR (2)    NOT NULL,
    [ADPRI]               NVARCHAR (3)    NOT NULL,
    [SEL]                 NVARCHAR (1)    NOT NULL,
    [CCI]                 NVARCHAR (1)    NOT NULL,
    [SEN]                 NVARCHAR (6)    NOT NULL,
    [PSEL]                NVARCHAR (1)    NOT NULL,
    [PCCI]                NVARCHAR (1)    NOT NULL,
    [PSEN]                NVARCHAR (6)    NOT NULL,
    [CAN]                 NVARCHAR (20)   NOT NULL,
    [ICY]                 NVARCHAR (2)    NOT NULL,
    [ITY]                 NVARCHAR (2)    NOT NULL,
    [KWD]                 NVARCHAR (12)   NOT NULL,
    [AGE]                 NVARCHAR (12)   NOT NULL,
    [SPQ]                 NVARCHAR (4)    NOT NULL,
    [PLT]                 NVARCHAR (2)    NOT NULL,
    [DMC]                 NVARCHAR (6)    NOT NULL,
    [MSQ]                 NVARCHAR (5)    NOT NULL,
    [PCA]                 NVARCHAR (2)    NOT NULL,
    [UDC]                 NVARCHAR (5)    NOT NULL,
    [SHM]                 NVARCHAR (3)    NOT NULL,
    [CAR]                 NVARCHAR (5)    NOT NULL,
    [SHF]                 NVARCHAR (5)    NOT NULL,
    [COP]                 NVARCHAR (5)    NOT NULL,
    [IPP]                 NVARCHAR (9)    NOT NULL,
    [SIN]                 NVARCHAR (1)    NOT NULL,
    [TRU]                 NVARCHAR (20)   NOT NULL,
    [AMN]                 NVARCHAR (3)    NOT NULL,
    [ECC]                 NVARCHAR (7)    NOT NULL,
    [DNO]                 NVARCHAR (12)   NOT NULL,
    [STATUS]              NVARCHAR (20)   NOT NULL,
    [LABSG]               NVARCHAR (1)    NOT NULL,
    [FABSG]               NVARCHAR (1)    NOT NULL,
    [PR_L_L]              NVARCHAR (10)   NOT NULL,
    [PR_F_F]              NVARCHAR (10)   NOT NULL,
    [PR_F_L]              NVARCHAR (10)   NOT NULL,
    [FERC_IND]            NVARCHAR (4)    NOT NULL,
    [KOSTL]               NVARCHAR (10)   NOT NULL,
    [FONDS]               NVARCHAR (10)   NOT NULL,
    [FISTL]               NVARCHAR (16)   NOT NULL,
    [FKBER]               NVARCHAR (16)   NOT NULL,
    [GRANT_NBR]           NVARCHAR (20)   NOT NULL,
    [BUDGET_PD]           NVARCHAR (10)   NOT NULL,
    [FITLIST]             NVARCHAR (1)    NOT NULL,
    [RULECHECK]           NVARCHAR (1)    NOT NULL,
    [IUID_RELEVANT]       NVARCHAR (1)    NOT NULL,
    [EQUNR]               NVARCHAR (18)   NOT NULL,
    [EQART]               NVARCHAR (10)   NOT NULL,
    [J_3GLVART]           NVARCHAR (4)    NOT NULL,
    [J_3GDATVO]           NVARCHAR (8)    NOT NULL,
    [J_3GDATBI]           NVARCHAR (8)    NOT NULL,
    [J_3GBELNRI]          NVARCHAR (10)   NOT NULL,
    [J_3GPOSNRI]          NVARCHAR (5)    NOT NULL,
    [MILL_SE_GPOSN]       NVARCHAR (6)    NOT NULL,
    [MILL_BATCH_SEL_F]    NVARCHAR (1)    NOT NULL,
    [PRS_OBJNR]           NVARCHAR (22)   NOT NULL,
    [PRS_SD_SPSNR]        NVARCHAR (8)    NOT NULL,
    [PRS_WORK_PERIOD]     NVARCHAR (7)    NOT NULL,
    [TAS]                 NVARCHAR (30)   NOT NULL,
    [BETC]                NVARCHAR (10)   NOT NULL,
    [MOD_ALLOW]           NVARCHAR (1)    NOT NULL,
    [CANCEL_ALLOW]        NVARCHAR (1)    NOT NULL,
    [PAY_METHOD]          NVARCHAR (10)   NOT NULL,
    [BPN]                 NVARCHAR (6)    NOT NULL,
    [REP_FREQ]            NVARCHAR (3)    NOT NULL,
    [FMFGUS_KEY]          NVARCHAR (22)   NOT NULL,
    [PARGB]               NVARCHAR (4)    NOT NULL,
    [AUFPL_OAA]           NVARCHAR (10)   NOT NULL,
    [APLZL_OAA]           NVARCHAR (8)    NOT NULL,
    [SCNBR]               NVARCHAR (10)   NOT NULL,
    [SCITEM]              NVARCHAR (6)    NOT NULL,
    [SCMATNR]             NVARCHAR (18)   NOT NULL,
    [PROFILE]             NVARCHAR (10)   NOT NULL,
    [VARIANT]             NVARCHAR (14)   NOT NULL,
    [VLCENDCU]            NVARCHAR (10)   NOT NULL,
    [WRF_CHARSTC1]        NVARCHAR (18)   NOT NULL,
    [WRF_CHARSTC2]        NVARCHAR (18)   NOT NULL,
    [WRF_CHARSTC3]        NVARCHAR (18)   NOT NULL,
    [ARSNUM]              NVARCHAR (10)   NOT NULL,
    [ARSPOS]              NVARCHAR (4)    NOT NULL,
    [WTYSC_CLMITEM]       NVARCHAR (16)   NOT NULL,
    [ZZTOT_QTY]           SMALLINT        NOT NULL,
    [ZZFRE_QTY]           SMALLINT        NOT NULL,
    [ZZDELI_TYPE]         NVARCHAR (30)   NOT NULL,
    [ZZTREAT_OPT]         NVARCHAR (30)   NOT NULL,
    [ZZPROD_PRIO]         NVARCHAR (2)    NOT NULL,
    [ZZREF_MATNR]         NVARCHAR (18)   NOT NULL,
    [ZZITEM_CLASSI]       NVARCHAR (6)    NOT NULL,
    [ZZPROMO]             NVARCHAR (6)    NOT NULL,
    [ZZTREV_DATE]         NVARCHAR (8)    NOT NULL,
    [ZZTOT_QTY_COPA]      NVARCHAR (10)   NOT NULL,
    [ZZFRE_QTY_COPA]      NVARCHAR (10)   NOT NULL,
    [ZZTOTAL_QTY]         SMALLINT        NOT NULL,
    [ZZCLINICAL]          NVARCHAR (1)    NOT NULL,
    [ZZTOTAL_QTY_COPA]    NVARCHAR (10)   NOT NULL,
    [ZZCOMP_IND]          NVARCHAR (10)   NOT NULL,
    [ZZMFG_PLANT]         NVARCHAR (4)    NOT NULL,
    [ZZMAX_STAGES]        NVARCHAR (10)   NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([VBELN]));


GO
CREATE NONCLUSTERED INDEX [VBAP_VBELN]
    ON [SrcSAP].[VBAP]([VBELN] ASC);

