CREATE TABLE [SrcSAP].[VBRP] (
    [LZBatchID]       INT             NOT NULL,
    [ADLSBatchID]     INT             NOT NULL,
    [ADLSTimestamp]   DATETIME2 (0)   NOT NULL,
    [MANDT]           NVARCHAR (3)    NOT NULL,
    [VBELN]           NVARCHAR (10)   NOT NULL,
    [POSNR]           NVARCHAR (6)    NOT NULL,
    [UEPOS]           NVARCHAR (6)    NOT NULL,
    [FKIMG]           DECIMAL (13, 3) NOT NULL,
    [VRKME]           NVARCHAR (3)    NOT NULL,
    [UMVKZ]           DECIMAL (5)     NOT NULL,
    [UMVKN]           DECIMAL (5)     NOT NULL,
    [MEINS]           NVARCHAR (3)    NOT NULL,
    [SMENG]           DECIMAL (13, 3) NOT NULL,
    [FKLMG]           DECIMAL (13, 3) NOT NULL,
    [LMENG]           DECIMAL (13, 3) NOT NULL,
    [NTGEW]           DECIMAL (15, 3) NOT NULL,
    [BRGEW]           DECIMAL (15, 3) NOT NULL,
    [GEWEI]           NVARCHAR (3)    NOT NULL,
    [VOLUM]           DECIMAL (15, 3) NOT NULL,
    [VOLEH]           NVARCHAR (3)    NOT NULL,
    [GSBER]           NVARCHAR (4)    NOT NULL,
    [PRSDT]           NVARCHAR (8)    NOT NULL,
    [FBUDA]           NVARCHAR (8)    NOT NULL,
    [KURSK]           DECIMAL (9, 5)  NOT NULL,
    [NETWR]           DECIMAL (15, 2) NOT NULL,
    [VBELV]           NVARCHAR (10)   NOT NULL,
    [POSNV]           NVARCHAR (6)    NOT NULL,
    [VGBEL]           NVARCHAR (10)   NOT NULL,
    [VGPOS]           NVARCHAR (6)    NOT NULL,
    [VGTYP]           NVARCHAR (1)    NOT NULL,
    [AUBEL]           NVARCHAR (10)   NOT NULL,
    [AUPOS]           NVARCHAR (6)    NOT NULL,
    [AUREF]           NVARCHAR (1)    NOT NULL,
    [MATNR]           NVARCHAR (18)   NOT NULL,
    [ARKTX]           NVARCHAR (40)   NOT NULL,
    [PMATN]           NVARCHAR (18)   NOT NULL,
    [CHARG]           NVARCHAR (10)   NULL,
    [MATKL]           NVARCHAR (9)    NULL,
    [PSTYV]           NVARCHAR (4)    NULL,
    [POSAR]           NVARCHAR (1)    NULL,
    [PRODH]           NVARCHAR (18)   NULL,
    [VSTEL]           NVARCHAR (4)    NULL,
    [ATPKZ]           NVARCHAR (1)    NULL,
    [SPART]           NVARCHAR (2)    NULL,
    [POSPA]           NVARCHAR (6)    NULL,
    [WERKS]           NVARCHAR (4)    NULL,
    [ALAND]           NVARCHAR (3)    NULL,
    [WKREG]           NVARCHAR (3)    NULL,
    [WKCOU]           NVARCHAR (3)    NULL,
    [WKCTY]           NVARCHAR (4)    NULL,
    [TAXM1]           NVARCHAR (1)    NULL,
    [TAXM2]           NVARCHAR (1)    NULL,
    [TAXM3]           NVARCHAR (1)    NULL,
    [TAXM4]           NVARCHAR (1)    NULL,
    [TAXM5]           NVARCHAR (1)    NULL,
    [TAXM6]           NVARCHAR (1)    NULL,
    [TAXM7]           NVARCHAR (1)    NULL,
    [TAXM8]           NVARCHAR (1)    NULL,
    [TAXM9]           NVARCHAR (1)    NULL,
    [KOWRR]           NVARCHAR (1)    NULL,
    [PRSFD]           NVARCHAR (1)    NULL,
    [SKTOF]           NVARCHAR (1)    NULL,
    [SKFBP]           DECIMAL (13, 2) NULL,
    [KONDM]           NVARCHAR (2)    NULL,
    [KTGRM]           NVARCHAR (2)    NULL,
    [KOSTL]           NVARCHAR (10)   NULL,
    [BONUS]           NVARCHAR (2)    NULL,
    [PROVG]           NVARCHAR (2)    NULL,
    [EANNR]           NVARCHAR (13)   NULL,
    [VKGRP]           NVARCHAR (3)    NULL,
    [VKBUR]           NVARCHAR (4)    NULL,
    [SPARA]           NVARCHAR (2)    NULL,
    [SHKZG]           NVARCHAR (1)    NULL,
    [ERNAM]           NVARCHAR (12)   NULL,
    [ERDAT]           NVARCHAR (8)    NULL,
    [ERZET]           NVARCHAR (6)    NULL,
    [BWTAR]           NVARCHAR (10)   NULL,
    [LGORT]           NVARCHAR (4)    NULL,
    [STAFO]           NVARCHAR (6)    NULL,
    [WAVWR]           DECIMAL (13, 2) NULL,
    [KZWI1]           DECIMAL (13, 2) NULL,
    [KZWI2]           DECIMAL (13, 2) NULL,
    [KZWI3]           DECIMAL (13, 2) NULL,
    [KZWI4]           DECIMAL (13, 2) NULL,
    [KZWI5]           DECIMAL (13, 2) NULL,
    [KZWI6]           DECIMAL (13, 2) NULL,
    [STCUR]           DECIMAL (9, 5)  NULL,
    [UVPRS]           NVARCHAR (1)    NULL,
    [UVALL]           NVARCHAR (1)    NULL,
    [EAN11]           NVARCHAR (18)   NULL,
    [PRCTR]           NVARCHAR (10)   NULL,
    [KVGR1]           NVARCHAR (3)    NULL,
    [KVGR2]           NVARCHAR (3)    NULL,
    [KVGR3]           NVARCHAR (3)    NULL,
    [KVGR4]           NVARCHAR (3)    NULL,
    [KVGR5]           NVARCHAR (3)    NULL,
    [MVGR1]           NVARCHAR (3)    NULL,
    [MVGR2]           NVARCHAR (3)    NULL,
    [MVGR3]           NVARCHAR (3)    NULL,
    [MVGR4]           NVARCHAR (3)    NULL,
    [MVGR5]           NVARCHAR (3)    NULL,
    [MATWA]           NVARCHAR (18)   NULL,
    [BONBA]           DECIMAL (13, 2) NULL,
    [KOKRS]           NVARCHAR (4)    NULL,
    [PAOBJNR]         NVARCHAR (10)   NULL,
    [PS_PSP_PNR]      NVARCHAR (8)    NULL,
    [AUFNR]           NVARCHAR (12)   NULL,
    [TXJCD]           NVARCHAR (15)   NULL,
    [CMPRE]           DECIMAL (11, 2) NULL,
    [CMPNT]           NVARCHAR (1)    NULL,
    [CUOBJ]           NVARCHAR (18)   NULL,
    [CUOBJ_CH]        NVARCHAR (18)   NULL,
    [KOUPD]           NVARCHAR (1)    NULL,
    [UECHA]           NVARCHAR (6)    NULL,
    [XCHAR]           NVARCHAR (1)    NULL,
    [ABRVW]           NVARCHAR (3)    NULL,
    [SERNR]           NVARCHAR (8)    NULL,
    [BZIRK_AUFT]      NVARCHAR (6)    NULL,
    [KDGRP_AUFT]      NVARCHAR (2)    NULL,
    [KONDA_AUFT]      NVARCHAR (2)    NULL,
    [LLAND_AUFT]      NVARCHAR (3)    NULL,
    [MPROK]           NVARCHAR (1)    NULL,
    [PLTYP_AUFT]      NVARCHAR (2)    NULL,
    [REGIO_AUFT]      NVARCHAR (3)    NULL,
    [VKORG_AUFT]      NVARCHAR (4)    NULL,
    [VTWEG_AUFT]      NVARCHAR (2)    NULL,
    [ABRBG]           NVARCHAR (8)    NULL,
    [PROSA]           NVARCHAR (1)    NULL,
    [UEPVW]           NVARCHAR (1)    NULL,
    [AUTYP]           NVARCHAR (1)    NULL,
    [STADAT]          NVARCHAR (8)    NULL,
    [FPLNR]           NVARCHAR (10)   NULL,
    [FPLTR]           NVARCHAR (6)    NULL,
    [AKTNR]           NVARCHAR (10)   NULL,
    [KNUMA_PI]        NVARCHAR (10)   NULL,
    [KNUMA_AG]        NVARCHAR (10)   NULL,
    [PREFE]           NVARCHAR (1)    NULL,
    [MWSBP]           DECIMAL (13, 2) NULL,
    [AUGRU_AUFT]      NVARCHAR (3)    NULL,
    [FAREG]           NVARCHAR (1)    NULL,
    [UPMAT]           NVARCHAR (18)   NULL,
    [UKONM]           NVARCHAR (2)    NULL,
    [CMPRE_FLT]       NVARCHAR (15)   NULL,
    [ABFOR]           NVARCHAR (2)    NULL,
    [ABGES]           NVARCHAR (15)   NULL,
    [J_1ARFZ]         NVARCHAR (1)    NULL,
    [J_1AREGIO]       NVARCHAR (3)    NULL,
    [J_1AGICD]        NVARCHAR (2)    NULL,
    [J_1ADTYP]        NVARCHAR (2)    NULL,
    [J_1ATXREL]       NVARCHAR (10)   NULL,
    [J_1BCFOP]        NVARCHAR (10)   NULL,
    [J_1BTAXLW1]      NVARCHAR (3)    NULL,
    [J_1BTAXLW2]      NVARCHAR (3)    NULL,
    [J_1BTXSDC]       NVARCHAR (2)    NULL,
    [BRTWR]           DECIMAL (15, 2) NULL,
    [WKTNR]           NVARCHAR (10)   NULL,
    [WKTPS]           NVARCHAR (6)    NULL,
    [RPLNR]           NVARCHAR (10)   NULL,
    [KURSK_DAT]       NVARCHAR (8)    NULL,
    [WGRU1]           NVARCHAR (18)   NULL,
    [WGRU2]           NVARCHAR (18)   NULL,
    [KDKG1]           NVARCHAR (2)    NULL,
    [KDKG2]           NVARCHAR (2)    NULL,
    [KDKG3]           NVARCHAR (2)    NULL,
    [KDKG4]           NVARCHAR (2)    NULL,
    [KDKG5]           NVARCHAR (2)    NULL,
    [VKAUS]           NVARCHAR (3)    NULL,
    [J_1AINDXP]       NVARCHAR (5)    NULL,
    [J_1AIDATEP]      NVARCHAR (8)    NULL,
    [KZFME]           NVARCHAR (1)    NULL,
    [MWSKZ]           NVARCHAR (2)    NULL,
    [VERTT]           NVARCHAR (1)    NULL,
    [VERTN]           NVARCHAR (13)   NULL,
    [SGTXT]           NVARCHAR (50)   NULL,
    [DELCO]           NVARCHAR (3)    NULL,
    [BEMOT]           NVARCHAR (2)    NULL,
    [RRREL]           NVARCHAR (1)    NULL,
    [AKKUR]           DECIMAL (9, 5)  NULL,
    [WMINR]           NVARCHAR (10)   NULL,
    [VGBEL_EX]        NVARCHAR (10)   NULL,
    [VGPOS_EX]        NVARCHAR (6)    NULL,
    [LOGSYS]          NVARCHAR (10)   NULL,
    [VGTYP_EX]        NVARCHAR (3)    NULL,
    [J_1BTAXLW3]      NVARCHAR (3)    NULL,
    [J_1BTAXLW4]      NVARCHAR (3)    NULL,
    [J_1BTAXLW5]      NVARCHAR (3)    NULL,
    [MSR_ID]          NVARCHAR (10)   NULL,
    [MSR_REFUND_CODE] NVARCHAR (3)    NULL,
    [MSR_RET_REASON]  NVARCHAR (3)    NULL,
    [NRAB_KNUMH]      NVARCHAR (10)   NULL,
    [NRAB_VALUE]      DECIMAL (13, 2) NULL,
    [DISPUTE_CASE]    NVARCHAR (100)  NULL,
    [FUND_USAGE_ITEM] NVARCHAR (100)  NULL,
    [FARR_RELTYPE]    NVARCHAR (10)   NULL,
    [CLAIMS_TAXATION] NVARCHAR (1)    NULL,
    [KURRF_DAT_ORIG]  NVARCHAR (8)    NULL,
    [VGTYP_EXT]       NVARCHAR (4)    NULL,
    [SGT_RCAT]        NVARCHAR (16)   NULL,
    [SGT_SCAT]        NVARCHAR (16)   NULL,
    [ZAPCGKI]         NVARCHAR (4)    NULL,
    [APCGK_EXTENDI]   NVARCHAR (10)   NULL,
    [ZABDATI]         NVARCHAR (8)    NULL,
    [AUFPL]           NVARCHAR (10)   NULL,
    [APLZL]           NVARCHAR (8)    NULL,
    [AUDAT]           NVARCHAR (8)    NULL,
    [EDATU]           NVARCHAR (8)    NULL,
    [PLAUFZ]          NVARCHAR (3)    NULL,
    [PLAUEZ]          NVARCHAR (1)    NULL,
    [CONTNBR]         NVARCHAR (10)   NULL,
    [CONTITM]         NVARCHAR (6)    NULL,
    [DPCNR]           NVARCHAR (10)   NULL,
    [DCPNR]           NVARCHAR (3)    NULL,
    [DPNRB]           NVARCHAR (3)    NULL,
    [BOSFAR]          NVARCHAR (1)    NULL,
    [DP_BELNR]        NVARCHAR (10)   NULL,
    [DP_BUKRS]        NVARCHAR (4)    NULL,
    [DP_GJAHR]        NVARCHAR (4)    NULL,
    [DP_BUZEI]        NVARCHAR (3)    NULL,
    [PACKNO]          NVARCHAR (10)   NULL,
    [PEROP_BEG]       NVARCHAR (8)    NULL,
    [PEROP_END]       NVARCHAR (8)    NULL,
    [FMFGUS_KEY]      NVARCHAR (22)   NULL,
    [FONDS]           NVARCHAR (10)   NULL,
    [FISTL]           NVARCHAR (16)   NULL,
    [FKBER]           NVARCHAR (16)   NULL,
    [GRANT_NBR]       NVARCHAR (20)   NULL,
    [BUDGET_PD]       NVARCHAR (10)   NULL,
    [J_3GBELNRI]      NVARCHAR (10)   NULL,
    [J_3GPMAUFE]      NVARCHAR (12)   NULL,
    [J_3GPMAUFV]      NVARCHAR (12)   NULL,
    [J_3GETYPA]       NVARCHAR (2)    NULL,
    [J_3GETYPE]       NVARCHAR (2)    NULL,
    [J_3GORGUEB]      NVARCHAR (1)    NULL,
    [PRS_WORK_PERIOD] NVARCHAR (7)    NULL,
    [PPRCTR]          NVARCHAR (10)   NULL,
    [PARGB]           NVARCHAR (4)    NULL,
    [AUFPL_OAA]       NVARCHAR (10)   NULL,
    [APLZL_OAA]       NVARCHAR (8)    NULL,
    [CAMPAIGN]        NVARCHAR (100)  NULL,
    [COMPREAS]        NVARCHAR (4)    NULL,
    [WRF_CHARSTC1]    NVARCHAR (18)   NULL,
    [WRF_CHARSTC2]    NVARCHAR (18)   NULL,
    [WRF_CHARSTC3]    NVARCHAR (18)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([VBELN]));

