CREATE TABLE [SrcSAP].[ZRTR_MKPF_MSEG1] (
    [LZBatchID]        INT             NOT NULL,
    [ADLSBatchID]      INT             NOT NULL,
    [ADLSTimestamp]    DATETIME2 (0)   NOT NULL,
    [MANDT]            NVARCHAR (15)   NULL,
    [MBLNR]            NVARCHAR (20)   NOT NULL,
    [MJAHR]            INT             NOT NULL,
    [VGART]            NVARCHAR (15)   NULL,
    [BLART]            NVARCHAR (15)   NULL,
    [BLAUM]            NVARCHAR (10)   NULL,
    [BLDAT]            NVARCHAR (15)   NULL,
    [BUDAT]            NVARCHAR (15)   NULL,
    [CPUDT]            NVARCHAR (15)   NULL,
    [CPUTM]            NVARCHAR (15)   NULL,
    [AEDAT]            NVARCHAR (15)   NULL,
    [USNAM]            NVARCHAR (20)   NULL,
    [TCODE]            NVARCHAR (15)   NULL,
    [XBLNR]            NVARCHAR (20)   NULL,
    [BKTXT]            NVARCHAR (30)   NULL,
    [FRATH]            DECIMAL (13, 3) NULL,
    [FRBNR]            NVARCHAR (20)   NULL,
    [WEVER]            NVARCHAR (10)   NULL,
    [XABLN]            NVARCHAR (15)   NULL,
    [AWSYS]            NVARCHAR (15)   NULL,
    [BLA2D]            NVARCHAR (10)   NULL,
    [TCODE2]           NVARCHAR (30)   NULL,
    [BFWMS]            NVARCHAR (15)   NULL,
    [EXNUM]            NVARCHAR (15)   NULL,
    [SPE_BUDAT_UHR]    NVARCHAR (10)   NULL,
    [SPE_BUDAT_ZONE]   NVARCHAR (10)   NULL,
    [LE_VBELN]         NVARCHAR (15)   NULL,
    [SPE_LOGSYS]       NVARCHAR (15)   NULL,
    [SPE_MDNUM_EWM]    NVARCHAR (20)   NULL,
    [GTS_CUSREF_NO]    NVARCHAR (50)   NULL,
    [FLS_RSTO]         NVARCHAR (15)   NULL,
    [MSR_ACTIVE]       NVARCHAR (10)   NULL,
    [KNUMV]            NVARCHAR (15)   NULL,
    [XCOMPL]           NVARCHAR (25)   NULL,
    [MSEG_MANDT]       NVARCHAR (25)   NULL,
    [MSEG_MBLNR]       NVARCHAR (25)   NULL,
    [MSEG_MJAHR]       NVARCHAR (25)   NULL,
    [ZEILE]            NVARCHAR (25)   NOT NULL,
    [LINE_ID]          NVARCHAR (20)   NULL,
    [PARENT_ID]        NVARCHAR (20)   NULL,
    [LINE_DEPTH]       NVARCHAR (25)   NULL,
    [MAA_URZEI]        NVARCHAR (25)   NULL,
    [BWART]            NVARCHAR (10)   NULL,
    [XAUTO]            NVARCHAR (10)   NULL,
    [MATNR]            NVARCHAR (30)   NULL,
    [WERKS]            NVARCHAR (10)   NULL,
    [LGORT]            NVARCHAR (10)   NULL,
    [CHARG]            NVARCHAR (15)   NULL,
    [INSMK]            NVARCHAR (10)   NULL,
    [ZUSCH]            NVARCHAR (10)   NULL,
    [ZUSTD]            NVARCHAR (10)   NULL,
    [SOBKZ]            NVARCHAR (10)   NULL,
    [LIFNR]            NVARCHAR (15)   NULL,
    [KUNNR]            NVARCHAR (15)   NULL,
    [KDAUF]            NVARCHAR (15)   NULL,
    [KDPOS]            NVARCHAR (25)   NULL,
    [KDEIN]            NVARCHAR (25)   NULL,
    [PLPLA]            NVARCHAR (15)   NULL,
    [SHKZG]            NVARCHAR (20)   NULL,
    [WAERS]            NVARCHAR (15)   NULL,
    [DMBTR]            DECIMAL (20, 3) NULL,
    [BNBTR]            DECIMAL (20, 3) NULL,
    [BUALT]            DECIMAL (20, 3) NULL,
    [SHKUM]            NVARCHAR (20)   NULL,
    [DMBUM]            DECIMAL (20, 3) NULL,
    [BWTAR]            NVARCHAR (15)   NULL,
    [MENGE]            DECIMAL (20, 3) NULL,
    [MEINS]            NVARCHAR (25)   NULL,
    [ERFMG]            DECIMAL (20, 3) NULL,
    [ERFME]            NVARCHAR (25)   NULL,
    [BPMNG]            DECIMAL (20, 3) NULL,
    [BPRME]            NVARCHAR (25)   NULL,
    [EBELN]            NVARCHAR (15)   NULL,
    [EBELP]            NVARCHAR (25)   NULL,
    [LFBJA]            NVARCHAR (25)   NULL,
    [LFBNR]            NVARCHAR (15)   NULL,
    [LFPOS]            NVARCHAR (25)   NULL,
    [SJAHR]            NVARCHAR (25)   NULL,
    [SMBLN]            NVARCHAR (15)   NULL,
    [SMBLP]            NVARCHAR (25)   NULL,
    [ELIKZ]            NVARCHAR (20)   NULL,
    [SGTXT]            NVARCHAR (60)   NULL,
    [EQUNR]            NVARCHAR (20)   NULL,
    [WEMPF]            NVARCHAR (15)   NULL,
    [ABLAD]            NVARCHAR (30)   NULL,
    [GSBER]            NVARCHAR (10)   NULL,
    [KOKRS]            NVARCHAR (10)   NULL,
    [PARGB]            NVARCHAR (10)   NULL,
    [PARBU]            NVARCHAR (10)   NULL,
    [KOSTL]            NVARCHAR (15)   NULL,
    [PROJN]            NVARCHAR (20)   NULL,
    [AUFNR]            NVARCHAR (25)   NULL,
    [ANLN1]            NVARCHAR (25)   NULL,
    [ANLN2]            NVARCHAR (10)   NULL,
    [XSKST]            NVARCHAR (10)   NULL,
    [XSAUF]            NVARCHAR (10)   NULL,
    [XSPRO]            NVARCHAR (20)   NULL,
    [XSERG]            NVARCHAR (20)   NULL,
    [GJAHR]            NVARCHAR (25)   NULL,
    [XRUEM]            NVARCHAR (20)   NULL,
    [XRUEJ]            NVARCHAR (20)   NULL,
    [BUKRS]            NVARCHAR (20)   NULL,
    [BELNR]            NVARCHAR (15)   NULL,
    [BUZEI]            NVARCHAR (25)   NULL,
    [BELUM]            NVARCHAR (15)   NULL,
    [BUZUM]            NVARCHAR (25)   NULL,
    [RSNUM]            NVARCHAR (25)   NULL,
    [RSPOS]            NVARCHAR (25)   NULL,
    [KZEAR]            NVARCHAR (10)   NULL,
    [PBAMG]            DECIMAL (13, 3) NULL,
    [KZSTR]            NVARCHAR (10)   NULL,
    [UMMAT]            NVARCHAR (25)   NULL,
    [UMWRK]            NVARCHAR (20)   NULL,
    [UMLGO]            NVARCHAR (20)   NULL,
    [UMCHA]            NVARCHAR (15)   NULL,
    [UMZST]            NVARCHAR (10)   NULL,
    [UMZUS]            NVARCHAR (10)   NULL,
    [UMBAR]            NVARCHAR (15)   NULL,
    [UMSOK]            NVARCHAR (10)   NULL,
    [KZBEW]            NVARCHAR (10)   NULL,
    [KZVBR]            NVARCHAR (10)   NULL,
    [KZZUG]            NVARCHAR (10)   NULL,
    [WEUNB]            NVARCHAR (10)   NULL,
    [PALAN]            DECIMAL (13, 2) NULL,
    [LGNUM]            NVARCHAR (10)   NULL,
    [LGTYP]            NVARCHAR (10)   NULL,
    [LGPLA]            NVARCHAR (15)   NULL,
    [BESTQ]            NVARCHAR (20)   NULL,
    [BWLVS]            NVARCHAR (25)   NULL,
    [TBNUM]            NVARCHAR (25)   NULL,
    [TBPOS]            NVARCHAR (25)   NULL,
    [XBLVS]            NVARCHAR (20)   NULL,
    [VSCHN]            NVARCHAR (20)   NULL,
    [NSCHN]            NVARCHAR (20)   NULL,
    [DYPLA]            NVARCHAR (10)   NULL,
    [UBNUM]            NVARCHAR (25)   NULL,
    [TBPRI]            NVARCHAR (10)   NULL,
    [TANUM]            NVARCHAR (25)   NULL,
    [WEANZ]            NVARCHAR (25)   NULL,
    [GRUND]            NVARCHAR (25)   NULL,
    [EVERS]            NVARCHAR (10)   NULL,
    [EVERE]            NVARCHAR (10)   NULL,
    [IMKEY]            NVARCHAR (10)   NULL,
    [KSTRG]            NVARCHAR (15)   NULL,
    [PAOBJNR]          NVARCHAR (25)   NULL,
    [PRCTR]            NVARCHAR (10)   NULL,
    [PS_PSP_PNR]       NVARCHAR (25)   NULL,
    [NPLNR]            NVARCHAR (15)   NULL,
    [AUFPL]            NVARCHAR (25)   NULL,
    [APLZL]            NVARCHAR (25)   NULL,
    [AUFPS]            NVARCHAR (25)   NULL,
    [VPTNR]            NVARCHAR (15)   NULL,
    [FIPOS]            NVARCHAR (20)   NULL,
    [SAKTO]            NVARCHAR (15)   NULL,
    [BSTMG]            DECIMAL (13, 3) NULL,
    [BSTME]            NVARCHAR (25)   NULL,
    [XWSBR]            NVARCHAR (10)   NULL,
    [EMLIF]            NVARCHAR (15)   NULL,
    [EXBWR]            DECIMAL (13, 3) NULL,
    [VKWRT]            DECIMAL (13, 3) NULL,
    [AKTNR]            NVARCHAR (20)   NULL,
    [ZEKKN]            NVARCHAR (25)   NULL,
    [VFDAT]            NVARCHAR (20)   NULL,
    [CUOBJ_CH]         NVARCHAR (25)   NULL,
    [EXVKW]            DECIMAL (13, 3) NULL,
    [PPRCTR]           NVARCHAR (15)   NULL,
    [RSART]            NVARCHAR (20)   NULL,
    [GEBER]            NVARCHAR (15)   NULL,
    [FISTL]            NVARCHAR (20)   NULL,
    [MATBF]            NVARCHAR (20)   NULL,
    [UMMAB]            NVARCHAR (20)   NULL,
    [BUSTM]            NVARCHAR (20)   NULL,
    [BUSTW]            NVARCHAR (10)   NULL,
    [MENGU]            NVARCHAR (10)   NULL,
    [WERTU]            NVARCHAR (10)   NULL,
    [LBKUM]            DECIMAL (13, 3) NULL,
    [SALK3]            DECIMAL (13, 3) NULL,
    [VPRSV]            NVARCHAR (10)   NULL,
    [FKBER]            NVARCHAR (20)   NULL,
    [DABRBZ]           NVARCHAR (10)   NULL,
    [VKWRA]            DECIMAL (13, 3) NULL,
    [DABRZ]            NVARCHAR (10)   NULL,
    [XBEAU]            NVARCHAR (10)   NULL,
    [LSMNG]            DECIMAL (13, 3) NULL,
    [LSMEH]            NVARCHAR (25)   NULL,
    [KZBWS]            NVARCHAR (20)   NULL,
    [QINSPST]          NVARCHAR (10)   NULL,
    [URZEI]            NVARCHAR (25)   NULL,
    [J_1BEXBASE]       DECIMAL (20, 3) NULL,
    [MWSKZ]            NVARCHAR (20)   NULL,
    [TXJCD]            NVARCHAR (20)   NULL,
    [EMATN]            NVARCHAR (25)   NULL,
    [J_1AGIRUPD]       NVARCHAR (20)   NULL,
    [VKMWS]            NVARCHAR (10)   NULL,
    [HSDAT]            NVARCHAR (10)   NULL,
    [BERKZ]            NVARCHAR (10)   NULL,
    [MAT_KDAUF]        NVARCHAR (20)   NULL,
    [MAT_KDPOS]        NVARCHAR (25)   NULL,
    [MAT_PSPNR]        NVARCHAR (25)   NULL,
    [XWOFF]            NVARCHAR (10)   NULL,
    [BEMOT]            NVARCHAR (10)   NULL,
    [PRZNR]            NVARCHAR (15)   NULL,
    [LLIEF]            NVARCHAR (10)   NULL,
    [LSTAR]            NVARCHAR (10)   NULL,
    [XOBEW]            NVARCHAR (10)   NULL,
    [GRANT_NBR]        NVARCHAR (25)   NULL,
    [ZUSTD_T156M]      NVARCHAR (10)   NULL,
    [SPE_GTS_STOCK_TY] NVARCHAR (10)   NULL,
    [KBLNR]            NVARCHAR (15)   NULL,
    [KBLPOS]           NVARCHAR (25)   NULL,
    [XMACC]            NVARCHAR (10)   NULL,
    [VGART_MKPF]       NVARCHAR (20)   NULL,
    [BUDAT_MKPF]       NVARCHAR (10)   NULL,
    [CPUDT_MKPF]       NVARCHAR (10)   NULL,
    [CPUTM_MKPF]       NVARCHAR (10)   NULL,
    [USNAM_MKPF]       NVARCHAR (20)   NULL,
    [XBLNR_MKPF]       NVARCHAR (20)   NULL,
    [TCODE2_MKPF]      NVARCHAR (30)   NULL,
    [VBELN_IM]         NVARCHAR (30)   NULL,
    [VBELP_IM]         NVARCHAR (15)   NULL,
    [SGT_SCAT]         NVARCHAR (20)   NULL,
    [SGT_UMSCAT]       NVARCHAR (20)   NULL,
    [_DATAAGING]       NVARCHAR (15)   NULL,
    [SGT_RCAT]         NVARCHAR (20)   NULL,
    [/BEV2/ED_KZ_VER]  NVARCHAR (15)   NULL,
    [/BEV2/ED_USER]    NVARCHAR (15)   NULL,
    [/BEV2/ED_AEDAT]   NVARCHAR (15)   NULL,
    [/BEV2/ED_AETIM]   NVARCHAR (15)   NULL,
    [DISUB_OWNER]      NVARCHAR (15)   NULL,
    [COMPL_MARK]       NVARCHAR (10)   NULL,
    [FZGLS_MARK]       NVARCHAR (20)   NULL,
    [ETANP_MARK]       NVARCHAR (15)   NULL,
    [POPUP_MARK]       NVARCHAR (20)   NULL,
    [OINAVNW]          DECIMAL (10, 2) NULL,
    [OICONDCOD]        NVARCHAR (20)   NULL,
    [CONDI]            NVARCHAR (10)   NULL,
    [WRF_CHARSTC1]     NVARCHAR (25)   NULL,
    [WRF_CHARSTC2]     NVARCHAR (25)   NULL,
    [WRF_CHARSTC3]     NVARCHAR (25)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([MBLNR]));

