CREATE TABLE [SrcSAP].[ZRTR_MKPF_MSEG1_ParquetLoad]
(
	[MANDT] [nvarchar](15) NULL,
	[MBLNR] [nvarchar](20) NOT NULL,
	[MJAHR] [nvarchar](20) NOT NULL,
	[VGART] [nvarchar](15) NULL,
	[BLART] [nvarchar](15) NULL,
	[BLAUM] [nvarchar](10) NULL,
	[BLDAT] [nvarchar](15) NULL,
	[BUDAT] [nvarchar](15) NULL,
	[CPUDT] [nvarchar](15) NULL,
	[CPUTM] [nvarchar](15) NULL,
	[AEDAT] [nvarchar](15) NULL,
	[USNAM] [nvarchar](20) NULL,
	[TCODE] [nvarchar](15) NULL,
	[XBLNR] [nvarchar](20) NULL,
	[BKTXT] [nvarchar](30) NULL,
	[FRATH] [decimal](13, 3) NULL,
	[FRBNR] [nvarchar](20) NULL,
	[WEVER] [nvarchar](10) NULL,
	[XABLN] [nvarchar](15) NULL,
	[AWSYS] [nvarchar](15) NULL,
	[BLA2D] [nvarchar](10) NULL,
	[TCODE2] [nvarchar](30) NULL,
	[BFWMS] [nvarchar](15) NULL,
	[EXNUM] [nvarchar](15) NULL,
	[SPE_BUDAT_UHR] [nvarchar](10) NULL,
	[SPE_BUDAT_ZONE] [nvarchar](10) NULL,
	[LE_VBELN] [nvarchar](15) NULL,
	[SPE_LOGSYS] [nvarchar](15) NULL,
	[SPE_MDNUM_EWM] [nvarchar](20) NULL,
	[GTS_CUSREF_NO] [nvarchar](50) NULL,
	[FLS_RSTO] [nvarchar](15) NULL,
	[MSR_ACTIVE] [nvarchar](10) NULL,
	[KNUMV] [nvarchar](15) NULL,
	[XCOMPL] [nvarchar](25) NULL,
	[MSEG_MANDT] [nvarchar](25) NULL,
	[MSEG_MBLNR] [nvarchar](25) NULL,
	[MSEG_MJAHR] [nvarchar](25) NULL,
	[ZEILE] [nvarchar](25) NOT NULL,
	[LINE_ID] [nvarchar](20) NULL,
	[PARENT_ID] [nvarchar](20) NULL,
	[LINE_DEPTH] [nvarchar](25) NULL,
	[MAA_URZEI] [nvarchar](25) NULL,
	[BWART] [nvarchar](10) NULL,
	[XAUTO] [nvarchar](10) NULL,
	[MATNR] [nvarchar](30) NULL,
	[WERKS] [nvarchar](10) NULL,
	[LGORT] [nvarchar](10) NULL,
	[CHARG] [nvarchar](15) NULL,
	[INSMK] [nvarchar](10) NULL,
	[ZUSCH] [nvarchar](10) NULL,
	[ZUSTD] [nvarchar](10) NULL,
	[SOBKZ] [nvarchar](10) NULL,
	[LIFNR] [nvarchar](15) NULL,
	[KUNNR] [nvarchar](15) NULL,
	[KDAUF] [nvarchar](15) NULL,
	[KDPOS] [nvarchar](25) NULL,
	[KDEIN] [nvarchar](25) NULL,
	[PLPLA] [nvarchar](15) NULL,
	[SHKZG] [nvarchar](20) NULL,
	[WAERS] [nvarchar](15) NULL,
	[DMBTR] [decimal](20, 3) NULL,
	[BNBTR] [decimal](20, 3) NULL,
	[BUALT] [decimal](20, 3) NULL,
	[SHKUM] [nvarchar](20) NULL,
	[DMBUM] [decimal](20, 3) NULL,
	[BWTAR] [nvarchar](15) NULL,
	[MENGE] [decimal](20, 3) NULL,
	[MEINS] [nvarchar](25) NULL,
	[ERFMG] [decimal](20, 3) NULL,
	[ERFME] [nvarchar](25) NULL,
	[BPMNG] [decimal](20, 3) NULL,
	[BPRME] [nvarchar](25) NULL,
	[EBELN] [nvarchar](15) NULL,
	[EBELP] [nvarchar](25) NULL,
	[LFBJA] [nvarchar](25) NULL,
	[LFBNR] [nvarchar](15) NULL,
	[LFPOS] [nvarchar](25) NULL,
	[SJAHR] [nvarchar](25) NULL,
	[SMBLN] [nvarchar](15) NULL,
	[SMBLP] [nvarchar](25) NULL,
	[ELIKZ] [nvarchar](20) NULL,
	[SGTXT] [nvarchar](60) NULL,
	[EQUNR] [nvarchar](20) NULL,
	[WEMPF] [nvarchar](15) NULL,
	[ABLAD] [nvarchar](30) NULL,
	[GSBER] [nvarchar](10) NULL,
	[KOKRS] [nvarchar](10) NULL,
	[PARGB] [nvarchar](10) NULL,
	[PARBU] [nvarchar](10) NULL,
	[KOSTL] [nvarchar](15) NULL,
	[PROJN] [nvarchar](20) NULL,
	[AUFNR] [nvarchar](25) NULL,
	[ANLN1] [nvarchar](25) NULL,
	[ANLN2] [nvarchar](10) NULL,
	[XSKST] [nvarchar](10) NULL,
	[XSAUF] [nvarchar](10) NULL,
	[XSPRO] [nvarchar](20) NULL,
	[XSERG] [nvarchar](20) NULL,
	[GJAHR] [nvarchar](25) NULL,
	[XRUEM] [nvarchar](20) NULL,
	[XRUEJ] [nvarchar](20) NULL,
	[BUKRS] [nvarchar](20) NULL,
	[BELNR] [nvarchar](15) NULL,
	[BUZEI] [nvarchar](25) NULL,
	[BELUM] [nvarchar](15) NULL,
	[BUZUM] [nvarchar](25) NULL,
	[RSNUM] [nvarchar](25) NULL,
	[RSPOS] [nvarchar](25) NULL,
	[KZEAR] [nvarchar](10) NULL,
	[PBAMG] [decimal](13, 3) NULL,
	[KZSTR] [nvarchar](10) NULL,
	[UMMAT] [nvarchar](25) NULL,
	[UMWRK] [nvarchar](20) NULL,
	[UMLGO] [nvarchar](20) NULL,
	[UMCHA] [nvarchar](15) NULL,
	[UMZST] [nvarchar](10) NULL,
	[UMZUS] [nvarchar](10) NULL,
	[UMBAR] [nvarchar](15) NULL,
	[UMSOK] [nvarchar](10) NULL,
	[KZBEW] [nvarchar](10) NULL,
	[KZVBR] [nvarchar](10) NULL,
	[KZZUG] [nvarchar](10) NULL,
	[WEUNB] [nvarchar](10) NULL,
	[PALAN] [decimal](13, 2) NULL,
	[LGNUM] [nvarchar](10) NULL,
	[LGTYP] [nvarchar](10) NULL,
	[LGPLA] [nvarchar](15) NULL,
	[BESTQ] [nvarchar](20) NULL,
	[BWLVS] [nvarchar](25) NULL,
	[TBNUM] [nvarchar](25) NULL,
	[TBPOS] [nvarchar](25) NULL,
	[XBLVS] [nvarchar](20) NULL,
	[VSCHN] [nvarchar](20) NULL,
	[NSCHN] [nvarchar](20) NULL,
	[DYPLA] [nvarchar](10) NULL,
	[UBNUM] [nvarchar](25) NULL,
	[TBPRI] [nvarchar](10) NULL,
	[TANUM] [nvarchar](25) NULL,
	[WEANZ] [nvarchar](25) NULL,
	[GRUND] [nvarchar](25) NULL,
	[EVERS] [nvarchar](10) NULL,
	[EVERE] [nvarchar](10) NULL,
	[IMKEY] [nvarchar](10) NULL,
	[KSTRG] [nvarchar](15) NULL,
	[PAOBJNR] [nvarchar](25) NULL,
	[PRCTR] [nvarchar](10) NULL,
	[PS_PSP_PNR] [nvarchar](25) NULL,
	[NPLNR] [nvarchar](15) NULL,
	[AUFPL] [nvarchar](25) NULL,
	[APLZL] [nvarchar](25) NULL,
	[AUFPS] [nvarchar](25) NULL,
	[VPTNR] [nvarchar](15) NULL,
	[FIPOS] [nvarchar](20) NULL,
	[SAKTO] [nvarchar](15) NULL,
	[BSTMG] [decimal](13, 3) NULL,
	[BSTME] [nvarchar](25) NULL,
	[XWSBR] [nvarchar](10) NULL,
	[EMLIF] [nvarchar](15) NULL,
	[EXBWR] [decimal](13, 3) NULL,
	[VKWRT] [decimal](13, 3) NULL,
	[AKTNR] [nvarchar](20) NULL,
	[ZEKKN] [nvarchar](25) NULL,
	[VFDAT] [nvarchar](20) NULL,
	[CUOBJ_CH] [nvarchar](25) NULL,
	[EXVKW] [decimal](13, 3) NULL,
	[PPRCTR] [nvarchar](15) NULL,
	[RSART] [nvarchar](20) NULL,
	[GEBER] [nvarchar](15) NULL,
	[FISTL] [nvarchar](20) NULL,
	[MATBF] [nvarchar](20) NULL,
	[UMMAB] [nvarchar](20) NULL,
	[BUSTM] [nvarchar](20) NULL,
	[BUSTW] [nvarchar](10) NULL,
	[MENGU] [nvarchar](10) NULL,
	[WERTU] [nvarchar](10) NULL,
	[LBKUM] [decimal](13, 3) NULL,
	[SALK3] [decimal](13, 3) NULL,
	[VPRSV] [nvarchar](10) NULL,
	[FKBER] [nvarchar](20) NULL,
	[DABRBZ] [nvarchar](10) NULL,
	[VKWRA] [decimal](13, 3) NULL,
	[DABRZ] [nvarchar](10) NULL,
	[XBEAU] [nvarchar](10) NULL,
	[LSMNG] [decimal](13, 3) NULL,
	[LSMEH] [nvarchar](25) NULL,
	[KZBWS] [nvarchar](20) NULL,
	[QINSPST] [nvarchar](10) NULL,
	[URZEI] [nvarchar](25) NULL,
	[J_1BEXBASE] [decimal](20, 3) NULL,
	[MWSKZ] [nvarchar](20) NULL,
	[TXJCD] [nvarchar](20) NULL,
	[EMATN] [nvarchar](25) NULL,
	[J_1AGIRUPD] [nvarchar](20) NULL,
	[VKMWS] [nvarchar](10) NULL,
	[HSDAT] [nvarchar](10) NULL,
	[BERKZ] [nvarchar](10) NULL,
	[MAT_KDAUF] [nvarchar](20) NULL,
	[MAT_KDPOS] [nvarchar](25) NULL,
	[MAT_PSPNR] [nvarchar](25) NULL,
	[XWOFF] [nvarchar](10) NULL,
	[BEMOT] [nvarchar](10) NULL,
	[PRZNR] [nvarchar](15) NULL,
	[LLIEF] [nvarchar](10) NULL,
	[LSTAR] [nvarchar](10) NULL,
	[XOBEW] [nvarchar](10) NULL,
	[GRANT_NBR] [nvarchar](25) NULL,
	[ZUSTD_T156M] [nvarchar](10) NULL,
	[SPE_GTS_STOCK_TY] [nvarchar](10) NULL,
	[KBLNR] [nvarchar](15) NULL,
	[KBLPOS] [nvarchar](25) NULL,
	[XMACC] [nvarchar](10) NULL,
	[VGART_MKPF] [nvarchar](20) NULL,
	[BUDAT_MKPF] [nvarchar](10) NULL,
	[CPUDT_MKPF] [nvarchar](10) NULL,
	[CPUTM_MKPF] [nvarchar](10) NULL,
	[USNAM_MKPF] [nvarchar](20) NULL,
	[XBLNR_MKPF] [nvarchar](20) NULL,
	[TCODE2_MKPF] [nvarchar](30) NULL,
	[VBELN_IM] [nvarchar](30) NULL,
	[VBELP_IM] [nvarchar](15) NULL,
	[SGT_SCAT] [nvarchar](20) NULL,
	[SGT_UMSCAT] [nvarchar](20) NULL,
	[_DATAAGING] [nvarchar](15) NULL,
	[SGT_RCAT] [nvarchar](20) NULL,
	[/BEV2/ED_KZ_VER] [nvarchar](15) NULL,
	[/BEV2/ED_USER] [nvarchar](15) NULL,
	[/BEV2/ED_AEDAT] [nvarchar](15) NULL,
	[/BEV2/ED_AETIM] [nvarchar](15) NULL,
	[DISUB_OWNER] [nvarchar](15) NULL,
	[COMPL_MARK] [nvarchar](10) NULL,
	[FZGLS_MARK] [nvarchar](20) NULL,
	[ETANP_MARK] [nvarchar](15) NULL,
	[POPUP_MARK] [nvarchar](20) NULL,
	[OINAVNW] [decimal](10, 2) NULL,
	[OICONDCOD] [nvarchar](20) NULL,
	[CONDI] [nvarchar](10) NULL,
	[WRF_CHARSTC1] [nvarchar](25) NULL,
	[WRF_CHARSTC2] [nvarchar](25) NULL,
	[WRF_CHARSTC3] [nvarchar](25) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)