CREATE TABLE [SrcMESCorp].[DC_at_RTMImpression] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [dc_instance_key]      BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time]   DATETIME       NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [op_name]              NVARCHAR (64)  NULL,
    [user_name]            NVARCHAR (64)  NULL,
    [object_key]           BIGINT         NOT NULL,
    [object_name]          NVARCHAR (128) NULL,
    [object_type]          NVARCHAR (64)  NOT NULL,
    [l_DirtyScans]         NVARCHAR (5)   NULL,
    [l_DoubleImprint]      NVARCHAR (5)   NULL,
    [l_ExcessMaterial]     NVARCHAR (5)   NULL,
    [l_MissingData]        NVARCHAR (5)   NULL,
    [l_MissingTooth]       NVARCHAR (5)   NULL,
    [l_RoughScans]         NVARCHAR (5)   NULL,
    [l_StitchingError]     NVARCHAR (5)   NULL,
    [status]               NVARCHAR (16)  NULL,
    [tech]                 NVARCHAR (32)  NULL,
    [u_DirtyScans]         NVARCHAR (5)   NULL,
    [u_DoubleImprint]      NVARCHAR (5)   NULL,
    [u_ExcessMaterial]     NVARCHAR (5)   NULL,
    [u_MissingData]        NVARCHAR (5)   NULL,
    [u_MissingTooth]       NVARCHAR (5)   NULL,
    [u_RoughScans]         NVARCHAR (5)   NULL,
    [u_StitchingError]     NVARCHAR (5)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

