CREATE TABLE [SrcMESCorp].[DC_at_BinkyOEData] (
    [LZBatchID]                INT            NOT NULL,
    [ADLSBatchID]              INT            NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)  NOT NULL,
    [dc_instance_key]          BIGINT         NOT NULL,
    [site_num]                 INT            NOT NULL,
    [creation_time]            DATETIME       NULL,
    [last_modified_time]       DATETIME       NULL,
    [is_finished]              INT            NULL,
    [route_name]               NVARCHAR (64)  NULL,
    [route_step_name]          NVARCHAR (64)  NULL,
    [op_name]                  NVARCHAR (64)  NULL,
    [user_name]                NVARCHAR (64)  NULL,
    [dscomment]                NVARCHAR (255) NULL,
    [dslocation]               NVARCHAR (64)  NULL,
    [object_key]               BIGINT         NOT NULL,
    [object_name]              NVARCHAR (128) NULL,
    [object_type]              NVARCHAR (64)  NULL,
    [at_BinkyClinCheckDataKey] BIGINT         NULL,
    [DeliverableTypeIndex]     BIGINT         NULL,
    [Description]              NVARCHAR (80)  NULL,
    [ItemNumber]               NVARCHAR (80)  NULL,
    [ItemType]                 NVARCHAR (80)  NULL,
    [LowerEnd]                 BIGINT         NULL,
    [LowerStart]               BIGINT         NULL,
    [ManufacturingOrderNumber] NVARCHAR (80)  NULL,
    [UpperEnd]                 BIGINT         NULL,
    [UpperStart]               BIGINT         NULL,
    [BoostQuantity]            BIGINT         NULL,
    [creation_time_u]          DATETIME       NULL,
    [creation_time_z]          NVARCHAR (64)  NULL,
    [last_modified_time_u]     DATETIME       NULL,
    [last_modified_time_z]     NVARCHAR (64)  NULL,
    [CDNQ]                     BIGINT         NULL,
    [QCPass]                   BIGINT         NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));

