CREATE TABLE [SrcMESCorp].[DC_at_MaterialsPending] (
    [LZBatchID]                    INT            NOT NULL,
    [ADLSBatchID]                  INT            NOT NULL,
    [ADLSTimestamp]                DATETIME2 (0)  NOT NULL,
    [dc_instance_key]              BIGINT         NOT NULL,
    [site_num]                     INT            NOT NULL,
    [creation_time]                DATETIME       NULL,
    [last_modified_time]           DATETIME       NULL,
    [user_name]                    NVARCHAR (64)  NULL,
    [dscomment]                    NVARCHAR (255) NULL,
    [object_key]                   BIGINT         NOT NULL,
    [object_name]                  NVARCHAR (128) NULL,
    [object_type]                  NVARCHAR (64)  NULL,
    [IncompleteTxForm]             NVARCHAR (80)  NULL,
    [MissingLowerImpression]       NVARCHAR (80)  NULL,
    [MissingPhotos]                NVARCHAR (80)  NULL,
    [MissingPVSBite]               NVARCHAR (80)  NULL,
    [MissingUpperImpression]       NVARCHAR (80)  NULL,
    [MissingXrays]                 NVARCHAR (80)  NULL,
    [RequireLowerImpression]       NVARCHAR (80)  NULL,
    [RequirePhotos]                NVARCHAR (80)  NULL,
    [RequirePVSBite]               NVARCHAR (80)  NULL,
    [RequireUpperImpression]       NVARCHAR (80)  NULL,
    [RequireXrays]                 NVARCHAR (80)  NULL,
    [MetalImpressionsTrayRejected] NVARCHAR (80)  NULL,
    [OCAttachmentsInImpressions]   NVARCHAR (80)  NULL,
    [creation_time_u]              DATETIME       NULL,
    [creation_time_z]              NVARCHAR (64)  NULL,
    [last_modified_time_u]         DATETIME       NULL,
    [last_modified_time_z]         NVARCHAR (64)  NULL,
    [MissingIOSLower]              NVARCHAR (80)  NULL,
    [MissingIOSUpper]              NVARCHAR (80)  NULL,
    [RejectedIOSLower]             NVARCHAR (80)  NULL,
    [RejectedIOSUpper]             NVARCHAR (80)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

