CREATE TABLE [SrcMESCorp].[DC_at_DoctorInformation] (
    [LZBatchID]            INT             NOT NULL,
    [ADLSBatchID]          INT             NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)   NOT NULL,
    [dc_instance_key]      BIGINT          NOT NULL,
    [site_num]             INT             NOT NULL,
    [creation_time]        DATETIME        NULL,
    [last_modified_time]   DATETIME        NULL,
    [is_finished]          INT             NULL,
    [route_name]           NVARCHAR (64)   NULL,
    [route_step_name]      NVARCHAR (64)   NULL,
    [op_name]              NVARCHAR (64)   NULL,
    [dscomment]            NVARCHAR (255)  NULL,
    [dslocation]           NVARCHAR (64)   NULL,
    [object_key]           BIGINT          NOT NULL,
    [object_name]          NVARCHAR (128)  NULL,
    [object_type]          NVARCHAR (64)   NULL,
    [ClinicianID]          NVARCHAR (80)   NULL,
    [Source]               NVARCHAR (80)   NULL,
    [CertLevel]            BIGINT          NULL,
    [WarningMessageIDs]    NVARCHAR (280)  NULL,
    [CalculatedLevel]      BIGINT          NULL,
    [CalculatedLevelFlag]  NVARCHAR (1)    NULL,
    [JDETeam]              NVARCHAR (12)   NULL,
    [OrderSubmitted]       BIGINT          NULL,
    [SkillLevel]           BIGINT          NULL,
    [creation_time_u]      DATETIME        NULL,
    [creation_time_z]      NVARCHAR (64)   NULL,
    [last_modified_time_u] DATETIME        NULL,
    [last_modified_time_z] NVARCHAR (64)   NULL,
    [DoctorID]             NVARCHAR (80)   NULL,
    [FirstName]            NVARCHAR (1000) NULL,
    [LastName]             NVARCHAR (1000) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

