CREATE TABLE [SrcMESCorp].[DC_at_PVSRejection] (
    [LZBatchID]                 INT            NOT NULL,
    [ADLSBatchID]               INT            NOT NULL,
    [ADLSTimestamp]             DATETIME2 (0)  NOT NULL,
    [dc_instance_key]           BIGINT         NOT NULL,
    [site_num]                  INT            NOT NULL,
    [creation_time]             DATETIME       NULL,
    [last_modified_time]        DATETIME       NULL,
    [is_finished]               INT            NULL,
    [route_name]                NVARCHAR (64)  NULL,
    [route_step_name]           NVARCHAR (64)  NULL,
    [op_name]                   NVARCHAR (64)  NULL,
    [user_name]                 NVARCHAR (64)  NULL,
    [dscomment]                 NVARCHAR (255) NULL,
    [dslocation]                NVARCHAR (64)  NULL,
    [object_key]                BIGINT         NOT NULL,
    [object_name]               NVARCHAR (128) NULL,
    [object_type]               NVARCHAR (64)  NULL,
    [l_AirBubbles]              NVARCHAR (5)   NULL,
    [l_BiteOff]                 NVARCHAR (5)   NULL,
    [l_BlendedToothAndGingival] NVARCHAR (5)   NULL,
    [l_DoubleImpression]        NVARCHAR (5)   NULL,
    [l_Elongated]               NVARCHAR (5)   NULL,
    [l_ExcessMaterial]          NVARCHAR (5)   NULL,
    [l_IncisalEdgesTooThin]     NVARCHAR (5)   NULL,
    [l_IncompleteTermMolars]    NVARCHAR (5)   NULL,
    [l_MissingAnatomy]          NVARCHAR (5)   NULL,
    [l_NotFullyCaptured]        NVARCHAR (5)   NULL,
    [l_NotFullyErupted]         NVARCHAR (5)   NULL,
    [l_PushThrough]             NVARCHAR (5)   NULL,
    [ll_1]                      NVARCHAR (5)   NULL,
    [ll_2]                      NVARCHAR (5)   NULL,
    [ll_3]                      NVARCHAR (5)   NULL,
    [ll_4]                      NVARCHAR (5)   NULL,
    [ll_5]                      NVARCHAR (5)   NULL,
    [ll_6]                      NVARCHAR (5)   NULL,
    [ll_7]                      NVARCHAR (5)   NULL,
    [ll_8]                      NVARCHAR (5)   NULL,
    [lr_1]                      NVARCHAR (5)   NULL,
    [lr_2]                      NVARCHAR (5)   NULL,
    [lr_3]                      NVARCHAR (5)   NULL,
    [lr_4]                      NVARCHAR (5)   NULL,
    [lr_5]                      NVARCHAR (5)   NULL,
    [lr_6]                      NVARCHAR (5)   NULL,
    [lr_7]                      NVARCHAR (5)   NULL,
    [lr_8]                      NVARCHAR (5)   NULL,
    [u_AirBubbles]              NVARCHAR (5)   NULL,
    [u_BiteOff]                 NVARCHAR (5)   NULL,
    [u_BlendedToothAndGingival] NVARCHAR (5)   NULL,
    [u_DoubleImpression]        NVARCHAR (5)   NULL,
    [u_Elongated]               NVARCHAR (5)   NULL,
    [u_ExcessMaterial]          NVARCHAR (5)   NULL,
    [u_IncisalEdgesTooThin]     NVARCHAR (5)   NULL,
    [u_IncompleteTermMolars]    NVARCHAR (5)   NULL,
    [u_MissingAnatomy]          NVARCHAR (5)   NULL,
    [u_NotFullyCaptured]        NVARCHAR (5)   NULL,
    [u_NotFullyErupted]         NVARCHAR (5)   NULL,
    [u_PushThrough]             NVARCHAR (5)   NULL,
    [ul_1]                      NVARCHAR (5)   NULL,
    [ul_2]                      NVARCHAR (5)   NULL,
    [ul_3]                      NVARCHAR (5)   NULL,
    [ul_4]                      NVARCHAR (5)   NULL,
    [ul_5]                      NVARCHAR (5)   NULL,
    [ul_6]                      NVARCHAR (5)   NULL,
    [ul_7]                      NVARCHAR (5)   NULL,
    [ul_8]                      NVARCHAR (5)   NULL,
    [ur_1]                      NVARCHAR (5)   NULL,
    [ur_2]                      NVARCHAR (5)   NULL,
    [ur_3]                      NVARCHAR (5)   NULL,
    [ur_4]                      NVARCHAR (5)   NULL,
    [ur_5]                      NVARCHAR (5)   NULL,
    [ur_6]                      NVARCHAR (5)   NULL,
    [ur_7]                      NVARCHAR (5)   NULL,
    [ur_8]                      NVARCHAR (5)   NULL,
    [creation_time_u]           DATETIME       NULL,
    [creation_time_z]           NVARCHAR (64)  NULL,
    [last_modified_time_u]      DATETIME       NULL,
    [last_modified_time_z]      NVARCHAR (64)  NULL,
    [l_IntraOralScanIssue]      NVARCHAR (5)   NULL,
    [u_IntraOralScanIssue]      NVARCHAR (5)   NULL,
    [l_PoorlyDefinedEdges]      NVARCHAR (5)   NULL,
    [l_RoughScan]               NVARCHAR (5)   NULL,
    [u_PoorlyDefinedEdges]      NVARCHAR (5)   NULL,
    [u_RoughScan]               NVARCHAR (5)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

