CREATE TABLE [SrcMESCorp].[LOT] (
    [LZBatchID]                      INT             NOT NULL,
    [ADLSBatchID]                    INT             NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)   NOT NULL,
    [lot_key]                        BIGINT          NOT NULL,
    [site_num]                       INT             NOT NULL,
    [order_key]                      BIGINT          NOT NULL,
    [order_item_key]                 BIGINT          NOT NULL,
    [lot_name]                       NVARCHAR (128)  NOT NULL,
    [quantity_scrapped]              NUMERIC (23, 9) NULL,
    [quantity_finished]              NUMERIC (23, 9) NULL,
    [quantity_shipped]               NUMERIC (23, 9) NULL,
    [quantity_closed]                NUMERIC (23, 9) NULL,
    [part_number]                    NVARCHAR (64)   NULL,
    [part_revision]                  NVARCHAR (64)   NULL,
    [description]                    NVARCHAR (255)  NULL,
    [dscomment]                      NVARCHAR (255)  NULL,
    [promised_time]                  DATETIME        NULL,
    [est_remaining_consume_duration] INT             NULL,
    [est_lot_remaining_duration]     INT             NULL,
    [finished_time]                  DATETIME        NULL,
    [shipped_time]                   DATETIME        NULL,
    [inst_list_key]                  BIGINT          NULL,
    [note_key]                       BIGINT          NULL,
    [tbom_key]                       BIGINT          NULL,
    [mother_lot_key]                 BIGINT          NOT NULL,
    [split_parent_lot_key]           BIGINT          NOT NULL,
    [revived]                        INT             NULL,
    [uda_0]                          NVARCHAR (255)  NULL,
    [uda_1]                          NVARCHAR (255)  NULL,
    [uda_2]                          NVARCHAR (255)  NULL,
    [uda_3]                          NVARCHAR (255)  NULL,
    [uda_4]                          NVARCHAR (255)  NULL,
    [uda_5]                          NVARCHAR (255)  NULL,
    [uda_6]                          NVARCHAR (255)  NULL,
    [uda_7]                          NVARCHAR (255)  NULL,
    [uda_8]                          NVARCHAR (255)  NULL,
    [uda_9]                          NVARCHAR (255)  NULL,
    [udt_0]                          DATETIME        NULL,
    [udt_1]                          DATETIME        NULL,
    [udt_2]                          DATETIME        NULL,
    [xfr_insert_pid]                 INT             NULL,
    [xfr_update_pid]                 INT             NULL,
    [creation_time]                  DATETIME        NOT NULL,
    [last_modified_time]             DATETIME        NOT NULL,
    [quantity_consumed]              NUMERIC (23, 9) NOT NULL,
    [bill_account_key]               BIGINT          NULL,
    [build_account_key]              BIGINT          NULL,
    [ship_account_key]               BIGINT          NULL,
    [user_account_0]                 BIGINT          NULL,
    [priority]                       INT             NULL,
    [stand_alone]                    INT             NOT NULL,
    [quantity_serialized]            NUMERIC (23, 9) NOT NULL,
    [item_part_number]               NVARCHAR (64)   NULL,
    [item_part_revision]             NVARCHAR (64)   NULL,
    [item_bom_name]                  NVARCHAR (64)   NULL,
    [item_bom_revision]              NVARCHAR (64)   NULL,
    [inventory_status]               INT             NOT NULL,
    [on_hand_status]                 INT             NOT NULL,
    [owner_account_key]              BIGINT          NOT NULL,
    [supplier_account_key]           BIGINT          NOT NULL,
    [location]                       NVARCHAR (64)   NULL,
    [trx_id]                         CHAR (38)       NOT NULL,
    [quantity_sampled]               NUMERIC (23, 9) NOT NULL,
    [expiration_time]                DATETIME        NULL,
    [rework_count]                   INT             NOT NULL,
    [rework_flag]                    INT             NOT NULL,
    [original_lot_type]              INT             NOT NULL,
    [quantity_scrapped_consumed]     NUMERIC (23, 9) NOT NULL,
    [quantity_yield_initial]         NUMERIC (23, 9) NULL,
    [quantity_yield_finished]        NUMERIC (23, 9) NULL,
    [output_lot_tbom_part_list_key]  BIGINT          NOT NULL,
    [output_lot_parent_lot_key]      BIGINT          NOT NULL,
    [output_lot_source_lot_key]      BIGINT          NOT NULL,
    [promised_time_u]                DATETIME        NULL,
    [promised_time_z]                NVARCHAR (64)   NULL,
    [finished_time_u]                DATETIME        NULL,
    [finished_time_z]                NVARCHAR (64)   NULL,
    [shipped_time_u]                 DATETIME        NULL,
    [shipped_time_z]                 NVARCHAR (64)   NULL,
    [udt_0_u]                        DATETIME        NULL,
    [udt_0_z]                        NVARCHAR (64)   NULL,
    [udt_1_u]                        DATETIME        NULL,
    [udt_1_z]                        NVARCHAR (64)   NULL,
    [udt_2_u]                        DATETIME        NULL,
    [udt_2_z]                        NVARCHAR (64)   NULL,
    [creation_time_u]                DATETIME        NULL,
    [creation_time_z]                NVARCHAR (64)   NULL,
    [last_modified_time_u]           DATETIME        NULL,
    [last_modified_time_z]           NVARCHAR (64)   NULL,
    [expiration_time_u]              DATETIME        NULL,
    [expiration_time_z]              NVARCHAR (64)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([lot_key]));

