CREATE TABLE [SrcMESCorp].[PART] (
    [LZBatchID]                INT            NOT NULL,
    [ADLSBatchID]              INT            NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)  NOT NULL,
    [part_key]                 BIGINT         NOT NULL,
    [site_num]                 INT            NOT NULL,
    [part_number]              NVARCHAR (64)  NOT NULL,
    [part_revision]            NVARCHAR (64)  NOT NULL,
    [description]              NVARCHAR (255) NULL,
    [category]                 NVARCHAR (50)  NULL,
    [image_key]                BIGINT         NULL,
    [inst_list_key]            BIGINT         NULL,
    [bom_name]                 NVARCHAR (64)  NULL,
    [bom_revision]             NVARCHAR (64)  NULL,
    [bom_tracked_mode]         INT            NULL,
    [creation_time]            DATETIME       NOT NULL,
    [last_modified_time]       DATETIME       NOT NULL,
    [uda_0]                    NVARCHAR (255) NULL,
    [uda_1]                    NVARCHAR (255) NULL,
    [uda_2]                    NVARCHAR (255) NULL,
    [uda_3]                    NVARCHAR (255) NULL,
    [uda_4]                    NVARCHAR (255) NULL,
    [uda_5]                    NVARCHAR (255) NULL,
    [uda_6]                    NVARCHAR (255) NULL,
    [uda_7]                    NVARCHAR (255) NULL,
    [uda_8]                    NVARCHAR (255) NULL,
    [uda_9]                    NVARCHAR (255) NULL,
    [creation_time_u]          DATETIME       NULL,
    [creation_time_z]          NVARCHAR (64)  NULL,
    [last_modified_time_u]     DATETIME       NULL,
    [last_modified_time_z]     NVARCHAR (64)  NULL,
    [quantity]                 INT            NULL,
    [consumption_duration]     INT            NULL,
    [consumption_type]         NVARCHAR (50)  NOT NULL,
    [revived]                  INT            NULL,
    [shelf_life]               INT            NOT NULL,
    [warranty_period]          INT            NOT NULL,
    [unit_of_measure]          NVARCHAR (64)  NULL,
    [part_ext_revision]        NVARCHAR (64)  NOT NULL,
    [replacement_type]         NVARCHAR (64)  NULL,
    [carrier_class_key]        BIGINT         NULL,
    [logically_empty_quantity] NVARCHAR (64)  NULL,
    [mixing_type]              INT            NULL,
    [storage_class_enforced]   INT            NULL,
    [storage_unit_class_key]   BIGINT         NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

