CREATE TABLE [SrcMESCorp].[TRACKED_OBJECT_STATUS] (
    [LZBatchID]              INT           NOT NULL,
    [ADLSBatchID]            INT           NOT NULL,
    [ADLSTimestamp]          DATETIME2 (0) NOT NULL,
    [tobj_status_key]        BIGINT        NOT NULL,
    [site_num]               INT           NOT NULL,
    [tobj_key]               BIGINT        NOT NULL,
    [tobj_type]              NVARCHAR (50) NOT NULL,
    [route_key]              BIGINT        NULL,
    [route_name]             NVARCHAR (64) NULL,
    [route_step_key]         BIGINT        NULL,
    [route_step_name]        NVARCHAR (64) NULL,
    [queue_key]              BIGINT        NULL,
    [queue_name]             NVARCHAR (64) NULL,
    [op_key]                 BIGINT        NULL,
    [op_name]                NVARCHAR (64) NULL,
    [start_time]             DATETIME      NULL,
    [complete_time]          DATETIME      NULL,
    [status]                 NVARCHAR (50) NOT NULL,
    [state]                  NVARCHAR (50) NOT NULL,
    [reason]                 NVARCHAR (64) NULL,
    [pause_time]             DATETIME      NULL,
    [tobj_history_key]       BIGINT        NULL,
    [tobj_queue_history_key] BIGINT        NULL,
    [last_modified_time]     DATETIME      NOT NULL,
    [start_time_u]           DATETIME      NULL,
    [start_time_z]           NVARCHAR (64) NULL,
    [complete_time_u]        DATETIME      NULL,
    [complete_time_z]        NVARCHAR (64) NULL,
    [pause_time_u]           DATETIME      NULL,
    [pause_time_z]           NVARCHAR (64) NULL,
    [last_modified_time_u]   DATETIME      NULL,
    [last_modified_time_z]   NVARCHAR (64) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([tobj_key]));

