CREATE TABLE [SrcMESCorp].[UDA_Lot] (
    [LZBatchID]                      INT             NOT NULL,
    [ADLSBatchID]                    INT             NOT NULL,
    [ADLSTimestamp]                  DATETIME2 (0)   NOT NULL,
    [object_key]                     BIGINT          NOT NULL,
    [site_num]                       INT             NOT NULL,
    [last_modifier_key]              BIGINT          NOT NULL,
    [last_modified_time]             DATETIME        NOT NULL,
    [xfr_insert_pid]                 INT             NULL,
    [xfr_update_pid]                 INT             NULL,
    [trx_id]                         CHAR (38)       NOT NULL,
    [at_AssigneeTeam_S]              NVARCHAR (80)   NULL,
    [at_AssigneeTech_S]              NVARCHAR (80)   NULL,
    [at_JDELineNumber_I]             BIGINT          NULL,
    [at_JDEOrderType_S]              NVARCHAR (80)   NULL,
    [at_Staging_LowerEnd_S]          NVARCHAR (3)    NULL,
    [at_Staging_LowerStart_S]        NVARCHAR (3)    NULL,
    [at_Staging_UpperEnd_S]          NVARCHAR (3)    NULL,
    [at_Staging_UpperStart_S]        NVARCHAR (3)    NULL,
    [at_TeamNumber_S]                NVARCHAR (80)   NULL,
    [at_IsVAIL_I]                    BIGINT          NULL,
    [at_InternalPriority_I]          BIGINT          NULL,
    [at_IsReject_I]                  BIGINT          NULL,
    [at_ManufacturingCell_S]         NVARCHAR (80)   NULL,
    [at_MaterialsPendingFlag_I]      BIGINT          NULL,
    [at_CurrentTreatmentComment_S]   NVARCHAR (4000) NULL,
    [at_IsAPartialIExpress_I]        BIGINT          NULL,
    [at_OriginalPartNumber_S]        NVARCHAR (64)   NULL,
    [at_OriginalPartRevision_S]      NVARCHAR (64)   NULL,
    [at_UDWarningFlag_I]             BIGINT          NULL,
    [at_UpgradeDowngradeAttempts_I]  BIGINT          NULL,
    [at_Original_LowerEnd_S]         NVARCHAR (3)    NULL,
    [at_Original_LowerStart_S]       NVARCHAR (3)    NULL,
    [at_Original_UpperEnd_S]         NVARCHAR (3)    NULL,
    [at_Original_UpperStart_S]       NVARCHAR (3)    NULL,
    [at_RetainerLowerOrgFile_S]      NVARCHAR (50)   NULL,
    [at_RetainerUpperOrgFile_S]      NVARCHAR (50)   NULL,
    [at_ClinicalStudy_S]             NVARCHAR (50)   NULL,
    [at_CurrentPSMatchStatus_I]      BIGINT          NULL,
    [at_CurSwitchLifeCycleNumber_I]  BIGINT          NULL,
    [at_PreviousPartNumber_S]        NVARCHAR (64)   NULL,
    [at_PreviousPartRevision_S]      NVARCHAR (64)   NULL,
    [last_modified_time_u]           DATETIME        NULL,
    [last_modified_time_z]           NVARCHAR (64)   NULL,
    [list_key]                       BIGINT          NULL,
    [at_Plant_S]                     NVARCHAR (225)  NULL,
    [at_SOIMaterialNumber_I]         BIGINT          NULL,
    [at_ClinCheckConfirmationSent_I] BIGINT          NULL,
    [at_ActualPlant_S]               NVARCHAR (80)   NULL,
    [at_ProcessType_S]               NVARCHAR (80)   NULL,
    [at_EntryTime_T]                 DATETIME        NULL,
    [at_EntryTime_u]                 DATETIME        NULL,
    [at_EntryTime_z]                 NVARCHAR (64)   NULL,
    [at_TxOperationFlow_I]           BIGINT          NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));

