CREATE TABLE [SrcMESCorp].[UDA_Order] (
    [LZBatchID]                  INT            NOT NULL,
    [ADLSBatchID]                INT            NOT NULL,
    [ADLSTimestamp]              DATETIME2 (0)  NOT NULL,
    [object_key]                 BIGINT         NOT NULL,
    [site_num]                   INT            NOT NULL,
    [last_modified_time]         DATETIME       NOT NULL,
    [xfr_update_pid]             INT            NULL,
    [trx_id]                     CHAR (38)      NOT NULL,
    [at_DoctorID_S]              NVARCHAR (80)  NULL,
    [at_JDEOrderType_S]          NVARCHAR (80)  NULL,
    [at_JDERoutingType_S]        NVARCHAR (3)   NULL,
    [at_TreatmentID_S]           NVARCHAR (15)  NULL,
    [at_VipOrderNumber_S]        NVARCHAR (80)  NULL,
    [at_IsICS_I]                 BIGINT         NULL,
    [at_expedite_hold_status_I]  BIGINT         NULL,
    [at_expedite_scope_S]        NVARCHAR (64)  NULL,
    [at_HasAssetScanLot_I]       BIGINT         NULL,
    [at_TreatedArch_S]           NVARCHAR (80)  NULL,
    [last_modified_time_u]       DATETIME       NULL,
    [last_modified_time_z]       NVARCHAR (64)  NULL,
    [list_key]                   BIGINT         NULL,
    [at_IsRejectedImpressions_I] BIGINT         NULL,
    [at_IOScan_S]                NVARCHAR (10)  NULL,
    [at_AllMaterialRecdTime_S]   NVARCHAR (225) NULL,
    [at_IsAMRSend_I]             BIGINT         NULL,
    [at_Pilot_S]                 NVARCHAR (100) NULL,
    [at_MaintainStudy_S]         NVARCHAR (20)  NULL,
    [at_IOScanType_S]            NVARCHAR (64)  NULL,
    [at_IOScanHardwareVersion_S] NVARCHAR (50)  NULL,
    [at_IOScanSoftwareVersion_S] NVARCHAR (50)  NULL,
    [at_Submission_S]            NVARCHAR (64)  NULL,
    [at_DeliverableType_S]       NVARCHAR (225) NULL,
    [at_PlantOA_S]               NVARCHAR (225) NULL,
    [at_ServiceLevel_S]          NVARCHAR (225) NULL,
    [at_Country_S]               NVARCHAR (225) NULL,
    [at_SOIMaterialNumber_I]     BIGINT         NULL,
    [at_TreatmentCategory_S]     NVARCHAR (225) NULL,
    [at_OrderType_S]             NVARCHAR (80)  NULL,
    [at_ProductionOrderType_S]   NVARCHAR (80)  NULL,
    [at_SalesOrderItem_S]        NVARCHAR (80)  NULL,
    [at_TreatmentOption_S]       NVARCHAR (225) NULL,
    [at_externalTreatmentId_S]   NVARCHAR (80)  NULL,
    [at_StorageLocation_S]       NVARCHAR (80)  NULL,
    [at_DentalRecords_S]         NVARCHAR (80)  NULL,
    [at_MTPExecuted_I]           BIGINT         NULL,
    [at_MAFeature_I]             BIGINT         NULL,
    [at_IsMTPSend_I]             BIGINT         NULL,
    [at_STPExecuted_I]           BIGINT         NULL,
    [at_IsSTPSend_I]             BIGINT         NULL,
    [at_ProcessingType_S]        NVARCHAR (80)  NULL,
    [at_TreatmentFlow_S]         NVARCHAR (80)  NULL,
    [at_PortingFlow_S]           NVARCHAR (80)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([object_key]));

