CREATE TABLE [SrcMESCorp].[WORK_ORDER_ITEMS] (
    [LZBatchID]               INT           NOT NULL,
    [ADLSBatchID]             INT           NOT NULL,
    [ADLSTimestamp]           DATETIME2 (0) NOT NULL,
    [order_item_key]          BIGINT        NOT NULL,
    [site_num]                INT           NOT NULL,
    [order_key]               BIGINT        NOT NULL,
    [order_item]              NVARCHAR (64) NOT NULL,
    [part_number]             NVARCHAR (64) NULL,
    [bom_name]                NVARCHAR (64) NULL,
    [bom_revision]            NVARCHAR (64) NULL,
    [finished_time]           DATETIME      NULL,
    [shipped_time]            DATETIME      NULL,
    [order_state]             NVARCHAR (64) NULL,
    [planned_start_time]      DATETIME      NULL,
    [planned_finish_time]     DATETIME      NULL,
    [scheduled_start_time]    DATETIME      NULL,
    [scheduled_finish_time]   DATETIME      NULL,
    [creation_time]           DATETIME      NOT NULL,
    [last_modified_time]      DATETIME      NOT NULL,
    [part_revision]           NVARCHAR (64) NULL,
    [tobj_status_key]         BIGINT        NOT NULL,
    [finished_time_u]         DATETIME      NULL,
    [finished_time_z]         NVARCHAR (64) NULL,
    [shipped_time_u]          DATETIME      NULL,
    [shipped_time_z]          NVARCHAR (64) NULL,
    [planned_start_time_u]    DATETIME      NULL,
    [planned_start_time_z]    NVARCHAR (64) NULL,
    [planned_finish_time_u]   DATETIME      NULL,
    [planned_finish_time_z]   NVARCHAR (64) NULL,
    [scheduled_start_time_u]  DATETIME      NULL,
    [scheduled_start_time_z]  NVARCHAR (64) NULL,
    [scheduled_finish_time_u] DATETIME      NULL,
    [scheduled_finish_time_z] NVARCHAR (64) NULL,
    [creation_time_u]         DATETIME      NULL,
    [creation_time_z]         NVARCHAR (64) NULL,
    [last_modified_time_u]    DATETIME      NULL,
    [last_modified_time_z]    NVARCHAR (64) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([order_key]));

