CREATE VIEW [DWVirtualCare].[MyInvisalignAppEvents]
AS SELECT
       [event_timestamp]
      ,[event_name]
      ,[user_pseudo_id]
      ,[_count]
      ,[event_date]
      ,[event_params]
      ,[event_previous_timestamp]
      ,[event_value_in_usd]
      ,[event_bundle_sequence_id]
      ,[event_server_timestamp_offset]
      ,[user_id]
      ,[user_properties]
      ,[user_first_touch_timestamp]
      ,[user_ltv]
      ,[device]
      ,[geo]
      ,[app_info]
      ,[traffic_source]
      ,[stream_id]
      ,[platform]
      ,[event_dimensions]
      ,[ecommerce]
      ,[items]
      ,[event_params_firebase_screen_class]
      ,[event_params_category]
      ,[event_params_firebase_screen]
      ,[event_params_ga_session_id]
FROM [SrcGoogleBigQuery].[MyInvisalignAppOther];