CREATE TABLE [DWIRIS].[DimAsset] (
    [SKAsset]                  INT             NOT NULL,
    [ADLSBatchID]              INT             NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)   NOT NULL,
    [LZBatchID]                INT             NOT NULL,
    [DWBatchID]                INT             NOT NULL,
    [DWHash]                   CHAR (40)       NOT NULL,
    [AccountNumber]            NCHAR (80)      NULL,
    [SKAccount]                INT             NOT NULL,
    [CreatedDateKey]           INT             NULL,
    [CreatedDate]              DATETIME2 (7)   NULL,
    [Description]              NVARCHAR (4000) NULL,
    [EquipmentCardID]          INT             NULL,
    [Id]                       NCHAR (50)      NULL,
    [InstallDateKey]           INT             NULL,
    [InstallDate]              DATETIME2 (7)   NULL,
    [IsActive]                 VARCHAR (5)     NULL,
    [LastReferencedDateKey]    INT             NULL,
    [LastReferencedDate]       DATETIME2 (7)   NULL,
    [MATDescription]           NVARCHAR (50)   NULL,
    [ParentID]                 NCHAR (36)      NULL,
    [SKParent]                 INT             NOT NULL,
    [ProductId]                NCHAR (18)      NULL,
    [PurchaseDateKey]          INT             NULL,
    [PurchaseDate]             DATETIME2 (7)   NULL,
    [SerialNumber]             NVARCHAR (160)  NULL,
    [StockKeepingUnit]         NVARCHAR (360)  NULL,
    [UsageEndDateKey]          INT             NULL,
    [UsageEndDate]             DATETIME2 (7)   NULL,
    [WandNumber]               NVARCHAR (160)  NULL,
    [FirstRegistrationDateKey] INT             NULL,
    [FirstRegistrationDate]    DATETIME2 (7)   NULL,
    [LastRegistrationDateKey]  INT             NULL,
    [LastRegistrationDate]     DATETIME2 (7)   NULL,
    [AssetType]                VARCHAR (64)    NULL,
    [AssetKind]                NVARCHAR (255)  NULL,
    [AssetName]                NVARCHAR (255)  NULL,
    [ScannerSoftwareType]      NVARCHAR (255)  NULL,
    [SoftwareEndDate]          DATETIME2 (7)   NULL,
    [SourceSystem]             NVARCHAR (20)   NULL,
    [Status]                   NVARCHAR (40)   NULL,
    [InstalledAccount]         NVARCHAR (18)   NULL,
    [PGIDate]                  DATETIME2 (7)   NULL,
    [BillToAccount]            NVARCHAR (255)  NULL,
    [ShipToAccount]            NVARCHAR (255)  NULL,
    [TermMonths]               NVARCHAR (255)  NULL,
    [SAPSalesOrder]            NVARCHAR (255)  NULL,
    [OpportunityNumber]        NVARCHAR (255)  NULL,
    [PayerAccount]             NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([SKAsset]), DISTRIBUTION = REPLICATE);

