CREATE TABLE [DWIRIS].[DimOpportunity] (
    [SKOpportunity]     INT             NOT NULL,
    [ADLSBatchID]       INT             NOT NULL,
    [ADLSTimestamp]     DATETIME2 (0)   NOT NULL,
    [LZBatchID]         INT             NOT NULL,
    [DWBatchID]         INT             NOT NULL,
    [DWHash]            CHAR (40)       NOT NULL,
    [KeyOpportunity]    NCHAR (255)     NOT NULL,
    [SKUser]            INT             NULL,
    [SKAccount]         INT             NULL,
    [OpportunityName]   NVARCHAR (120)  NULL,
    [OpportunityNumber] NVARCHAR (30)   NULL,
    [CommissionDate]    DATETIME2 (7)   NULL,
    [ShippedDate]       DATETIME2 (7)   NULL,
    [SaleType]          NVARCHAR (255)  NULL,
    [OpportunityId_C]   NVARCHAR (255)  NULL,
    [GeneratedBy]       NCHAR (18)      NULL,
    [CloseDate]         DATETIME2 (7)   NULL,
    [Amount]            DECIMAL (18, 2) NULL,
    [ProductName]       NCHAR (18)      NULL,
    [StageName]         NVARCHAR (40)   NULL,
    [DemoDate]          DATETIME2 (7)   NULL,
    [ContractLoadDate]  DATETIME2 (7)   NULL,
    [AgreementEffectiveDate] [datetime2](7) NULL,
    [AlertStatusDate] [datetime2](7) NULL,
    [AlignSignatureDate] [datetime2](7) NULL,
    [CancellationDate] [datetime2](7) NULL,
    [CancellationReason] [nvarchar](510) NULL,
    [CancellationStatus] [nvarchar](510) NULL,
    [Cancelled] [decimal](18,0) NULL,
    [ChildOpportunityId] [nvarchar](36) NULL,
    [ClosedReason] [nvarchar](510) NULL,
    [CompetitorInvolved] [nvarchar](510) NULL,
    [Contact] [nchar](36) NULL,
    [ContractSignedDate] [datetime2](7) NULL,
    [ContractType] [nvarchar](510) NULL,
    [Country] [nvarchar](2600) NULL,
    [CreatedById] [nchar](36) NULL,
    [CreatedDate] [datetime2](7) NULL,
    [CurrencyIsoCode] [nvarchar](10) NULL,
    [DeliveredDate] [datetime2](7) NULL,
    [Dep] [varchar](10) NULL,
    [Description] [nvarchar](4000)  NULL,
    [Distributor] [nvarchar](510) NULL,
    [ExpectedRevenue] [decimal](18,2) NULL,
    [FundingSource] [nvarchar](510) NULL,
    [GoDigital] [varchar](10) NULL,
    [GoDigitalOpp] [nchar](36) NULL,
    [HasOpportunityLineItem] [varchar](10) NULL,
    [isRefurbishedProduct] [varchar](10) NULL,
    [IsDeleted] [varchar](10) NULL,
    [iTeroType] [nvarchar](510) NULL,
    [LastModifiedDate] [datetime2](7) NULL,
    [LeadSource] [nvarchar](80) NULL,
    [LeasingCompany] [nvarchar](510) NULL,
    [Name] [nvarchar](240) NULL,
    [NumberofScanners] [decimal](18,0) NULL,
    [PaymentType] [nvarchar](160) NULL,
    [Probability] [decimal](18,0) NULL,
    [ProductOption] [nvarchar](510) NULL,
    [Promotion] [nvarchar](510) NULL,
    [RecordTypeId] [nchar](36) NULL,
    [RequestFormat] [nvarchar](510) NULL,
    [ScannerDemoDate] [datetime2](7) NULL,
    [ScannerQuantity] [decimal](18,0) NULL,
    [ScannerSalesChannel] [nvarchar](36) NULL,
    [ScannerSN] [nvarchar](160) NULL,
    [SubLeadSource] [nvarchar](510) NULL,
    [SystemModstamp] [datetime2](7) NULL,
    [TotalQuantity] [decimal](18,2) NULL,
    [TotalOpportunityQuantity] [decimal](18,2) NULL,
    [TradeInSerialNumber] [nvarchar](510) NULL,
    [RoutedDate] [datetime2](7) NULL,
    [ParentOpportunity] [nchar](36) NULL
)
WITH (CLUSTERED INDEX([SKOpportunity]), DISTRIBUTION = HASH([SKOpportunity]));

