CREATE TABLE [DWIRIS].[DimProposal] (
    [SKProposal]                 INT             NOT NULL,
    [ADLSBatchID]                INT             NOT NULL,
    [ADLSTimestamp]              DATETIME2 (0)   NOT NULL,
    [LZBatchID]                  INT             NOT NULL,
    [DWBatchID]                  INT             NOT NULL,
    [DWHash]                     CHAR (40)       NOT NULL,
    [KeyProposal]                NCHAR (255)     NOT NULL,
    [AccountNumber]              NVARCHAR (1300) NULL,
    [ApprovalStage]              NVARCHAR (255)  NULL,
    [ProposalPrimary]            BIT             NULL,
    [PrimaryContactId]           NCHAR (18)      NULL,
    [CreatedDate]                DATETIME2 (7)   NULL,
    [ProposalElementScannerType] NVARCHAR (255)  NULL,
    [ProposalName]               NVARCHAR (255)  NULL,
    [ServiceFeesPAV]             NVARCHAR (255)  NULL,
    [ProposalId]                 NCHAR (18)      NULL,
    [TreatmentCategory]          NVARCHAR (255)  NULL,
    [ProposalLastModifiedDate]   DATETIME2 (7)   NULL,
    [OpportunityId]              NCHAR (18)      NULL,
    [ProductName]                NVARCHAR (1300) NULL,
    [Quantity1]                  DECIMAL (18, 2) NULL,
    [ProposalQuantity]           DECIMAL (18)    NULL,
    [IsPrimaryLine]              BIT             NULL,
    [LineItemElementScannerType] NVARCHAR (255)  NULL,
    [LineItemName]               NVARCHAR (255)  NULL,
    [LineItemLastModifiedDate]   DATETIME2 (7)   NULL,
    [ProductCode]                NVARCHAR (1300) NULL,
    [OpportunityNumber]          NVARCHAR (255)  NULL,
    [IncentiveCode]              NVARCHAR (255)  NULL,
	[NetPrice]                   DECIMAL (18, 5) NULL,
	[ListPrice]                  DECIMAL (18, 5) NULL,
    [IsDeleted]                  BIT             NULL
)
WITH (CLUSTERED INDEX([SKProposal]), DISTRIBUTION = REPLICATE);

