CREATE TABLE [DWIRIS].[DimSalesContract] (
    [SKSalesContract]                  INT             NOT NULL,
    [ADLSBatchID]                      INT             NOT NULL,
    [ADLSTimestamp]                    DATETIME2 (0)   NOT NULL,
    [LZBatchID]                        INT             NOT NULL,
    [DWBatchID]                        INT             NOT NULL,
    [DWHash]                           CHAR (40)       NOT NULL,
    [KeySalesContract]                 NCHAR (18)      NOT NULL,
    [SKAsset]                          INT             NOT NULL,
    [SKAccount]                        INT             NOT NULL,
    [SKTeam]                           INT             NOT NULL,
    [SKUser]                           INT             NOT NULL,
    [AuditCompletedDate]               DATETIME2 (0)   NULL,
    [AuditCompletedDateKey]            INT             NULL,
    [CaseManufacturingDate]            DATETIME2 (0)   NULL,
    [CaseManufacturingDateKey]         INT             NULL,
    [ContractSignedDate]               DATETIME2 (0)   NULL,
    [ContractSignedDateKey]            INT             NULL,
    [FirstContactEmailDateKey]         INT             NULL,
    [FirstContactEmailDate]            DATETIME2 (0)   NULL,
    [FourthContactDateKey]             INT             NULL,
    [FourthContactDate]                DATETIME2 (0)   NULL,
    [MiMDateKey]                       INT             NULL,
    [MiMDate]                          DATETIME2 (0)   NULL,
    [NotificationSenttoTrainerDateKey] INT             NULL,
    [NotificationSenttoTrainerDate]    DATETIME2 (0)   NULL,
    [ThirdContactDateKey]              INT             NULL,
    [ThirdContactDate]                 DATETIME2 (0)   NULL,
    [InvoiceDateKey]                   INT             NULL,
    [InvoiceDate]                      DATETIME2 (0)   NULL,
    [DimLeasingStatusDateKey]          INT             NULL,
    [DimLeasingStatusDate]             DATETIME2 (0)   NULL,
    [FinalReceivedDateKey]             INT             NULL,
    [FinalReceivedDate]                DATETIME2 (0)   NULL,
    [iTeroScannerRevRecDateKey]        INT             NULL,
    [iTeroScannerRevRecDate]           DATETIME2 (0)   NULL,
    [CaseOrderStatus]                  NVARCHAR (255)  NULL,
    [OpportunityOrderStatus]           NVARCHAR (255)  NULL,
    [OnboardingDateKey]                INT             NULL,
    [OnboardingDate]                   DATETIME2 (0)   NULL,
    [PaymentMethod]                    NVARCHAR (255)  NULL,
    [ProcessingCompletedDateKey]       INT             NULL,
    [ProcessingCompletedDate]          DATETIME2 (0)   NULL,
    [ShippingDateKey]                  INT             NULL,
    [ShippingDate]                     DATETIME2 (0)   NULL,
    [SpareDeliveryDateKey]             INT             NULL,
    [SpareDeliveryDate]                DATETIME2 (0)   NULL,
    [VCTTrainingDateKey]               INT             NULL,
    [VCTTrainingDate]                  DATETIME2 (0)   NULL,
    [AuditTimeElapsed]                 DECIMAL (18, 2) NULL,
    [ProcessingTimeElapsed]            DECIMAL (18, 2) NULL,
    [ShipmentTimeElapsed]              DECIMAL (18, 2) NULL,
    [iTeroSalesRep]                    NVARCHAR (510)  NULL,
    [Priority]                         NVARCHAR (40)   NULL,
    [AuditCompletedSteps]              INT             NULL,
    [AuditingStageStatus]              NVARCHAR (20)   NULL,
    [AuditStatus]                      NVARCHAR (510)  NULL,
    [SerialNumber]                     NVARCHAR (4000)   NULL,
    [DeliveredDate]                    DATETIME2 (0)   NULL,
    [DeliveredDateKey]                 INT             NULL,
    [TicketNumber]                     NVARCHAR (60)   NULL,
    [FinalStatus]                      NVARCHAR (255)  NULL,
    [ScannerQuantity]                  DECIMAL (18)    NULL,
    [ContractOpenDateKey]              INT             NULL,
    [ContractOpenDate]                 DATETIME2 (0)   NULL,
    [ContractDate]                     DATETIME2 (0)   NULL,
    [ContractDateKey]                  INT             NULL,
    [OpportunityNumber]                NVARCHAR (256)  NULL,
    [CancellationDate]                 DATETIME2 (0)   NULL,
    [CancellationDateKey]              INT             NULL,
    [Opp_Contract_Date]                DATETIME2 (0)   NULL,
    [Ticket_Contract_Date]             DATETIME2 (0)   NULL,
    [Opp_Ship_Date]                    DATETIME2 (0)   NULL,
    [Ticket_Ship_Date]                 DATETIME2 (0)   NULL,
    [Opp_Qty]                          INT             NULL,
    [Ticket_Qty]                       INT             NULL,
    [Opp_RecordTypeId]                 NVARCHAR (255)  NULL,
    [Opp_StageName]                    NVARCHAR (40)   NULL,
    [Ticket_Cancellation_received]     NVARCHAR (255)  NULL,
    [Opp_Cancellation_Date]            DATETIME2 (0)   NULL,
    [Ticket_Purchase_Price]            DECIMAL (18, 2) NULL,
    [Opp_Purchase_Price]               NVARCHAR (255)  NULL,
    [Opp_Product_option]               NVARCHAR (255)  NULL,
    [Ticket_Scanner_Model]             NVARCHAR (510)  NULL,
    [Ticket_RecordType]                NVARCHAR (255)  NULL,
    [Opp_RecordType]                   NVARCHAR (255)  NULL,
    [ProductFamily]                    NVARCHAR (40)   NULL,
    [ProductName]                      NVARCHAR (255)  NULL,
    [ProductCode]                      NVARCHAR (40)   NULL,
    [OplQuantity]                      DECIMAL (18, 2) NULL,
    [OplProductCode]                   NVARCHAR (255)  NULL,
    [Opp_Commission_Date]              DATETIME2 (0)   NULL,
    [Opp_Description]                  NVARCHAR (4000) NULL,
    [IsDeleted]                        INT             NULL,
    [Opp_EMEA_Sales_Channel]           NVARCHAR (50)   NULL,
    [Opp_Distributor]                  NVARCHAR (255)  NULL,
    [Opp_iTero_Type]                   NVARCHAR (255)  NULL,
    [Opp_Promotion]                    NVARCHAR (255)  NULL,
    [OppCloseDate]                     DATETIME2 (0)   NULL,
    [ContactID]                        NVARCHAR (18)   NULL,
    [OpportunityLineItemID]            NVARCHAR (18)   NULL,
    [IsChildOpportunity]                BIT             NULL
)
WITH (CLUSTERED INDEX([SKSalesContract]), DISTRIBUTION = HASH([SKSalesContract]));

