CREATE TABLE [DWIRIS].[DimTicket] (
    [SKTicket]                           INT             NOT NULL,
    [ADLSBatchID]                        INT             NOT NULL,
    [ADLSTimestamp]                      DATETIME2 (0)   NOT NULL,
    [LZBatchID]                          INT             NOT NULL,
    [DWBatchID]                          INT             NULL,
    [DWHash]                             CHAR (40)       NULL,
    [KeyTicket]                          NCHAR (18)      NULL,
    [SKAccount]                          INT             NULL,
    [SKAsset]                            INT             NULL,
    [SKParentTicket]                     INT             NULL,
    [SKTeam]                             INT             NULL,
    [CancellationCause]                  NVARCHAR (255)  NULL,
    [CancellationStatus]                 NVARCHAR (255)  NULL,
    [ContactFullName]                    NVARCHAR (600)  NULL,
    [DidScannerShipFlag]                 NVARCHAR (255)  NULL,
    [IssueFoundDateKey]                  INT             NULL,
    [IssueFoundDate]                     DATETIME2 (0)   NULL,
    [EntityType]                         NVARCHAR (50)   NULL,
    [FinalStatus]                        NVARCHAR (255)  NULL,
    [ScannerSN]                          NVARCHAR (500)  NULL,
    [IsClosed]                           VARCHAR (5)     NULL,
    [IsClosedOnCreate]                   VARCHAR (5)     NULL,
    [IsDeleted]                          VARCHAR (5)     NULL,
    [IsEscalated]                        VARCHAR (5)     NULL,
    [IssueType]                          NVARCHAR (255)  NULL,
    [LastModifiedDate]                   DATETIME2 (0)   NOT NULL,
    [LocationStatus]                     NVARCHAR (255)  NULL,
    [MATTicketID]                        INT             NULL,
    [NewIteroCustomer]                   NVARCHAR (255)  NULL,
    [Origin]                             NVARCHAR (40)   NULL,
    [ParentTicket]                       NCHAR (18)      NULL,
    [Priority]                           NVARCHAR (40)   NULL,
    [PriorityGenericDescription]         NVARCHAR (50)   NULL,
    [ProcessingStageStatus]              NVARCHAR (255)  NULL,
    [RecordType]                         NVARCHAR (80)   NULL,
    [ReturnType]                         NVARCHAR (255)  NULL,
    [ScannerRevReq]                      DECIMAL (18, 2) NULL,
    [ShippingStageStatus]                NVARCHAR (255)  NULL,
    [Status]                             NVARCHAR (80)   NULL,
    [SubIssueType]                       NVARCHAR (255)  NULL,
    [TicketAssignedTo]                   NVARCHAR (600)  NULL,
    [TicketCancelledDateKey]             INT             NULL,
    [TicketCancelledDate]                DATETIME2 (0)   NULL,
    [TicketClosedDateKey]                INT             NULL,
    [TicketClosedDate]                   DATETIME2 (0)   NULL,
    [TicketIssueAssetGenericDescription] NVARCHAR (200)  NULL,
    [TicketNumber]                       NVARCHAR (60)   NULL,
    [TicketOpenDateKey]                  INT             NULL,
    [TicketOpenDate]                     DATETIME2 (0)   NULL,
    [TicketOpenedBy]                     NVARCHAR (600)  NULL,
    [TicketResolvedDateKey]              INT             NULL,
    [TicketResolvedDate]                 DATETIME2 (0)   NULL,
    [TicketStatus]                       NVARCHAR (80)   NULL,
    [TicketType]                         NVARCHAR (510)  NULL,
    [TrackStatus]                        NVARCHAR (1300) NULL,
    [Ticket Net Hrs]                     FLOAT (53)      NULL,
    [Ticket Calendar Hrs]                INT             NULL,
    [Ticket Aging]                       INT             NULL,
    [Tickets Count]                      INT             NOT NULL,
    [RMA Count]                          INT             NOT NULL,
    [BusinessHoursId]                    NCHAR (18)      NULL,
    [SKUser]                             INT             NULL,
    [FirstInteractionResolution]         NVARCHAR (255)  NULL,
    [OrderID]                            INT             NULL,
    [ActivityCount]                      INT             NULL,
    [LastActivityDate]                   DATETIME2 (7)   NULL,
    [SKUserAssignedTo]                   INT             NULL,
    [IsInvalid]                          INT             NULL,
    [SourceSystem]                       NVARCHAR (20)   NULL,
    [NumberOfComments]                   INT             NULL,
    [NumberOfAttachments]                INT             NULL,
    [SAP_SO]                             NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([SKTicket]), DISTRIBUTION = REPLICATE);

