CREATE TABLE [DWIRIS].[DimTicketComplaint] (
    [SKTicketComplaint]                               INT             NOT NULL,
    [ADLSBatchID]                                     INT             NOT NULL,
    [ADLSTimestamp]                                   DATETIME2 (0)   NOT NULL,
    [LZBatchID]                                       INT             NOT NULL,
    [DWBatchID]                                       INT             NULL,
    [DWHash]                                          CHAR (40)       NULL,
    [KeyTicketComplaint]                              NCHAR (18)      NULL,
    [SKAccount]                                       INT             NULL,
    [SKAsset]                                         INT             NULL,
    [SKUser]                                          INT             NULL,
    [SKTeam]                                          INT             NULL,
    [SKParentTicket]                                  INT             NULL,
    [CreatedDateKey]                                  INT             NULL,
    [CreatedDate]                                     DATETIME2 (0)   NULL,
    [ClosedDateKey]                                   INT             NULL,
    [ClosedDate]                                      DATETIME2 (0)   NULL,
    [ResolvedDateKey]                                 INT             NULL,
    [ResolvedDate]                                    DATETIME2 (0)   NULL,
    [CancelledDateKey]                                INT             NULL,
    [CancelledDate]                                   DATETIME2 (0)   NULL,
    [ContactFullName]                                 NVARCHAR (600)  NULL,
    [IssueType]                                       NVARCHAR (255)  NULL,
    [SubIssueType]                                    NVARCHAR (255)  NULL,
    [IssueAsset]                                      NVARCHAR (200)  NULL,
    [LastModifiedDate]                                DATETIME2 (0)   NOT NULL,
    [Origin]                                          NVARCHAR (40)   NULL,
    [Priority]                                        NVARCHAR (50)   NULL,
    [Status]                                          NVARCHAR (80)   NULL,
    [TicketType]                                      NVARCHAR (510)  NULL,
    [TicketNumber]                                    NVARCHAR (60)   NULL,
    [RecordType]                                      NVARCHAR (80)   NULL,
    [TicketAssignedTo]                                NVARCHAR (600)  NULL,
    [TicketOpenedBy]                                  NVARCHAR (600)  NULL,
    [AdditionalCommentsOther]                         NVARCHAR (4000) NULL,
    [AdditionalInformation]                           NVARCHAR (4000) NULL,
    [ComplaintHandlingAndAssessmentDoneBy]            NVARCHAR (4000) NULL,
    [ComplaintStatus]                                 NVARCHAR (80)   NULL,
    [CustomerIssueDescription]                        NVARCHAR (4000) NULL,
    [CustomerServiceInitialInvestigation]             NVARCHAR (4000) NULL,
    [DidEventResultIn]                                BIT             NULL,
    [DuplicateOf]                                     NVARCHAR (50)   NULL,
    [EvaluationImpactLevel]                           NVARCHAR (4000) NULL,
    [HazardSituation]                                 NVARCHAR (4000) NULL,
    [InvestigationCAPAReference]                      NVARCHAR (50)   NULL,
    [InWhatCountry]                                   NVARCHAR (4000) NULL,
    [IsFurtherInvestigationNeeded]                    BIT             NULL,
    [IsRegulatoryNonConformance]                      BIT             NULL,
    [IsReportable]                                    VARCHAR (5)     NULL,
    [IsSafety]                                        NVARCHAR (4000) NULL,
    [IsSafetyOrPotentially]                           NVARCHAR (4000) NULL,
    [IsValidComplaint]                                NVARCHAR (4000) NULL,
    [JustificationReportSummary]                      NVARCHAR (4000) NULL,
    [RationaleForFurtherInvestigationCAPANotRequired] NVARCHAR (4000) NULL,
    [RiskAnalysisDOC]                                 NVARCHAR (50)   NULL,
    [RootCause]                                       NVARCHAR (4000) NULL,
    [ComplaintCount]                                  INT             NOT NULL,
    [Category]                                        NVARCHAR (512)  NULL,
    [ComplaintType]                                   NVARCHAR (512)  NULL,
    [ComplaintSubType]                                NVARCHAR (512)  NULL,
    [IsInvalid]                                       INT             NULL,
    [SourceSystem]                                    NVARCHAR (20)   NULL
)
WITH (CLUSTERED INDEX([SKTicketComplaint]), DISTRIBUTION = REPLICATE);

