CREATE TABLE [DWIRIS].[DimTicketTraining] (
    [SKTicketTraining]                 INT             NOT NULL,
    [ADLSBatchID]                      INT             NOT NULL,
    [ADLSTimestamp]                    DATETIME2 (0)   NOT NULL,
    [LZBatchID]                        INT             NOT NULL,
    [DWBatchID]                        INT             NULL,
    [DWHash]                           CHAR (40)       NULL,
    [KeyTicketTraining]                NCHAR (18)      NULL,
    [SKAccount]                        INT             NULL,
    [SKAsset]                          INT             NULL,
    [SKParentTicket]                   INT             NULL,
    [SKTeam]                           INT             NULL,
    [SKUser]                           INT             NULL,
    [TicketAssignedTo]                 NVARCHAR (600)  NULL,
    [TicketNumber]                     NVARCHAR (60)   NULL,
    [ContactFullName]                  NVARCHAR (600)  NULL,
    [Origin]                           NVARCHAR (40)   NULL,
    [TicketStatus]                     NVARCHAR (80)   NULL,
    [ProcessingStageStatus]            NVARCHAR (255)  NULL,
    [ShippingStageStatus]              NVARCHAR (255)  NULL,
    [FinalStatus]                      NVARCHAR (255)  NULL,
    [Priority]                         NVARCHAR (40)   NULL,
    [TicketCancelledDateKey]           INT             NULL,
    [TicketCancelledDate]              DATETIME2 (0)   NULL,
    [TicketClosedDateKey]              INT             NULL,
    [TicketClosedDate]                 DATETIME2 (0)   NULL,
    [TicketOpenDateKey]                INT             NULL,
    [TicketOpenDate]                   DATETIME2 (0)   NULL,
    [TicketOpenedBy]                   NVARCHAR (600)  NULL,
    [TicketResolvedDateKey]            INT             NULL,
    [TicketResolvedDate]               DATETIME2 (0)   NULL,
    [TicketFirstContactEmailDateKey]   INT             NULL,
    [TicketFirstContactEmailDate]      DATETIME2 (0)   NULL,
    [TicketThirdContactDateKey]        INT             NULL,
    [TicketThirdContactDate]           DATETIME2 (0)   NULL,
    [TicketFourthContactDateKey]       INT             NULL,
    [TicketFourthContactDate]          DATETIME2 (0)   NULL,
    [NotificationSentToTrainerDateKey] INT             NULL,
    [NotificationSentToTrainerDate]    DATETIME2 (0)   NULL,
    [LeasingStatusDateKey]             INT             NULL,
    [LeasingStatusDate]                DATETIME2 (0)   NULL,
    [TrainingDateKey]                  INT             NULL,
    [TrainingDate]                     DATETIME2 (0)   NULL,
    [TicketType]                       NVARCHAR (510)  NULL,
    [TrackStatus]                      NVARCHAR (1300) NULL,
    [Ticket Net Hrs]                   FLOAT (53)      NULL,
    [Ticket Calendar Hrs]              INT             NULL,
    [Ticket Aging]                     INT             NULL,
    [Tickets Count]                    INT             NOT NULL,
    [BusinessHoursId]                  NCHAR (18)      NULL,
    [ParentTicketNumber]               NVARCHAR (60)   NULL,
    [IssueType]                        NVARCHAR (255)  NULL
)
WITH (CLUSTERED INDEX([SKTicketTraining]), DISTRIBUTION = REPLICATE);

