CREATE TABLE [DWIRIS].[DimUser] (
    [SKUser]          INT            NOT NULL,
    [ADLSBatchID]     INT            NOT NULL,
    [ADLSTimestamp]   DATETIME2 (0)  NOT NULL,
    [LZBatchID]       INT            NOT NULL,
    [DWBatchID]       INT            NOT NULL,
    [DWHash]          CHAR (40)      NOT NULL,
    [KeyUser]         NCHAR (18)     NOT NULL,
    [SourceSystem]    VARCHAR (10)   NOT NULL,
    [UserName]        NVARCHAR (80)  NULL,
    [UserType]        NVARCHAR (80)  NULL,
    [FirstName]       NVARCHAR (40)  NULL,
    [LastName]        NVARCHAR (160) NOT NULL,
    [Name]            NVARCHAR (242) NOT NULL,
    [Email]           NVARCHAR (256) NOT NULL,
    [Alias]           NVARCHAR (10)  NULL,
    [Title]           NVARCHAR (80)  NULL,
    [EmployeeNumber]  NVARCHAR (20)  NULL,
    [CompanyName]     NVARCHAR (80)  NULL,
    [Department]      NVARCHAR (80)  NULL,
    [Division]        NVARCHAR (80)  NULL,
    [EmpHireDate]     DATETIME       NULL,
    [City]            NVARCHAR (80)  NULL,
    [Country]         NVARCHAR (160) NULL,
    [Region]          NVARCHAR (100) NULL,
    [State]           NVARCHAR (80)  NULL,
    [PostalCode]      NVARCHAR (40)  NULL,
    [Address]         NVARCHAR (255) NULL,
    [Phone]           NVARCHAR (80)  NULL,
    [CreatedDate]     DATETIME       NOT NULL,
    [AccountId]       NCHAR (18)     NULL,
    [MAT_ID]          INT            NULL,
    [IsiTeroRep]      VARCHAR (5)    NULL,
    [ManagerId]       VARCHAR (18)   NULL,
    [RoleOnTerritory] NVARCHAR (255) NULL,
    [IsActive]        VARCHAR (5)    NOT NULL
)
WITH (CLUSTERED INDEX([SKUser]), DISTRIBUTION = REPLICATE);

