CREATE TABLE [DWIRIS].[DimVctTraining] (
    [SKVctTraining]        INT             NOT NULL,
    [ADLSBatchID]          INT             NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)   NOT NULL,
    [LZBatchID]            INT             NOT NULL,
    [DWBatchID]            INT             NULL,
    [DWHash]               CHAR (40)       NULL,
    [KeyVctTraining]       NCHAR (18)      NULL,
    [TicketNumber]         NVARCHAR (60)   NULL,
    [IsCompleted]          BIT             NULL,
    [CreatedDate]          DATETIME2 (7)   NULL,
    [Id]                   NCHAR (18)      NULL,
    [IsInvisalign]         BIT             NULL,
    [IsDeleted]            BIT             NULL,
    [Name]                 NVARCHAR (80)   NULL,
    [NumberOfParticipants] DECIMAL (18)    NULL,
    [RecordType]           NVARCHAR (80)   NULL,
    [MethodOfTraining]     NVARCHAR (255)  NULL,
    [ModulesCompleted]     NVARCHAR (MAX)  NULL,
    [Status]               NVARCHAR (255)  NULL,
    [TotalTime]            DECIMAL (18, 1) NULL,
    [Type]                 NVARCHAR (255)  NULL,
    [VCTTrainingDate]      DATETIME2 (7)   NULL,
    [IsBasic]              BIT             NULL,
    [IsOrtho]              BIT             NULL,
    [IsOtherSW]            BIT             NULL,
    [IsRestorative]        BIT             NULL,
    [AccountNumber]        NVARCHAR (40)   NULL,
    [ContactNumber]        NVARCHAR (40)   NULL,
    [MATID]                NVARCHAR (25)   NULL,
    [Lab]                  BIT             NULL
)
WITH (CLUSTERED INDEX([SKVctTraining]), DISTRIBUTION = REPLICATE);

