CREATE TABLE [SrcMES_AFAB_MX2].[BOX] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [box_key]              BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [box_name]             NVARCHAR (128) NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [capacity]             INT            NULL,
    [quantity]             INT            NULL,
    [dscomment]            NVARCHAR (255) NULL,
    [creation_time]        DATETIME       NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [udt_0]                DATETIME       NULL,
    [udt_1]                DATETIME       NULL,
    [udt_2]                DATETIME       NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [bill_account_key]     BIGINT         NULL,
    [build_account_key]    BIGINT         NULL,
    [ship_account_key]     BIGINT         NULL,
    [user_account_0]       BIGINT         NULL,
    [finished_time]        DATETIME       NULL,
    [shipped_time]         DATETIME       NULL,
    [container_key]        BIGINT         NULL,
    [container_name]       NVARCHAR (128) NULL,
    [container_type]       NVARCHAR (50)  NULL,
    [container_sub_type]   INT            NULL,
    [priority]             INT            NULL,
    [location]             NVARCHAR (64)  NULL,
    [tobj_status_key]      BIGINT         NOT NULL,
    [revision]             INT            NOT NULL,
    [box_type]             INT            NOT NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [box_count]            INT            NULL,
    [lot_count]            INT            NULL,
    [partial_lot_count]    INT            NULL,
    [unit_count]           INT            NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [udt_0_u]              DATETIME       NULL,
    [udt_0_z]              NVARCHAR (64)  NULL,
    [udt_1_u]              DATETIME       NULL,
    [udt_1_z]              NVARCHAR (64)  NULL,
    [udt_2_u]              DATETIME       NULL,
    [udt_2_z]              NVARCHAR (64)  NULL,
    [finished_time_u]      DATETIME       NULL,
    [finished_time_z]      NVARCHAR (64)  NULL,
    [shipped_time_u]       DATETIME       NULL,
    [shipped_time_z]       NVARCHAR (64)  NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [purged]               INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([box_key]));

