CREATE TABLE [SrcMES_AFAB_MX2].[INSTRUCTION] (
    [LZBatchID]            INT             NOT NULL,
    [ADLSBatchID]          INT             NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)   NOT NULL,
    [inst_key]             BIGINT          NOT NULL,
    [site_num]             INT             NOT NULL,
    [inst_name]            NVARCHAR (64)   NOT NULL,
    [description]          NVARCHAR (255)  NULL,
    [category]             NVARCHAR (50)   NULL,
    [image_key]            BIGINT          NULL,
    [type]                 NVARCHAR (50)   NULL,
    [pathname]             NVARCHAR (2000) NULL,
    [is_link]              INT             NULL,
    [creator_key]          BIGINT          NOT NULL,
    [creation_time]        DATETIME        NOT NULL,
    [last_modifier_key]    BIGINT          NOT NULL,
    [last_modified_time]   DATETIME        NOT NULL,
    [uda_0]                NVARCHAR (255)  NULL,
    [uda_1]                NVARCHAR (255)  NULL,
    [uda_2]                NVARCHAR (255)  NULL,
    [uda_3]                NVARCHAR (255)  NULL,
    [uda_4]                NVARCHAR (255)  NULL,
    [xfr_insert_pid]       INT             NULL,
    [xfr_update_pid]       INT             NULL,
    [trx_id]               CHAR (38)       NOT NULL,
    [update_privilege_key] BIGINT          NULL,
    [delete_privilege_key] BIGINT          NULL,
    [creation_time_u]      DATETIME        NULL,
    [creation_time_z]      NVARCHAR (64)   NULL,
    [last_modified_time_u] DATETIME        NULL,
    [last_modified_time_z] NVARCHAR (64)   NULL,
    [pd_xfr_update_pid]    INT             NOT NULL,
    [src_xfr_update_pid]   INT             NOT NULL,
    [purged]               INT             NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

