CREATE TABLE [SrcMES_AFAB_MX2].[OPERATION] (
    [LZBatchID]            INT            NOT NULL,
    [ADLSBatchID]          INT            NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)  NOT NULL,
    [op_key]               BIGINT         NOT NULL,
    [site_num]             INT            NOT NULL,
    [op_name]              NVARCHAR (64)  NOT NULL,
    [description]          NVARCHAR (255) NULL,
    [category]             NVARCHAR (50)  NULL,
    [image_key]            BIGINT         NULL,
    [inst_list_key]        BIGINT         NULL,
    [dcs_list_key]         BIGINT         NULL,
    [form_key]             BIGINT         NULL,
    [checklist_key]        BIGINT         NULL,
    [cycle_duration]       INT            NULL,
    [value_added]          INT            NULL,
    [failure]              INT            NULL,
    [creator_key]          BIGINT         NOT NULL,
    [creation_time]        DATETIME       NOT NULL,
    [last_modifier_key]    BIGINT         NOT NULL,
    [last_modified_time]   DATETIME       NOT NULL,
    [version]              INT            NOT NULL,
    [access_level]         INT            NOT NULL,
    [checkout_user_key]    BIGINT         NULL,
    [uda_0]                NVARCHAR (255) NULL,
    [uda_1]                NVARCHAR (255) NULL,
    [uda_2]                NVARCHAR (255) NULL,
    [uda_3]                NVARCHAR (255) NULL,
    [uda_4]                NVARCHAR (255) NULL,
    [xfr_insert_pid]       INT            NULL,
    [xfr_update_pid]       INT            NULL,
    [trx_id]               CHAR (38)      NOT NULL,
    [update_privilege_key] BIGINT         NULL,
    [delete_privilege_key] BIGINT         NULL,
    [creation_time_u]      DATETIME       NULL,
    [creation_time_z]      NVARCHAR (64)  NULL,
    [last_modified_time_u] DATETIME       NULL,
    [last_modified_time_z] NVARCHAR (64)  NULL,
    [pd_xfr_update_pid]    INT            NOT NULL,
    [src_xfr_update_pid]   INT            NOT NULL,
    [purged]               INT            NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

