CREATE TABLE [SrcMES_AFAB_MX2].[TRACKED_OBJECT_STATUS] (
    [LZBatchID]                INT            NOT NULL,
    [ADLSBatchID]              INT            NOT NULL,
    [ADLSTimestamp]            DATETIME2 (0)  NOT NULL,
    [tobj_status_key]          BIGINT         NOT NULL,
    [site_num]                 INT            NOT NULL,
    [tobj_key]                 BIGINT         NOT NULL,
    [tobj_type]                NVARCHAR (50)  NOT NULL,
    [route_key]                BIGINT         NULL,
    [route_name]               NVARCHAR (64)  NULL,
    [route_step_key]           BIGINT         NULL,
    [route_step_name]          NVARCHAR (64)  NULL,
    [queue_key]                BIGINT         NULL,
    [queue_name]               NVARCHAR (64)  NULL,
    [op_key]                   BIGINT         NULL,
    [op_name]                  NVARCHAR (64)  NULL,
    [p_line_key]               BIGINT         NULL,
    [p_line_name]              NVARCHAR (64)  NULL,
    [wc_key]                   BIGINT         NULL,
    [wc_name]                  NVARCHAR (64)  NULL,
    [parent_route_key]         BIGINT         NULL,
    [parent_embedded_step_key] BIGINT         NULL,
    [top_route_key]            BIGINT         NULL,
    [start_time]               DATETIME       NULL,
    [complete_time]            DATETIME       NULL,
    [status]                   NVARCHAR (50)  NOT NULL,
    [state]                    NVARCHAR (50)  NOT NULL,
    [reason]                   NVARCHAR (64)  NULL,
    [arc_history]              NVARCHAR (255) NULL,
    [previous_status]          NVARCHAR (50)  NULL,
    [previous_state]           NVARCHAR (50)  NULL,
    [pause_time]               DATETIME       NULL,
    [pause_accumulator]        INT            NULL,
    [tobj_history_key]         BIGINT         NULL,
    [tobj_queue_history_key]   BIGINT         NULL,
    [previous_node_key]        BIGINT         NULL,
    [previous_node_name]       NVARCHAR (64)  NULL,
    [previous_node_type]       NVARCHAR (50)  NULL,
    [xfr_insert_pid]           INT            NULL,
    [xfr_update_pid]           INT            NULL,
    [p_queue_key]              BIGINT         NULL,
    [p_queue_name]             NVARCHAR (64)  NULL,
    [tos_stack_key]            BIGINT         NULL,
    [revision]                 INT            NOT NULL,
    [previous_robj_key]        BIGINT         NULL,
    [previous_robj_type]       NVARCHAR (50)  NULL,
    [previous_robj_name]       NVARCHAR (64)  NULL,
    [previous_p_line_key]      BIGINT         NULL,
    [previous_p_line_name]     NVARCHAR (64)  NULL,
    [hold_reservation_key]     BIGINT         NULL,
    [hold_reservation_count]   INT            NULL,
    [trx_id]                   CHAR (38)      NOT NULL,
    [last_modified_time]       DATETIME       NOT NULL,
    [start_time_u]             DATETIME       NULL,
    [start_time_z]             NVARCHAR (64)  NULL,
    [complete_time_u]          DATETIME       NULL,
    [complete_time_z]          NVARCHAR (64)  NULL,
    [pause_time_u]             DATETIME       NULL,
    [pause_time_z]             NVARCHAR (64)  NULL,
    [last_modified_time_u]     DATETIME       NULL,
    [last_modified_time_z]     NVARCHAR (64)  NULL,
    [pd_xfr_update_pid]        INT            NOT NULL,
    [src_xfr_update_pid]       INT            NOT NULL,
    [purged]                   INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([tobj_key]));

