CREATE TABLE [SrcMES_AFAB_MX2].[UDA] (
    [LZBatchID]            INT             NOT NULL,
    [ADLSBatchID]          INT             NOT NULL,
    [ADLSTimestamp]        DATETIME2 (0)   NOT NULL,
    [uda_key]              BIGINT          NOT NULL,
    [site_num]             INT             NOT NULL,
    [object_type]          NVARCHAR (50)   NOT NULL,
    [name]                 NVARCHAR (30)   NULL,
    [db_name]              NVARCHAR (30)   NOT NULL,
    [type]                 NVARCHAR (50)   NOT NULL,
    [text_length]          INT             NULL,
    [category]             NVARCHAR (50)   NULL,
    [description]          NVARCHAR (255)  NULL,
    [xfr_insert_pid]       INT             NULL,
    [xfr_update_pid]       INT             NULL,
    [trx_id]               CHAR (38)       NOT NULL,
    [last_modified_time]   DATETIME        NOT NULL,
    [sub_type]             NVARCHAR (50)   NULL,
    [boolean_value]        INT             NULL,
    [decimal_value]        NUMERIC (23, 9) NULL,
    [int_value]            BIGINT          NULL,
    [object_key]           BIGINT          NULL,
    [string_value]         NVARCHAR (1024) NULL,
    [time_value]           DATETIME        NULL,
    [last_modified_time_u] DATETIME        NULL,
    [last_modified_time_z] NVARCHAR (64)   NULL,
    [time_value_u]         DATETIME        NULL,
    [time_value_z]         NVARCHAR (64)   NULL,
    [referred_key]         BIGINT          NULL,
    [list_support]         INT             NULL,
    [list_key]             BIGINT          NULL,
    [measured_value]       NVARCHAR (64)   NULL,
    [pd_xfr_update_pid]    INT             NOT NULL,
    [src_xfr_update_pid]   INT             NOT NULL,
    [purged]               INT             NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

