CREATE TABLE [SrcMedallia].[MedalliaSurvey] (
    [LZBatchID]                                                INT             NOT NULL,
    [ADLSBatchID]                                              INT             NOT NULL,
    [ADLSTimestamp]                                            DATETIME2 (0)   NOT NULL,
    [align_doctorid_text]                                      NVARCHAR (4000) NULL,
    [survey_id_text]                                           NVARCHAR (4000) NOT NULL,
    [survey_type]                                              NVARCHAR (4000) NULL,
    [responsedate]                                             DATE            NULL,
    [aligntech_itero_satisfaction_comment_comment]             NVARCHAR (MAX)  NULL,
    [comments]                                                 NVARCHAR (MAX)  NULL,
    [align_record_type]                                        NVARCHAR (4000) NULL,
    [align_cs_osat_comment]                                    NVARCHAR (MAX)  NULL,
    [aligntech_itero_likelihood_to_recommend_sc11]             NVARCHAR (4000) NULL,
    [aligntech_relationship_likelihood_to_continue_sc10]       NVARCHAR (4000) NULL,
    [aligntech_relationship_likelihood_to_recommend_sc10]      NVARCHAR (4000) NULL,
    [aligntech_customer_support_multiling_oe_text]             NVARCHAR (MAX)  NULL,
    [aligntech_relationship_additional_kpi_feedback_text]      NVARCHAR (MAX)  NULL,
    [aligntech_customer_support_ltr_comment_text]              NVARCHAR (MAX)  NULL,
    [alert_date_closed]                                        DATE            NULL,
    [alert_date_created]                                       DATE            NULL,
    [alert_date_resolved]                                      DATE            NULL,
    [alert_date_status_changed]                                DATE            NULL,
    [alert_desc]                                               NVARCHAR (4000) NULL,
    [alert_ever_escalated]                                     NVARCHAR (4000) NULL,
    [alert_ever_escalated2]                                    NVARCHAR (4000) NULL,
    [alert_ever_overdue]                                       NVARCHAR (4000) NULL,
    [alert_num_reopened]                                       INT             NULL,
    [alert_resolution_time_hours]                              INT             NULL,
    [alert_status]                                             NVARCHAR (4000) NULL,
    [alert_status_code]                                        NVARCHAR (4000) NULL,
    [alert_triggered]                                          NVARCHAR (4000) NULL,
    [alert_type]                                               NVARCHAR (4000) NULL,
    [align_agentid]                                            NVARCHAR (4000) NULL,
    [align_alert_emailtemplates_perfectten_agentrep_text]      NVARCHAR (4000) NULL,
    [align_alert_resolution_time]                              NVARCHAR (4000) NULL,
    [align_alert_type]                                         NVARCHAR (4000) NULL,
    [align_all_doctor_global_region_enum]                      NVARCHAR (4000) NULL,
    [align_case_closed_timestamp]                              DATE            NULL,
    [align_case_opened_timestamp]                              DATE            NULL,
    [align_cases_six_months_integer]                           INT             NULL,
    [align_cc_accepted_cases_12_months_integer]                INT             NULL,
    [align_cc_action_enum]                                     NVARCHAR (4000) NULL,
    [align_cc_alert_email]                                     NVARCHAR (4000) NULL,
    [align_cc_alert_escalation_email]                          NVARCHAR (4000) NULL,
    [align_cc_casemanagement_resolutioncontact_text]           NVARCHAR (4000) NULL,
    [align_cc_escalated_alert_country_code]                    NVARCHAR (4000) NULL,
    [align_cc_id_text]                                         NVARCHAR (4000) NULL,
    [align_cc_new_alert_country_code]                          NVARCHAR (4000) NULL,
    [align_cc_ordernum_text]                                   NVARCHAR (4000) NULL,
    [align_cc_product_clincheck_submitted_for_auto]            NVARCHAR (4000) NULL,
    [align_cc_product_enum]                                    NVARCHAR (4000) NULL,
    [align_cc_version]                                         NVARCHAR (4000) NULL,
    [align_cs_agent_first_name]                                NVARCHAR (4000) NULL,
    [align_cs_interaction_date]                                DATE            NULL,
    [align_cs_ticket_type]                                     NVARCHAR (4000) NULL,
    [align_cscc_surveyunit_lead_text]                          NVARCHAR (4000) NULL,
    [align_cscc_surveyunit_supervisor_text]                    NVARCHAR (4000) NULL,
    [align_date_last_case_date]                                DATE            NULL,
    [align_doc_join_date]                                      DATE            NULL,
    [align_doctor_volume]                                      INT             NULL,
    [align_escalated_relationship_alert_emails]                NVARCHAR (4000) NULL,
    [align_new_relationship_alert_emails]                      NVARCHAR (4000) NULL,
    [align_open_alert_status_cs_enum]                          NVARCHAR (4000) NULL,
    [align_open_alert_status_enum]                             NVARCHAR (4000) NULL,
    [align_overdue_relationship_alert_emails]                  NVARCHAR (4000) NULL,
    [align_perfect_score_alert_type]                           NVARCHAR (4000) NULL,
    [align_rel_territorymgrname]                               NVARCHAR (4000) NULL,
    [align_rl_closedloop_followupowner_text]                   NVARCHAR (4000) NULL,
    [align_rl_surveyunit_regionalmanager_text]                 NVARCHAR (4000) NULL,
    [align_rl_surveyunit_rep_text]                             NVARCHAR (4000) NULL,
    [align_symptom_code]                                       NVARCHAR (4000) NULL,
    [align_tfm_doctor_org_filter]                              NVARCHAR (4000) NULL,
    [align_total_cc_orders_integer]                            INT             NULL,
    [align_volume_tier_by_global_region]                       NVARCHAR (4000) NULL,
    [align_volume_tier_enum]                                   NVARCHAR (4000) NULL,
    [aligntech_alert_closed_48_hours_yn]                       NVARCHAR (4000) NULL,
    [aligntech_alert_goal_closed_48_hours_yn]                  NVARCHAR (4000) NULL,
    [aligntech_alert_goal_closed_5_day_yn]                     NVARCHAR (4000) NULL,
    [aligntech_alert_has_been_enum]                            NVARCHAR (4000) NULL,
    [aligntech_alert_open_48_hours_yn]                         NVARCHAR (4000) NULL,
    [aligntech_alert_open_5_days_yn]                           NVARCHAR (4000) NULL,
    [aligntech_alert_owner_manager_text]                       NVARCHAR (4000) NULL,
    [aligntech_alert_owner_rep_text]                           NVARCHAR (4000) NULL,
    [aligntech_alert_owner_text]                               NVARCHAR (4000) NULL,
    [aligntech_all_tfm_flag]                                   NVARCHAR (4000) NULL,
    [aligntech_cs_invisalign_pro_yn]                           NVARCHAR (4000) NULL,
    [aligntech_customer_support_agent_osat_sc10]               NVARCHAR (4000) NULL,
    [aligntech_customer_support_call_resolution_pick1]         NVARCHAR (4000) NULL,
    [aligntech_customer_support_communicating_clearly_sc10]    NVARCHAR (4000) NULL,
    [aligntech_customer_support_knowledgeable_sc10]            NVARCHAR (4000) NULL,
    [aligntech_customer_support_osat_sc10]                     NVARCHAR (4000) NULL,
    [aligntech_customer_support_understanding_your_needs_sc10] NVARCHAR (4000) NULL,
    [aligntech_customer_support_willingness_to_help_sc10]      NVARCHAR (4000) NULL,
    [aligntech_invisalign_pro_yn]                              NVARCHAR (4000) NULL,
    [aligntech_itero_customer_support_sc11na]                  NVARCHAR (4000) NULL,
    [aligntech_itero_ease_scanning_yn]                         NVARCHAR (4000) NULL,
    [aligntech_itero_installation_sc11na]                      NVARCHAR (4000) NULL,
    [cc_initial_setup_rating_enum]                             NVARCHAR (4000) NULL,
    [align_cc_initialsetup_ratinggroup_enum]                   NVARCHAR (4000) NULL,
    [align_rl_surveyunit_salesdirector_text]                   NVARCHAR (4000) NULL,
    [aligntech_relationship_account_management_osat_sc10]      NVARCHAR (4000) NULL,
    [aligntech_relationship_company_trust_sc10]                NVARCHAR (4000) NULL,
    [aligntech_relationship_expertise_osat_sc10]               NVARCHAR (4000) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

