CREATE TABLE [SrcSplunk].[CCCloud_AppInit] (
    [LZBatchID]                          INT                NOT NULL,
    [ADLSBatchID]                        INT                NOT NULL,
    [ADLSTimestamp]                      DATETIME2 (0)      NOT NULL,
    [trace]                              NVARCHAR (100)     NOT NULL,
    [action]                             NVARCHAR (250)     NOT NULL,
    [ts]                                 DATETIMEOFFSET (7) NOT NULL,
    [_count]                             INT                NOT NULL,
    [splunk_time]                        DATETIMEOFFSET (7) NULL,
    [appVersion]                         NVARCHAR (50)      NULL,
    [caseId]                             NVARCHAR (50)      NULL,
    [clinCheckType]                      NVARCHAR (50)      NULL,
    [date]                               NVARCHAR (250)     NULL,
    [deviceId]                           NVARCHAR (50)      NULL,
    [flow]                               NVARCHAR (50)      NULL,
    [level]                              NVARCHAR (50)      NULL,
    [pageUrl]                            NVARCHAR (4000)    NULL,
    [version]                            NVARCHAR (50)      NULL,
    [browser_devicePixelRatio]           NVARCHAR (50)      NULL,
    [browser_isTouchDevice]              NVARCHAR (5)       NULL,
    [browser_language]                   NVARCHAR (50)      NULL,
    [browser_name]                       NVARCHAR (250)     NULL,
    [browser_userAgent]                  NVARCHAR (500)     NULL,
    [browser_viewPortHeight]             NVARCHAR (50)      NULL,
    [browser_viewPortWidth]              NVARCHAR (50)      NULL,
    [gpu_renderer]                       NVARCHAR (250)     NULL,
    [gpu_vendor]                         NVARCHAR (250)     NULL,
    [toolStatus_AnterButton]             NVARCHAR (6)       NULL,
    [toolStatus_ArchWidth]               NVARCHAR (6)       NULL,
    [toolStatus_AttachButton]            NVARCHAR (6)       NULL,
    [toolStatus_BiteButton]              NVARCHAR (6)       NULL,
    [toolStatus_BoltonButton]            NVARCHAR (6)       NULL,
    [toolStatus_EruptionButton]          NVARCHAR (6)       NULL,
    [toolStatus_GridButton]              NVARCHAR (6)       NULL,
    [toolStatus_IprButton]               NVARCHAR (6)       NULL,
    [toolStatus_LeftButton]              NVARCHAR (6)       NULL,
    [toolStatus_LowerButton]             NVARCHAR (6)       NULL,
    [toolStatus_MandButton]              NVARCHAR (6)       NULL,
    [toolStatus_MaxilButton]             NVARCHAR (6)       NULL,
    [toolStatus_NumberingButton]         NVARCHAR (6)       NULL,
    [toolStatus_OJOBButton]              NVARCHAR (6)       NULL,
    [toolStatus_OcclusalPlaneButton]     NVARCHAR (6)       NULL,
    [toolStatus_OcclusionContactsButton] NVARCHAR (6)       NULL,
    [toolStatus_OverButton]              NVARCHAR (6)       NULL,
    [toolStatus_PanButton]               NVARCHAR (6)       NULL,
    [toolStatus_PonticButton]            NVARCHAR (6)       NULL,
    [toolStatus_RightButton]             NVARCHAR (6)       NULL,
    [toolStatus_RotateButton]            NVARCHAR (6)       NULL,
    [toolStatus_SmileButton]             NVARCHAR (6)       NULL,
    [toolStatus_StagingButton]           NVARCHAR (6)       NULL,
    [toolStatus_SuperButton]             NVARCHAR (6)       NULL,
    [toolStatus_TMTButton]               NVARCHAR (6)       NULL,
    [toolStatus_TmaButton]               NVARCHAR (6)       NULL,
    [toolStatus_UpperButton]             NVARCHAR (6)       NULL,
    [toolStatus_ZoomInOutButton]         NVARCHAR (6)       NULL,
    [toolStatus]                         NVARCHAR (1000)    NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

