CREATE TABLE [SrcSplunk].[CCCloud_FeatureBig] (
    [LZBatchID]           INT                NOT NULL,
    [ADLSBatchID]         INT                NOT NULL,
    [ADLSTimestamp]       DATETIME2 (0)      NOT NULL,
    [trace]               NVARCHAR (100)     NOT NULL,
    [action]              NVARCHAR (250)     NOT NULL,
    [ts]                  DATETIMEOFFSET (7) NOT NULL,
    [_count]              INT                NOT NULL,
    [splunk_time]         DATETIMEOFFSET (7) NULL,
    [appVersion]          NVARCHAR (50)      NULL,
    [Pitch]               NVARCHAR (30)      NULL,
    [Roll]                NVARCHAR (20)      NULL,
    [data]                NVARCHAR (100)     NULL,
    [done]                NVARCHAR (10)      NULL,
    [duration]            NVARCHAR (20)      NULL,
    [_index]              NVARCHAR (10)      NULL,
    [indicator]           NVARCHAR (10)      NULL,
    [jaw]                 NVARCHAR (50)      NULL,
    [mode]                NVARCHAR (50)      NULL,
    [next]                NVARCHAR (10)      NULL,
    [opened_from_academy] NVARCHAR (10)      NULL,
    [planId]              NVARCHAR (10)      NULL,
    [position]            NVARCHAR (10)      NULL,
    [_role]               NVARCHAR (50)      NULL,
    [score]               NVARCHAR (10)      NULL,
    [skip]                NVARCHAR (10)      NULL,
    [stage]               NVARCHAR (10)      NULL,
    [step_id]             NVARCHAR (50)      NULL,
    [tooltip_id]          NVARCHAR (50)      NULL,
    [type]                NVARCHAR (10)      NULL,
    [_value]              NVARCHAR (10)      NULL,
    [_view]               NVARCHAR (50)      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

