CREATE VIEW [DWWorkday].[SalesRoster]
AS SELECT [Public_Work_Mobile_Phones]
      ,[Primary_Home_Address_State]
      ,[Primary_Home_Address_City]
      ,[Primary_Home_Address_Country]
      ,[Worker]
      ,[location]
      ,[Worker_s_Manager]
      ,[Hire_Date]
      ,[Primary_Home_Address_Postal_Code]
      ,[primaryWorkEmail]
      ,[Primary_Home_Address]
      ,[rownum]
  FROM [SrcWorkday].[SalesRoster];